### PR TITLE
Avoid using SymbolDisplay while binding type

### LINKED ISSUE #42840: A crash with duplicate generic type parameter name
**Version Used**: 
VS16.5.1

**Steps to Reproduce**:
1. git checkout https://github.com/verybadcat/CSharpMath
(commit 4052dd9abdb0d5f12a85b8c9e4967f72c853305c)
2. git submodule init
3. git submodule update
2. Open `CSharpMath.sln`
3. Open folder `Avalonia UI` -> project `CSharpMath.Avalonia` -> file `CSharpMathBlock.cs`
4. Type `, TContentProvider` between `public abstract class CSharpMathBlock<TPainter, TContent` and `> : Control`

**Expected Behavior**:
C# typed without crashing

**Actual Behavior**:
Visual Studio lags then crashes after typing `TContent`
Actual

### PR DESCRIPTION
**Pull request by cston**
`SymbolDisplay` may require parts of the `ISymbol` implementation that are not yet calculated while binding the type declaration.

Fixes #42840

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 1]
```diff
@@ -563,6 +562,25 @@ private Symbol ResolveMultipleSymbolsInAttributeTypeLookup(ArrayBuilder<Symbol>
...
+        {
+            if (isRoot(x))
+            {
+                return isRoot(y);
+            }
+            if (isRoot(y))
+            {
+                return false;
+            }
+            if (!NameAndArityMatchRecursively(x.ContainingSymbol, y.ContainingSymbol))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:575]: nit: consider swapping the name comparison with the recursive call, so that we fail faster when there are differences.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 2]
```diff
@@ -553,8 +553,7 @@ private Symbol ResolveMultipleSymbolsInAttributeTypeLookup(ArrayBuilder<Symbol>
                 var mdSymbol = symbols[secondBest.Index];
 
                 //if names match, arities match, and containing symbols match (recursively), ...
-                if (srcSymbol.ToDisplayString(SymbolDisplayFormat.QualifiedNameArityFormat) ==
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:556]: >ToDisplayString [](start = 30, length = 15)

Do we have more references to this API in the compiler? Consider opening an issue to follow up on them too.

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs [hunk 3]
```diff
@@ -7653,6 +7653,82 @@ class Goo: Attribute
                 Diagnostic(ErrorCode.ERR_NotAnAttributeClass, "X").WithArguments("X"));
         }
 
+        [Fact]
+        public void AmbiguousClassNamespaceLookup_Container()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs:7657]: >AmbiguousClassNamespaceLookup_Container [](start = 20, length = 39)

Consider adding a WorkItem attribute

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetSemanticInfoTests.cs [hunk 4]
```diff
@@ -5971,5 +5971,36 @@ class C
...
+                // (5,17): error CS0229: Ambiguity between 'U' and 'U'
+                //     where T : A<U>
+                Diagnostic(ErrorCode.ERR_AmbigMember, "U").WithArguments("U", "U").WithLocation(5, 17));
+
+            comp = CreateCompilation(source);
+            var tree = comp.SyntaxTrees[0];
+            var model = comp.GetSemanticModel(tree);
+            var syntax = tree.GetRoot().DescendantNodes().OfType<TypeParameterSyntax>().Last();
+            var symbol = model.GetDeclaredSymbol(syntax);
+            Assert.False(symbol.IsReferenceType);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/GetSemanticInfoTests.cs:6003]: >Assert.False(symbol.IsReferenceType); [](start = 12, length = 37)

Consider asserting the same for the previous type parameter.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:556]: >SymbolDisplayFormat.QualifiedNameArityFormat [](start = 46, length = 44)

Is it possible that SymbolDisplay tries to ask more information than it really needs for this format? Would it make sense to open an issue to follow up on that?

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs:7657]: These tests did not fail previously.

---
In reply to: [405651976](https://github.com/dotnet/roslyn/pull/43181#discussion_r405651976) [](ancestors = 405651976)

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 5]
```diff
@@ -563,6 +562,30 @@ private Symbol ResolveMultipleSymbolsInAttributeTypeLookup(ArrayBuilder<Symbol>
...
+            {
+                if (isRoot(x))
+                {
+                    return isRoot(y);
+                }
+                if (isRoot(y))
+                {
+                    return false;
+                }
+                if (x.Name != y.Name || mangleName(x) != mangleName(y) || x.GetArity() != y.GetArity())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: >mangleName(x) != mangleName(y) [](start = 40, length = 30)

Why would this matter for the purpose of the name lookup? Mangling is not a language concept and Name is stripped of it. Do we have a test demonstrating significance of this check?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: Also, is this really consistent with SymbolDisplayFormat.QualifiedNameArityFormat?

---
In reply to: [405714806](https://github.com/dotnet/roslyn/pull/43181#discussion_r405714806) [](ancestors = 405714806)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: Yes, this is for consistency with `QualifiedNameArityFormat`. See `PropertyTests.CanNotReadPropertyFromAmbiguousGenericClass()` for a test that fails without this.

---
In reply to: [405715480](https://github.com/dotnet/roslyn/pull/43181#discussion_r405715480) [](ancestors = 405715480,405714806)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: > See PropertyTests.CanNotReadPropertyFromAmbiguousGenericClass() for a test that fails without this.

How exactly does it fail?

---
In reply to: [405765060](https://github.com/dotnet/roslyn/pull/43181#discussion_r405765060) [](ancestors = 405765060,405715480,405714806)

Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: The following error is reported:
```
(4,16): error CS0433: The type 'A<T>' exists in both
    '_0_09f9df97-a228-4ca4-9b71-151909f205e6, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and
    '_0_09f9df97-a228-4ca4-9b71-151909f205e6, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```
instead of:
```
(4,16): error CS0104: 'A<>' is an ambiguous reference between 'A<T>' and 'A<T>'
```

---
In reply to: [405767894](https://github.com/dotnet/roslyn/pull/43181#discussion_r405767894) [](ancestors = 405767894,405765060,405715480,405714806)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:577]: I think we should accept the baseline change. I think the original behavior (pay attention to mangling) was not intentional and from the language point of view both types have the same name.

---
In reply to: [405774516](https://github.com/dotnet/roslyn/pull/43181#discussion_r405774516) [](ancestors = 405774516,405767894,405765060,405715480,405714806)

**Comment by 333fred** [comment]
This might actually be the root cause of https://github.com/dotnet/roslyn/issues/37345, which was noticing string allocations in a mainline csc execution.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:556]: [https://github.com/dotnet/roslyn/issues/43206](https://github.com/dotnet/roslyn/issues/43206)

---
In reply to: [405648673](https://github.com/dotnet/roslyn/pull/43181#discussion_r405648673) [](ancestors = 405648673)

**Comment by jcouv** [comment]
@cston This fix may be fixing another as well (looking for `BindTypeOrAlias`: https://github.com/dotnet/roslyn/issues/41707
