### PR TITLE
🧹 Fix prototype comments in inheritdoc implementation

### LINKED ISSUE #53885: Some prototype markers snuck into Compilers.sln
```
        private static XNode[]? RewriteInheritdocElement(ISymbol memberSymbol, HashSet<ISymbol>? visitedSymbols, Compilation compilation, XElement element, CancellationToken cancellationToken)
        {
...
                if (loadedElements?.Length > 0)
                {
                    // change the current XML file path for nodes contained in the document:
                    // prototype(inheritdoc): what should the file path be?
                    var result = RewriteMany(symbol, visitedSymbols, compilation, loadedElements, cancellationToken);

                    // The elements could be rewritten away if they are includes that refer to invalid
                    // (but existing and accessible) XML files.  If this occurs, behave as if we
                    // had failed to find any XPath results (as in Dev11).
                    if (result.Length > 0)
                    {
                        return result;
                    }
                }

                return null;
            }
...

            // Local functions
            static ISymbol? GetCandidateSymbol(ISymbol memberSymbol)
            {
...
                else if (memberSymbol is INamedTypeSymbol typeSymbol)
                {
                    if (typeSymbol.TypeKind == TypeKind.Class)
                    {
                        // prototype(inheritdoc): when does base class take precedence over interface?
                        return typeSymbol.BaseType;
                    }
                    else if (typeSymbol.TypeKind == TypeKind.Interface)
                    {
                        return typeSymbol.Interfaces.FirstOrDefault();
                    }
                    else
                    {
                        // This includes structs, enums, and delegates as mentioned in the inheritdoc spec
                        return null;
                    }
                }

                return memberSymbol.ExplicitOrImplicitInterfaceImplementations().FirstOrDefault();
            }
...
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #53885
Resolves https://github.com/dotnet/roslyn/pull/36028#discussion_r306507124

### CODE REVIEW

File: src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs [hunk 1]
```diff
@@ -425,27 +426,7 @@ private static XNode[] RewriteMany(ISymbol symbol, HashSet<ISymbol>? visitedSymb
...
-                    // (but existing and accessible) XML files.  If this occurs, behave as if we
-                    // had failed to find any XPath results (as in Dev11).
-                    if (result.Length > 0)
-                    {
-                        return result;
-                    }
-                }
-
-                return null;
+                return loadedElements ?? Array.Empty<XNode>();
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs:429]: 📝 Details for this change given in commit message

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by jcouv** [comment]
Thanks!

**Comment by davkean** [comment]
@sharwell Heads up this, this introduced a UI delay: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385578.
