### PR TITLE
Fix few false positives in unused value assignment analyzer

### LINKED ISSUE #33843: Invalid IDE0059 (value never used) with using and local function capture
**Version Used**: 
16.0.0 RC

**Steps to Reproduce**:

```csharp
private class Disposable: IDisposable { public void Dispose() { } }
public int M()
{
    var result = 0;
    void append() => result += 1; // IDE0059 for 'result'
    using (var a = new Disposable())
        append();
    return result;
}
```

**Expected Behavior**:
No message, everything is used as expected.

**Actual Behavior**:
IDE0059 is triggered within the local function. Applying the code fix changes the local function to the invalid
```csharp
void append() => 1;
```

Not only the using is required, but also the assignment within. Removing `var a = ` from the sample also removes IDE0059.

### LINKED ISSUE #33937: IDE0059 doesn't realize assignment before rethrow is read in finally block
**Version Used**: VS 2019 RC.1 SVC 1

```cs
using System;

public static class Program
{
    public static void Main()
    {
        try
        {
            Test();
        }
        catch (Exception)
        {
        }
    }

    public static void Test()
    {
        var exceptionThrown = false;
        try
        {
            throw new Exception();
        }
        catch
        {
            // The `exceptionThrown` token is incorrectly greyed out in the IDE
            // IDE0059 Value assigned to 'exceptionThrown' is never used
            exceptionThrown = true;
            throw;
        }
        finally
        {
            // Breakpoint on this line is hit and 'true' is printed
            Console.WriteLine(exceptionThrown);
        }
    }
}
```

### LINKED ISSUE #33949: Unused Assignment false positive
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L3893

This is flagged as an unused assignment, but it is used.

Update: I got a minimal repro, which requires a conditional expression as an argument prior to the read.

```csharp
class A
{
    public static void M(int? x)
    {
        A a = new A();
        a = M2(x ?? 1, a);
    }

    private static A M2(int? x, A a)
    {
        return a;
    }
}
```

### PR DESCRIPTION
**Pull request by mavasani**
I would recommend reviewing commit by commit for each of the following fixes:

1. https://github.com/dotnet/roslyn/commit/a7e07f77f60663bd952f97135275faee25460c3b: Handle assignment with flow capture reference target similar to the way we handle non-flow capture reference assignment targets in the SymbolUsageAnalysis walker. Fixes #33949
2. https://github.com/dotnet/roslyn/commit/57ca50f3502d060f4be8381afca1ce969b91ac42: Fix logic that computes reachable writes into the finally region. Fixes #33843
3. https://github.com/dotnet/roslyn/commit/3f0b73c076d01799fcff26a6cf4fae4ebf2e5b70: Fix dataflow walker to walk the finally regions from throw/rethrow branches. Fixes #33937

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
CFG stuff is complex enough for me that i won't be able to get to this until early next week most likely.  So don't gate on me!

**Comment by mavasani** [comment]
Thanks @CyrusNajmabadi

Ping @heejaechang @genlu for review. Thanks

**Comment by mavasani** [comment]
Ping @heejaechang @genlu for review - I'd like to merge this in this week before I go on vacation. Thanks!

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs [hunk 1]
```diff
@@ -195,6 +189,100 @@ private PooledHashSet<(ISymbol, IOperation)> GetOrCreateSymbolWritesInBlockRange
...
                 }
 
+                private void AddOperationsInRange(
+                    ControlFlowGraph cfg,
+                    int firstBlockOrdinal,
+                    int lastBlockOrdinal,
+                    PooledHashSet<IOperation> operationsBuilder)
+                {
+                    // Compute all descendant operations in basic block range.
+                    for (int i = firstBlockOrdinal; i <= lastBlockOrdinal; i++)
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs]: do these need cancellation token? asking since loop seems could be big?

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs [hunk 2]
```diff
@@ -145,50 +145,61 @@ private void OnReferenceFound(ISymbol symbol, IOperation operation)
...
 
-                    return false;
+                    set.Add((symbolOpt, operation));
+                    return true;
                 }
-            }
 
+                return false;
+            }
             private void ProcessPendingWritesForAssignmentTarget(IAssignmentOperation operation)
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs]: new line missing?

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs [hunk 3]
```diff
@@ -145,50 +145,61 @@ private void OnReferenceFound(ISymbol symbol, IOperation operation)
...
-                        var set = PooledHashSet<(ISymbol, IOperation)>.GetInstance();
-                        set.Add((symbol, operation));
-                        _pendingWritesMap.Add(assignmentOperation, set);
-                        return true;
-                    }
-                    else if (operation.IsInLeftOfDeconstructionAssignment(out var deconstructionAssignment))
+                    var set = PooledHashSet<(ISymbol, IOperation)>.GetInstance();
+                    set.Add((symbolOpt, operation));
+                    _pendingWritesMap.Add(assignmentOperation, set);
+                    return true;
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs]: who put this pooled set back?

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs (hunk 1 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs]: Sure, I can thread in the cancellation token through the dataflow walker API

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs (hunk 3 above)
Comment (heejaechang) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs]: found it.

Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs]: Ah, it should be done here: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs,195, but seems I forgot to release. I will fix it.

Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs]: Actually seems I did it here: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs,73 :)

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs [hunk 4]
```diff
@@ -195,6 +189,100 @@ private PooledHashSet<(ISymbol, IOperation)> GetOrCreateSymbolWritesInBlockRange
...
+                        }
+                    }
+
+                    return;
+
+                    // Local functions.
+                    void AddOperationsFromDelegateCreationTargets(PooledHashSet<IOperation> targets)
+                    {
+                        foreach (var target in targets)
+                        {
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs]: can this be.. like GetDecedentControlFlowGraph API? it would be hard for anyone except you would know what all controlflowgraph they need to take care for all sub tree operations..

Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs]: Sure, I will rename it.

**Comment by mavasani** [comment]
@sharwell integration test failure: https://dev.azure.com/dnceng/public/_build/results?buildId=127574

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/34247 with logs and screenshots for integration test failure.
