### PR TITLE
Fix analyzer conflicts on Linux

### LINKED ISSUE #65415: Analyzer / generator shadow load directory needs to be per user on Unix
Context: https://github.com/dotnet/runtime/issues/77723

The root cause of this problem is the temp directory on Unix is the global one while on Windows it's per user. Hence there is a bit of a disconnect on how the shadow copy logic works there. Need to add a user component to the path on Unix to make things consistent here. 

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### PR DESCRIPTION
**Pull request by jaredpar**
This changes analyzer loading on Linux to be per user where before clashes could occur in the temp directory.

This fix initially started out by making our temp directory logic more robust. Essentially add per user sub directories, do extended permission checks, etc ... That exacerbated a number of existing corner cases in the code and forced us to put a lot more error handling into the workspaces layer.

After discussion with the IDE team I decided to take the approach of loading from a `Stream` on non-Windows platforms. The performance difference is neglible (1ms to 2ms per assembly) and it removes the overhead of copying them around on disk as well as the complexities that come with managing the shadow copy directory.

This will be observable to any analyzer that used `Assembly.Location` as it will now be `""`. That is only useful though for inspecting disks which is already illegal for analyzers hence it's considered an acceptable break.

To test the performance of this change I wrote a simple benchmark that loads assemblies directly from path, copy then load (simulate shadow copy) and loading them from stream. The results on Windows is pretty striking

|Method | Mean | Error | StdDev | Median|
-- | -- | -- | -- | --| 
|LoadViaPath | 1.552 ms | 0.0387 ms | 0.1142 ms | 1.529 ms|
|LoadViaPathShadow | 33.147 ms | 0.9000 ms | 2.6537 ms | 33.883 ms|
|LoadViaStream | 495.945 ms | 9.5040 ms | 9.7599 ms | 493.297 ms|

Notice the penalty of `LoadFromStream` is severe on Windows. That is due to the AV having to run on every load since it can't cache like it can when loading from path. On Linux though the results are much nicer

|Method | Mean | Error | StdDev | Median|
|-- | -- | -- | -- | --|
|LoadViaPath | 1.301 ms | 0.0258 ms | 0.0326 ms | 1.299 ms|
|LoadViaPathShadow | 4.126 ms | 0.3567 ms | 1.0060 ms | 3.742 ms|
|LoadViaStream | 2.514 ms | 0.0501 ms | 0.0536 ms | 2.497 m|

This means the change should be a small win on Linux but probably not in the noticable range. 

closes #65415

### CODE REVIEW

File: src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs [hunk 1]
```diff
@@ -18,6 +18,7 @@ internal sealed class RemoteAnalyzerAssemblyLoader : AnalyzerAssemblyLoader
 
         public RemoteAnalyzerAssemblyLoader(string baseDirectory)
         {
+            // jason should we load from stream here on Linux or is this VS only?
```
Comment (jaredpar) [inline src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs:21]: @jasonmalinowski I wanted you to look at this. The current state is always loading directly from disk (no shadow copy) and confirm it is the correct decision. If so I'll just leave this file alone (maybe add a comment to the effect). If this runs on Linux we could consider doing a stream based load here.

File: src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
Comment (jjonescz) [inline src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs:1]: > This will be observable to any analyzer that used `Assembly.Location` as it will now be `""`. That is only useful though for inspecting disks which is already illegal for analyzers hence it's considered an acceptable break.

Should this be documented in [breaking API changes](https://github.com/dotnet/roslyn/blob/main/docs/Breaking%20API%20Changes.md) or similar doc?

Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs:1]: Would not hurt to put it in there.

File: docs/Breaking API Changes.md [hunk 2]
```diff
@@ -87,4 +87,12 @@ All `SymbolDisplayFormat`s (predefined and user-created) now include parameter n
...
 when the input to the step was modified in a way that produced a new output.
-Now the reason will be reported more accurately as `IncrementalStepRunReason.New`.
\ No newline at end of file
+Now the reason will be reported more accurately as `IncrementalStepRunReason.New`.
+
+# Version 4.8.0
+
+### Changed `Assembly.Location` behavior in non-Windows
+
+The value of `Assembly.Location` previously held the location on disk where an analyzer or source generator was loaded from. This could be either the original location or the shadow copy location. In 4.8 this will be `""` in certain cases when running on non Windows platforms. This is due the compiler server loading assemblies using `AssemblyLoadContext.LoadFromStream` instead of loading from disk.
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply docs/Breaking API Changes.md:96]: Yes we should do that.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs [hunk 3]
```diff
@@ -11,19 +11,46 @@
...
         private readonly AssemblyLoadContext _compilerLoadContext;
         private readonly Dictionary<string, DirectoryLoadContext> _loadContextByDirectory = new Dictionary<string, DirectoryLoadContext>(StringComparer.Ordinal);
+        private readonly AnalyzerLoadOption _loadOption;
 
         internal AssemblyLoadContext CompilerLoadContext => _compilerLoadContext;
+        internal AnalyzerLoadOption AnalyzerLoadOption => _loadOption;
 
-        internal AnalyzerAssemblyLoader(AssemblyLoadContext? compilerLoadContext = null)
+        internal AnalyzerAssemblyLoader()
+            : this(null, AnalyzerLoadOption.LoadFromDisk)
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs:47]: This constructor is tricky cause because of how our multi-targeting works out you have to provide an empty constructor in every target framework. Not having one requires us to push a lot more complexity through the workspaces layer. The default constructor in both cases though is "load from disk at the current path" and this meets that.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs [hunk 4]
```diff
@@ -17,14 +18,19 @@ internal sealed class DefaultAnalyzerAssemblyLoader : AnalyzerAssemblyLoader
     {
 #if NETCOREAPP
 
-        // Called from a netstandard2.0 project, so need to ensure a parameterless constructor is available.
         internal DefaultAnalyzerAssemblyLoader()
             : this(null)
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs:22]: I was worried about spreading around the _default_ values too much. Just realized though that after my latest changes I can just delete the ctor chaining entirely here and let it fall back to the empty constructor on the base.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs [hunk 5]
```diff
@@ -36,5 +42,42 @@ internal DefaultAnalyzerAssemblyLoader(System.Runtime.Loader.AssemblyLoadContext
...
         /// <returns></returns>
         protected override string PreparePathToLoad(string fullPath) => fullPath;
+
+        /// <summary>
+        /// Return an <see cref="IAnalyzerAssemblyLoader"/> which does not lock assemblies on disk that is
+        /// most appropriate for the current platform.
+        /// </summary>
+        /// <param name="windowsShadowPath">A shadow copy path will be created on Windows and this value 
+        /// will be the base directory where shadow copy assemblies are stored. </param>
+        internal static IAnalyzerAssemblyLoader CreateNonLockingLoader(string? windowsShadowPath = null)
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs:52]: The issue with making this required is that every consumer must provide a value on every operating system. Even though tis value is not used on Linux / Mac customers still must provide it. That will push consumers to use either `Path.GetTempPath` which will trigger scrutiny as it's an API to avoid for cases like this or invent a location on disk that we'll never actually use. Basically it makes call sites complicated and error prone. 

The current setup is meant to avoid that. By default the implementation will choose an appropriate and safe location. In the cases where you are comfortable picking a shadow copy path then you are free to do so.

**Review by RikkiGibson — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs]: Chatted offline and decided to make it mandatory.

**Review by jjonescz — APPROVED** [review]

File: docs/Breaking API Changes.md [hunk 6]
```diff
@@ -87,4 +87,12 @@ All `SymbolDisplayFormat`s (predefined and user-created) now include parameter n
 
 `IncrementalGeneratorRunStep.Outputs` previously contained `IncrementalStepRunReason.Modified` as `Reason`
 when the input to the step was modified in a way that produced a new output.
-Now the reason will be reported more accurately as `IncrementalStepRunReason.New`.
\ No newline at end of file
+Now the reason will be reported more accurately as `IncrementalStepRunReason.New`.
+
+# Version 4.8.0
+
+### Changed `Assembly.Location` behavior in non-Windows
```
Comment (jasonmalinowski) [inline docs/Breaking API Changes.md:94]: Might want to adjust the title to say something about analyzers/generators so the context is clearer from the outset.

Comment (jasonmalinowski) [inline docs/Breaking API Changes.md:94]: Massive kudos for remembering to update the docs!

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs [hunk 7]
```diff
@@ -114,11 +141,24 @@ public DirectoryLoadContext(string directory, AnalyzerAssemblyLoader loader, Ass
...
+                Assembly loadCore(string assemblyPath)
+                {
+                    if (_loader.AnalyzerLoadOption == AnalyzerLoadOption.LoadFromDisk)
+                    {
+                        return LoadFromAssemblyPath(assemblyPath);
+                    }
+                    else
+                    {
+                        using var stream = File.Open(assemblyPath, FileMode.Open, FileAccess.Read, FileShare.Read);
+                        return LoadFromStream(stream);
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs:159]: Random question: for the performance penalty on Windows due the virus scanner, is that because .NET is explicitly invoking the virus scanner on the stream data, or just because the virus scanner doesn't see this as a memory mapped file?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs [hunk 8]
```diff
@@ -17,14 +18,18 @@ internal sealed class DefaultAnalyzerAssemblyLoader : AnalyzerAssemblyLoader
     {
 #if NETCOREAPP
 
-        // Called from a netstandard2.0 project, so need to ensure a parameterless constructor is available.
         internal DefaultAnalyzerAssemblyLoader()
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs:21]: To @RikkiGibson's other question -- do we need this still? Because I don't quite understand the comment here that we had a net2.0 project calling something #ifdef'ed in a NETCOREAPP TFM?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs [hunk 9]
```diff
@@ -36,5 +41,42 @@ internal DefaultAnalyzerAssemblyLoader(System.Runtime.Loader.AssemblyLoadContext
...
+
+        /// <summary>
+        /// Return an <see cref="IAnalyzerAssemblyLoader"/> which does not lock assemblies on disk that is
+        /// most appropriate for the current platform.
+        /// </summary>
+        /// <param name="windowsShadowPath">A shadow copy path will be created on Windows and this value 
+        /// will be the base directory where shadow copy assemblies are stored. </param>
+        internal static IAnalyzerAssemblyLoader CreateNonLockingLoader(string windowsShadowPath)
+        {
+#if NETCOREAPP
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs:53]: If you restructure this as:

```csharp
#if NETCOREAPP
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    return new DefaultAnalyzerAssemblyLoader(loadOption: AnalyzerLoadOption.LoadFromStream);
}
#endif
// (the contents of createShadowLoaderWindows)
```

You can shorten this up a bit and also remove the local function. That might make it a bit clearer that we are only doing something special on NETCOREAPP and non-Windows.

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 10]
```diff
@@ -34,16 +34,6 @@ internal sealed class BuildServerConnection
...
         /// </summary>
-        /// <remarks>
-        /// Even though compilation itself does not specifically require a temporary directory to be successful
-        /// this API deliberately requires <paramref name="tempDirectory"/> to have a value. The reason for this is
-        /// that the server itself requires a temporary directory to startup and it uses the same logic as the client
-        /// to calculate it.
-        /// 
-        /// That means if the client can't calculate the temporary directory the server won't be able to either and 
-        /// hence won't be able to start. So creating <see cref="BuildRequest"/> instances isn't useful cause it's 
-        /// wasting time trying to start a server that won't be able to start.
```
Comment (jasonmalinowski) [inline src/Compilers/Shared/BuildServerConnection.cs:45]: Does this need some other comment then explaining tempDirectory?

File: src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs:21]: This file isn't used on Linux, so your question may be somewhat moot. But the comment here makes me think that this kicks in if we're loading analyzers that shipped in Roslyn itself, so reading directly from disk is fine since there's not locking concerns in the first place.

Comment (jasonmalinowski) [reply src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs:21]: @genlu may also want to chime in here.

**Review by jasonmalinowski — COMMENTED** [review]
Some comments left but nothing concerning -- I would have signed off on the original PR (except for that line tagging me. :smile:)

File: src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs (hunk 1 above)
Comment (genlu) [reply src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs:21]: Yes, the sole purpose of this is to load our own assemblies in ServiceHub process

File: docs/Breaking API Changes.md (hunk 6 above)
Comment (jaredpar) [reply docs/Breaking API Changes.md:94]: Kudos go to @jjonescz for reminding me to do this 

https://github.com/dotnet/roslyn/pull/69406#discussion_r1286816066

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs:159]: The runtime team said it has to do with caching. When the file is on disk, even when it's copied, the scans can be cached, while when it's in memory they cannot be. Feels like you could still do a SHA-256 cache but right now this is the reality 😦

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs (hunk 8 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs:21]: There is a need for a parameterless ctor but I think it can be pulled out of the `#if` now and just have a single one.

File: src/Compilers/Shared/BuildServerConnection.cs (hunk 10 above)
Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs:45]: The history of this comment is I added at the start of an earlier PR. Then some feedback came in and I realized this invariant was wrong and restructured the PR but I forgot to delete the comment. It was pointed out to me post merge and I deleted it at the start of this PR. 

So basically this never should have existed in the first place.
