### PR TITLE
Nullability attributes in user-defined conversions

### LINKED ISSUE #39802: NotNullIfNotNull is not working with implicit operator
Probably Roslyn compiler ignores `NotNullIfNotNullAttribute` when it is applied to `implicit operator`.
Let's assume that we have a class
```csharp
public sealed class Foo
{
  private readonly int value;
  
  internal Foo(int value) => this.value = value;

  [return: NotNullIfNotNull("foo")]
  public static implicit operator string?(Foo? foo) => foo is null ? null : foo.value.ToString();
 }
```
Now we can convert it into `string` implicitly as follows:
```csharp
string str = new Foo(10);
```
In this case the compiler emits CS8600 warning: `Converting null literal or possible null value to non-nullable type`. However, it is obviously that `new` operator is null-safe.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #39802

This doesn't implement analysis of nullability attributes for other kinds of user-defined operators.

When I started working on this, I had hoped to make use of `VisitArguments` or similar calls, to try and treat user-defined conversions similar to analysis of regular method calls. But I just don't think it makes sense. Either you thread the complexity of lifted conversions into VisitArguments, etc., or you thread the complexity of NotNullIfNotNull into VisitUserDefinedConversion. The latter seemed easier.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -6944,12 +6945,26 @@ static bool dependsOnTypeParameter(TypeParameterSymbol typeParameter1, TypeParam
...
+            }
+
             // method parameter type -> method return type
             var methodReturnType = methodOpt.ReturnTypeWithAnnotations;
             operandType = GetLiftedReturnTypeIfNecessary(isLiftedConversion, methodReturnType, operandState);
-            if (!isLiftedConversion)
+            if (!isLiftedConversion || operandState.IsNotNull())
             {
-                // Analyze operator call return value (honoring [Maybe|NotNull] attribute annotations) https://github.com/dotnet/roslyn/issues/32671
+                var returnNotNull = operandState.IsNotNull() && methodOpt.ReturnNotNullIfParameterNotNull.Contains(parameter.Name);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6959]: >methodOpt [](start = 64, length = 9)

nit: can we rename `methodOpt` to `method`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -6944,12 +6945,26 @@ static bool dependsOnTypeParameter(TypeParameterSymbol typeParameter1, TypeParam
...
+            if (!isLiftedConversion)
+            {
+                CheckDisallowedNullAssignment(operandType, parameterAnnotations, conversionOperand.Syntax.Location);
+            }
+
             // method parameter type -> method return type
             var methodReturnType = methodOpt.ReturnTypeWithAnnotations;
             operandType = GetLiftedReturnTypeIfNecessary(isLiftedConversion, methodReturnType, operandState);
-            if (!isLiftedConversion)
+            if (!isLiftedConversion || operandState.IsNotNull())
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6957]: Do we need the ` || operandState.IsNotNull()` part here?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6957]: Hmm. Perhaps I should move the comment on line 6948 down here for clarity. It sort of applies to both of the checks.

Basically the `operandState.IsNotNull()` is necessary because in the case where we `isLiftedConversion` is true, we assume the operand must be not-null in order for the user-defined conversion operator to actually be called, and thus any postconditions on the return value should be respected.

A test which is affected by this condition is `UserDefinedConversion_UnconditionalParamAttributes_Lifted`. See `struct C` and `struct D`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -6919,7 +6919,8 @@ static bool dependsOnTypeParameter(TypeParameterSymbol typeParameter1, TypeParam
             Debug.Assert(operandType.Type is object);
 
             var parameter = methodOpt.Parameters[0];
-            var parameterType = parameter.TypeWithAnnotations;
+            var parameterAnnotations = GetParameterAnnotations(parameter);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6922]: Looking through this file there are a number of places where we still use `parameter.TypeWithAnnotations` vs. `GetParameterAnnotations`. Why did we need to update this call and have we audited the other uses in this file to see if they would benefit from `GetParameterAnnotations`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6922]: Basically if you just access something like the TypeWithAnnotations on a symbol, and you don't try to "fold in" the FlowAnalysisAnnotations on that symbol into the TypeWithAnnotations, you probably have bugs related to nullability attributes. It does feel like there should be something like `GetAdjustedTypeWithAnnotations()` (strawman name) on certain kinds of symbols in order to make it easier to do the right thing.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6922]: To clarify, I think such a refactoring should be attempted in a separate PR.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -28476,6 +28476,263 @@ void M2()
...
+        public void UserDefinedConversion_UnconditionalParamAttributes_Lifted()
+        {
+            var source = @"
+using System.Diagnostics.CodeAnalysis;
+
+public struct A { }
+
+public struct B
+{
+    public static implicit operator A([DisallowNull] B b)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28616]: >[DisallowNull] [](start = 38, length = 14)

What does `[DisallowNull]` mean for a user-defined conversion operand that is a value type?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -28476,6 +28476,263 @@ void M2()
...
+        M0((C?)null);
+
+        M1((C?)new C());
+        M1((C?)null); // 2
+    }
+}
+
+public struct D
+{
+    [return: NotNullIfNotNull(""d"")]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28657]: >NotNullIfNotNull(""d"") [](start = 13, length = 23)

`d` is never `null`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6922]: Let's file a follow up issue to look at this. Just looking around in this file I see lots of instances of the pattern that you fixed here. It's possible those are intentional but if so think it would help to have both a helper method like you suggested plus a declarative method of stating "I have reasons for just acessing TWA directly here".

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28616]: Curious what it means for both the operator and the lifted version of the operator.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6922]: Opened #47635

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28616]: Here I was trying to verify that the attribute doesn't affect anything, on a non-nullable operator lifted to nullable, and on a nullable operator lifted to return nullable. The only situation where we believe the operator will be called is if the argument is non-nullable, in which case there is nothing for the DisallowNullAttribute to verify.

If these tests seem too inconsequential I can delete them.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28657]: I wanted to verify that this postcondition is respected, even in this contrived scenario, but it feels maybe interesting for the input to be System.Nullable for this and for `operator A?(C c)` above.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28657]: I think that although this is not a reasonable real-world coding pattern (user should just use [NotNull] instead), it is good to record the behavior of this scenario. I may get rid of `[DisallowNull]`, though.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -28476,6 +28476,263 @@ void M2()
...
+        public void UserDefinedConversion_UnconditionalReturnAttributes()
+        {
+            var source = @"
+using System.Diagnostics.CodeAnalysis;
+
+public struct A { }
+public struct B
+{
+    [return: NotNull]
+    public static implicit operator A?(B? b)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28700]: Consider testing `[return: NotNull] public static implicit operator A(B b) => new A();` with conversion from `B?`, to ensure we treat the result as `A?`.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28616]: Think the test is fine and important. The code is indeed non-sense but it's legal for users to write this and we should verify that we behave as expected. I would suggest a comment noting that the intent here is to verify we correctly do nothing special.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6957]: Alternatively, we could make this part unconditional, and add something afterwards like `if (isLiftedConversion) operandType = operandType.WithState(operandType.State.Join(NullableFlowState.MaybeNull));`. But just it achieves the same behavior while doing a bit more work.

**Comment by eerhardt** [comment]
Will this make it into the compiler that ships with .NET 5.0?

The reason I'm asking is because we annotated `XElement` in 5.0, and this issue is causing the typical way of creating an `XElement` to report incorrect nullable errors.

image

**Comment by RikkiGibson** [comment]
> Will this make it into the compiler that ships with .NET 5.0?

Yes.
