### PR TITLE
Add tests to demonstrate that a bug is fixed

### LINKED ISSUE #20724: SpeculativeSemanticModel returns error type on binary expression containing is-pattern.
Repro steps:

Sync to https://github.com/dotnet/roslyn/pull/20723/commits/3bba6c7c3810d922b4ca08fd2142e86e01eedda3

Build and run Roslyn.  (i.e. select VisualStudioSetup.Next and f5 to launch the experimental hive) 
Use the following steps to try to generate a .Equals  method:

1. Create this code:

```c#
    public class Class1
    {
        int i;   // go to the line after this and hit ctrl-dot

        
    }
```

2. Hit ctrl-dot and pick "Generate Equals(object)" 

image

This generates:

```C#
    public class Class1
    {
        int i;

        public override bool Equals(object obj)
        {
            return obj is global::Class1 @class &&
                   this.i == @class.i;
        }
    }
```

Instead of 

```c#
    public class Class1
    {
        int i;

        public override bool Equals(object obj)
        {
            return obj is Class1 @class &&
                   this.i == @class.i;
        }
    }
```

i.e. we are not simplifying "global::Class1" to "Class1".  The reason that is not simplified is due to the following callstack:

```
>	Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(node, cancellationToken) Line 1007	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(expression, cancellationToken) Line 878	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(node, cancellationToken) Line 4592	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoCore(node, cancellationToken) Line 4695	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.SemanticModel.GetTypeInfo(node, cancellationToken) Line 220	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.ModelExtensions.GetTypeInfo(semanticModel, node, cancellationToken) Line 60	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CommonForEachStatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ThrowStatementSyntax, Microsoft.CodeAnalysis.CSharp.Conversion>.TypesAreCompatible(originalExpression, newExpression) Line 220	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Utilities.SpeculationAnalyzer.ReplacementBreaksBinaryExpression(binaryExpression, newBinaryExpression) Line 598	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Utilities.SpeculationAnalyzer.ReplacementChangesSemanticsForNodeLanguageSpecific(currentOriginalNode, currentReplacedNode, previousOriginalNode, previousReplacedNode) Line 286	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CommonForEachStatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ThrowStatementSyntax, Microsoft.CodeAnalysis.CSharp.Conversion>.ReplacementChangesSemanticsForNode(currentOriginalNode, currentReplacedNode, previousOriginalNode, previousReplacedNode) Line 499	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CommonForEachStatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ThrowStatementSyntax, Microsoft.CodeAnalysis.CSharp.Conversion>.ReplacementChangesSemantics(currentOriginalNode, currentReplacedNode, originalRoot, skipVerificationForCurrentNode) Line 429	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CommonForEachStatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ThrowStatementSyntax, Microsoft.CodeAnalysis.CSharp.Conversion>.ReplacementChangesSemantics() Line 408	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.CanReplaceWithReducedName(name, reducedName, semanticModel, cancellationToken) Line 2055	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduce(name, semanticModel, replacementNode, issueSpan, optionSet, cancellationToken) Line 1579	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceExplicitName(expression, semanticModel, replacementNode, issueSpan, optionSet, cancellationToken) Line 695	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceOrSimplifyExplicitName(expression, semanticModel, replacementNode, issueSpan, optionSet, cancellationToken) Line 663	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.SimplifyName(node, semanticModel, optionSet, cancellationToken) Line 49	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyNode<Microsoft.CodeAnalysis.SyntaxNode>(node, newNode, parentNode, simplifier) Line 125	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyExpression<Microsoft.CodeAnalysis.SyntaxNode>(expression, newNode, simplifier) Line 149	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitQualifiedName(node) Line 65	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 150	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitDeclarationPattern(node) Line 3046	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.DeclarationPatternSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 6743	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIsPatternExpression(node) Line 3026	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.IsPatternExpressionSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 6502	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitParenthesizedExpression(node) Line 2576	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedExpressionSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 1237	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBinaryExpression(node) Line 2647	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitBinaryExpression(node) Line 181	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.BinaryExpressionSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 2066	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitReturnStatement(node) Line 3212	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Syntax.ReturnStatementSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(visitor) Line 8635	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(node) Line 37	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.VisitNodeOrToken(nodeOrToken, semanticModel, simplifyAllDescendants) Line 188	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CrefSyntax>.ReduceAsync.AnonymousMethod__0() Line 248	C#	Symbols loaded.
```

We bind ```(obj is global::ClassLibrary.Class1 @class) && ((this.i) == (@class.i))``` in the real semantic model and it returns 'boolean' (correct).  We then bind ```(obj is Class1 @class) && ((this.i) == (@class.i))``` in the speculative semantic model and we get an Error type back.  Because of this we do not simplify the expression.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #20724

@cston @agocke @dotnet/roslyn-compiler May I please have a review of this test-only addition?

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs [hunk 1]
```diff
@@ -1911,5 +1911,75 @@ static bool Test(C<T> x)
...
+            var modifiedReturnStatement = (ReturnStatementSyntax)new RemoveAliasQual().Visit(returnStatement);
+            Assert.Equal("return obj is Class1 @class;", modifiedReturnStatement.ToString());
+            var gotModel = model.TryGetSpeculativeSemanticModel(returnStatement.Location.SourceSpan.Start, modifiedReturnStatement, out var speculativeModel);
+            Assert.True(gotModel);
+            Assert.NotNull(speculativeModel);
+            var typeInfo = speculativeModel.GetTypeInfo(modifiedReturnStatement.Expression);
+            Assert.Equal(SpecialType.System_Boolean, typeInfo.Type.SpecialType);
+        }
+
+        class RemoveAliasQual : CSharpSyntaxRewriter
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs]: Perhaps `private class RemoveAliasQualifier`.
