### PR TITLE
CanAddNullCheck update for nullable reference types

### LINKED ISSUE #41428: Generate constructor incorrectly adds null checks for nullable propeties in c#8
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/902752/generate-constructor-incorrectly-adds-null-checks.html)._

---
If you declare an immutable class in c# 8 with explicit nullable references enabled:

```csharp
class Foo
{
  public string Prop1 {get;}
  public string? Prop2 {get;}
}
```

And then choose the quick action to generate a constructor with the "Add null checks" checkbox ticked, it creates a constructor that adds null checks for both Prop1 and Prop2.

When a property is explicitly marked nullable as Prop2 is above, I think the generated constructor shouldn't include null checks for it.

---
#### Visual Studio Feedback System on 2/3/2020, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by faso**
Fixes #41428

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Hi FSO.  Thanks for the contribution!

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs [hunk 1]
```diff
@@ -23,7 +23,11 @@ internal static partial class ITypeSymbolExtensions
         private const string DefaultBuiltInParameterName = "v";
 
         public static bool CanAddNullCheck([NotNullWhen(returnValue: true)] this ITypeSymbol? type)
+#if CODE_STYLE // TODO: Remove this #if once 'WithNullableAnnotation' and 'NullableAnnotation' are available in CodeStyle layer.
             => type != null && (type.IsReferenceType || type.IsNullable());
+#else
+            => type != null && ((type.IsReferenceType && type.NullableAnnotation != NullableAnnotation.Annotated) || type.IsNullable());
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs:29]: logic seems sound.  However:

1. this line has gotten too long (beyond the wdith of github).
2. the expression is getting too complex.  i.e. all the mixsing of &&, != and || just makes it hard to read.  Can you convert this to a simple method body with statements that are checking the cases clearly?  Thanks!

Other than this, we just need tests.  But we'd def take this once you add that.  Thanks!

Comment (faso) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs]: Pushed an update to implement your feedback

Comment (faso) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs]: Pushed a test. I assume I need more tests, but I am having trouble figuring out what/where they should be. Any pointers about this would be welcome! (also pushed a fix for a random typo I found, hope that's okay)

**Comment by CyrusNajmabadi** [comment]
Can you add a test with generics where the type parameter is constrained on 'class' and the field looks like 'T?'. Thanks!

**Comment by faso** [comment]
> 
> 
> Can you add a test with generics where the type parameter is constrained on 'class' and the field looks like 'T?'. Thanks!

Done

File: src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs [hunk 2]
```diff
@@ -1002,6 +1002,84 @@ class Z
...
+using System.Collections.Generic;
+#nullable enable
+
+class Z<T> where T : class
+{
+    int a;
+    string b;
+    T? c;
+
+    public Z(int a, string b, T c{|Navigation:)|}
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs:1072]: looks like the `T?` was lost here.  intentional? a remaining bug?

Comment (faso) [reply src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs:1072]: Remaining bug. Was going to open a separate issue for it, since this one is about the generated null checks.

Should I look it in the scope of this issue? I'm up to fix it.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs:1072]: if it's cheap to fix, go for it :)

otehrwise, we can open a new issue.  Up to you! :)

Comment (faso) [reply src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs:1072]: I'm working on it, but my local environment has broken down for some reason, so this might take a little while. If it's better to merge this PR instead of waiting for me to fix the other issue, I'll open a new issue for this.

**Comment by faso** [comment]
Ugh, my local environment is somehow absolutely broken, I think a full reinstall needs to take place. 

Let's just merge this one as is and in the meantime I'll continue working on the other bug? Don't want to leave a PR hanging for a long time.

**Comment by CyrusNajmabadi** [comment]
Thanks for the contribution!
