### PR TITLE
Validate FunctionId does not contain duplicate values

### LINKED ISSUE #43607: FunctionId cannot contain duplicate values
When FunctionId contains duplicate values, integration tests can start to fail with a dialog reporting the following error:

```
SetSite failed for package [Roslyn Diagnostics Window]Source: 'mscorlib' Description: An item with the same key has already been added.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Internal.Log.Logger.GetLoggingChecker(IGlobalOptionService optionService)
   at Roslyn.VisualStudio.DiagnosticsWindow.OptionsPages.PerformanceLoggersPage.SetLoggers(IGlobalOptionService optionService, IThreadingContext threadingContext, IRemoteHostClientService remoteService)
   at Roslyn.VisualStudio.DiagnosticsWindow.VisualStudioDiagnosticsWindowPackage.<InitializeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
```

We should have a unit test for the workspaces layer that ensures this situation is caught prior to integration tests.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #43607

### CODE REVIEW

File: src/Workspaces/CoreTest/FunctionIdTests.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+        [Fact]
+        public void NoDuplicateValues()
+        {
+            var map = new Dictionary<FunctionId, string>();
+            foreach (var name in Enum.GetNames(typeof(FunctionId)))
+            {
+                var value = (FunctionId)Enum.Parse(typeof(FunctionId), name);
+                if (map.TryGetValue(value, out var existingName))
+                {
+                    Assert.True(false, $"'{nameof(FunctionId)}.{name}' cannot have the same value as '{nameof(FunctionId)}.{existingName}'");
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTest/FunctionIdTests.cs:23]:
```suggestion
                    throw new Exception($"'{nameof(FunctionId)}.{name}' cannot have the same value as '{nameof(FunctionId)}.{existingName}'");
```

Otherwise you get a lot of head scratching as to why we expected true and got false.

Comment (sharwell) [reply src/Workspaces/CoreTest/FunctionIdTests.cs:23]: This is the official xUnit pattern for `Assert.Fail`.
https://xunit.net/docs/comparisons.html

Comment (jasonmalinowski) [reply src/Workspaces/CoreTest/FunctionIdTests.cs:23]: Oh really I had always thought the advice was indeed just throw.

**Comment by jasonmalinowski** [comment]
Overriding the CI checks as we're seeing some failures do this this; there more things to unpack but this we know needs to be fixed regardless.
