### PR TITLE
Change stackalloc conversion to a converted bound node

### LINKED ISSUE #21887: IDE crashes when editing code that involves stackalloc expressions
When I am trying to edit stuff that involves stackalloc I frequently see a crash with the following stack.
It seems that semantic model is not robust against broken code when stackalloc is involved.

==============

Message: System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundBadExpression' to type 'Microsoft.CodeAnalysis.CSharp.BoundConversion'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoForNode(BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)

### PR DESCRIPTION
**Pull request by OmarTawfik**
Follow up on comments from #21006 
Fixes #21887

cc @gafter @VSadov 
@dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs [hunk 1]
```diff
@@ -118,39 +112,33 @@ public void Method()
...
             var obj2 = variables.ElementAt(1);
             Assert.Equal("obj2", obj2.Identifier.Text);
 
             var obj2Value = model.GetSemanticInfoSummary(obj2.Initializer.Value);
-            Assert.Null(obj2Value.Type);
-            Assert.True(obj2Value.ConvertedType is PointerTypeSymbol);
-            Assert.Equal("Int32", ((PointerTypeSymbol)obj2Value.ConvertedType).PointedAtType.Name);
-            Assert.Equal(ConversionKind.StackAllocToPointerType, obj2Value.ImplicitConversion.Kind);
-            Assert.Equal(ConversionKind.Identity, obj2Value.ImplicitConversion.UnderlyingConversions.Single().Kind);
+            Assert.Equal(SpecialType.System_Int32, ((PointerTypeSymbol)obj2Value.Type).PointedAtType.SpecialType);
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: We need to confirm with what the spec will say about this. 
The Type might need to be <null> here and conversionKind should be StackAllocToPointerType

Similar would apply to the Span case.

Let's not change this now. It will be a simple change in semantic model once we confirm what needs to be reported for this per spec.

**Comment by VSadov** [comment]
>         int* obj4 = stackalloc int[10];

need a test similar to this for a scenario where conversion does not exists - just to make sure semantic info does not crash and reports something sane.
Example:

double v = stackalloc int[10];


---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs:31 in a7d1248. [](commit_id = a7d12481b040c0e9b2a3c73d6cd6aa7e4afc735e, deletion_comment = False)

**Comment by OmarTawfik** [comment]
@gafter can you please take a look?

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: There will be no conversions in the tree now after merging this PR. Everything will be a bound converted stackalloc node.

---
In reply to: [135353665](https://github.com/dotnet/roslyn/pull/21746#discussion_r135353665) [](ancestors = 135353665)

**Comment by OmarTawfik** [comment]
@dotnet-bot test ubuntu_16_debug_prtest
Network error: https://ci.dot.net/job/dotnet_roslyn/job/features_readonly-ref/job/ubuntu_16_debug_prtest/355/console

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 2]
```diff
@@ -736,6 +735,12 @@ private TypeSymbol BindVariableType(CSharpSyntaxNode declarationNode, Diagnostic
 
             BoundExpression expression = BindValue(initializer, diagnostics, valueKind);
 
+            if (expression is BoundStackAllocArrayCreation boundStackAlloc)
+            {
+                var type = new PointerTypeSymbol(boundStackAlloc.ElementType);
+                expression = GenerateConversionForAssignment(type, boundStackAlloc, diagnostics, false, refKind);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: name arg?

File: src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt [hunk 3]
```diff
@@ -3,3 +3,4 @@ Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax.ReadOnlyKeyword.get -> Micros
 Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax.Update(Microsoft.CodeAnalysis.SyntaxToken refKeyword, Microsoft.CodeAnalysis.SyntaxToken readOnlyKeyword, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax type) -> Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax
 Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax.WithReadOnlyKeyword(Microsoft.CodeAnalysis.SyntaxToken readOnlyKeyword) -> Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax
 static Microsoft.CodeAnalysis.CSharp.SyntaxFactory.RefType(Microsoft.CodeAnalysis.SyntaxToken refKeyword, Microsoft.CodeAnalysis.SyntaxToken readOnlyKeyword, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax type) -> Microsoft.CodeAnalysis.CSharp.Syntax.RefTypeSyntax
+Microsoft.CodeAnalysis.CSharp.Conversion.IsStackAlloc.get -> bool
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt]: FYI @jaredpar @gafter for public API change.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 4]
```diff
@@ -2053,7 +2053,7 @@ internal static bool CheckValEscape(SyntaxNode node, BoundExpression expr, uint
                     }
                     return true;
 
-                case BoundKind.StackAllocArrayCreation:
+                case BoundKind.ConvertedStackAllocExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: I think we don't expect BoundStackAllocArrayCreation to reach here anymore. Consider adding case with Unreachable.
Same above.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 5]
```diff
@@ -2193,21 +2193,10 @@ internal bool IsNonMoveableVariable(BoundExpression expr, out Symbol accessedLoc
                         }
                     case BoundKind.PointerIndirectionOperator: //Covers ->, since the receiver will be one of these.
                     case BoundKind.PointerElementAccess:
-                    case BoundKind.StackAllocArrayCreation:
+                    case BoundKind.ConvertedStackAllocExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Can this method be called with BoundStackAllocArrayCreation anymore?

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs [hunk 6]
```diff
@@ -458,6 +458,17 @@ public bool IsIdentity
         }
 
         /// <summary>
+        /// Returns true if the conversion is a stackalloc conversion.
+        /// </summary>
+        public bool IsStackAlloc
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs]: For other conversion kinds, the public API allows you to figure out exactly which kind it is. For example, if it has IsNumeric and IsImplicit, then you know it was ConversionKind.ImplicitNumeric.
The public API for stack alloc doesn't allow you to figure out which one it was.
Can you add a work item or PROTOTYPE to review with Neal?

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 7]
```diff
@@ -1964,6 +1964,23 @@ public override void Accept(OperationVisitor visitor)
...
+        protected override ImmutableArray<IOperation> Children => ImmutableArray.Create<IOperation>(this.Count);
+
+        public override void Accept(OperationVisitor visitor)
+        {
+            visitor.VisitNoneOperation(this);
+        }
+
+        public override TResult Accept<TArgument, TResult>(OperationVisitor<TArgument, TResult> visitor, TArgument argument)
+        {
+            return visitor.VisitNoneOperation(this, argument);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Let's take a note to notify IOperation folks. They should have a backlog to add this to.

**Comment by jcouv** [comment]
>         public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreation node)

Is this still needed?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs:2569 in c248cd3. [](commit_id = c248cd31ac371770c7ed53684d15b2c31ce0a035, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs [hunk 8]
```diff
@@ -389,7 +389,7 @@ public override BoundNode VisitAssignmentOperator(BoundAssignmentOperator node)
                 NeedsProxy(leftLocal.LocalSymbol))
             {
                 Debug.Assert(!proxies.ContainsKey(leftLocal.LocalSymbol));
-                Debug.Assert(!IsStackAlloc(originalRight));
+                Debug.Assert(originalRight.Kind != BoundKind.ConvertedStackAllocExpression);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs]: I don't understand why we have asserts right before throwing an exception. It will always throw...

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs [hunk 9]
```diff
@@ -150,15 +150,18 @@ internal static bool IsLegalSpanStackAllocPosition(this SyntaxNode node)
...
                     {
-                        // In case of a declaration of a Span<T> variable
-                        return parentNode.Parent.IsKind(SyntaxKind.VariableDeclarator);
+                        SyntaxNode variableDeclarator = parentNode.Parent;
+
+                        return variableDeclarator.IsKind(SyntaxKind.VariableDeclarator) &&
+                            variableDeclarator.Parent.IsKind(SyntaxKind.VariableDeclaration);
                     }
+                // In case of reassignment to a Span<T> variable
                 case SyntaxKind.SimpleAssignmentExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs]: How about in the case of calling a method that accepts a Span, passing in a stackalloc? Is that allowed?

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs [hunk 10]
```diff
@@ -29,6 +29,7 @@ public void Method()
         var obj2 = stackalloc int[10];
         Span<int> obj3 = stackalloc int[10];
         int* obj4 = stackalloc int[10];
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: Should we test explicit casts too? (both for the pointer and the span cases)

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs (hunk 6 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs]: Is this property tested?

---
In reply to: [136683924](https://github.com/dotnet/roslyn/pull/21746#discussion_r136683924) [](ancestors = 136683924)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs]: @jcouv The public api lets you know which one it was by testing the resulting type for being a pointer type.

File: src/Compilers/CSharp/Portable/BoundTree/Formatting.cs [hunk 11]
```diff
@@ -149,7 +149,15 @@ internal partial class BoundStackAllocArrayCreation
     {
         public override object Display
         {
-            get { return string.Format(MessageID.IDS_StackAllocExpression.Localize().ToString(), ElementType); }
+            get { return string.Format(MessageID.IDS_StackAllocExpression.Localize().ToString(), ElementType, Count.Syntax); }
+        }
+    }
+
+    internal partial class BoundConvertedStackAllocExpression
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: Since a converted stack alloc expression has a type, it should not have any special `Display` implementation. Please remove.

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs [hunk 12]
```diff
@@ -1826,7 +1826,7 @@ private void EmitArrayCreationExpression(BoundArrayCreation expression, bool use
             EmitPopIfUnused(used);
         }
 
-        private void EmitStackAllocArrayCreationExpression(BoundStackAllocArrayCreation expression, bool used)
+        private void EmitConvertedStackAllocExpression(BoundConvertedStackAllocExpression expression, bool used)
         {
             EmitExpression(expression.Count, used: true);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: I know this is existing code, but it looks wrong, and if so this is a serious bug. According to the specification for the `localloc` instruction, its operand is the number of *bytes* to be allocated. However, in the bound node the `Count` field is the number of elements of the array to be allocated. Unless it is an array of `byte`, these are not the same thing.

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs [hunk 13]
```diff
@@ -1571,11 +1571,11 @@ public override BoundNode VisitCatchBlock(BoundCatchBlock node)
             return node.Update(node.Locals, exceptionSourceOpt, exceptionTypeOpt, boundFilter, boundBlock, node.IsSynthesizedAsyncCatchAll);
         }
 
-        public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreation node)
+        public override BoundNode VisitConvertedStackAllocExpression(BoundConvertedStackAllocExpression node)
         {
             // CLI spec section 3.47 requires that the stack be empty when localloc occurs.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: Where is this CLI requirement enforced?

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 12 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: I see that the count is rewritten in lowering.

**Comment by gafter** [comment]
I have some concerns, more about the implementation of the feature rather than this particular PR. It is possible that these concerns are already addressed.
- Correctness of the use of the `localloc` instruction requires that the stack be empty (except for the operand to `localloc`). I don't see where the code is rewritten to ensure that is the case.
- The `localloc` instruction may not be used within an exception block (filter, catch, finally, or fault). There must be corresponding language constraints to ensure the generated code is correct. Are there?

**Comment by gafter** [comment]
Other than the `Display` for a converted stack-alloc, the set of changes looks good to me. I will open an issue for my remaining concerns.

**Comment by OmarTawfik** [comment]
>         public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreation node)

They will survive in case of invalid code.

---
In reply to: [326709158](https://github.com/dotnet/roslyn/pull/21746#issuecomment-326709158) [](ancestors = 326709158)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs:2569 in c248cd3. [](commit_id = c248cd31ac371770c7ed53684d15b2c31ce0a035, deletion_comment = False)

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs (hunk 13 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: This expression is never allowed in places where there might be values on the stack (for now). We will look into stack-spilling if that changes in the future.

---
In reply to: [137105053](https://github.com/dotnet/roslyn/pull/21746#discussion_r137105053) [](ancestors = 137105053)

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs (hunk 6 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs]: Done.

---
In reply to: [136685033](https://github.com/dotnet/roslyn/pull/21746#discussion_r136685033) [](ancestors = 136685033,136683924)

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 5 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: No. This API is for internal testing only on valid compilations.

---
In reply to: [136683286](https://github.com/dotnet/roslyn/pull/21746#discussion_r136683286) [](ancestors = 136683286)

**Comment by OmarTawfik** [comment]
Will follow up with the issue created.

---
In reply to: [327295534](https://github.com/dotnet/roslyn/pull/21746#issuecomment-327295534) [](ancestors = 327295534)

File: src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs (hunk 8 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs]: It should always throw (unreachable code).
However, my understanding is that this should warn the dev debugging this to the fact that `stackalloc` should never be here (and the fact that we are thworing shouldn't hide that).

---
In reply to: [136684142](https://github.com/dotnet/roslyn/pull/21746#discussion_r136684142) [](ancestors = 136684142)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 4 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: `BoundStackAllocArrayCreation` will stay in the tree in case of invalid code (that we cannot convert).

---
In reply to: [136683059](https://github.com/dotnet/roslyn/pull/21746#discussion_r136683059) [](ancestors = 136683059)

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 7 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Filed #21921 for that.

---
In reply to: [136684070](https://github.com/dotnet/roslyn/pull/21746#discussion_r136684070) [](ancestors = 136684070)
