### PR TITLE
Fix race in SourceEventSymbol.GetAttributesBag

### LINKED ISSUE #28954: Race condition in SourceEventSymbol
The test `Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase` failed once on my desktop with an assertion failure, likely indicating a race condition in the compiler. Here is the stack trace:

``` none
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
	at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
	Symbols\Source\SourceNamespaceSymbol_Completion.cs(53,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Source\SourceModuleSymbol.cs(258,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Source\SourceAssemblySymbol.cs(908,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2332,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2219,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2155,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2149,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)
	Diagnostics\DiagnosticExtensions.cs(98,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
	Attributes\AttributeTests_WellKnownAttributes.cs(6944,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase()
	----- Inner Stack Trace -----
	ThrowingTraceListener.cs(24,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition)
	Symbols\Source\SourceEventSymbol.cs(184,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributesBag()
	Symbols\Source\SourceEventSymbol.cs(200,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributes()
	Symbols\Symbol_Attributes.cs(725,0): at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteObsoleteAttribute()
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(693,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckOverrideMember(Symbol overridingMember, OverriddenOrHiddenMembersResult overriddenOrHiddenMembers, DiagnosticBag diagnostics, Boolean& suppressAccessors)
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(463,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckMembersAgainstBaseType(DiagnosticBag diagnostics, CancellationToken cancellationToken)
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(31,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetSynthesizedExplicitImplementations(CancellationToken cancellationToken)
	Symbols\Source\SourceMemberContainerSymbol.cs(499,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Symbol.cs(712,0): at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
	Symbols\Source\SourceNamespaceSymbol_Completion.cs(56,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass47_1.<ForceComplete>b__0(Int32 i)
	InternalUtilities\UICultureUtilities.cs(157,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param)
	at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
	at System.Threading.Tasks.Task.InnerInvoke()
	at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
	at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

### PR DESCRIPTION
**Pull request by jaredpar**
There is a race condition around the setting of
`CompletionPart.Attributes` in `SourceEventSymbol`. This can be exposed
when the following execution pattern occurs:

- Thread1: Calls `GetAttributesBag` and pauses execution on the line `
`DeclaringCompilation.SymbolDeclaredEvent(this)`
- Thread2: Calls `ForceComplete` which will unconditionally call
`state.NotePartComplete(CompletionPart.Attributes)`
- Thread1: Resumes and hits an assert because `NotePartComplete` returns
`false`.

The root problem here is the unconditional call of `NotePartComplete`
inside of `ForceComplete`. The pattern in all of our other symbols for
`ForceComplete` is the following:

- Call `GetAttributes`
- Call `SpinWaitComplete(CompletionPart.Attributes, cancellationToken)`

This ensures that `NotePartComplete` is executed on the thread which
actually completes the loading of attributes.

As a part of fixing this I looked through all other uses of
`NotePartComplete(CompletionPart.Attributes)` to ensure they didn't have
this problem. Checked VB as well and it doesn't seem to have this issue.

Struggled to find a good way to test this as it's a race condition.
Given the high number of bugs we've recently filed on this assert I'm
confident we have the indirect coverage in our suites.

closes #28954

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @roslyn-compiler for review

**Comment by jaredpar** [comment]
Note: this race condition was reproducing at near 100% on my Ubuntu 18.04 VM. Cherry picking my patch over and I've been able to verify it no longer reproduces there.

**Comment by agocke** [comment]
I'm a little concerned about the pattern that allows us to return from GetAttributes without having `CompletionPart.Attributes` set. Should we have a follow-up bug on this?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs [hunk 1]
```diff
@@ -180,7 +203,7 @@ private CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
                 LoadAndValidateAttributes(OneOrMany.Create(this.AttributeDeclarationSyntaxList), ref _lazyCustomAttributesBag))
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: I think the key problem I don't like here is that we use `_lazyCustomAttributesBag` to indicate that we're done loading attributes without checking `CompletionPart.Attributes` as well.

**Comment by jaredpar** [comment]
> I'm a little concerned about the pattern that allows us to return from GetAttributes without having CompletionPart.Attributes set. Should we have a follow-up bug on this?

I think we should ask @gafter if this was intended or not. It's certainly how every symbol is implemented at this point.

**Comment by jaredpar** [comment]
retest windows_release_unit32_prtest please

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs [hunk 2]
```diff
@@ -62,12 +62,35 @@ internal sealed override bool RequiresCompletion
 
         internal sealed override bool HasComplete(CompletionPart part)
         {
-            return state.HasComplete(part);
+            return _state.HasComplete(part);
         }
 
         internal override void ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
         {
-            state.DefaultForceComplete(this);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: >state.DefaultForceComplete(this); [](start = 12, length = 33)

It looks like there is another consumer of this helper

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: Good catch and it looks like that has the same issue. Let me get antother PR out.
