### PR TITLE
Fix 'GetRefEscape' for invocation using old rules

### LINKED ISSUE #80244: Unexpected error when using Span defined with old ref safety rules
We got a report from @brianrob that a new ref safety error is being reported on upgrade at the following location
https://github.com/microsoft/perfview/blob/049ed4f9462f39e2212a500fe80d55f1821dbb66/src/TraceEvent/EventPipe/SpanReader.cs#L45

```log
(CoreCompile target) ->
         E:\perfview\src\TraceEvent\EventPipe\SpanReader.cs(52,28): error CS8157: Cannot return 'ret' by reference because it was initialized to a value that cannot be returned by reference [
       E:\perfview\src\TraceEvent\TraceEvent.csproj::TargetFramework=netstandard2.0]
```

Notably the compilation which is failing, has a netstandard2.0 reference to System.Memory and therefore the Span indexer uses the old ref safety rules.

I think the above case may have been exposed by #79447, the error is not reported when replaying the complog before that PR, and is reported afterwards.

However I think the below repro is showing a more general bug which may have already existed for some time.

```xml
<-- MyLib/MyLib.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework> <!-- Change to net8.0 to remove the error (new ref safety rules) -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

```cs
// MyLib/Class1.cs
namespace MyLib;

public ref struct RS
{
    public ref byte this[int i] => throw null!;
}
```

```cs
// lab.cs
#:project ./MyLib
#:property TargetFramework=net9.0

using MyLib;

Console.WriteLine();

static ref byte M1(RS rs)
{
    ref byte ret = ref rs[1];
    return ref ret; // unexpected error when referencing net6.0
}

static ref byte M2(RS rs)
{
    return ref rs[1]; // no error with either net6.0 or 8.0
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #80244

The reason this only pops up when indirecting to a local is: the safe-contexts of a local are calc'd when its initializer is visited, using `GetRefEscape()`/`GetValEscape()`, and are stored. When a usage of the local is found, these safe-contexts are looked up and checked against the context of the usage.

Simple cases like `return ref rs[1]` don't end up actually using `GetRefEscape()` for `ref rs[1]`. Instead it uses `CheckRefEscape()` only, which uses a completely different code path to check the escape, which correctly understood that `this` does not escape by-reference.

The `GetRefEscape()` path needed to be changed to reflect that `this` doesn't escape by-reference in the old rules.

I saw that the `Check()` path also sometimes adjusts the `MethodInvocationInfo` to drop the receiver in order to visit it separately. This didn't seem necessary here.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -3056,7 +3056,13 @@ private void GetEscapeValuesForOldRules(
...
                 }
 
-                if (parameter.RefKind != RefKind.None)
+                // https://github.com/dotnet/csharpstandard/blob/0ad29bf615b18ae463d92ef64f557eeb007b76f1/standard/variables.md#9723-parameter-ref-safe-context
+                // For a parameter `p`:
+                // - If `p` is a reference or input parameter, its ref-safe-context is the caller-context. If `p` is an input parameter, it can’t be returned as a writable `ref` but can be returned as `ref readonly`.
+                // - If `p` is an output parameter, its ref-safe-context is the caller-context.
+                // - Otherwise, if `p` is the `this` parameter of a struct type, its ref-safe-context is the function-member.
+                // - Otherwise, the parameter is a value parameter, and its ref-safe-context is the function-member.
+                if (parameter.RefKind != RefKind.None && !parameter.IsThis)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:3065]: A similar check occurs in line 3001, for the "new rules", where it delegates to helper `GetParameterRefEscapeLevel` that accounts for UnscopedRef, etc. We could consider also using that helper here. However, I feel the implementation here, is somewhat more clearly in line with the standard.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by RikkiGibson** [comment]
Looks like CoreClr test jobs have all timed out. I checked one of the jobs and all the work items are still in Waiting state after 90 minutes. So there might be an infra issue.
