### PR TITLE
Reference Microsoft.NetFramework.Analyzers and fix violations

### LINKED ISSUE #33197: Reference Microsoft.NetFramework.Analyzers and fix violations
Some of the SDL and security related analyzers are currently not enabled for Roslyn. For full security coverage we should reference `Microsoft.NetFramework.Analyzers` and fix any existing violations that come up.

### PR DESCRIPTION
**Pull request by davidwengier**
Part of #33197

I was planning on opening that issue to begin discussion about the work, but it turned out to be so small I just did it. Feel free to tell me why this is not a good idea in here, instead of the issue :)

After this change, a build on my machine only showed formatting warnings which I believe are known.

There are two analyzers that are _not_ enabled with this change, covered by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770175 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770068

### CODE REVIEW

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 1]
```diff
@@ -87,7 +87,9 @@ public ProjectBuildManager(ImmutableDictionary<string, string> additionalGlobalP
 
                 using (var stream = FileUtilities.OpenAsyncRead(path))
                 using (var readStream = await SerializableBytes.CreateReadableStreamAsync(stream, cancellationToken).ConfigureAwait(false))
+#pragma warning disable CA3075 // Insecure DTD processing in XML
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Why is this safe to skip this one? I thought this was a security rule and thus we'd have to follow it.

Comment (Pilchie) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Agreed.

Comment (333fred) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: In fact, this seems like the only really important one, as the others are in test code.

Comment (mavasani) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Tagging @dotpaul who has owns this security analyzer and has recently looked at false positives around it - https://github.com/dotnet/roslyn-analyzers/issues/1591#issuecomment-443960542

Comment (mavasani) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: From the thread on that issue, seems like default setting for `XmlReader.Create` is secure and this is false positive from the analyzer. I'd still let @dotpaul confirm.

Comment (dotpaul) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: The fix is in v2.6.3.

Comment (dotpaul) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Guess I can't comment on lines not in the diff, but &lt;RoslynDiagnosticsNugetPackageVersion&gt; in Versions.prop is 2.6.2-beta2.

Comment (davidwengier) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: This is indeed a false positive, not necessarily because of the defaults for `XmlReader.Create` but because `s_xmlReaderSettings` is defined correctly according to the security guidelines:
https://github.com/dotnet/roslyn/blob/bae1454a81c62db5820ced24e7885bd07c3a471b/src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs#L19-L23

I was planning on verifying if a new version of the analyzer had fixed this today so thank you for doing that for me while I was asleep :)

Comment (dotpaul) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Oops, sorry, I was thinking of a different overload.  I don't think that case has been fixed yet.

Comment (Pilchie) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Can we make sure there is a comment on the suppression that explains why it's safe to suppress?

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 2]
```diff
@@ -87,7 +87,10 @@ public ProjectBuildManager(ImmutableDictionary<string, string> additionalGlobalP
...
+                // s_xmlReaderSettings is compliant with CA3075 (no resolver, prohibit DTD) but the analyzer doesn't pick it up correctly
                 using (var xmlReader = XmlReader.Create(readStream, s_xmlReaderSettings))
```
Comment (sharwell) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: 📝 This is not a performance-sensitive code path for a single allocation. I would prefer to see the value inlined so the analyzer does not need to be suppressed.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 3]
```diff
@@ -303,8 +303,12 @@ public static unsafe string GetMethodIL(this ImmutableArray<byte> ilArray)
         public static Dictionary<int, string> GetSequencePointMarkers(string pdbXml, string source = null)
         {
             string[] lines = source?.Split(new[] { "\r\n" }, StringSplitOptions.None);
-            var doc = new XmlDocument();
-            doc.LoadXml(pdbXml);
+            var doc = new XmlDocument() { XmlResolver = null };
+            using (var sr = new StringReader(pdbXml))
+            using (var reader = new XmlTextReader(sr) { DtdProcessing = DtdProcessing.Prohibit })
```
Comment (sharwell) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: 📝 `reader.Dispose()` already calls `sr.Dispose()`, so there is no need for nested `using` statements.

```suggestion
            using (var reader = new XmlTextReader(new StringReader(pdbXml)) { DtdProcessing = DtdProcessing.Prohibit })
```

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs (hunk 2 above)
Comment (sharwell) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: ❓ Is there a bug tracking correcting this case? If so, what is the ETA?

File: eng/config/rulesets/NonShipping.ruleset [hunk 4]
```diff
@@ -43,4 +43,10 @@
     <Rule Id="CA2213" Action="None" />
     <Rule Id="CA1063" Action="None" />
   </Rules>
+  <!-- Don't worry about custom exceptions in tests -->
+  <Rules AnalyzerId="Microsoft.NetFramework.Analyzers" RuleNamespace="Microsoft.NetFramework.Analyzers">
```
Comment (sharwell) [inline eng/config/rulesets/NonShipping.ruleset]: 💡 Can you document each of these exclusions with the title of the suppressed item?

File: src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs [hunk 5]
```diff
@@ -40,8 +40,12 @@ public static bool CheckIfSpanWithinSequencePoints(TextSpan span, string source,
             var endRow = endLine.LineNumber + 1;
             var endColumn = span.End - endLine.Start + 1;
 
-            var doc = new XmlDocument();
-            doc.LoadXml(pdb);
+            var doc = new XmlDocument() { XmlResolver = null };
+            using (var sr = new System.IO.StringReader(pdb))
+            using (var reader = new XmlTextReader(sr) { DtdProcessing = DtdProcessing.Prohibit })
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs]: 📝 `reader.Dispose()` already calls `sr.Dispose()`, so there is no need for nested `using` statements.

```suggestion
            using (var reader = new XmlTextReader(new StringReader(pdb)) { DtdProcessing = DtdProcessing.Prohibit })
```

**Comment by jaredpar** [comment]
A 7% regression for that small number of fixes. Feels like we're out of balance here. Why is there a need to take this now, and push back perf of entire team, versuse fixing the build perf now?

**Comment by davidwengier** [comment]
> please email me the name of the person assigned to fix the performance regression

Guessing that is @dotpaul https://github.com/dotnet/roslyn-analyzers/issues/2103

**Comment by davidwengier** [comment]
> I think we should either take the fixes and push on performance before we merge this in.

I will adjust this PR and remove the analyzer reference, but leave the rest in place. I'll leave #33197 for tracking adding it back in, in whichever form is deemed best.

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs (hunk 2 above)
Comment (davidwengier) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: https://github.com/dotnet/roslyn-analyzers/issues/2105

Comment (davidwengier) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: https://github.com/dotnet/roslyn-analyzers/issues/2105

Comment (davidwengier) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Since this PR no longer introduces the analyzer, I'll leave this. Its easy enough to address when the analyzer is put in place if https://github.com/dotnet/roslyn-analyzers/issues/2105 has not been resolved first.

**Comment by davidwengier** [comment]
Without the addition of the analyzer this PR is _super_ unimportant :)

File: src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs [hunk 6]
```diff
@@ -40,8 +40,12 @@ public static bool CheckIfSpanWithinSequencePoints(TextSpan span, string source,
             var endRow = endLine.LineNumber + 1;
             var endColumn = span.End - endLine.Start + 1;
 
-            var doc = new XmlDocument();
-            doc.LoadXml(pdb);
+            var doc = new XmlDocument() { XmlResolver = null };
+            using (var sr = new System.IO.StringReader(pdb))
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs]: 💡 Unused variable

```suggestion
```

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 7]
```diff
@@ -303,8 +303,12 @@ public static unsafe string GetMethodIL(this ImmutableArray<byte> ilArray)
         public static Dictionary<int, string> GetSequencePointMarkers(string pdbXml, string source = null)
         {
             string[] lines = source?.Split(new[] { "\r\n" }, StringSplitOptions.None);
-            var doc = new XmlDocument();
-            doc.LoadXml(pdbXml);
+            var doc = new XmlDocument() { XmlResolver = null };
+            using (var sr = new StringReader(pdbXml))
```
Comment (sharwell) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: 💡 Unused variable

```suggestion
```

**Comment by jaredpar** [comment]
> Without the addition of the analyzer this PR is _super_ unimportant :)

Why do you believe that? The other changes in the PR appear to be valuable.

In any case I think the right balance here is limiting the analyzer to the windows build correctness leg only. The evidence from this PR indicates that violations will be rare hence it doesn't seem like it's necessary to have a part of the inner dev loop. The windows build correctness leg runs on every PR so there is no loss of coverage here. It's just taking an expensive analyzer and putting it in a place where it won't impact day to day performance.

File: src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs [hunk 8]
```diff
@@ -41,7 +41,7 @@ public static bool CheckIfSpanWithinSequencePoints(TextSpan span, string source,
             var endColumn = span.End - endLine.Start + 1;
 
             var doc = new XmlDocument() { XmlResolver = null };
-            using (var reader = new XmlTextReader(new StringReader(pdb)) { DtdProcessing = DtdProcessing.Prohibit })
+            using (var reader = new XmlTextReader(new System.IO.StringReader(pdb)) { DtdProcessing = DtdProcessing.Prohibit })
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs]: :bulb: A new `using` directive would be preferable.

**Comment by davidwengier** [comment]
Integration test failures look unrelated to me?

**Comment by sharwell** [comment]
> Integration test failures look unrelated to me?

Yes.
