### PR TITLE
Trivial fix for 6805.

### LINKED ISSUE #6805: ExpressionLambdaRewriter.VisitArrayAccess check seems off
```csharp
if (node.Type != _int32Type)
```

looks like it should be

```csharp
if (arg.Type != _int32Type)
```

### PR DESCRIPTION
**Pull request by VSadov**
Just fixing the easy-out check that verifies if index conversion is needed at all. Currently the condition is always true - likely a typo.
Otherwise, the part that creates conversion does the right thing regardless, so the end result should be the same.

Fixes #6805

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler  please review. Very simple change.

**Comment by gafter** [comment]
LGTM

**Comment by davkean** [comment]
unit32 failure was:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

Which is a known issue, and can be retried.

retest prtest/win/dbg/unit32 please

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs [hunk 1]
```diff
@@ -303,7 +303,7 @@ private BoundExpression Indices(ImmutableArray<BoundExpression> expressions)
             foreach (var arg in expressions)
             {
                 var index = Visit(arg);
-                if (arg.Type != _int32Type)
+                if (index.Type != _int32Type)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: Consider removing the `if` conditions instead, especially since the expressions were always true previously.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs [hunk 2]
```diff
@@ -285,7 +285,7 @@ private BoundExpression VisitArrayAccess(BoundArrayAccess node)
             {
                 var arg = node.Indices[0];
                 var index = Visit(arg);
-                if (node.Type != _int32Type)
+                if (index.Type != _int32Type)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: Consider removing the `if` condition instead, especially since the expression was always true previously.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs [hunk 3]
```diff
@@ -303,7 +303,7 @@ private BoundExpression Indices(ImmutableArray<BoundExpression> expressions)
             foreach (var arg in expressions)
             {
                 var index = Visit(arg);
-                if (arg.Type != _int32Type)
+                if (index.Type != _int32Type)
                 {
                     index = ConvertIndex(index, arg.Type, _int32Type);
                 }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: Consider extracting the body of the loop to a `VisitIndex` method shared between the two uses.

**Comment by AlekseyTs** [comment]
LGTM
