### PR TITLE
Avoid infinite cycle caused by an early binding of DefaultParameterValue attribute.

### LINKED ISSUE #70206: Passing the method back into `DefaultParameterValue` crashes
**Version Used**: main (12 Sep 2023)

**Steps to Reproduce**:

Use this code on a fresh C# console project in VS (or use the sharplab link below):
```csharp
using System.Runtime.InteropServices;

static class Program
{
    public static void Evil([DefaultParameterValue(Evil)]) {}

    public static void Main() {}
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAOgCUBXGAFyjAFMCBJC6gJwHsAHAZWYDcoBjagGcA3AFgAUBPwA2XACZceAOwSA3hOybcAZkWz0AFmwBRXgBsAFAG0AItQBmEEmfIAFCEwg1yzAGoQzEmoLUygzAEoAXXDsVQBfCQ0tdDkFeIk4oA=) (this just keeps compiling)

**Expected Behavior**: Not crash and report some diagnostics

**Actual Behavior**: Crashes/Hangs

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #70206.
Also:
- Add support for using `nameof` in early bound well-known attributes in VB
- Address a number of issues with support for Asc, AscW, Chr, ChrW VB functions in early bound well-known attributes

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -576,252 +576,264 @@ private BoundExpression BindExpressionInternal(ExpressionSyntax node, BindingDia
                 return BadExpression(node, LookupResultKind.NotAValue);
             }
 
-            Debug.Assert(node != null);
-            switch (node.Kind())
+            BoundExpression result = bindExpressionInternal(node, diagnostics, invoked, indexed);
+
+            if (IsEarlyAttributeBinder && result.Kind == BoundKind.MethodGroup && (!IsInsideNameof || EnclosingNameofArgument != node))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:581]: I was wondering in what scenario is `EnclosingNameofArgument != node` needed for correct behavior?

**Review by RikkiGibson — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:581]: > I was wondering in what scenario is `EnclosingNameofArgument != node` needed for correct behavior?

I have taken a conservatives approach to check for scenarios that I think can result in a successful binding in a most precise way. It is quite possible that I am missing some scenario and this condition is too strict, but I cannot think of any at the moment.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Review by 333fred — APPROVED** [review]
