### PR TITLE
`SwitchBinder.KeyForConstant`: nint/nuint values should not collide with values for constants of other types.

### LINKED ISSUE #81784: Bug with `goto case (n{u}int)myconstant` when a prior `case myconstant:` exists before it
**Version Used**: lab.razor.fyi, sharplab.io, godbolt.org

**Steps to Reproduce**:

```csharp
using System;

switch ((object)(nint)2)
{
    case 2:
        break;
    case (nint)2:
        Console.WriteLine("Case 2");
        goto case (nint)2;
}
```

[Link](https://lab.razor.fyi/#41rByMUVUJSfXpSYq5dcLDSTsbQ4My9dIbiyuCQ115qLq7g8syQ5Q0FDIz8pKzW5RFMjLzOvRNNIk6uaS0FBQSE5sThVwcgKzAaBpKLUxGxrhBRUOUKBc35ecX5Oql54UWZJqk9mXqqGkjPYDCVNiDYQSM8vyUfRb81Vy-XFXFSaF8XJ8evU06fP0wRYEhgrGAE)

**Expected Behavior**:

Loops printing "Case 2" forever.

**Actual Behavior**:

Prints "Case 2" only once.

Note: the following code blocks do not exhibit the bug:
```csharp
using System;

switch ((object)(nuint)2)
{
    case 2:
        break;
    case (nuint)2:
        Console.WriteLine("Case 2");
        goto case (nuint)2;
}
```
```csharp
using System;

switch ((object)(long)2)
{
    case 2:
        break;
    case (long)2:
        Console.WriteLine("Case 2");
        goto case (long)2;
}
```
```csharp
using System;

switch ((object)(int)2)
{
    case (short)2:
        break;
    case 2:
        Console.WriteLine("Case 2");
        goto case (int)2;
}
```
```csharp
using System;

switch ((object)2L)
{
    case (nint)2:
        break;
    case 2L:
        Console.WriteLine("Case 2");
        goto case 2L;
}
```
```csharp
using System;

switch ((object)(nint)2)
{
    case (nint)2:
        Console.WriteLine("Case 2");
        goto case (nint)2;
}
```

This case also exhibits it:
```csharp
using System;

switch ((object)(nuint)2)
{
    case (uint)2u:
        break;
    case (nuint)2:
        Console.WriteLine("Case 2");
        goto case (nuint)2;
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #81784

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs [hunk 1]
```diff
@@ -3525,5 +3525,42 @@ public void AssignSwitchToRefReturningMethod()
                 Diagnostic(ErrorCode.ERR_RefReturningCallAndAwait, "GetRef()").WithArguments("Program.<<Main>$>g__GetRef|0_0()").WithLocation(2, 1)
             );
         }
+
+        [Theory]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/81784")]
+        [CombinatorialData]
+        public void GotoCase(
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: Consider testing that `IntPtr` and `nint` are treated equivalently; I'm thinking in particular, it would be good to test using `IntPtr` on line 3557 when line 3552 is `nint`, and vice versa. And it would also be interesting to test that across C# 10 and 11, since 11 changed the definition of `nint`. #Resolved

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: While the added tests are good, it doesn't look like the scenario I was asking for is covered. It would be something like:


```cs
class Program
{
    static void Main()
    {
        int count = 0;

        switch ((object)(nint)2)
        {
            case (int)2:
                break;
            case (nint)2:
                System.Console.Write("Case 2");
                count++;

                if (count == 3) break;
                goto case (System.IntPtr)2;
        }
    }
} 
```

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: > While the added tests are good, it doesn't look like the scenario I was asking for is covered.

The added tests clearly demonstrate that ```(System.IntPtr)2``` is not a constant expression. The expectations "`IntPtr` and `nint` are treated equivalently" are incorrect. Therefore, I think the added tests are sufficient and, given the current language rules, the requested scenarios are not going to add anything new.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: There is no compilation error in this [sample](https://lab.razor.fyi/#bU_NagIxGMSlB82p-ASDpwRhke2t4slTCwWhB8GTMY2auiaQfPaHsm_TBxDPfSEPvfco2V1slzqnMN_MZIb9JIxNvFt5uU1V6B4TlcsQUFPsgwFAIElG4cWZJzxIY7ko6eoYYSxBuZ0ljDAYsjMfXg2pNTh3i2etSHBrLImssjcjAEDJoMFLyW3jELHwWm6GF_RV5n_D43sgvU3HzgaX63TqDWneG0dP1hPNpDItDuj3_9Q_z1uC1_NGuBGXqkSsHLm6U_33naUJeZH9aovyVbAC94nJZ53259f-8L28vpq33lon). What am I missing?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: > There is no compilation error in this [sample](https://lab.razor.fyi/#bU_NagIxGMSlB82p-ASDpwRhke2t4slTCwWhB8GTMY2auiaQfPaHsm_TBxDPfSEPvfco2V1slzqnMN_MZIb9JIxNvFt5uU1V6B4TlcsQUFPsgwFAIElG4cWZJzxIY7ko6eoYYSxBuZ0ljDAYsjMfXg2pNTh3i2etSHBrLImssjcjAEDJoMFLyW3jELHwWm6GF_RV5n_D43sgvU3HzgaX63TqDWneG0dP1hPNpDItDuj3_9Q_z1uC1_NGuBGXqkSsHLm6U_33naUJeZH9aovyVbAC94nJZ53259f-8L28vpq33lon). What am I missing?

Now I feel like I am missing something. The following test reflects behavior that I observe locally (with and without the fix):
```
        [Fact]
        [WorkItem("https://github.com/dotnet/roslyn/issues/81784")]
        public void GotoCase_06()
        {
            var source = $$$"""
class Program
{
    static void Main()
    {
        int count = 0;

        switch ((object)(nint)2)
        {
            case (int)2:
                break;
            case (nint)2:
                System.Console.Write("Case 2");
                count++;

                if (count == 3) break;
                goto case (System.IntPtr)2;
        }
    }
} 
""";

            var expected = new[] {
                // (16,17): error CS0150: A constant value is expected
                //                 goto case (System.IntPtr)2;
                Diagnostic(ErrorCode.ERR_ConstantExpected, "goto case (System.IntPtr)2;").WithLocation(16, 17),
                // (11,13): error CS8070: Control cannot fall out of switch from final case label ('case (nint)2:')
                //             case (nint)2:
                Diagnostic(ErrorCode.ERR_SwitchFallOut, "case (nint)2:").WithArguments("case (nint)2:").WithLocation(11, 13)
            };

            CreateCompilation(source).VerifyDiagnostics(expected);
            CreateCompilation(source, parseOptions: TestOptions.Regular10).VerifyDiagnostics(expected);
            CreateCompilation(source, parseOptions: TestOptions.Regular11).VerifyDiagnostics(expected);
        }
```

I'll try to figure out what might cause a different behavior at https://lab.razor.fyi/

Comment (333fred) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: It's because you're not targeting .NET 7 and are missing `RuntimeFeature.NumericIntPtr`, so `nint` and `IntPtr` are not being treated equivalently.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: > It's because you're not targeting .NET 7 and are missing `RuntimeFeature.NumericIntPtr`, so `nint` and `IntPtr` are not being treated equivalently.

Thank you. I arrived to the same conclusion

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs]: Added a bunch of tests

**Review by 333fred — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs [hunk 2]
```diff
@@ -3525,5 +3525,515 @@ public void AssignSwitchToRefReturningMethod()
...
+        public void GotoCase_01(
+            [CombinatorialValues("byte", "sbyte", "short", "ushort", "int", "uint", "long", "ulong", "nint", "nuint")] string type1,
+            [CombinatorialValues("byte", "sbyte", "short", "ushort", "int", "uint", "long", "ulong", "nint", "nuint")] string type2)
+        {
+            if (type1 == type2)
+            {
+                return;
+            }
+
+            var source = $$$"""
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Emit3/Semantics/PatternSwitchTests.cs:3541]: nit: only two dollars seem needed here.

**Review by CyrusNajmabadi — APPROVED** [review]
