### PR TITLE
Fix IArgument.InConversion/OutConversion

### LINKED ISSUE #18548: InConversion and OutConversion of VB ByRef argument exposes placeholder nodes as IOperations
When passing a modifiable element as argument for a VB `ByRef` parameter, the `In/OutConversion`  properties of  the `IArgument` operation would expose placeholder nodes as `Operand` (as those properties themselves are of type `IConversionExpression`). 

```vb
Class Program
    Sub M1()
        Dim x = 1.0
        M2(x)
    End Sub

    Sub M2(ByRef a As Integer)
    End Sub
End Class
```

```
IOperation tree for "M2(x)"

IInvocationExpression ( Sub Program.M2(ByRef a As System.Int32)) (OperationKind.InvocationExpression, Type: System.Void) (Syntax: 'M2(x)')
  Instance Receiver: IInstanceReferenceExpression (InstanceReferenceKind.Implicit) (OperationKind.InstanceReferenceExpression, Type: Program) (Syntax: 'M2')
  Arguments(1): IArgument (ArgumentKind.Explicit Matching Parameter: a) (OperationKind.Argument) (Syntax: 'x')
      ILocalReferenceExpression: x (OperationKind.LocalReferenceExpression, Type: System.Double) (Syntax: 'x')
      InConversion: IConversionExpression (ConversionKind.Basic, Implicit) (OperationKind.ConversionExpression, Type: System.Int32) (Syntax: 'x')
          IOperation:  (OperationKind.None) (Syntax: 'x')
      OutConversion: IConversionExpression (ConversionKind.Basic, Implicit) (OperationKind.ConversionExpression, Type: System.Double) (Syntax: 'x')
          IPlaceholderExpression (OperationKind.PlaceholderExpression, Type: System.Int32) (Syntax: 'x')
```

Related: #8905

### PR DESCRIPTION
**Pull request by genlu**
Fix #18548. Changed the In/OutConversion from `IConversionExpression` to `CommonConversion` (added in #21040 )

```cs
    public interface IArgument : IOperation
    {
        /// <summary>
        /// Kind of argument.
        /// </summary>
        ArgumentKind ArgumentKind { get; }
        /// <summary>
        /// Parameter the argument matches.
        /// </summary>
        IParameterSymbol Parameter { get; }
        /// <summary>
        /// Value supplied for the argument.
        /// </summary>
        IOperation Value { get; }
        /// <summary>
        /// Information of the conversion applied to the argument value passing it into the target method. Applicable only to VB Reference arguments.
        /// </summary>
        CommonConversion InConversion { get; }
        /// <summary>
        /// Information of the conversion applied to the argument value after the invocation. Applicable only to VB Reference arguments.
        /// </summary>
        CommonConversion OutConversion { get; }
    }
```

### CODE REVIEW

**Comment by genlu** [comment]
I think this is mostly done. Please review @AlekseyTs @cston @dotnet/analyzer-ioperation

**Comment by genlu** [comment]
windows_debug_unit64_prtest failure is probably another instance of #14592:
https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit64_prtest/463/

File: src/Compilers/CSharp/Portable/Operations/CSharpArgument.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using System;
+using Microsoft.CodeAnalysis.Semantics;
+
+namespace Microsoft.CodeAnalysis.CSharp
+{
+    internal abstract class BaseCSharpArgument : BaseArgument, IArgument
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpArgument.cs]: `BaseArgument` already implements `IArgument`.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+            OutConversionInternal = outConversion
+        End Sub
+
+        Friend ReadOnly Property InConversionInternal As Conversion
+
+        Friend ReadOnly Property OutConversionInternal As Conversion
+
+        Public Overrides ReadOnly Property InConversion As [Optional](Of CommonConversion)
+            Get
+                Return If(InConversionInternal = Nothing, New [Optional](Of CommonConversion)(), InConversionInternal.ToCommonConversion())
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb]: Can use `Nothing` instead of `New [Optional](Of CommonConversion)()`. Same comment for `OutConversion` below.

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb [hunk 3]
```diff
@@ -1379,6 +1379,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             End If
         End Function
 
+        ''' <summary>
+        ''' Gets the underlying <see cref="Conversion"/> information for InConversion of <see cref="IArgument"/> that was created from Visual Basic code.
+        ''' </summary>
+        ''' <param name="argument">The argument to get original info from.</param>
+        ''' <returns>The underlying <see cref="Conversion"/> of the InConversion.</returns>
+        ''' <exception cref="InvalidCastException">If the <see cref="IArgument"/> was not created from Visual Basic code.</exception>
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: These methods throw `ArgumentException` rather than `InvalidCastException`.

File: src/Compilers/Core/Portable/Operations/IArgument.cs [hunk 4]
```diff
@@ -24,13 +24,13 @@ public interface IArgument : IOperation
         /// </summary>
         IOperation Value { get; }
         /// <summary>
-        /// Conversion applied to the argument value passing it into the target method. Applicable only to VB Reference arguments.
+        /// Information of the conversion applied to the argument value passing it into the target method. Applicable only to VB Reference arguments.
         /// </summary>
-        IOperation InConversion { get; }
+        Optional<CommonConversion> InConversion { get; }
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/IArgument.cs]: >Optional<CommonConversion> [](start = 8, length = 26)

It doesn't look like it is a common pattern to use ```Optional<T>``` in IOperation API. Would it be better to use identity conversion for situations when no conversion is needed?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb]: >InConversionInternal = Nothing [](start = 26, length = 30)

```Conversion``` is a structure. What does it mean to compare a structure with Nothing and why is it the right thing to do here?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+            End Get
+        End Property
+
+        Public Overrides ReadOnly Property OutConversion As [Optional](Of CommonConversion)
+            Get
+                Return If(OutConversionInternal = Nothing, New [Optional](Of CommonConversion)(), OutConversionInternal.ToCommonConversion())
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb]: >OutConversionInternal = Nothing [](start = 26, length = 31)

Same issue around ```Nothing```.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 6]
```diff
@@ -71,18 +71,31 @@ Namespace Microsoft.CodeAnalysis.Semantics
             Return arguments.ToImmutableAndFree()
         End Function
 
+        Private Function CreateConversion(expression As BoundExpression) As Conversion
+            If expression.Kind = BoundKind.Conversion Then
+                Dim conversion = DirectCast(expression, BoundConversion)
+                Dim method As MethodSymbol = Nothing
+                If conversion.Operand.Kind = BoundKind.UserDefinedConversion Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >conversion.Operand.Kind = BoundKind.UserDefinedConversion [](start = 19, length = 57)

It feels like we should also make sure that the conversion kind for the ```conversion``` node is user-defined conversion.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs [hunk 7]
```diff
@@ -51,9 +51,7 @@ static void Test2(int y, params int[] x)
       IArgument (ArgumentKind.Explicit, Matching Parameter: x) (OperationKind.Argument) (Syntax: 'null')
         IConversionExpression (Implicit, TryCast: False, Unchecked) (OperationKind.ConversionExpression, Type: System.Int32[], Constant: null) (Syntax: 'null')
           Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: True, IsUserDefined: False) (MethodSymbol: null)
-          Operand: ILiteralExpression (Text: null) (OperationKind.LiteralExpression, Type: null, Constant: null) (Syntax: 'null')
-        InConversion: null
-        OutConversion: null");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs]: It feels like these properties should still be validated.

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb [hunk 8]
```diff
@@ -835,5 +758,110 @@ BC30272: 'y' is not a parameter of 'Public Sub M2(x As Integer)'.
             VerifyOperationTreeAndDiagnosticsForTest(Of InvocationExpressionSyntax)(source, expectedOperationTree, expectedDiagnostics)
         End Sub
 
+
+
+        <CompilerTrait(CompilerFeature.IOperation)>
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb]: ><CompilerTrait(CompilerFeature.IOperation)> [](start = 8, length = 43)

It looks like there are three new lines between this test and the one above. We usually use one line to separate tests.

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb [hunk 9]
```diff
@@ -835,5 +758,110 @@ BC30272: 'y' is not a parameter of 'Public Sub M2(x As Integer)'.
...
+]]>.Value
+
+            Dim expectedDiagnostics = String.Empty
+
+            VerifyOperationTreeAndDiagnosticsForTest(Of InvocationExpressionSyntax)(source, expectedOperationTree, expectedDiagnostics)
+        End Sub
+
+        <CompilerTrait(CompilerFeature.IOperation)>
+        <Fact>
+        Public Sub InOutConversionUserDefined()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb]: >InOutConversionUserDefined [](start = 19, length = 26)

It would be good to have tests for scenarios when standard conversions are involved into user-defined conversion, either for the input value, or for the method's return value. The cases when either BoundUserDefinedConversion.InConversionOpt, or BoundUserDefinedConversion.OutConversionOpt are not null.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb (hunk 9 above)
Comment (genlu) [reply src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb]: I have added a test in the last commit. Is that what you suggested?

**Comment by genlu** [comment]
@AlekseyTs Could you take another look please?

**Comment by AlekseyTs** [comment]
@genlu It looks like there are legitimate test failures.

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb [hunk 10]
```diff
@@ -1379,6 +1379,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        ''' <param name="argument">The argument to get original info from.</param>
+        ''' <returns>The underlying <see cref="Conversion"/> of the InConversion.</returns>
+        ''' <exception cref="ArgumentException">If the <see cref="IArgument"/> was not created from Visual Basic code.</exception>
+        <Extension>
+        Public Function GetInConversion(argument As IArgument) As Conversion
+            Dim basicArgument = TryCast(argument, BaseVisualBasicArgument)
+            If basicArgument IsNot Nothing Then
+                Return basicArgument.InConversionInternal
+            Else
+                Throw New ArgumentException(String.Format(VBResources.IArgumentIsNotVisualBasicArgument,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: >Throw New ArgumentException(String.Format(VBResources.IArgumentIsNotVisualBasicArgument, [](start = 16, length = 88)

Do we have tests for this code path?

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb [hunk 11]
```diff
@@ -1379,6 +1379,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        ''' <param name="argument">The argument to get original info from.</param>
+        ''' <returns>The underlying <see cref="Conversion"/> of the OutConversion.</returns>
+        ''' <exception cref="ArgumentException">If the <see cref="IArgument"/> was not created from Visual Basic code.</exception>
+        <Extension>
+        Public Function GetOutConversion(argument As IArgument) As Conversion
+            Dim basicArgument = TryCast(argument, BaseVisualBasicArgument)
+            If basicArgument IsNot Nothing Then
+                Return basicArgument.OutConversionInternal
+            Else
+                Throw New ArgumentException(String.Format(VBResources.IArgumentIsNotVisualBasicArgument,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: >Throw New ArgumentException(String.Format(VBResources.IArgumentIsNotVisualBasicArgument, [](start = 16, length = 88)

Do we have tests for this code path?

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb [hunk 12]
```diff
@@ -1379,6 +1379,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        ''' Gets the underlying <see cref="Conversion"/> information for InConversion of <see cref="IArgument"/> that was created from Visual Basic code.
+        ''' </summary>
+        ''' <param name="argument">The argument to get original info from.</param>
+        ''' <returns>The underlying <see cref="Conversion"/> of the InConversion.</returns>
+        ''' <exception cref="ArgumentException">If the <see cref="IArgument"/> was not created from Visual Basic code.</exception>
+        <Extension>
+        Public Function GetInConversion(argument As IArgument) As Conversion
+            Dim basicArgument = TryCast(argument, BaseVisualBasicArgument)
+            If basicArgument IsNot Nothing Then
+                Return basicArgument.InConversionInternal
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: >Return basicArgument.InConversionInternal [](start = 16, length = 41)

Do we have tests for this code path?

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb [hunk 13]
```diff
@@ -1379,6 +1379,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        ''' Gets the underlying <see cref="Conversion"/> information for OutConversion of <see cref="IArgument"/> that was created from Visual Basic code.
+        ''' </summary>
+        ''' <param name="argument">The argument to get original info from.</param>
+        ''' <returns>The underlying <see cref="Conversion"/> of the OutConversion.</returns>
+        ''' <exception cref="ArgumentException">If the <see cref="IArgument"/> was not created from Visual Basic code.</exception>
+        <Extension>
+        Public Function GetOutConversion(argument As IArgument) As Conversion
+            Dim basicArgument = TryCast(argument, BaseVisualBasicArgument)
+            If basicArgument IsNot Nothing Then
+                Return basicArgument.OutConversionInternal
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: >Return basicArgument.OutConversionInternal [](start = 16, length = 42)

Do we have tests for this code path?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb [hunk 14]
```diff
@@ -0,0 +1,62 @@
...
+            OutConversionInternal = outConversion
+        End Sub
+
+        Friend ReadOnly Property InConversionInternal As Conversion
+
+        Friend ReadOnly Property OutConversionInternal As Conversion
+
+        Public Overrides ReadOnly Property InConversion As CommonConversion
+            Get
+                Return If(InConversionInternal.Exists, InConversionInternal.ToCommonConversion(), New CommonConversion(exists:=True, isIdentity:=True, isNumeric:=False, isReference:=False, methodSymbol:=Nothing))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb]: >If(InConversionInternal.Exists, InConversionInternal.ToCommonConversion(), New CommonConversion(exists:=True, isIdentity:=True, isNumeric:=False, isReference:=False, methodSymbol:=Nothing)) [](start = 23, length = 189)

This logic feels strange. Do we ever get  conversion that doesn't exist? We probably should return it anyway.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb [hunk 15]
```diff
@@ -0,0 +1,62 @@
...
+            End Get
+        End Property
+
+        Public Overrides ReadOnly Property OutConversion As CommonConversion
+            Get
+                Return If(OutConversionInternal.Exists, OutConversionInternal.ToCommonConversion(), New CommonConversion(exists:=True, isIdentity:=True, isNumeric:=False, isReference:=False, methodSymbol:=Nothing))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicArgument.vb]: >If(OutConversionInternal.Exists, OutConversionInternal.ToCommonConversion(), New CommonConversion(exists:=True, isIdentity:=True, isNumeric:=False, isReference:=False, methodSymbol:=Nothing)) [](start = 23, length = 191)

Same comment.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 16]
```diff
@@ -71,19 +71,33 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
+            If expression.Kind = BoundKind.Conversion Then
+                Dim conversion = DirectCast(expression, BoundConversion)
+                Dim conversionKind = conversion.ConversionKind
+                Dim method As MethodSymbol = Nothing
+                If conversionKind.HasFlag(VisualBasic.ConversionKind.UserDefined) AndAlso conversion.Operand.Kind = BoundKind.UserDefinedConversion Then
+                    method = DirectCast(conversion.Operand, BoundUserDefinedConversion).Call.Method
+                End If
+                Return New Conversion(KeyValuePair.Create(conversionKind, method))
+            End If
+            Return New Conversion(Nothing) 'NoConversion
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Nothing [](start = 34, length = 7)

Probably should use identity, given the current design.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 17]
```diff
@@ -100,12 +114,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
                         Dim value = Create(argument)
 
-                        Return New Argument(
+                        Return New VisualBasicArgument(
                             kind,
                             parameter,
                             value,
-                            inConversion:=Nothing,
-                            outConversion:=Nothing,
+                            inConversion:=New Conversion(Nothing), 'NoConversion,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Nothing [](start = 57, length = 7)

Identity?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 18]
```diff
@@ -100,12 +114,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
+                            outConversion:=New Conversion(Nothing), 'NoConversion,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Nothing [](start = 58, length = 7)

Identity?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 19]
```diff
@@ -120,12 +134,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
                         Dim value = Create(argument)
 
-                        Return New Argument(
+                        Return New VisualBasicArgument(
                             kind,
                             parameter,
                             value,
-                            inConversion:=Nothing,
-                            outConversion:=Nothing,
+                            inConversion:=New Conversion(Nothing), 'NoConversion,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Nothing [](start = 57, length = 7)

Identity?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 20]
```diff
@@ -120,12 +134,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
+                            outConversion:=New Conversion(Nothing), 'NoConversion,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Nothing [](start = 58, length = 7)

Identity?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 21]
```diff
@@ -71,19 +71,33 @@ Namespace Microsoft.CodeAnalysis.Semantics
             Return arguments.ToImmutableAndFree()
         End Function
 
+        Private Function CreateConversion(expression As BoundExpression) As Conversion
+            If expression.Kind = BoundKind.Conversion Then
```
Comment (genlu) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: @AlekseyTs It just occurs to me, do we need a null check here for `expression`? A quick look at the binder code that creates `BoundByRefArgumentWithCopyBack` seems to suggest this is not necessary

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb (hunk 10 above)
Comment (genlu) [reply src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: Nope, don't have tests for this new extension method. Will add one.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 21 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: > A quick look at the binder code that creates BoundByRefArgumentWithCopyBack seems to suggest this is not necessary

I agree.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 18)

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb (hunk 10 above)
Comment (genlu) [reply src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: Added.

**Comment by genlu** [comment]
@cston @AlekseyTs Another look please?

**Comment by genlu** [comment]
`windows_debug_unit64_prtest` timed out. 

https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit64_prtest/607/

```
14:47:02 Roslyn Error: test timeout exceeded, dumping remaining processes
14:47:03 Dumping xunit.console 5760 to D:\j\workspace\windows_debug---a5b724b3\Binaries\Debug\xunit.console-0.dmp ... succeeded
```

@dotnet/roslyn-infrastructure

**Comment by genlu** [comment]
Ping... @AlekseyTs @cston

File: src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb (hunk 10 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb]: > Added

Could you point me to the tests? What file they are in? What are the names?

**Comment by genlu** [comment]
@AlekseyTs Added tests for extension methods

**Comment by AlekseyTs** [comment]
@genlu It looks like there are some legitimate test failures.

File: src/Compilers/Test/Utilities/VisualBasic/BasicTestBase.vb [hunk 22]
```diff
@@ -852,6 +852,24 @@ Public MustInherit Class BasicTestBaseBase
...
         Return DumpAllDiagnostics(allDiagnostics, suppressInfos)
     End Function
+
+    Friend Shared Function GetOperationAndSyntaxForTest(Of TSyntaxNode As SyntaxNode)(compilation As Compilation, fileName As String, Optional which As integer  = 0) As (operation as IOperation, synxtaxNode As SyntaxNode)
+        Dim node As SyntaxNode = CompilationUtils.FindBindingText(Of TSyntaxNode)(compilation, fileName, which, prefixMatch:=True)
+        If node Is Nothing Then
+            Return (Nothing, Nothing)
+        End If
+
+        Dim tree = (From t In compilation.SyntaxTrees Where t.FilePath = fileName).Single()
```
Comment (AlekseyTs) [inline src/Compilers/Test/Utilities/VisualBasic/BasicTestBase.vb]: >Dim tree = (From t In compilation.SyntaxTrees Where t.FilePath = fileName).Single() [](start = 8, length = 83)

Why so complex? Would ```node.SyntaxTree``` work?

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb [hunk 23]
```diff
@@ -821,5 +831,198 @@ BC30272: 'y' is not a parameter of 'Public Sub M2(x As Integer)'.
...
+            Dim compilation = CreateCompilationWithMscorlib45AndVBRuntime({syntaxTree}, DefaultVbReferences.Concat({ValueTupleRef, SystemRuntimeFacadeRef}))
+            Dim result = GetOperationAndSyntaxForTest(Of InvocationExpressionSyntax)(compilation, fileName)
+
+            Dim operatorNodes = compilation.SyntaxTrees(0).GetRoot().DescendantNodes.Where(Function(n As SyntaxNode) As Boolean
+                                                                                           return n.Kind = SyntaxKind.OperatorStatement
+                                                                                        End Function).ToList()
+            Dim semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees(0))
+            
+            Dim expectedInKind = ConversionKind.Widening Or ConversionKind.UserDefined
+            Dim exptectedInMethod = CType(semanticModel.GetDeclaredSymbolFromSyntaxNode(operatorNodes(0)), IMethodSymbol)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb]: >CType(semanticModel.GetDeclaredSymbolFromSyntaxNode(operatorNodes(0)), IMethodSymbol) [](start = 36, length = 85)

This looks more complicated than it should be. There is no need to use semantic model to find methods, I believe that could be done by name.

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb [hunk 24]
```diff
@@ -821,5 +831,198 @@ BC30272: 'y' is not a parameter of 'Public Sub M2(x As Integer)'.
...
+BC33037: Cannot copy the value of 'ByRef' parameter 'a' back to the matching argument because type 'Integer' cannot be converted to type 'C'.
+        M2(x)'BIND:"M2(x)"
+           ~
+]]>.Value
+            VerifyOperationTreeAndDiagnosticsForTest(Of InvocationExpressionSyntax)(source, expectedOperationTree, expectedDiagnostics)
+        End Sub
+
+        <CompilerTrait(CompilerFeature.IOperation)>
+        <Fact>
+        Public Sub GettingInOutConverionFromVBArgument()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IArgument.vb]: >GettingInOutConverionFromVBArgument [](start = 19, length = 35)

There is probably a value in testing clone operation, consider keeping the TestCloneInOutConversion unit-test from iteration 21.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 22). The only blocking issue is the failing test.

**Comment by genlu** [comment]
@dotnet/roslyn-infrastructure It seems the tests are not triggered by new commits. Any ideas?

**Comment by AlekseyTs** [comment]
> It seems the tests are not triggered by new commits. Any ideas?

Looking into this.

**Comment by genlu** [comment]
@cston Can I get another review from compiler team please?

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 25]
```diff
@@ -2214,6 +2221,34 @@ struct G<T>
             VerifyOperationTreeAndDiagnosticsForTest<InvocationExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
         }
 
+
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [Fact]
+        public void GettingInOutConverionFromCSharpArgumentShouldThrowException()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Typo: `Conversion`

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 26]
```diff
@@ -2214,6 +2221,34 @@ struct G<T>
...
+";
+            var compilation = CreateCompilation(source);
+            var (operation, syntaxNode) = GetOperationAndSyntaxForTest<InvocationExpressionSyntax>(compilation);
+
+            var invocation = (IInvocationExpression)operation;
+            var argument = invocation.ArgumentsInEvaluationOrder[0];
+
+            Assert.Throws<ArgumentException>(() => argument.GetInConversion());
+            Assert.Throws<ArgumentException>(() => argument.GetOutConversion());
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Where are `GetInConversion` and `GetOutConversion` defined? And why do they throw `ArgumentException` in this case?

File: src/Compilers/CSharp/Portable/Operations/CSharpArgument.cs [hunk 27]
```diff
@@ -0,0 +1,43 @@
...
+            base(argumentKind, parameter, semanticModel, syntax, type, constantValue, isImplicit)
+        {
+        }
+
+        public override CommonConversion InConversion => new CommonConversion(exists:true, isIdentity:true, isNumeric:false, isReference:false, methodSymbol:null);
+
+        public override CommonConversion OutConversion => new CommonConversion(exists: true, isIdentity: true, isNumeric: false, isReference: false, methodSymbol: null);
+    }
+
+    internal sealed partial class CSharpArgument : BaseCSharpArgument
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpArgument.cs]: Do these `CSharpArgument` classes need to be `partial`?

File: src/Compilers/Test/Utilities/VisualBasic/BasicTestBase.vb [hunk 28]
```diff
@@ -852,6 +852,23 @@ Public MustInherit Class BasicTestBaseBase
...
+            Return (Nothing, Nothing)
+        End If
+        
+        Dim semanticModel = compilation.GetSemanticModel(node.SyntaxTree)
+        Dim operation = semanticModel.GetOperationInternal(node)
+        If operation IsNot Nothing Then
+            Return (operation, node)
+        Else
+            Return (Nothing, Nothing)
+        End If
```
Comment (cston) [inline src/Compilers/Test/Utilities/VisualBasic/BasicTestBase.vb]: Is `If operation IsNot Nothing` necessary or could this method `Return (operation, node)` always?

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs (hunk 26 above)
Comment (genlu) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Those are extension methods for VB only (defined in MS.CA.VB.dll), as it returns VB `Conversion`. In this test we pass in an IArgument from C# code, therefore it throws.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 29]
```diff
@@ -120,12 +134,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
                             kind,
                             parameter,
                             value,
-                            inConversion:=Nothing,
-                            outConversion:=Nothing,
+                            inConversion:=New Conversion(Conversions.Identity),
+                            outConversion:=New Conversion(Conversions.Identity),
                             semanticModel:=_semanticModel,
                             syntax:=value.Syntax,
                             type:=Nothing,
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: It looks like the only difference between `If` and `Else` is `kind`. Consider calculating `kind` inside the `If` and move the remainder outside the `If`.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs (hunk 26 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Are these `VisualBasicExtension` methods? If so, perhaps add a comment here so it's clear why we expect exceptions to be thrown.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 30]
```diff
@@ -2245,6 +2245,7 @@ static void M2(int x)
             var invocation = (IInvocationExpression)operation;
             var argument = invocation.ArgumentsInEvaluationOrder[0];
 
+            // We are calling VB extension methods on IArgument in C# code, therefore exception is expteced here.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Typo: `expected`

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 31]
```diff
@@ -105,47 +105,37 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                            isImplicit:=isImplicit)
+                        kind = If(argument.WasCompilerGenerated, ArgumentKind.DefaultValue, ArgumentKind.Explicit)
+                        parameter = parameters(index)
                     End If
+                    
+                    Dim value = Create(argument)
+                    Return New VisualBasicArgument(
+                        kind,
+                        parameter,
+                        Create(argument),
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: `value`

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 32]
```diff
@@ -105,47 +105,37 @@ Namespace Microsoft.CodeAnalysis.Semantics
                         isImplicit:=isImplicit)
                 Case Else
                     Dim lastParameterIndex = parameters.Length - 1
+                    Dim kind As ArgumentKind
+                    Dim parameter As ParameterSymbol
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: `parameter = parameters(index)` in both branches.
