### PR TITLE
Set val escape on expression variables

### LINKED ISSUE #22361: Out vars should get their safe-to-escape scope from their declaring expression
From discussion with Neal and Vlad, declaration expressions should not contribute to the check of mixing on invocations. Instead, once the val escape of the invocation is determined (ignoring such declaration expressions), the val escape should be set onto those declaration expressions.

This is not critical to address in 15.5, as it should not be a breaking change (it will open up one of the usages in the example below).

```C#
        [Fact]
        public void RefLikeOutVarFromLocal()
        {
            var text = @"
using System;

public class C
{
    public void M(ref S global)
    {
        S local1 = stackalloc int[10];
        local1.M(out S local2); // we'd want this to succeed, but determine the safe-to-escape scope for local2 based on the invocation that declared it
        local1 = local2; // then this would be allowed 
        global = local2; // and this would fail 
    }
    public static void Main() => throw null;
}

public ref struct S
{
    public static implicit operator S(Span<int> s) => throw null;
    public void M(out S s) => throw null;
}
";
            CreateCompilationWithMscorlibAndSpan(text).VerifyDiagnostics(
                // (9,9): error CS8352: Cannot use local 'local1' in this context because it may expose referenced variables outside of their declaration scope
                //         local1.M(out S local2);
                Diagnostic(ErrorCode.ERR_EscapeLocal, "local1").WithArguments("local1").WithLocation(9, 9)
                );
        }
```

### LINKED ISSUE #64394: Incorrect scoped lifetime inference for out locals
**Version Used**: 4.4.0-3.22479.16 (23ecea2c)

**Steps to Reproduce**:

```csharp
ref struct ByteContainer
{
    public byte B;

    public static void GetSpan(ref ByteContainer @this, out Span<byte> span)
    {
        span = new(ref @this.B); // Ok: @this has RSTE to return-only, and out is STE return-only by default
    }

    public static void Test1(scoped ref ByteContainer container)
    {
        // error CS9075: Cannot return a parameter by reference 'container' because it is scoped to the current method
        // error CS8350: This combination of arguments to 'ByteContainer.GetSpan(ref ByteContainer, out Span<byte>)' is disallowed because it may expose variables referenced by parameter 'this' outside of their declaration scope
        GetSpan(ref container, out Span<byte> span);
    }
}
```

**Expected Behavior**:

The code should compile fine, and `span` should be implicitly `scoped`.

**Actual Behavior**:

Code fails to compile with the errors above.

**Additional notes**:

Related to #64318 (cc. @jaredpar as discussed on Discord).

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #64394
Closes #22361

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -3078,6 +3086,72 @@ private BoundExpression BindArgumentExpression(BindingDiagnosticBag diagnostics,
...
+                        return inferredOutArgumentSafeToEscape;
+                    }
+
+                    // the safe-to-escape of any out parameters in the method we are calling.
+                    uint outParamSafeToEscape = UseUpdatedEscapeRulesForInvocation(leastOverriddenMember) ? ReturnOnlyScope : CallingMethodScope;
+
+                    // the narrowest safe-to-escape of any argument which can escape (either by-value or by-reference) into the argument for any out parameter.
+                    uint narrowestArgSafeToEscape = CallingMethodScope;
+
+                    // TODO: try and reuse arg-mixing bits to reduce redundant logic here
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:3103]: sharing the "get escape values" logic is tricky here because several collections which ValueChecks wants as immutable are still builders in here. Overload resolution is done here, but we haven't bound default arguments (which I don't think matters for escape, since constants can always escape anywhere).

Maybe we should move this inference to occur *during* argument mixing checks somehow?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:3103]: I think effectively re-implsementing teh mixing logic here is fragile, I'd prefer we just refactored the underlying code to accept both types of inputs.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -3078,6 +3086,72 @@ private BoundExpression BindArgumentExpression(BindingDiagnosticBag diagnostics,
...
+
+                    if (receiver is not null && leastOverriddenMember.EnclosingThisSymbol() is { } thisParam)
+                    {
+                        findNarrowestArgumentEscape(thisParam, receiver);
+                    }
+
+                    lazyInferredOutArgumentSafeToEscape = narrowestArgSafeToEscape;
+                    return narrowestArgSafeToEscape;
+
+                    void findNarrowestArgumentEscape(ParameterSymbol sourceParam, BoundExpression argument)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:3140]: This is re-implementing the logic it took us so long to agree on in my previous PR. Duplicating the logic at a different layer in a different way seems like it's not the right path forward.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:3140]: I agree, I just don't know what that factoring looks like yet.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:3103]: Why would we not just add the inference to the start of `CheckInvocationArgMixing`? That is the choke point of our analysis and it's called on all method invocation paths. The only downside I could see is that we end up possibly doing inference twice but that should be fine cause it's idempotent

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 3]
```diff
@@ -4106,25 +4106,16 @@ public void M(ref S global)
...
-            // Tracking issue: https://github.com/dotnet/roslyn/issues/22361
-
             if (languageVersion == LanguageVersion.CSharp10)
             {
-                CreateCompilationWithMscorlibAndSpan(text, parseOptions: TestOptions.Regular.WithLanguageVersion(languageVersion)).VerifyDiagnostics(
-                    // (9,9): error CS8352: Cannot use variable 'local1' in this context because it may expose referenced variables outside of their declaration scope
-                    //         local1.M(out S local2);
-                    Diagnostic(ErrorCode.ERR_EscapeVariable, "local1").WithArguments("local1").WithLocation(9, 9)
-                    );
+                CreateCompilationWithMscorlibAndSpan(text, parseOptions: TestOptions.Regular.WithLanguageVersion(languageVersion)).VerifyDiagnostics();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4111]: it seems off to me that no error is given here in C# 10. I'm not sure why yet.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 4]
```diff
@@ -4714,5 +4705,254 @@ .maxstack  1
...
+                    {
+                        // RSTE of rs3 is CurrentMethod
+                        // STE of rs4 (local variable) is also CurrentMethod
+                        M0(ref rs3, out var rs4);
+                        return rs4; // 1
+                    }
+                }
+                """;
+
+            var comp = CreateCompilation(source, runtimeFeature: RuntimeFlag.ByRefFields);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4736]: >runtimeFeature: RuntimeFlag.ByRefFields [](http://example.com/codeflow?start=49&length=39)

It looks like the `runtimeFeature:` argument is not needed for these new tests.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 5]
```diff
@@ -2264,8 +2299,14 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
                     return true;
                 }
 
+                // track the widest scope that arguments could safely escape to.
+                // use this scope as the inferred STE of declaration expressions.
+                var escapeFrom = CallingMethodScope;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2304]: >escapeFrom [](http://example.com/codeflow?start=20&length=10)

The name `escapeFrom` is confusing if this is the scope that arguments can escape to.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 6]
```diff
@@ -2352,6 +2401,24 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+            // use this scope as the inferred STE of declaration expressions.
+            var escapeFrom = CallingMethodScope;
+            foreach (var (_, fromArg, _, isRefEscape) in escapeValues)
+            {
+                escapeFrom = Math.Max(escapeFrom, isRefEscape
+                    ? GetRefEscape(fromArg, scopeOfTheContainingExpression)
+                    : GetValEscape(fromArg, scopeOfTheContainingExpression));
+            }
+
+            foreach (var (fromParameter, fromArg, _, _) in escapeValues)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2414]: >fromParameter [](http://example.com/codeflow?start=26&length=13)

`_`?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 7]
```diff
@@ -1943,7 +1943,11 @@ bool isRefEscape
                         parameters[argsToParamsOpt.IsDefault ? argIndex : argsToParamsOpt[argIndex]] :
                         null;
 
-                    if (mixableArguments is not null && isMixableParameter(parameter))
+                    if (mixableArguments is not null
+                        && isMixableParameter(parameter)
+                        // assume any declaration variable is a valid mixing destination,
+                        // since we are going to infer a val-escape which makes it valid.
+                        && !IsLocalDeclarationExpression(argument, out _))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1950]: >!IsLocalDeclarationExpression(argument, out _) [](http://example.com/codeflow?start=27&length=46)

Is it correct to skip an `out` declaration expression if the target parameter is `[UnscopedRef] out`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1950]: In this position, yes. Only val escape matters for mixing destinations.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2304]: I think perhaps the comment should be rephrased. Definitely the name `escapeTo` is taken in this context, it refers to a destination variable whose val-escape is already known, and may be too wide to be safely used as a destination.

The goal here is to determine the widest legal destination scope for the declaration variable. This destination scope is equal to the narrowest scope of any incoming references.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 8]
```diff
@@ -4714,5 +4705,284 @@ .maxstack  1
...
+                        rs2 = rs1;
+                    }
+
+                    static RS M1(scoped RS rs3)
+                    {
+                        // STE of rs3 is CurrentMethod
+                        // STE of rs4 (local variable) is also CurrentMethod
+                        M0(rs3, out var rs4);
+                        return rs4; // 1
+                    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4763]: >} [](http://example.com/codeflow?start=20&length=1)

Consider including:
```csharp
static RS M2(scoped RS rs3)
{
    M0(rs3, out RS rs4);
    return rs4; // 2
}
static RS M3(scoped RS rs3)
{
    RS rs4;
    M0(rs3, out rs4); // 3
    return rs4;
}
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 9]
```diff
@@ -4714,5 +4705,284 @@ .maxstack  1
...
+
+                    static RS M1(scoped ref RS rs3)
+                    {
+                        // RSTE of rs3 is CurrentMethod
+                        // STE of rs4 (local variable) is also CurrentMethod
+                        M0(ref rs3, out var rs4);
+                        return rs4; // 1
+                    }
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4733]: >} [](http://example.com/codeflow?start=16&length=1)

Consider including:
```csharp
static RS M2(scoped ref RS rs3)
{
    M0(ref rs3, out RS rs4);
    return rs4; // 2
}
static RS M3(scoped ref RS rs3)
{
    RS rs4;
    M0(rs3, out rs4); // 3
    return rs4;
}
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 10]
```diff
@@ -4714,5 +4705,284 @@ .maxstack  1
...
+                        rs1 = new RS(ref __refvalue(ai.GetNextArg(), int)); // 1
+                    }
+
+                    static RS M1(scoped RS rs2)
+                    {
+                        M0(out var rs3, __arglist(rs2));
+                        return rs3; // 2
+                    }
+
+                    static RS M2(scoped RS rs4)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4894]: >scoped RS [](http://example.com/codeflow?start=33&length=9)

`scoped ref RS`?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2304]: Perhaps `widestDestinationValEscape` or something like that would be a better name.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 11]
```diff
@@ -4714,5 +4705,284 @@ .maxstack  1
...
+                        rs2 = new RS(ref this);
+                    }
+
+                    RS M1()
+                    {
+                        // RSTE of `this` is CurrentMethod
+                        // STE of rs4 (local variable) is also CurrentMethod
+                        M0(out var rs4);
+                        return rs4; // 1
+                    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4947]: >} [](http://example.com/codeflow?start=20&length=1)

Consider including (for comparison):
```csharp
[UnscopedRef]
RS M2()
{
    M0(out var rs4);
    return rs4;
}
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 12]
```diff
@@ -1943,7 +1943,11 @@ bool isRefEscape
                         parameters[argsToParamsOpt.IsDefault ? argIndex : argsToParamsOpt[argIndex]] :
                         null;
 
-                    if (mixableArguments is not null && isMixableParameter(parameter))
+                    if (mixableArguments is not null
+                        && isMixableParameter(parameter)
+                        // assume any declaration variable is a valid mixing destination,
+                        // since we are going to infer a val-escape which makes it valid.
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1949]: Opened #64556

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4894]: Could you please clarify why we would change this?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 13]
```diff
@@ -2195,6 +2199,30 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
 
+        private static bool ShouldInferDeclarationExpressionValEscape(BoundExpression argument, [NotNullWhen(true)] out SourceLocalSymbol? localSymbol)
+        {
+            var symbol = argument switch
+            {
+                BoundDeconstructValuePlaceholder p => p.ExpressionSymbol,
+                BoundLocal { DeclarationKind: not BoundLocalDeclarationKind.None } l => l.ExpressionSymbol,
+                _ => null
+            };
+            if (symbol is SourceLocalSymbol { ValEscapeScope: CallingMethodScope } local)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2210]: note that we really would prefer to use a sentinel ValEscapeScope in cases like these (e.g. with value `1 << 32`.). I attempted to do this but it started to really churn and wanted to be expedient for the purposes of getting this fix in.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 12 above)
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1949]:
```suggestion
                        // assume any expression variable is a valid mixing destination,
                        // since we will infer a legal val-escape for it (if it doesn't already have a narrower one).
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 14]
```diff
@@ -2252,6 +2280,13 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
             {
                 foreach (var (_, argument, refKind) in escapeArguments)
                 {
+                    if (ShouldInferDeclarationExpressionValEscape(argument, out _))
+                    {
+                        // assume any declaration variable is a valid mixing destination,
+                        // since we are going to infer a val-escape which makes it valid.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2286]:
```suggestion
                        // assume any expression variable is a valid mixing destination,
                        // since we will infer a legal val-escape for it (if it doesn't already have a narrower one).
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 15]
```diff
@@ -2352,6 +2401,24 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
                 }
             }
 
+            // find the widest scope that arguments could safely escape to.
+            // use this scope as the inferred STE of declaration expressions.
+            var escapeFrom = CallingMethodScope;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2406]:
```suggestion
            var inferredDestinationValEscape = CallingMethodScope;
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 16]
```diff
@@ -2352,6 +2401,24 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+            foreach (var (_, fromArg, _, isRefEscape) in escapeValues)
+            {
+                escapeFrom = Math.Max(escapeFrom, isRefEscape
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2409]:
```suggestion
                inferredDestinationValEscape = Math.Max(inferredDestinationValEscape, isRefEscape
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 17]
```diff
@@ -2352,6 +2401,24 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+                    ? GetRefEscape(fromArg, scopeOfTheContainingExpression)
+                    : GetValEscape(fromArg, scopeOfTheContainingExpression));
+            }
+
+            foreach (var (_, fromArg, _, _) in escapeValues)
+            {
+                if (ShouldInferDeclarationExpressionValEscape(fromArg, out var localSymbol))
+                {
+                    localSymbol.SetValEscape(escapeFrom);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2418]:
```suggestion
                    localSymbol.SetValEscape(inferredDestinationValEscape);
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 18]
```diff
@@ -2352,6 +2401,24 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+            }
+
+            foreach (var (_, fromArg, _, _) in escapeValues)
+            {
+                if (ShouldInferDeclarationExpressionValEscape(fromArg, out var localSymbol))
+                {
+                    localSymbol.SetValEscape(inferredDestinationValEscape);
+                }
+            }
+
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2421]: Consider moving this into a named local function

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 19]
```diff
@@ -4714,5 +4705,377 @@ .maxstack  1
...
+                    static RS M2(scoped ref RS rs3)
+                    {
+                        M0(ref rs3, out RS rs4);
+                        return rs4; // 2
+                    }
+
+                    static RS M3(scoped ref RS rs3)
+                    {
+                        RS rs4;
+                        M0(rs3, out rs4); // 3
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4743]: >M0(rs3, [](http://example.com/codeflow?start=24&length=7)

Should be `ref rs3`. (Sorry, my code suggestion above was incorrect.)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs (hunk 10 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4935]: `scoped RS` makes sense.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 20]
```diff
@@ -4714,5 +4705,377 @@ .maxstack  1
...
+                        rs2 = new RS(ref rs1);
+                    }
+
+                    static RS M1(ref RS rs3)
+                    {
+                        // RSTE of rs3 is ReturnOnly.
+                        // However, since rs4 is 'scoped', its STE should be narrowed to CurrentMethod
+                        M0(ref rs3, out scoped var rs4);
+                        return rs4; // 1
+                    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:5059]: >} [](http://example.com/codeflow?start=20&length=1)

Consider also testing an explicit type:
```
static RS M2(ref RS rs3)
{
    M0(ref rs3, out scoped RS rs5);
    return rs5; // 2
}
```

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs (hunk 19 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4743]: Oops 😓 I should have spotted that the resulting diagnostic did not look useful..

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4111]: Were you able to debug through and figure this out?

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4111]: image

I can't put a comment on this line cause it's not in the change but that is the problem. The `receiver` is not in the `escapedArgs` list so it's not being factored during inference. Need to add it in before you do the inference. 

In the updated code path we consider the receiver just like any other arg hence everything works out. Possible we should just do the same here and keep it simple (assuming it doesn't cause a lot of test churn)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4111]: I think we should be able to delete the special path for the receiver, and use some kind of test against what its corresponding parameter is to decide to give the same diagnostic, and thereby avoid much test churn. I am hopeful this will be the case, anyway :)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4111]: Thanks for debugging it!

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 21]
```diff
@@ -2264,8 +2299,14 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
 
+                // track the widest scope that arguments could safely escape to.
+                // use this scope as the inferred STE of declaration expressions.
+                var inferredDestinationValEscape = CallingMethodScope;
                 foreach (var (parameter, argument, _) in escapeArguments)
                 {
+                    // in the old rules, we assume that refs cannot escape into ref struct variables.
+                    // e.g. in `dest = M(ref arg)`, we assume `ref arg` will not escape into `dest`, but `arg` might.
+                    inferredDestinationValEscape = Math.Max(inferredDestinationValEscape, GetValEscape(argument, scopeOfTheContainingExpression));
                     var valid = CheckValEscape(argument.Syntax, argument, scopeOfTheContainingExpression, escapeTo, false, diagnostics);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: >receiver: null, // receiver handled explicitly below [](http://example.com/codeflow?start=16&length=52)

Note: We also pass `receiver: null` in `GetInvocationEscapeScope()` and `CheckInvocationEscape()`. I think it's reasonable to keep those callers as is for now, but mentioning it in case I've overlooked something.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 22]
```diff
@@ -1943,7 +1943,11 @@ bool isRefEscape
                         parameters[argsToParamsOpt.IsDefault ? argIndex : argsToParamsOpt[argIndex]] :
                         null;
 
-                    if (mixableArguments is not null && isMixableParameter(parameter))
+                    if (mixableArguments is not null
+                        && isMixableParameter(parameter)
+                        // assume any expression variable is a valid mixing destination,
+                        // since we will infer a legal val-escape for it (if it doesn't already have a narrower one).
+                        && !ShouldInferDeclarationExpressionValEscape(argument, out _))
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1950]: I don't think `ShouldInferDeclarationExpressionValEscape` is the best call here. Consider in the future if we actually did the change where we checked if it had been previously inferred. At that point I would expect `Should` to return `false` as we've already inferred the value. 

Wouldn't it be more correct to change `isMixableParameter` to just return `false` for any declaration expression? Those are not mixable parameters because they're completely inferred.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 23]
```diff
@@ -2252,43 +2280,51 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+                    }
+                }
+
+                foreach (var (_, argument, _) in escapeArguments)
+                {
+                    if (ShouldInferDeclarationExpressionValEscape(argument, out var localSymbol))
+                    {
+                        localSymbol.SetValEscape(inferredDestinationValEscape);
                     }
                 }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2320]: This code is the same between new and updated rules. Should it be factored otu?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2320]: I think it is just beneath the bar of factoring out.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 24]
```diff
@@ -4714,5 +4697,400 @@ .maxstack  1
...
+
+                    static RS M2(ref RS rs5)
+                    {
+                        // RSTE of rs3 is ReturnOnly.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:5058]: >rs3 [](http://example.com/codeflow?start=35&length=3)

`rs5`

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 22 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: I thought this through a bit, and yeah, I don't think there are any scenarios where a declaration variable needs to be *checked* as a mixing destination, since either:

1. it is an out var at the top level of a script, therefore is a class field, therefore its type will never be ref struct
2. it is a `out scoped var` in which case the val-escape is the narrowest which is even permitted to be referenced at that location.
3. it is a regular `out var` in which case the widest legal val-escape is inferred for it.

**Review by cston — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 25]
```diff
@@ -2252,43 +2283,51 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
             {
                 foreach (var (_, argument, refKind) in escapeArguments)
                 {
+                    if (ShouldInferDeclarationExpressionValEscape(argument, out _))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2286]: I think we also wanted to change this to use 'isMixableArgument'.

I think the behavior/factoring for the current release is going to be fine, we just want to make sure to iron these kinds of things out when we refactor in 17.5.
