### PR TITLE
Rename - fix rename conflicts not displaying in UI

### LINKED ISSUE #81535: Rename dialog doesn't warn about conflicts new name will introduce
**Version Used**:  Channel: Canary
Version: 18.3.0 Insiders [11302.173.main]

**Steps to Reproduce**:

1. Create a C# class with methods Foo and Bar
2. Invoke Rename on Foo and type "Bar"

**Expected Behavior**:
Rename dialog should warn me about conflict with existing Bar method

**Actual Behavior**:
No warning in the dialog, but Bar gets some sort of red adornment and squiggle. But if it's out of view port I have no way of knowing.

Image

### PR DESCRIPTION
**Pull request by akhera99**
Fixes #81535 
The rename dialog stopped displaying conflict warnings when renaming an identifier that conflicted with an existing symbol.
In `OnReplacementsChanged` the conflict detection was inside a block that only executes when the validity state changes, which it does not between two valid identifiers.

### CODE REVIEW

File: src/EditorFeatures/Core/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs [hunk 1]
```diff
@@ -355,48 +355,48 @@ private void OnReplacementsComputed(object sender, IInlineRenameReplacementInfo
         if (Set(ref _isReplacementTextValid, result.ReplacementTextValid, "IsReplacementTextValid"))
```
Comment (akhera99) [inline src/EditorFeatures/Core/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs:355]: view with hide whitespace

**Comment by jasonmalinowski** [comment]
How hard is adding a test for this?
