### PR TITLE
For the purpose of runtime capability check require RuntimeFeature type to be a static class.

### LINKED ISSUE #50491: Stack Overflow when compiling RuntimeFeature as an interface without runtime libraries
**Steps to Reproduce**:

Create a C# file called example.cs with the following content:

```
namespace System.Runtime.CompilerServices
{
    public static partial interface RuntimeFeature
    {
        /// <summary>
        /// Indicates that this version of runtime supports default interface method implementations.
        /// </summary>
        public const string DefaultImplementationsOfInterfaces = nameof(DefaultImplementationsOfInterfaces);

    }
}

```
Then run the following command:
```
dotnet exec "C:\Program Files\dotnet\sdk\5.0.101\Roslyn\bincore\csc.dll" example.cs /t:library
```

This results in a Stack Overflow from the compiler. 

Compiler Version: 3.8.0-5.20570.14 (6559f38c)

**Expected Behavior**:

The compiler to not crash. It is expected that the code would not compile.

**Actual Behavior**:

The compiler crashes.

### PR DESCRIPTION
**Pull request by AlekseyTs**
This avoids going into a cycle while trying to compile malformed declaration of the type.
Fixes #50491.

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

File: src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs [hunk 1]
```diff
@@ -435,7 +442,7 @@ internal void SetOverrideRuntimeSupportsUnmanagedSignatureCallingConvention()
             => _overrideRuntimeSupportUnmanagedSignatureCallingConvention = true;
 
         internal bool RuntimeSupportsUnmanagedSignatureCallingConvention
-            => GetSpecialTypeMember(SpecialMember.System_Runtime_CompilerServices_RuntimeFeature__UnmanagedSignatureCallingConvention) is object
+            => RuntimeSupportsFeature(SpecialMember.System_Runtime_CompilerServices_RuntimeFeature__UnmanagedSignatureCallingConvention)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs:445]: This is probably going to conflict with https://github.com/dotnet/roslyn/pull/50845.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 2]
```diff
@@ -60139,5 +60139,96 @@ interface IC
...
+        [Fact, WorkItem(50491, "https://github.com/dotnet/roslyn/issues/50491")]
+        public void RuntimeFeatureAsInterface_01()
+        {
+            var source1 =
+@"
+namespace System.Runtime.CompilerServices
+{
+    public static partial interface RuntimeFeature
+    {
+        public const string DefaultImplementationsOfInterfaces = nameof(DefaultImplementationsOfInterfaces);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:60152]: Nit: empty line below.

Comment (333fred) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:60152]: (Not that I'm saying hold off, just that it's a race)

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs:445]: (Not that I'm saying hold off, just that it's a race)
