### PR TITLE
Only make members required when RequiredMemberAttribute is present

### LINKED ISSUE #68478: C# 11 required properties do not compile on dotnet 6
[Update(jcouv):] The ask is that required properties not be recommended by the IDE on .NET 6 or lower.

### Describe the bug
When I want to use required properties in a project targeting net6.0 with LangVersion set to latest I face some compile errors.

### To Reproduce

1.
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

</Project>

namespace Csharp11OnDotnet6;

public class Person
{
    public required string Name { get; init; }
}
```

2.`dotnet build`

### Exceptions (if any)

```
error CS0656: Missing compiler required member 'System.Runtime.CompilerServices.RequiredMemberAttribute..ctor'
error CS0656: Missing compiler required member 'System.Runtime.CompilerServices.CompilerFeatureRequi
redAttribute..ctor'
```

### Expected Behavior: build successful

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #68478

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs [hunk 1]
```diff
@@ -119,6 +120,28 @@ public static IEnumerable<object[]> AccessorAccessibilityModifierCombinationsWhe
             yield return new[] { "internal", "private protected" };
         }
 
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/68478")]
+        public async Task SimpleSetPropertyMissingRequiredAttribute()
+        {
+            var code =
+                """
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs:128]: ➡️ This is the style I use for raw strings.

File: src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs [hunk 2]
```diff
@@ -6,6 +6,7 @@
 using System.Collections.Generic;
 using System.Collections.Immutable;
 using System.Composition;
+using System.Runtime.CompilerServices;
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs:9]: :( Didn't mean to do this. Will fix.

File: src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs [hunk 3]
```diff
@@ -119,6 +120,28 @@ public static IEnumerable<object[]> AccessorAccessibilityModifierCombinationsWhe
             yield return new[] { "internal", "private protected" };
         }
 
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/68478")]
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs:124]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/68478")]
```

File: src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs:128]: my preference would also be consistency.   but it's not a deal breaker.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs (hunk 3 above)
Comment (sharwell) [reply src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs:124]: ➡️ Keeping this one as-is
