### PR TITLE
Fix parsing of constant patterns such as int.MaxValue

### LINKED ISSUE #10465: is-pattern-expression (1 is int.MaxValue) does not parse correctly
The code
```cs
    if (1 is int.MaxValue) {}
```
does not parse correctly when pattern-matching is enabled. The parser finds the type `int` and then treats `.MaxValue` as unexpected tokens.

### PR DESCRIPTION
**Pull request by gafter**
Fix parsing of constant patterns such as int.MaxValue
Remove two ambiguities in the formal grammar for type_pattern
Fixes #10465 

The issue (and fix) arises because of the inherent ambiguity between _type_ and _expression_ in the grammar

```antlr
relational_expression
    : relational_expression 'is' type
    | relational_expression 'is' pattern
    ;

pattern
    : constant_pattern
    ;

constant_pattern
    : shift_expression
    ;
```

I've adjusted the heuristics used to disambiguate them. In truly ambiguous cases, we parse as a type and then, if the binder finds a constant expression, we just use the value of that expression.

I'm doing some research now to determine if these heuristics introduce any incompatibilities.

@agocke @AlekseyTs Please review
@dotnet/roslyn-compiler FYI

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @AlekseyTs Please review. I have more PRs queued up behind these changes (i.e. blocked on this review).

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 1]
```diff
@@ -65,13 +65,14 @@ private CSharpSyntaxNode ParseTypeOrPattern()
                     if (node == null)
                     {
                         Debug.Assert(Precedence.Shift == Precedence.Relational + 1);
-                        if (IsExpectedBinaryOperator(tk) && GetPrecedence(SyntaxFacts.GetBinaryExpression(tk)) > Precedence.Relational)
+                        if (IsExpectedBinaryOperator(tk) && GetPrecedence(SyntaxFacts.GetBinaryExpression(tk)) > Precedence.Relational ||
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Can you surround this conditional with parens so the precedence is clear?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -15173,9 +15188,10 @@ public class X
 {
     public static void Main()
     {
-        Console.WriteLine(1 is 1);
-        Console.WriteLine(1 is int.MaxValue);
-        Console.WriteLine(new int[] {1, 2} is int[]);
+        Console.WriteLine(1 is 1); // true
+        Console.WriteLine(1L is int.MaxValue); // OK, but false
+        Console.WriteLine(1 is int.MaxValue); // false
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: I would expect a success case for matching against `int.MaxValue`

**Comment by agocke** [comment]
:+1: Aside from comments

**Comment by gafter** [comment]
@dotnet/roslyn-compiler @AlekseyTs Please review. I have more PRs queued up behind these changes (i.e. blocked on this review).

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 3]
```diff
@@ -65,13 +65,14 @@ private CSharpSyntaxNode ParseTypeOrPattern()
                     if (node == null)
                     {
                         Debug.Assert(Precedence.Shift == Precedence.Relational + 1);
-                        if (IsExpectedBinaryOperator(tk) && GetPrecedence(SyntaxFacts.GetBinaryExpression(tk)) > Precedence.Relational)
+                        if ((IsExpectedBinaryOperator(tk) && GetPrecedence(SyntaxFacts.GetBinaryExpression(tk)) > Precedence.Relational) ||
+                            tk == SyntaxKind.DotToken)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: It would be good to add a comment about why do we need to handle DotToken here.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 4]
```diff
@@ -15179,17 +15179,32 @@ public class X
 {
     public static void Main()
     {
-        Console.WriteLine(1L is 1); // should fail to compile due to type mismatch
-        Console.WriteLine(1L is int.MaxValue); // should fail to compile due to type mismatch
+        Console.WriteLine(1L is string); // warning: type mismatch
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Consider testing scenarios with qualified type names like System.String, etc.
