### PR TITLE
Fixed parsing logic for rsp file arguments to implement speced behavior.

### LINKED ISSUE #1784: Support /define values surrounded by quotes
`xbuild` will produce `/define` entries in the RSP file which have the following format:

``` 
/define:"VALUE1;VALUE2"
```

`mcs` appears to handle this case correctly but `csc` does not.  We need to extend `csc` to support this to make it easier to integrate into our cross platform tool chains.

### PR DESCRIPTION
**Pull request by VSadov**
In particular, it is allowed for arguments to have embedded quoted portions like

/define:Unquoted"Quoted"Unquoted"Quoted"

wich means

/define:UnquotedQuotedUnquotedQuoted

when passed on command line, and should mean exactly the same when passed in an rsp file.

The change fixes #1784

### CODE REVIEW

**Comment by VSadov** [comment]
@agocke , @jaredpar , @AlekseyTs , @gafter

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 1]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
...
+            if (v.IndexOf('"') < 0 && v.IndexOf('\\') < 0)
+            {
+                return v;
+            }
+
+            // split on " 
+            // except for preceeded by \ like  \" 
+            // ignore pairs like \\
+            bool afterSingleBackslash = false;
+            var splitted = Split(v, c =>
```
Comment (agocke) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: `splitted` -> `split`

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 2]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
...
 
+        private static string UnquoteAndUnescape(string v)
+        {
+            if (v.IndexOf('"') < 0 && v.IndexOf('\\') < 0)
+            {
+                return v;
+            }
+
+            // split on " 
+            // except for preceeded by \ like  \"
```
Comment (agocke) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: 'preceded'

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 3]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
                 }))
             .Select(arg => arg.Trim())                                                                  // Trim whitespace
             .TakeWhile(arg => (!removeHashComments || !arg.StartsWith("#", StringComparison.Ordinal)))  // If removeHashComments is true, skip all arguments after one that starts with '#'
-            .Select(arg => CondenseDoubledBackslashes(arg).Unquote())                                   // Remove quotes and handle backslashes.
```
Comment (agocke) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: What happened to CondenseDoubledBackslashes?

As far as I can tell this was the only place that referenced the method. If it is now unused it should be deleted.

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 4]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
...
+            .Select(arg => UnquoteAndUnescape(NormalizeBackslashes(arg)))                                 // Remove quotes and handle backslashes.
             .Where(arg => !string.IsNullOrEmpty(arg));                        							// Don't produce empty strings.
         }
 
+        private static string UnquoteAndUnescape(string v)
```
Comment (agocke) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: A lot of the behavior here seems similar to the split in SplitCommandLineIntoArguments. Can we be clearer here about what the preconditions/postconditions are for this method?

How do we expect the command line to change after the first split and what do we expect it to look like after UnquoteAndUnescape?

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 5]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
                 }))
             .Select(arg => arg.Trim())                                                                  // Trim whitespace
             .TakeWhile(arg => (!removeHashComments || !arg.StartsWith("#", StringComparison.Ordinal)))  // If removeHashComments is true, skip all arguments after one that starts with '#'
-            .Select(arg => CondenseDoubledBackslashes(arg).Unquote())                                   // Remove quotes and handle backslashes.
+            .Select(arg => UnquoteAndUnescape(NormalizeBackslashes(arg)))                                 // Remove quotes and handle backslashes.
```
Comment (AlekseyTs) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: Formatting: consider aligning the comment at the end of the line with the one on the previous line.

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 6]
```diff
@@ -578,10 +578,52 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
...
+            for(int i = 0; i < splitted.Length; i++)
+            {
+                if (splitted[i].IndexOf('\\') >= 0)
+                {
+                    splitted[i] = splitted[i].Replace(@"\""", @"""");
+                    splitted[i] = splitted[i].Replace(@"\\", @"\");
+                }
+            }
+
+            // the behavior of unpaired quote seems to be not well undefined
```
Comment (AlekseyTs) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: Typo? "not well undefined"

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 7]
```diff
@@ -612,9 +654,9 @@ private static IEnumerable<string> Split(string str, Func<char, bool> splitHere)
         }
 
         /// <summary>
-        /// Condense double backslashes that precede a quotation mark to single backslashes.
+        /// Make all backslashes escaped regardless whether they preceed a quote or not.
```
Comment (AlekseyTs) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: Is this comment accurate? It looks like backslashes preceding a quote are handled differently.

Comment (VSadov) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: That is correct. In the input, the backslashes not preceding quotes are not escaped (possibly to not force the user to type so many slashes). That makes it very hard to either unescape slashes after quotes are removed or remove quotes after slashes are unescaped.
What is happening here is that I make the slashes that do not precede quotes to be "escaped" the same way as the slashes that do. This way I can later unescape slashes and not rely on presence of quotes.

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: done

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs (hunk 2 above)
Comment (VSadov) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: done

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs (hunk 4 above)
Comment (VSadov) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: No, the purpose of SplitCommandLineIntoArguments is to separate the line into multiple arguments on whitespaces. It needs to maintain the inQuotes state to ensure we do not break line while in a quoted text. It also needs to count slashes since odd number of slashes before a quote escaped that quote.

Once the line is split into arguments we need to remove quotes that are not escaped, and need to remove slashes that are used for escaping. That is what UnquoteAndUnescape does.

NormalizeBackslashes is just to be able to deal with slashes once quotes are removed. Whether slashes are as-is or escaping depend on whether they precede a quote. Normalizing turns the input into a form that is not dependent on the presence of quotes. Thus I no longer have circular dependency and can remove quotes first and then remove escaping slashes.

Comment (VSadov) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: added more comments

File: src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs [hunk 8]
```diff
@@ -578,10 +582,54 @@ public static IEnumerable<string> SplitCommandLineIntoArguments(string commandLi
...
+            for(int i = 0; i < split.Length; i++)
+            {
+                if (split[i].IndexOf('\\') >= 0)
+                {
+                    split[i] = split[i].Replace(@"\""", @"""");
+                    split[i] = split[i].Replace(@"\\", @"\");
+                }
+            }
+
+            // the behavior of unpaired quote seems to be not well undefined
```
Comment (AlekseyTs) [inline src/Compilers/Core/Desktop/CommandLine/CommonCommandLineParser.cs]: Typo? "NOT well UNdefined"

**Comment by AlekseyTs** [comment]
Other than a possible typo and a comment formatting issue, LGTM
