### PR TITLE
Fix receiver capturing for various extension scenarios

### LINKED ISSUE #79379: Inconsistent capturing for interpolated string handlers
`ExtensionTests.InterpolationHandler_StructReceiverParameter_ByValueThroughField` shows that capturing behaves differently when extension parameters are captured vs when the extension method is called in normal form.

Ref: https://github.com/dotnet/roslyn/pull/78425#issuecomment-3067521757.

### LINKED ISSUE #79436: Invalid order of evaluation for compound assignment involving expanded param array form
```
public struct S1
{
    public int this[int i, params int[] j]
    {
        get
        {
            System.Console.Write("get_Item ");
            System.Console.Write(i);
            System.Console.Write(j[0]);
            System.Console.Write(" ");
            return 0;
        }
        set
        {
            System.Console.Write("set_Item ");
            System.Console.Write(i);
            System.Console.Write(j[0]);
            System.Console.Write(value);
        }
    }
}

class Program
{
    static void Main()
    {
        Test1(default);
        System.Console.WriteLine();
        Test2(default);
    }

    static void Test1(S1 s)
    {
        s[Get1(), Get2()] += Get3(); 
    }

    static void Test2(S1 s)
    {
        s[Get1(), [Get2()]] += Get3(); 
    }
    
    public static int Get1()
    {
        System.Console.Write("Get1 ");
        return 1;
    }

    public static int Get2()
    {
        System.Console.Write("Get2 ");
        return 2;
    }

    public static int Get3()
    {
        System.Console.Write("Get3 ");
        return 3;
    }
}
```

Observed:
```
Get2 Get1 get_Item 12 Get3 set_Item 123
Get1 Get2 get_Item 12 Get3 set_Item 123
```

Expected: 
```
Get1 Get2 get_Item 12 Get3 set_Item 123
Get1 Get2 get_Item 12 Get3 set_Item 123
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #79379
Fixes #79436

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jcouv, @jjonescz, @dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 1]
```diff
@@ -673,41 +686,48 @@ private ImmutableArray<BoundExpression> VisitArgumentsAndCaptureReceiverIfNeeded
...
+                                               stackLocalsOpt: null))
+                            {
+                                refKind = RefKind.Ref;
+                            }
                         }
                     }
                 }
 
-                receiverTemp = _factory.StoreToTemp(rewrittenReceiver, out assignmentToTemp, refKind);
+                receiverTemp = _factory.StoreToTemp(rewrittenReceiver, out assignmentToTemp, (refKind is RefKind.RefReadOnlyParameter or RefKind.In) ? RefKindExtensions.StrictIn : refKind);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >(refKind is RefKind.RefReadOnlyParameter or RefKind.In) ? RefKindExtensions.StrictIn : refKind [](http://example.com/codeflow?start=93&length=94)

I didn't follow why we need this change. When I revert it, it doesn't seem to affect any extensions test.
If the change is desirable, would we also want it in `TransformPropertyOrEventReceiver` when computing the refKind for the temp for the receiver? #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 2]
```diff
@@ -157,30 +159,67 @@ private BoundExpression MakeIndexerAccess(
                 Debug.Assert(getMethod is not null);
 
                 ArrayBuilder<LocalSymbol>? temps = null;
+                bool needSpecialExtensionPropertyReceiverReadOrder = false;
+                ArrayBuilder<BoundExpression>? storesOpt = null;
+
+                if (IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, indexer))
+                {
+                    // The receiever has location, but extension indexer takes receiver by value.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]: Typo:
```suggestion
                    // The receiver has location, but extension indexer takes receiver by value.
``` #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 3]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
...
+
+            bool needSpecialExtensionPropertyReceiverReadOrder = false;
+            ArrayBuilder<BoundExpression>? storesOpt = null;
+
+            if (rewrittenReceiver is not null &&
+                assignmentKind is not (AssignmentKind.CompoundAssignment or AssignmentKind.NullCoalescingAssignment or AssignmentKind.Deconstruction or AssignmentKind.IncrementDecrement) &&
+                IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, property) &&
+                (arguments.Length != 0 || !IsSafeForReordering(rewrittenRight, RefKind.None)))
+            {
+                // The receiever has location, but extension property/indexer takes receiver by value.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: Typo:
```suggestion
                // The receiver has location, but extension property/indexer takes receiver by value.
``` #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 4]
```diff
@@ -264,6 +277,17 @@ private BoundExpression MakeStaticAssignmentOperator(
             }
         }
 
+        private bool IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(BoundExpression rewrittenReceiver, PropertySymbol property)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: >IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads [](http://example.com/codeflow?start=21&length=86)

Consider renaming to `IsExtensionPropertyWithByValPossiblyStructReceiverWhichHasHomeAndCanChangeValueBetweenReads` as only **extension** properties qualify and to avoid multiplying concepts ("home" versus "location"). #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 5]
```diff
@@ -157,30 +159,67 @@ private BoundExpression MakeIndexerAccess(
                 Debug.Assert(getMethod is not null);
 
                 ArrayBuilder<LocalSymbol>? temps = null;
+                bool needSpecialExtensionPropertyReceiverReadOrder = false;
+                ArrayBuilder<BoundExpression>? storesOpt = null;
+
+                if (IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, indexer))
+                {
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs:166]: ~~Consider leaving follow-up comment to cover this logic when implementing extension indexers~~ Never mind, I see you added skipped tests #Closed

**Comment by jcouv** [comment]
>     public void PropertyAccess_Set_01()

nit: consider adding tests for disambiguation invocation syntax (`E.set_P1(this, Program.Get1())`, where the setter will see the old value of the struct) and instance invocation scenarios (`S1` implements `P1`, where the setter sees the updated value of the struct) #Closed

---
Refers to: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs:5570 in 814baf6. [](commit_id = 814baf66da30869e33a17022a8bfad507df07933, deletion_comment = False)

**Comment by jcouv** [comment]
>     public void IndexerAccess_CompoundAssignment_01()

Thank you!

---
Refers to: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs:11763 in 814baf6. [](commit_id = 814baf66da30869e33a17022a8bfad507df07933, deletion_comment = False)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (commit 7) with some nits to consider

**Comment by AlekseyTs** [comment]
@jjonescz, @dotnet/roslyn-compiler For a second review

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 6]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
             }
 
             ArrayBuilder<LocalSymbol>? argTempsBuilder = null;
+
+            bool needSpecialExtensionPropertyReceiverReadOrder = false;
+            ArrayBuilder<BoundExpression>? storesOpt = null;
+
+            if (rewrittenReceiver is not null &&
+                assignmentKind is not (AssignmentKind.CompoundAssignment or AssignmentKind.NullCoalescingAssignment or AssignmentKind.Deconstruction or AssignmentKind.IncrementDecrement) &&
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:326]: Should we check that `assignmentKind is AssignmentKind.SimpleAssignment` instead? #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 7]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
...
+                IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, property) &&
+                (arguments.Length != 0 || !IsSafeForReordering(rewrittenRight, RefKind.None)))
+            {
+                // The receiever has location, but extension property/indexer takes receiver by value.
+                // This means that we need to ensure that the the receiver value is read after
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]:
```suggestion
                // This means that we need to ensure that the receiver value is read after
``` #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 8]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
...
+                // any side-effecting arguments and right hand side are evaluated, so that the
+                // the setter receives the last value of the receiver, not the value before the
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]:
```suggestion
                // setter receives the last value of the receiver, not the value before the
``` #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 9]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
...
+#endif
+                Debug.Assert(storesOpt is { });
+                Debug.Assert(storesOpt.Count != 0);
+                Debug.Assert(argTempsBuilder is not null);
+
+                // Store everything that is non-trivial into a temporary; record the
+                // stores in storesToTemps and make the actual argument a reference to the temp.
+                arguments = ExtractSideEffectsFromArguments(arguments, property, expanded, argsToParamsOpt, ref argumentRefKindsOpt, storesOpt, argTempsBuilder);
+
+                if (!IsSafeForReordering(rewrittenRight, RefKind.None))
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:367]: Consider caching and reusing the result of `IsSafeForReordering(rewrittenRight, RefKind.None)` from above. I guess it might not be always computed, but perhaps having a `bool?` and recomputing it only if null would still be worth it. #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 10]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
             }
 
             ArrayBuilder<LocalSymbol>? argTempsBuilder = null;
+
+            bool needSpecialExtensionPropertyReceiverReadOrder = false;
+            ArrayBuilder<BoundExpression>? storesOpt = null;
+
+            if (rewrittenReceiver is not null &&
+                assignmentKind is not (AssignmentKind.CompoundAssignment or AssignmentKind.NullCoalescingAssignment or AssignmentKind.Deconstruction or AssignmentKind.IncrementDecrement) &&
+                IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, property) &&
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: Do you now get some trophy for the longest method name in the codebase? :D #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 11]
```diff
@@ -644,6 +644,18 @@ internal static bool IsCapturedPrimaryConstructorParameter(BoundExpression expre
...
         /// might be present in the arguments and creating temps for any discard parameters.
+        /// 
+        /// When <paramref name="forceReceiverCapturing"/> is true (which means the receiver must be captured regardless of
+        /// interpolated string handler conversions needs), <paramref name="storesOpt"/> must be not null.
+        /// 
+        /// If receiver is captured by this method:
+        /// - If <paramref name="storesOpt"/> is not null, the sideeffect of capturing is added to <paramref name="storesOpt"/>
+        ///   and <paramref name="rewrittenReceiver"/> is changed to the captured value;
+        /// - Otherwise, <paramref name="rewrittenReceiver"/> is changed to a <see cref="BoundSequence"/> node with no locals,
+        ///   the sideeffects of capturing are the sifeeffects of the sequence and its result is the captured value.
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]:
```suggestion
        ///   the sideeffects of capturing are the sideeffects of the sequence and its result is the captured value.
```

nit: additionally, I would write "side effects" (here and in other added comments) as I don't think it's a single word. #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 12]
```diff
@@ -644,6 +644,18 @@ internal static bool IsCapturedPrimaryConstructorParameter(BoundExpression expre
...
+        ///   
+        /// All temps introduced by this function for capturing purposes (including the temp capturing the receiver) are appended
+        /// to <paramref name="tempsOpt"/>, which is allocated, if 'null' on input.
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]:
```suggestion
        /// to <paramref name="tempsOpt"/>, which is allocated if 'null' on input.
``` #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 13]
```diff
@@ -157,30 +159,67 @@ private BoundExpression MakeIndexerAccess(
...
+                    // The receiever has location, but extension indexer takes receiver by value.
+                    // This means that we need to ensure that the the receiver value is read after
+                    // any side-effecting arguments are evaluated, so that the
+                    // the setter receives the last value of the receiver, not the value before the
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]:
```suggestion
                    // setter receives the last value of the receiver, not the value before the
``` #Closed

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 14]
```diff
@@ -157,30 +159,67 @@ private BoundExpression MakeIndexerAccess(
                 Debug.Assert(getMethod is not null);
 
                 ArrayBuilder<LocalSymbol>? temps = null;
+                bool needSpecialExtensionPropertyReceiverReadOrder = false;
+                ArrayBuilder<BoundExpression>? storesOpt = null;
+
+                if (IsPropertyWithByValPossiblyStructReceiverWhichHasLocationAndCanChangeValueBetweenReads(rewrittenReceiver, indexer))
+                {
+                    // The receiever has location, but extension indexer takes receiver by value.
+                    // This means that we need to ensure that the the receiver value is read after
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]:
```suggestion
                    // This means that we need to ensure that the receiver value is read after
``` #Resolved

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 15]
```diff
@@ -21144,14 +21194,113 @@ public void M([System.Runtime.CompilerServices.InterpolatedStringHandlerArgument
 
     [Theory, WorkItem("https://github.com/dotnet/roslyn/issues/78137")]
     [CombinatorialData]
-    public void InterpolationHandler_ReceiverParameter_ByIn_WithConstantReceiver(bool useMetadataRef)
+    public void InterpolationHandler_ReceiverParameter_Generic_ByRef(bool useMetadataRef)
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:21197]: Consider referencing https://github.com/dotnet/roslyn/issues/79379 in the modified/added tests #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 16]
```diff
@@ -293,25 +318,73 @@ private BoundExpression MakePropertyAssignment(
...
+                (arguments.Length != 0 || !IsSafeForReordering(rewrittenRight, RefKind.None)))
+            {
+                // The receiever has location, but extension property/indexer takes receiver by value.
+                // This means that we need to ensure that the the receiver value is read after
+                // any side-effecting arguments and right hand side are evaluated, so that the
+                // the setter receives the last value of the receiver, not the value before the
+                // arguments/rhs were evaluated. Receiver sideeffects should be evaluated at
+                // the very beginning, of course.
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:335]: What happens when the receiver does not have a home; is that always an error scenario? #Resolved

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:326]: I am checking for assignments that I know don't need special treatment. Doing an opposite check is not robust in the long run, if new kind is added.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs (hunk 9 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:367]: > Consider caching and reusing the result of 

I prefer to not complicate code trying to optimize something that is not yet proven to be a problem

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs (hunk 16 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs:335]: > What happens when the receiver does not have a home; is that always an error scenario?

Not necessary. If the receiver doesn't have home, no one can change its value after we read it. Therefore, we don't need to worry about capturing it by reference and dereferencing it right before invoking the accessor. If we try to do so, the value will be captured in a temp anyway.

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: > When I revert it, it doesn't seem to affect any extensions test.

Added ```InterpolationTests.StructReceiver_Lvalue_08``` which crashes compiler without the change.

Adding similar change to ```TransformPropertyOrEventReceiver``` for consistency and future proofing
