### PR TITLE
VisitType should visit type arguments for error types.

### LINKED ISSUE #38403: Visual Studio 2019 (and preview) crashes when I paste this code into the editor
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/703896/visual-studio-2019-and-preview-crashes-when-i-past.html)._

---
What steps will reproduce the problem?
1. Create a new .NET Core 3.0 (preview 7 or 8) Console Project in latest Visua Studio 2019 16.2 or preview 2.0 16.3.0 
2.  Just paste the following code below into the editor (replace the existing code)
3. Visual Studio just hangs and after a while just crash

What is the expected output? What do you see instead?

Editor shoudl not crash, confirmed on a blank fresh installed Windows 10, with fresh install of latest VS2019 and .NET Core 3 preview.

Please provide any additional information below.

The code that I paste in (don't ask me why),  just copied from some website while exploring the non-nullable types feature.

```cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Text;

public abstract class QueryAsserterBase
{
    public abstract void AssertQueryScalar<TItem1, TResult>(
        Func<IQueryable<TItem1>, IQueryable<Nullable<TResult>>> actualQuery)
        where TResult : struct;
}

public class QueryAsserter<TContext> : QueryAsserterBase
{
    public override void AssertQueryScalar<TItem1, TResult>(
        Func<IQueryable<TItem1>, IQueryable<TResult?>> actualQuery)
    {          
    }
}
```

---
#### Fiona Niu[MSFT] on 8/22/2019, 00:15 AM: 

<p>Thank you for taking the time to log this issue! Could you please provide more information via the Visual Studio Feedback Tool(Help -&gt; Send Feedback -&gt; Report A Problem)so that we can conduct further research?  The feedback tool  will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:</p>
<pre><code>• Open Visual Studio Feedback tool.
 
• Click the banner letting you know that you have problems requesting your attention.
 
• Click this problem from the list

• Click &quot;View their request and respond&quot; from the problem details banner

• Add a comment, in the Attachments/Record: click Start Recording

• When the Steps Recorder tool appears, perform the steps that reproduce the problem.

• When you're done, choose the Stop Record button.
 
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.

• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don't appear on Developer Community.
</code></pre>
<p>For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
We look forward to hearing from you!</p>

#### visualstudio on 8/22/2019, 00:28 AM: 

I just copy paste the code from the issue and bang the studio stops responding, just crashes/dies after a while.  I can't type anything else after I paste the code into a new fresh console appliction.
#### Tore Nestenius on 8/22/2019, 00:32 AM: 

<p>You got my recording?</p>

#### Fiona Niu[MSFT] on 8/22/2019, 00:51 AM: 

<p>Thanks a lot for providing the information. We got your attachments. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Greg Smith on 8/26/2019, 08:53 AM: 

I also get this crash on the third paste of std::isfinite to replace _finite. Exactly as the OP reports, VS goes unreponsive for a few seconds, then restarts.

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #38403.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -13978,6 +13978,86 @@ public class QueryAsserter<TContext> : QueryAsserterBase
...
+        [Fact]
+        [WorkItem(38403, "https://github.com/dotnet/roslyn/issues/38403")]
+        public void Overriding_36()
+        {
+            var source =
+@"
+#nullable enable
+using System;
+using System.Collections.Generic;
+using System.Text;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Consider removing these `using` statements from the two tests since they only add diagnostics.
