### PR TITLE
Last  \r in source should not be represented as if there is another line in the source.

### LINKED ISSUE #8200: New line handling changed in Version 1.2
In version 1.0 the below code produced `lines1 == lines2 == 3`, while in 1.2 an exception is thrown in the last line. It seems like a super special corner case, but it introduces a breaking change in 1.2.

```C#
var code = "\n\r"; // Note, it's not "\r\n"
var tree = CSharpSyntaxTree.ParseText(code);
var lines1 = tree.GetText().Lines.Count; // 3
var lines2 = tree.GetLineSpan(Text.TextSpan.FromBounds(0, tree.Length)).EndLinePosition.Line + 1; // throws ArgumentOutOfRangeException
```

Exception details:
```
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: span
  ParamName=span
  Source=Microsoft.CodeAnalysis
  StackTrace:
       at Microsoft.CodeAnalysis.Text.TextLine.FromSpan(SourceText text, TextSpan span)
       at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
       at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.GetLineFromPosition(Int32 position)
       at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLinePosition(Int32 position)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
...
  InnerException: 

```

This change in behavior was probably introduced in https://github.com/dotnet/roslyn/commit/174bf9450553b5cc45393f0462badebdf2712753, in `ParseLineStarts()`.

### PR DESCRIPTION
**Pull request by VSadov**
Last  \r in source should not be represented as if there is another line in the source.

Doing so will cause crashes if such line is obtained and is also a compat break.

Fixes #8200

### CODE REVIEW

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please take a look.

File: src/Compilers/Core/Portable/Text/SourceText.cs [hunk 1]
```diff
@@ -801,7 +801,7 @@ private int[] ParseLineStarts()
                 var index = 0;
                 if (lastWasCR)
                 {
-                    if (buffer.Length > 0 && buffer[0] == '\n')
+                    if (length > 0 && buffer[0] == '\n')
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Text/SourceText.cs]: This change makes me a bit nervous.  This seems like it's been wrong for a very long time.  How often is this code path hit?

**Comment by VSadov** [comment]
Why tests not running?

File: src/Compilers/Core/Portable/Text/SourceText.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/Core/Portable/Text/SourceText.cs]: The codepath is hit very often, but condition is false only when \r is last in the buffer. That is not common.
 In other cases length > 0 and buffer is never empty.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
LGTM

**Comment by VSadov** [comment]
@dotnet-bot test this please
