### PR TITLE
Fix InvalidCastException in CSharpOperationFactory for invalid nested…

### LINKED ISSUE #22967: InvalidCastException in operation factory code (CreateBoundMemberInitializerOperation) while executing latest FxCop operation analyzers
**Version Used**: Install latest d15rel drop 27031.1.d15rel

**Steps to Reproduce**:

1. git clone https://github.com/JamesNK/Newtonsoft.Json
2. add myget package feed for roslyn-analyzers: https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json
3. install latest preview of Microsoft.CodeAnalysis.FxCopAnalyzers version 2.6.0-beta1-62231-02 to all projects in solution
4. enable FSA for C#

Got the following AD0002 diagnostic for crash in Operation factory while executing analyzers:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0002	Analyzer driver threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.LazyInvalidOperation' to type 'Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation'.'.	Newtonsoft.Json.Tests(net35)		1	Active	Analyzer driver threw the following exception:
'System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.LazyInvalidOperation' to type 'Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation'.
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.<>c__DisplayClass49_0.<CreateBoundMemberInitializerOperation>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Operations.BaseMemberInitializerExpression.<get_Children>d__6.MoveNext()
   at Microsoft.CodeAnalysis.Operations.OperationExtensions.<Descendants>d__3.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
-----
'.
```

### PR DESCRIPTION
**Pull request by mavasani**
… member initializer

Type for [IMemberInitializerOperation.InitializedMember](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IMemberInitializerOperation.cs,24) has been changed from an `IMemberReferenceOperation` to an `IOperation` to account for error cases where it could be an `IInvalidOperation`. Additionally, doc comments for `IMemberInitializerOperation` have been fixed and #22979 tracks possibly renaming this interface to make it explicit that it represents nested object or collection initializer.

Fixes #22967 
vso : [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/518820)

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IObjectCreationExpression.cs [hunk 1]
```diff
@@ -451,5 +451,137 @@ static void Main()
...
+                //         var x1 = /*<bind>*/new C() { MissingMember = 1 }/*</bind>*/;
+                Diagnostic(ErrorCode.ERR_NoSuchMember, "MissingMember").WithArguments("C", "MissingMember").WithLocation(6, 38)
+            };
+
+            VerifyOperationTreeAndDiagnosticsForTest<ObjectCreationExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
+        }
+
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [Fact, WorkItem(22967, "https://github.com/dotnet/roslyn/issues/22967")]
+        public void ObjectCreationWithInvalidMemberInitializer()
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IObjectCreationExpression.cs]: Verified that this test fails with the invalid cast exception prior to this fix.

**Review by 333fred — APPROVED** [review]

**Review by jinujoseph — APPROVED** [review]

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for reviews

**Review by cston — APPROVED** [review]

**Comment by natidea** [comment]
Approved to merge via [518820](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/518820)

**Review by AlekseyTs — APPROVED** [review]
LGTM

**Comment by AlekseyTs** [comment]
I am going to merge this because I keep running into the issue addressed by this PR.
