### PR TITLE
log watson when codefix or refactoring throws

### LINKED ISSUE #2002: we should log non-fatal watson when extension throws an exception
we need at least to do that for our own ones such as code fixer, code refactoring and etc.

### PR DESCRIPTION
**Pull request by jmarolf**
When a codefix or refactoring throws an exception, we turn it off, log
it to the activity log, and put up and info bar telling the user what
happened.

With this change we also check to see if the codefix/refactoring was
implemented by the roslyn team and send a non-fatal watson report.

Fixes #2002

### CODE REVIEW

**Comment by jmarolf** [comment]
@srivatsn @tmeschter @shyamnamboodiripad @heejaechang @mavasani @JohnHamby Could you take a look please?

File: src/Workspaces/Core/Portable/CodeFixes/ReportCrashDumpsToMicrosoft.cs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+﻿namespace Microsoft.CodeAnalysis
+{
+    internal interface ReportCrashDumpsToMicrosoft { }
```
Comment (shyamnamboodiripad) [inline src/Workspaces/Core/Portable/CodeFixes/ReportCrashDumpsToMicrosoft.cs]: Rename to IReportCrashDumpsToMicrosoft.

File: src/VisualStudio/Core/Def/Implementation/Log/VisualStudioErrorLogger.cs [hunk 2]
```diff
@@ -4,23 +4,51 @@
...
     internal class VisualStudioErrorLogger : IErrorLoggerService
     {
-        public void LogError(string source, string message)
+        public void LogException(object source, Exception exception)
         {
-            ActivityLog.LogError(source, message);
+            var name = source.GetType().Name;
+            ActivityLog.LogError(name, ToLogFormat(exception));
+
+            if (source is ReportCrashDumpsToMicrosoft)
```
Comment (shyamnamboodiripad) [inline src/VisualStudio/Core/Def/Implementation/Log/VisualStudioErrorLogger.cs]: Why not just check to see if the name of the crashing code fix / refactoring provider appears in ```PredefinedCodeFixProviderNames``` or ```PredefinedCodeRefactoringProviderNames```? That way, we won't need to remember to inherit the interface for any new fix / refactoring providers we add. All we would need to do is have its name be in one of the predefined lists...

**Comment by shyamnamboodiripad** [comment]
:+1: modulo couple of comments

File: src/VisualStudio/Core/Def/Implementation/Log/VisualStudioErrorLogger.cs [hunk 3]
```diff
@@ -4,23 +4,85 @@
...
-        public void LogError(string source, string message)
+        public void LogException(object source, Exception exception)
         {
-            ActivityLog.LogError(source, message);
+            var name = source.GetType().Name;
+            ActivityLog.LogError(name, ToLogFormat(exception));
+
+            if (ShouldReportCrashDumps(source))
+            {
+                using (var report = WatsonErrorReport.CreateNonFatalReport(new ExceptionInfo(exception, name)))
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Log/VisualStudioErrorLogger.cs]: any reason not using FatalError static type we use to abstract out actual watson?
