### PR TITLE
Produce an error when a bridge method must be variadic

### LINKED ISSUE #24348: Compiler crash when implementing a varargs method via a base class in another assembly
**Version Used**: Visual Studio 15.4.0

**Steps to Reproduce**:

1. Compile the following code to one assembly:
```cs
public class VarArgs
{
    public void Invoke(__arglist)
    {
        var ai = new System.ArgIterator(__arglist);
        System.Console.WriteLine(ai.GetRemainingCount());
    }
}
```
2. Create a new assembly with this code, and reference the first one:
```cs
interface IVarArgs
{
    void Invoke(__arglist);
}

class MyVarArgs : VarArgs, IVarArgs
{

}
```

**Expected Behavior**: A valid assembly should be produced.

**Actual Behavior**: The compiler crashes:

> An unhandled exception of type 'System.IndexOutOfRangeException' occurred in Microsoft.CodeAnalysis.dll
> Index was outside the bounds of the array.

    Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsTask.AnonymousMethod__0()
    [Native to Managed Transition] Annotated Frame
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GetCallStackBehavior(Microsoft.CodeAnalysis.CSharp.BoundCall call)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(Microsoft.CodeAnalysis.CSharp.BoundCall call, Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.UseKind useKind)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCoreWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression expression, bool used)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression expression, bool used)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> statements)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock block)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl()
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, int methodOrdinal, Microsoft.CodeAnalysis.CSharp.BoundStatement block, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo> lambdaDebugInfo, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo> closureDebugInfo, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol stateMachineTypeOpt, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator variableSlotAllocatorOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain importChainOpt, bool emittingPdb, bool emitTestCoverageData, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.SourceSpan> dynamicAnalysisSpans)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType)
    Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsTask.AnonymousMethod__0()
    Microsoft.CodeAnalysis.dll!Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0()
    mscorlib.dll!System.Threading.Tasks.Task.Execute()
    mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
    mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
    mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)
    mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)
    mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()

### PR DESCRIPTION
**Pull request by VSadov**
Fixes:#24348

### Customer scenario

Customer writes code that requires injection of a bridge method. If the method also turns out to be variadic, there is no reliable way to express that in CLR/IL. 
Current behavior in such situations is a compiler crash.

### Bugs this fixes

#24348

### Workarounds, if any

Not writing code that requires variadic bridge methods.

### Risk

Low. We are making a situation that is a crash to become a compiler error.

### Performance impact

"Low perf impact because no extra allocations/no complexity changes.

### Is this a regression from a previous update?

No.

### Root cause analysis

The bug could be fairly old. Only now reported.

### How was the bug found?

Customer reported.

### Test documentation updated?

N/A

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review. Basically detecting the offending condition and reporting an error.

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review. Basically detecting the offending condition and reporting an error.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 1]
```diff
@@ -13292,6 +13292,96 @@ .maxstack  4
...
+        [WorkItem(24348, "https://github.com/dotnet/roslyn/issues/24348")]
+        [Fact]
+        public void VarargBridgeMeta()
+        {
+            var reference = CreateStandardCompilation(@"
+public class VarArgs
+{
+    public void Invoke(__arglist)
+    {
+        var ai = new System.ArgIterator(__arglist);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Nit: Method body could be removed (`throw null` instead)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 2]
```diff
@@ -13292,6 +13292,96 @@ .maxstack  4
 ");
         }
 
+        [WorkItem(24348, "https://github.com/dotnet/roslyn/issues/24348")]
+        [Fact]
+        public void VarargBridgeSource()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Consider merging the tests.
The first test is easily implemented inside the second one (`CompileAndVerify(lib_cs + client_cs, ...`).

Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Before the fix one test would pass, and another would fail. It also easy to get into a regression where either both start failing or only one. I had such cases due to mistakes while fixing the bug.
I figured, it is better to keep separate tests so that it would be easy to diagnose what went wrong.

---
In reply to: [166780870](https://github.com/dotnet/roslyn/pull/24679#discussion_r166780870) [](ancestors = 166780870)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs (hunk 1 above)
Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: That is from the original repro. I think it is ok to have. At least as some extra coverage.

---
In reply to: [166780416](https://github.com/dotnet/roslyn/pull/24679#discussion_r166780416) [](ancestors = 166780416)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 3]
```diff
@@ -141,7 +141,16 @@ private void CheckAbstractClassImplementations(DiagnosticBag diagnostics)
 
                     if ((object)synthesizedImplementation != null)
                     {
-                        synthesizedImplementations.Add(synthesizedImplementation);
+                        if (synthesizedImplementation.IsVararg)
+                        {
+                            diagnostics.Add(
+                                ErrorCode.ERR_InterfaceImplementedImplicitlyByVariadic,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs]: >ErrorCode.ERR_InterfaceImplementedImplicitlyByVariadic,  [](start = 32, length = 56)

Can we report this error under umbrella of ReportImplicitImplementationMatchDiagnostics method?

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 4]
```diff
@@ -1755,6 +1755,9 @@ If such a class is used as a base class and if the deriving class defines a dest
   <data name="ERR_InterfaceImplementedByConditional" xml:space="preserve">
     <value>Conditional member '{0}' cannot implement interface member '{1}' in type '{2}'</value>
   </data>
+  <data name="ERR_InterfaceImplementedImplicitlyByVariadic" xml:space="preserve">
+    <value>'{0}' cannot implement interface member '{1}' in type '{2}' because it has an __arglist parameter. Use an explicit interface implementation.</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >Use an explicit interface implementation. [](start = 110, length = 41)

This is somewhat inaccurate, I think. Can't implicit implementation still be used in some scenarios? I mean one can provide a new implicit implementation within the current type declaration.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs (hunk 3 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs]: This is the place where we definitely know that we need a vararg bridge regardless of the reasons. 
I think placing check here is appropriate.

---
In reply to: [167038304](https://github.com/dotnet/roslyn/pull/24679#discussion_r167038304) [](ancestors = 167038304)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 5]
```diff
@@ -13292,6 +13292,96 @@ .maxstack  4
...
+        {
+
+            var code = @"
+public class VarArgs
+{
+    public void Invoke(__arglist)
```
[the remark this answers is not in the document]
Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: It would need to be in source. How can it differ in modifiers? Example?

---
In reply to: [167042260](https://github.com/dotnet/roslyn/pull/24679#discussion_r167042260) [](ancestors = 167042260)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 4 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/CSharpResources.resx]: This is a very extreme corner case involving undocumented feature. I thing the depth of the error message is good enough.

---
In reply to: [167041130](https://github.com/dotnet/roslyn/pull/24679#discussion_r167041130) [](ancestors = 167041130,167039605)

Comment (VSadov) [reply src/Compilers/CSharp/Portable/CSharpResources.resx]: Perhaps should not suggest anything at all. In some scenarios explicit implementation is not really possible. - If user actually _needs_ to bridge to the base method.

---
In reply to: [167087930](https://github.com/dotnet/roslyn/pull/24679#discussion_r167087930) [](ancestors = 167087930,167041130,167039605)

Comment (VSadov) [reply src/Compilers/CSharp/Portable/CSharpResources.resx]: Will remove the suggestion part.

---
In reply to: [167089732](https://github.com/dotnet/roslyn/pull/24679#discussion_r167089732) [](ancestors = 167089732,167087930,167041130,167039605)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Will spend some time investigating this scenario.

---
In reply to: [167087717](https://github.com/dotnet/roslyn/pull/24679#discussion_r167087717) [](ancestors = 167087717,167042260)

**Comment by VSadov** [comment]
@dotnet-bot test ubuntu_16_mono_debug_prtest  please

**Comment by VSadov** [comment]
CC:@jaredpar  for ask mode approval

**Comment by jaredpar** [comment]
Approved. 

Note: cannot update labels from my phone.

**Comment by jaredpar** [comment]
Ignore mono test failure. Andy is looking into this.

**Comment by VSadov** [comment]
Will also check with @AlekseyTs . He wanted a test with modopts. There is one now.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 6]
```diff
@@ -13292,6 +13292,148 @@ .maxstack  4
...
+
+";
+
+            var reference = CompileIL(il);
+
+            var code = @"
+
+public class VarArgs
+{
+    public int Invoke(__arglist) => throw null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: >public int Invoke(__arglist) => throw null; [](start = 4, length = 43)

Could you also test scenario:
```
class MyVarArgs2 : IVarArgs
{
    public int Invoke(__arglist) => throw null;
}
```

Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: added
