### PR TITLE
Recreate the get accessor when extracting an interface member

### LINKED ISSUE #71640: "Extract interface" generates invalid code for read-write properties
**Version Used**: VS 17.8.4

**Steps to Reproduce**:

Open the lightbulb menu on the type, select "Extract interface…" and confirm the dialog.

```csharp
struct S
{
    public int I { get; set; }
}
```

**Expected Behavior**:
Valid code is generated.

**Actual Behavior**:
The unexpected keyword "readonly" is placed in front of the "get" keyword, making the code syntactically invalid.

```csharp
interface IS
{
    int I { readonly get; set; }
}
```

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #71640 

The issue was that when we have a struct with an auto property, it will semantically get the readonly modifier applied even if no such modifiers existed on the syntax tree (this is an intentional behavior). This created a problem when extracting an interface because the modifier isn't valid for them.

This pr addresses this by recreating the get accessor symbol when creating the property member which will remove its readonly modifier.

### CODE REVIEW

File: src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs [hunk 1]
```diff
@@ -411,6 +411,19 @@ private static ImmutableArray<ISymbol> CreateInterfaceMembers(IEnumerable<ISymbo
...
+                        if (hasGetMethod)
+                        {
+                            // We recreate the get accessor because it is possible it has the readonly modifier due
+                            // to being an auto property on a struct which is invalid for an interface member
+                            getMethod = CodeGenerationSymbolFactory.CreateAccessorSymbol(
+                                property.GetMethod,
+                                property.GetMethod.GetAttributes(),
+                                property.GetMethod.DeclaredAccessibility,
+                                property.GetMethod.ExplicitInterfaceImplementations);
+                        }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs:425]: could you just call: CreateAccessorSymbol(property.GetMethod)?  it looks like that has the same result.  (you may need to get the attributes as well).  but the accessibility and explicit interface impls will be taken care of for you.

Comment (sdelarosbil) [reply src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs:421]: done, kept the attributes.

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi hey, is there anything else holding this pr for review?

**Review by CyrusNajmabadi — APPROVED** [review]
