### PR TITLE
Don't call GetGenericsArguments unless IsGeneric is true

### LINKED ISSUE #8452: NotSupportedException from CommonObjectFormatter.FormatMethodSignature
MethodBase.GetGenericArguments() shouldn't be called on ConstructorInfo.

```C#
> class C { public C() { throw new Exception("error"); } }
> new C();
Unexpected error:
System.NotSupportedException: Derived classes must provide an implementation.
   at System.Reflection.MethodBase.GetGenericArguments()
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatUnhandledException(Exception e)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpObjectFormatter.FormatUnhandledException(Exception e)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<>c__DisplayClass42_0.<<ExecuteOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteOnUIThread>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteAsync>d__30.MoveNext()
```

### PR DESCRIPTION
**Pull request by amcasey**
Fixes #8452

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat

File: src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs [hunk 1]
```diff
@@ -93,7 +93,7 @@ public virtual string FormatTypeArguments(Type[] typeArguments, CommonTypeNameFo
 
             if (typeArguments.Length == 0)
             {
-                return "";
+                throw new ArgumentException(nameof(typeArguments));
```
Comment (davkean) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs]: You're passing the name of _typeArguments_ as the message, I don't think you meant that. You probably want null as the message (inheriting the default, and passing nameOf(typeArguments) as the paramName.

File: src/Scripting/Core/Hosting/ObjectFormatter/CommonObjectFormatter.cs [hunk 2]
```diff
@@ -101,7 +101,7 @@ public override string FormatUnhandledException(Exception e)
         /// Returns a method signature display string. Used to display stack frames.
         /// </summary>
         /// <returns>Null if the method is a compiler generated method that shouldn't be displayed to the user.</returns>
-        protected virtual string FormatMethodSignature(MethodBase method)
+        protected internal virtual string FormatMethodSignature(MethodBase method)
```
Comment (davkean) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonObjectFormatter.cs]: Why the "internal" change?

**Comment by davkean** [comment]
Apart from the two comments, LGTM.

**Comment by tmat** [comment]
While you are changing this could you also rename ```FormatUnhandledException``` to ```FormatException```. Whether the exception has been handled or not seems irrelevant.

File: src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs (hunk 1 above)
Comment (tmat) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs]: Since this is effectively an internal type, might be just fine to replace these exceptions with Debug.Assert.

File: src/Scripting/Core/Hosting/ObjectFormatter/CommonObjectFormatter.cs (hunk 2 above)
Comment (amcasey) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonObjectFormatter.cs]: @davkean internal so that it can be called directly from a unit test.

File: src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs (hunk 1 above)
Comment (amcasey) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs]: @davkean, yes that was intended to be the paramName.  I naively assumed that the parameter order matched `ArgumentNullException`.

@tmat, it was public when I originally wrote the validation, but I can switch to asserts now.

Comment (amcasey) [inline src/Scripting/Core/Hosting/ObjectFormatter/CommonTypeNameFormatter.cs]: @tmat, converting all the other argument validation to asserts is out of scope for this change, so I'm just going to leave the exception for now.

**Comment by amcasey** [comment]
@tmat Renamed `FormatUnhandledException`.

**Comment by tmat** [comment]
:+1:
