### PR TITLE
Extract MEF-shared helper SQLiteConnectionPoolService

### LINKED ISSUE #48262: Integration test failure due to SQLite database locking
**Version Used**: #48250

🔗 https://dev.azure.com/dnceng/public/_build/results?buildId=840074

**Steps to Reproduce**:

Integration tests

**Actual Behavior**:

```
10/02/2020 18:43:52 Coordinated Universal Time: Error : 1 :[devenv:1868] Unexpected exception: StreamJsonRpc.RemoteInvocationException: database table is locked: DocumentData3
database table is locked
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__123`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__10`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 114
RPC server exception:
Microsoft.CodeAnalysis.SQLite.Interop.SqlException: database table is locked: DocumentData3
database table is locked
      at Microsoft.CodeAnalysis.SQLite.v2.Interop.SqlConnection.Throw(SafeSqliteHandle handle, Result result) in /_/src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs:line 326
      at Microsoft.CodeAnalysis.SQLite.v2.SQLitePersistentStorage.Accessor`3.InsertOrReplaceBlobIntoWriteCache(SqlConnection connection, TDatabaseId dataId, Byte[] checksumBytes, Int32 checksumLength, Byte[] dataBytes, Int32 dataLength) in /_/src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs:line 288
      at Microsoft.CodeAnalysis.SQLite.v2.SQLitePersistentStorage.Accessor`3.WriteStream(TKey key, Stream stream, Checksum checksumOpt, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs:line 140
      at Microsoft.CodeAnalysis.SQLite.v2.SQLitePersistentStorage.Accessor`3.<>c.<WriteStreamAsync>b__17_0(ValueTuple`5 t) in /_/src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs:line 126
      at Microsoft.CodeAnalysis.PooledObjects.PooledDelegates.FuncWithBoundArgument`2.<Bind>b__0_0() in /_/src/Dependencies/PooledObjects/PooledDelegates.cs:line 399
      at System.Threading.Tasks.Task`1.InnerInvoke()
      at System.Threading.Tasks.Task.Execute()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.SQLite.v2.SQLitePersistentStorage.<PerformTaskAsync>d__80`2.MoveNext() in /_/src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs:line 51
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<SaveAsync>d__69.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs:line 87
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<GetIndexWorkerAsync>d__12.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs:line 124
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<GetIndexAsync>d__11.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs:line 79
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.<CreateIndexAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_ProjectIndex.cs:line 61
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<AddDescendantSourceTypesInProjectAsync>d__20.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs:line 475
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<DescendInheritanceTreeInProjectAsync>d__7.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs:line 199
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<DescendInheritanceTreeAsync>d__6.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs:line 122
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<FindTypesInCurrentProcessAsync>d__30.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_Remote.cs:line 80
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   --- End of stack trace from previous location where exception was thrown ---
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindDerivedClassesArrayAsync>d__57.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 217
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<FindTypesAsync>d__29.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_Remote.cs:line 51
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindDerivedClassesArrayAsync>d__57.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 217
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindDerivedClassesAsync>d__56.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 209
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindImplementedInterfaceMembersArrayAsync>d__54.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 124
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractMethodOrPropertyOrEventSymbolReferenceFinder`1.<DetermineCascadedSymbolsAsync>d__1.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMethodOrPropertyOrEventSymbolReferenceFinder.cs:line 41
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.OrdinaryMethodReferenceFinder.<DetermineCascadedSymbolsAsync>d__1.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs:line 39
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_1.<<DetermineAllSymbolsCoreAsync>b__0>d.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_MapCreation.cs:line 148
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsCoreAsync>d__20.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_MapCreation.cs:line 168
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsAsync>d__19.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_MapCreation.cs:line 113
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindDerivedClassesAsync>d__56.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 209
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 57
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindImplementedInterfaceMembersArrayAsync>d__54.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs:line 124
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 63
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractMethodOrPropertyOrEventSymbolReferenceFinder`1.<DetermineCascadedSymbolsAsync>d__1.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMethodOrPropertyOrEventSymbolReferenceFinder.cs:line 41
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 67
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.OrdinaryMethodReferenceFinder.<DetermineCascadedSymbolsAsync>d__1.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs:line 39
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Current.cs:line 56
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsCoreAsync>d__20.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_MapCreation.cs:line 168
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__39.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Legacy.cs:line 80
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsAsync>d__19.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_MapCreation.cs:line 113
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.<FindAsync>d__1`1.MoveNext() in /_/src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs:line 52
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 57
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 63
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<>c__DisplayClass5_0.<<FindReferenceMethodsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs:line 95
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 67
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 69
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__40.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Legacy.cs:line 99
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__39.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Legacy.cs:line 80
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.<FindAsync>d__1`1.MoveNext() in /_/src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs:line 52
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<>c__DisplayClass5_0.<<FindReferenceMethodsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs:line 95
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 69
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #48262

Needed to unblock SQLite V2

### CODE REVIEW

**Comment by sharwell** [comment]
@CyrusNajmabadi This is ready for review now. I'll back out the second commit before merging.

File: src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs [hunk 1]
```diff
@@ -11,17 +11,29 @@
...
 #endif
 
 namespace Microsoft.CodeAnalysis.Storage
 {
     [ExportWorkspaceServiceFactory(typeof(IPersistentStorageService), ServiceLayer.Desktop), Shared]
     internal class PersistenceStorageServiceFactory : IWorkspaceServiceFactory
     {
+#if !DOTNET_BUILD_FROM_SOURCE
+        private readonly SQLiteConnectionPoolService _connectionPoolService;
+#endif
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs:24]: for my understanding, this is because in `DOTNET_BUILD_FROM_SOURCE` we just have no persistence service at all?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs:24]: Right, there is no SQLite reference.

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+
+        private void CloseWorker()
+        {
+            lock (_connectionGate)
+            {
+                // Go through all our pooled connections and close them.
+                while (_connectionsPool.Count > 0)
+                {
+                    var connection = _connectionsPool.Pop();
+                    connection.Close_OnlyForUseBySqlPersistentStorage();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs:74]: this method name may need to change.  i.e. Close_OnlyForUseBySQLiteConnectionPool

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+namespace Microsoft.CodeAnalysis.SQLite.v2
+{
+    [Export]
+    [Shared]
+    internal sealed class SQLiteConnectionPoolService : IDisposable
+    {
+        private const string LockFile = "db.lock";
+
+        /// <summary>
+        /// Maps from database path to connection pool.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:27]:
```suggestion
        /// Maps from database file path to connection pool.
```

up to you.

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+        /// </summary>
+        private readonly Dictionary<string, ReferenceCountedDisposable<SQLiteConnectionPool>> _connectionPools = new();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:29]: might want to mention what is used to loc this (presumably itself).

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+        {
+            lock (_connectionPools)
+            {
+                if (_connectionPools.TryGetValue(databaseFilePath, out var pool))
+                {
+                    return pool.TryAddReference() ?? throw ExceptionUtilities.Unreachable;
+                }
+
+                // try to get db ownership lock. if someone else already has the lock. it will throw
+                var ownershipLock = TryGetDatabaseOwnership(databaseFilePath);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:87]: such an add named API then.  if it throws when someone else has the lock, why is it called Try? Consider an enum that represents the different types of failure modes for tihs API (up to you).

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:87]: actually, this comment doesn't to even be true.  if someone has hte lock, we'll likely get an exception that is captured by IOUtilities.PerformIO right?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:87]: I believe this was moved without change from the old location

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs [hunk 6]
```diff
@@ -118,35 +118,31 @@ internal partial class SQLitePersistentStorage : AbstractPersistentStorage
...
 
-            _select_star_from_string_table = $@"select * from {StringInfoTableName}";
-            _insert_into_string_table_values_0 = $@"insert into {StringInfoTableName}(""{DataColumnName}"") values (?)";
-            _select_star_from_string_table_where_0_limit_one = $@"select * from {StringInfoTableName} where (""{DataColumnName}"" = ?) limit 1";
+            _connectionPool = connectionPoolService.TryOpenDatabase(
+                bulkLoadSnapshot,
+                databaseFile,
+                faultInjector,
+                (bulkLoadSnapshot, connection, cancellationToken) => Initialize(bulkLoadSnapshot, connection, cancellationToken),
+                CancellationToken.None)!;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs:145]: trying to figure out hte `!` reasoning here.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs:145]: ah, i think i get it from seeing later code.  would be worthwhile to doc this.  i.e. that we do this to temporarily violate NRT rules, but that this then checked immediately after in TryCreate.

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs [hunk 7]
```diff
@@ -156,122 +152,49 @@ internal partial class SQLitePersistentStorage : AbstractPersistentStorage
...
                 }
-                catch
+                catch (Exception e)
                 {
-                    // An exception (likely OutOfMemoryException) occurred while returning the connection to the pool.
-                    // The connection will be discarded, so make sure to close it so the finalizer doesn't crash the
-                    // process later.
-                    connection.Close_OnlyForUseBySqlPersistentStorage();
-                    throw;
+                    // Flushing may fail.  We still have to close all our connections.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs:185]: consider mentioning who will do this.   note: i haven't 100% convinced myself this works/is-desirable.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs (hunk 5 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:87]: I left this one since it was moved without changes.

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs (hunk 7 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs:185]: Not making changes to that since I wasn't touching this code (aside from a formatting-required indentation adjustment).

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs (hunk 6 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs:147]: :arrow_right: Now documented

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:34]: ➡️ Now documented

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs]: ➡️ Done

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs]: ➡️ Renamed

File: src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs [hunk 8]
```diff
@@ -0,0 +1,159 @@
...
+using Microsoft.CodeAnalysis.Host.Mef;
+using Microsoft.CodeAnalysis.Shared.Utilities;
+using Microsoft.CodeAnalysis.SQLite.v2.Interop;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.SQLite.v2
+{
+    [Export]
+    [Shared]
+    internal sealed class SQLiteConnectionPoolService : IDisposable
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:22]: would prefer hiding this behind an interface (our general pattern).  thoughts?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:22]: Interfaces come with an abstraction cost that is paid for my amortized reuse. There would not be any benefit here.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:22]: The types are intentionally coupled. The consumable export area is by definition the exposed API of the implementation type.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:22]: 📝 I agree with interfaces when they are added for decoupling purposes, but here is unique since the service was added to the catalog with intentional coupling to other type(s) in the same component, and not for other use.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs:22]: Ok :)
