### PR TITLE
Fix DataTips for parameterized property access...

### LINKED ISSUE #2602: DataTips are not working for parameterized properties
Reported via blog comment:

1.  Create a VB Console App with the following code:
```
Module Module1
    Sub Main()
        Dim row = New DataRow()
        Stop
        Dim test = row.Item("Test Row")
    End Sub

    Class DataRow
        Public ReadOnly Property Item(ByVal str As String) As String
            Get
                Return str
            End Get
        End Property
    End Class
End Module
```
2.  F5
3.  Hover over "Item" (in "row.Item")

**RESULTS:**
No DataTip appears...

**EXPECTED RESULTS**
datatip

### PR DESCRIPTION
**Pull request by KevinH-MS**
The language service should return the full invocation expression if you hover over a method/property group.  It's up to the EE to block evaluation of expressions that "may have side effects" (i.e. method invocations).

(fixes #2602)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
Tagging @amcasey @cston @ManishJayaswal for review...

File: src/VisualStudio/VisualBasic/Impl/Debugging/DataTipInfoGetter.vb [hunk 1]
```diff
@@ -38,33 +38,32 @@ Namespace Microsoft.VisualStudio.LanguageServices.VisualBasic.Debugging
                     Return Nothing
                 End If
 
+                Dim conditionalAccess As ExpressionSyntax = Nothing
                 If expression.IsRightSideOfDotOrBang() Then
-                    Dim parent = DirectCast(expression.Parent, ExpressionSyntax)
-                    Dim curr = parent
+                    expression = DirectCast(expression.Parent, ExpressionSyntax)
+                    Dim curr = expression
```
Comment (amcasey) [inline src/VisualStudio/VisualBasic/Impl/Debugging/DataTipInfoGetter.vb]: Consider inserting a blank line before the declaration of ```curr```.  I think that would make it clearer that two separate computations happen within the ```if```: one to update ```expression``` and another to update ```conditionalAccess```.

**Comment by amcasey** [comment]
It took me a while to convince myself that that's what your change did, but I agree that your version is clearer.

**Comment by amcasey** [comment]
Does something similar need to happen for indexer reads or are they also ```InvocationExpressions```?

**Comment by amcasey** [comment]
Is this in support of VB builtins that are known to be side-effect free?

File: src/VisualStudio/VisualBasic/Impl/Debugging/DataTipInfoGetter.vb (hunk 1 above)
Comment (KevinH-MS) [inline src/VisualStudio/VisualBasic/Impl/Debugging/DataTipInfoGetter.vb]: Done

**Comment by KevinH-MS** [comment]
@amcasey 

- Indexers (Default Property) - Yes, those are also InvocationExpressions (not distinguishable using syntax).
- Is this for builtins? - No, this is a general thing.  The properties we eval *may* actually have side-effects (but you can turn off property evaluation in Tools > Options if you want to be safe).

**Comment by amcasey** [comment]
LGTM
