### PR TITLE
Avoid stack overflow in blank-line analyzers on deep trees

### LINKED ISSUE #83481: AbstractMultipleBlankLinesDiagnosticAnalyzer stack overflows on ErrorFacts.cs
**Steps to Reproduce**:

Open dotnet/roslyn (I had 1e6b058d5a30301ff23cacfec0f31e47c49cdcfe checked out) in VSCode with C# DevKit (I was on latest prerelease). Then open `ErrorFacts.cs` file.

**Expected Behavior**: does not crash

**Actual Behavior**: stack overflows

<details>

```log
2026-04-29 11:46:56.796 [error] Stack overflow.
2026-04-29 11:46:56.798 [error]    at Microsoft.CodeAnalysis.SyntaxTriviaList.get_Item(Int32)
2026-04-29 11:46:56.798 [error]    at Microsoft.CodeAnalysis.NewLines.MultipleBlankLines.AbstractMultipleBlankLinesDiagnosticAnalyzer.ContainsMultipleBlankLines(Microsoft.CodeAnalysis.SyntaxToken, Microsoft.CodeAnalysis.SyntaxTrivia ByRef)
2026-04-29 11:46:56.798 [error]    at Microsoft.CodeAnalysis.NewLines.MultipleBlankLines.AbstractMultipleBlankLinesDiagnosticAnalyzer.Recurse(Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalysisContext, Microsoft.CodeAnalysis.CodeStyle.NotificationOption2, Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
... repeats 970 times ...
2026-04-29 11:46:56.816 [error]    at Microsoft.CodeAnalysis.NewLines.MultipleBlankLines.AbstractMultipleBlankLinesDiagnosticAnalyzer.Recurse(Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalysisContext, Microsoft.CodeAnalysis.CodeStyle.NotificationOption2, Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
2026-04-29 11:46:56.816 [error]    at Microsoft.CodeAnalysis.NewLines.MultipleBlankLines.AbstractMultipleBlankLinesDiagnosticAnalyzer+<>c__DisplayClass3_0.<InitializeWorker>b__1(Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalysisContext)
2026-04-29 11:46:56.816 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxTreeActions(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalyzerAction>, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.Diagnostics.SourceOrAdditionalFile, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>, Boolean, System.Threading.CancellationToken)
2026-04-29 11:46:56.816 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecuteSyntaxTreeActions(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, System.Threading.CancellationToken)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsAsync>d__135.MoveNext()
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ExecutePrimaryAnalysisTaskAsync>d__100.MoveNext()
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<AttachQueueAndProcessAllEventsAsync>d__98.MoveNext()
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<<ComputeAnalyzerDiagnosticsAsync>g__attachQueueAndProcessAllEventsAsync|62_0>d.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<<ComputeAnalyzerDiagnosticsAsync>g__attachQueueAndProcessAllEventsAsync|62_0>d, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<ComputeAnalyzerDiagnosticsAsync>g__attachQueueAndProcessAllEventsAsync|62_0>d ByRef)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<ComputeAnalyzerDiagnosticsAsync>d__62.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<ComputeAnalyzerDiagnosticsAsync>d__62, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<CreateAndInitializeDriverAsync>d__41.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<CreateAndInitializeDriverAsync>d__41, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunOrQueueCompletionAction(System.Threading.Tasks.ITaskCompletionAction, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskResult)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass88_0+<<Initialize>b__0>d.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass88_0+<<Initialize>b__0>d, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task`1[[System.ValueTuple`2[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.ValueTuple`2<Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions,System.__Canon>)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<GetAnalyzerActionsAsync>d__153.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`2[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<GetAnalyzerActionsAsync>d__153, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetAnalyzerActionsAsync>d__12.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetAnalyzerActionsAsync>d__12, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetCompilationAnalysisScopeAsync>d__6.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetCompilationAnalysisScopeAsync>d__6, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetCompilationAnalysisScopeCoreAsync>d__7.MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2026-04-29 11:46:56.817 [error]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetCompilationAnalysisScopeCoreAsync>d__7, Microsoft.CodeAnalysis, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.FinishStageTwo()
2026-04-29 11:46:56.817 [error]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
2026-04-29 11:46:56.817 [error]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2026-04-29 11:46:56.817 [error]    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
2026-04-29 11:46:56.817 [error]    at System.Threading.Thread.StartCallback()
```

</details>

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #83481.

`AbstractMultipleBlankLinesDiagnosticAnalyzer` was walking the tree recursively, which stack-overflowed on `ErrorFacts.cs`. Moved it to an explicit `ArrayBuilder<SyntaxNode>` stack (Push/TryPop), matching the pattern already used by the sibling `ConsecutiveBracePlacementDiagnosticAnalyzer`.

Did the same to `AbstractConsecutiveStatementPlacementDiagnosticAnalyzer` while I was here, since it has the identical recursive walk.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/83483)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jjonescz ptal.

File: src/Analyzers/Core/Analyzers/NewLines/ConsecutiveStatementPlacement/AbstractConsecutiveStatementPlacementDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -43,24 +43,30 @@ private void AnalyzeTree(SyntaxTreeAnalysisContext context, CompilationOptions c
...
             return;
 
-        Recurse(context, option.Notification, context.GetAnalysisRoot(findInTrivia: false), context.CancellationToken);
-    }
-
-    private void Recurse(SyntaxTreeAnalysisContext context, NotificationOption2 notificationOption, SyntaxNode node, CancellationToken cancellationToken)
-    {
-        if (node.ContainsDiagnostics && node.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error))
-            return;
+        var cancellationToken = context.CancellationToken;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/Analyzers/NewLines/ConsecutiveStatementPlacement/AbstractConsecutiveStatementPlacementDiagnosticAnalyzer.cs:46]: disable github whitespace for an easier diff.

**Comment by CyrusNajmabadi** [comment]
@akhera99  @JoeRobich @dibarbet @ToddGrun ptal.

**Comment by CyrusNajmabadi** [comment]
@davidwengier ptal :)

**Comment by ToddGrun** [comment]
LGTM, but I'll let one of the Roslyn folks sign off

---
In reply to: [4342944763](https://github.com/dotnet/roslyn/pull/83483#issuecomment-4342944763) [](http://example.com/codeflow?ancestors=4342944763)

**Review by jjonescz — APPROVED** [review]

**Comment by jjonescz** [comment]
Thanks!
