### PR TITLE
Fix override completion to preserve added imports

### LINKED ISSUE #39909: C# override completion does not seem to be adding using directives
**Version Used**: 16.5.0 Preview 2.0 [29519.175.master]

Is this a known regression?

### PR DESCRIPTION
**Pull request by genlu**
Fix #39909
The regression is caused by adding simplifier annotation to added imports (https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Editing/ImportAdderService.cs#L137)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> The regression is caused by adding simplifier annotation to added imports

Why does that cause a regression?

File: src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs [hunk 1]
```diff
@@ -178,8 +178,11 @@ private TextSpan ComputeDestinationSpan(SyntaxNode insertionRoot)
         private async Task<SyntaxNode> GetTreeWithAddedSyntaxNodeRemovedAsync(
             Document document, CancellationToken cancellationToken)
         {
-            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            // Added imports are annotated for simplification too. Therefore, we simplify the document
+            // before removing added member node to preserve those imports in the document.
+            document = await Simplifier.ReduceAsync(document, Simplifier.Annotation, null, cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs:183]: named arg for null.

File: src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs [hunk 2]
```diff
@@ -188,7 +191,6 @@ private TextSpan ComputeDestinationSpan(SyntaxNode insertionRoot)
 
             var dismemberedDocument = document.WithSyntaxRoot(root);
 
-            dismemberedDocument = await Simplifier.ReduceAsync(dismemberedDocument, Simplifier.Annotation, null, cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs:191]: why was this a problem here  why would reduction remove imports?

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs:191]: After overriding member is removed, added usings become unnecessary.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs:191]: i see :)

**Comment by genlu** [comment]
Retargeting to 16.6 since this is a regression. 
FYI @vatsalyaagrawal @jinujoseph

**Comment by genlu** [comment]
This is approved for 16.6.
