### PR TITLE
Fixed NRE in IntroduceVariableCodeRefactoringProvider refactoring

### LINKED ISSUE #21373: 'IntroduceVariableCodeRefactoringProvider' encountered an error and has been disabled
**Version Used**: 15.0.26228.9

:link: Originally reported by [Guy Haskell](https://developercommunity.visualstudio.com/users/8032/7704a496-8f92-43bd-9ee4-c54f69646e52.html) on [developer community](https://developercommunity.visualstudio.com/content/problem/35938/introducevariablecoderefactoringprovider-encounter.html).

**Steps to Reproduce**:

1. Add the following to a VB module:

    ```vb
    <Example(3 + 3)>
    Public Property NewProperty()
    ```

2. Select the expression `3 + 3`

3. Drop down the light bulb

See the following image:

image

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**

'IntroduceVariableCodeRefactoringProvider' encountered an error and has been disabled

**Bugs this fixes:**
Fixes #21373

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

### CODE REVIEW

File: src/Features/VisualBasic/Portable/IntroduceVariable/VisualBasicIntroduceVariableService.vb [hunk 1]
```diff
@@ -113,9 +113,11 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.IntroduceVariable
 
         Protected Overrides Function IsInAutoPropertyInitializer(expression As ExpressionSyntax) As Boolean
             Dim propertyStatement = expression.GetAncestorOrThis(Of PropertyStatementSyntax)()
+            Dim equalsValueStatement = expression.GetAncestorOrThis(Of EqualsValueSyntax)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/IntroduceVariable/VisualBasicIntroduceVariableService.vb]: do we have this problem for C# as well?

Comment (zaytsev-victor) [inline src/Features/VisualBasic/Portable/IntroduceVariable/VisualBasicIntroduceVariableService.vb]: No, we don't have this problem for C#
