### PR TITLE
Limit the FileSystemWatchers to one per drive root for DefaultFileChangeWatcher

### LINKED ISSUE #82198: roslyn-language-server on linux hits inotify limits
Using the roslyn-language-server dotnet tool, we fallback to the .NET file watcher.  On linux loading roslyn, this causes many errors like
`Error while loading /home/dabarbet/source/repos/roslyn/src/Workspaces/MSBuild/Test/Resources/ProjectFiles/CSharp/MallformedAdditionalFilePath.csproj: Exception thrown: System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.`

### PR DESCRIPTION
**Pull request by JoeRobich**
To reduce the number of inotify instances, instead of creating individual file watchers for watched directories and file, we will create a watcher for the drive root and share it across contexts.

resolves #82198

### CODE REVIEW

File: src/Compilers/Test/Core/TempFiles/TempRoot.cs [hunk 1]
```diff
@@ -19,7 +19,31 @@ public sealed class TempRoot : IDisposable
 
         static TempRoot()
         {
-            Root = Path.Combine(Path.GetTempPath(), "RoslynTests");
+            var tempDirectory = new DirectoryInfo(Path.GetTempPath());
+
+#if NET
```
Comment (JoeRobich) [inline src/Compilers/Test/Core/TempFiles/TempRoot.cs:24]: Running the tests on MacOS fail without this change. Path.GetTempPath will return `/var/folders/...` which is a symlink to `/private/var/folders/...`. So we need to resolve the link because FileChanged event use the real path. We do this by walking up the temp path until we find a directory that is a link.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs [hunk 2]
```diff
@@ -2,135 +2,121 @@
...
+                return existingWatcher;
+            });
+    }
+
+    /// <summary>
+    /// Releases a reference to a shared watcher, disposing it if this was the last reference.
+    /// </summary>
+    private void ReleaseSharedWatcher(SharedRootWatcher watcher)
+    {
+        if (watcher.Release())
```
Comment (dibarbet) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: not 100% sure - is it possible here that we release the watcher (dispose of it), but then another thread comes in and gets the disposed watcher in GetOrCreateSharedWatcher (before the original thread can remove it from sharedRootWatchers)?

naybe this should be re-ordered?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs [hunk 3]
```diff
@@ -2,135 +2,121 @@
...
+        => new FileChangeContext(this, watchedDirectories);
+
+    /// <summary>
+    /// Acquires a shared watcher for the given root path, creating one if necessary.
+    /// </summary>
+    private SharedRootWatcher GetOrCreateSharedWatcher(string rootPath)
+    {
+        return _sharedRootWatchers.AddOrUpdate(
+            rootPath,
+            new SharedRootWatcher(rootPath),
```
Comment (dibarbet) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: not sure on the semantics here - could SharedRootWatcher be created twice if two threads race here?  And the one that isn't added to the dictionary doesn't get disposed of?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+
+        private bool AcquireSharedWatcher(string? filePath)
+        {
+            var rootPath = Path.GetPathRoot(filePath);
+            if (string.IsNullOrEmpty(rootPath) || !Directory.Exists(rootPath))
+                return false;
+
+            var sharedWatcher = _owner.GetOrCreateSharedWatcher(rootPath);
+            sharedWatcher.FileChanged += RaiseEvent;
+            _sharedWatchers.TryAdd(rootPath, sharedWatcher);
```
Comment (dibarbet) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Could we end up subscribing the sharedWatcher.FiledChanged twice (does that matter).  e..g two threads come into this method, both get the same watcher (but only one tryAdd succeeds)?

**Review by dibarbet — COMMENTED** [review]
def @jasonmalinowski to take a look.  wonder if locks would actually be simpler here

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 4 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: yes, looks like a place we could double subscribe

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs (hunk 3 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: I should not be creating one here. I should be using the addFactory overload. But upon reading the remarks, I think I may just want to lock. Sigh
> [AddOrUpdate](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate?view=net-10.0) is not atomic with regards to all other operations on the [ConcurrentDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-10.0) class.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs [hunk 5]
```diff
@@ -2,135 +2,121 @@
...
 /// use the LSP one.
 /// </summary>
 /// <remarks>
-/// This implementation is not remotely efficient, but is available as a fallback implementation. If this needs to regularly be used, then this should get some improvements.
+/// This implementation creates one <see cref="FileSystemWatcher"/> per root drive and uses filtering to route file
+/// change events to the appropriate watchers. The watchers are shared between all <see cref="FileChangeContext"/>
+/// instances and are disposed when all contexts using them have been disposed.
 /// </remarks>
-internal sealed class SimpleFileChangeWatcher : IFileChangeWatcher
+internal sealed partial class SimpleFileChangeWatcher : IFileChangeWatcher
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]:
```suggestion
internal sealed partial class FileSystemWatcherFileChangeWatcher : IFileChangeWatcher
```

Or something. It's not really "simple" anymore.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs [hunk 6]
```diff
@@ -2,135 +2,121 @@
...
 {
+    private static readonly StringComparer s_stringComparer = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
+        ? StringComparer.OrdinalIgnoreCase
+        : StringComparer.Ordinal;
+    private static readonly StringComparison s_stringComparison = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
+        ? StringComparison.OrdinalIgnoreCase
+        : StringComparison.Ordinal;
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]:
```suggestion
    private static readonly StringComparer s_pathStringComparer = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
        ? StringComparer.OrdinalIgnoreCase
        : StringComparer.Ordinal;
    private static readonly StringComparison s_pathStringComparison = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
        ? StringComparison.OrdinalIgnoreCase
        : StringComparison.Ordinal;
```

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs [hunk 7]
```diff
@@ -2,135 +2,121 @@
...
+    /// <summary>
+    /// A shared <see cref="FileSystemWatcher"/> that can be used by multiple <see cref="FileChangeContext"/> instances.
+    /// Uses reference counting to track how many contexts are using it. Does not use extension filters so it can be
+    /// shared across contexts with different filters.
+    /// </summary>
+    private sealed class SharedRootWatcher
     {
-        private readonly ImmutableArray<WatchedDirectory> _watchedDirectories;
+        private readonly FileSystemWatcher _watcher;
+        private int _refCount = 1;
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: FYI we have ReferenceCountedDisposable as a helper which might be useful here.

Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: And also a ReferenceCountedDisposableCache that uses it.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: Use ReferenceCountedDisposableCache.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.FileChangeContext.cs [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+            _sharedWatchers.TryAdd(rootPath, sharedWatcher);
+            return true;
+        }
+
+        private void RaiseEvent(object? sender, FileSystemEventArgs e)
+        {
+            // If the changed file is not covered by our watched directories or individual files, ignore it
+            if ((_watchedDirectories.IsEmpty || !WatchedDirectory.FilePathCoveredByWatchedDirectories(_watchedDirectories, e.FullPath, s_stringComparison))
+                 && !_individualWatchedFiles.ContainsKey(e.FullPath))
+                return;
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.FileChangeContext.cs]: Inverting the condition seems like this will be easier to understand. I'm also not sure of the significance of the _watcherDirectories.IsEmpty check, since looking at this portion:

> _watchedDirectories.IsEmpty || !WatchedDirectory.FilePathCoveredByWatchedDirectories(_watchedDirectories, e.FullPath, s_stringComparison

If _watchedDirectories is empty, then FilePathCoveredByWatchedDirectories will always return false, so the expression will be true. And that'll still be plenty fast to determine.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.FileChangeContext.cs [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+            // Try to acquire a root watcher that covers this file
+            AcquireSharedWatcher(filePath);
+
+            return new IndividualWatchedFile(filePath, this);
+        }
+
+        private void StopWatchingFile(string filePath)
+        {
+            if (_individualWatchedFiles.AddOrUpdate(filePath, 0, (_, count) => count - 1) == 0)
+                _individualWatchedFiles.TryRemove(filePath, out _);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.FileChangeContext.cs]: This unfortunately is a race since the count could have moved back from zero to one between the AddOrUpdate and the TryRemove.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 10]
```diff
@@ -0,0 +1,771 @@
...
+
+using Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.FileWatching;
+using Microsoft.CodeAnalysis.ProjectSystem;
+using Microsoft.CodeAnalysis.Test.Utilities;
+
+namespace Microsoft.CodeAnalysis.LanguageServer.UnitTests;
+
+public sealed class SimpleFileChangeWatcherTests : IDisposable
+{
+    private const int FileChangeTimeout = 10;
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]: Use a TimeSpan since otherwise this is 10...what?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 11]
```diff
@@ -0,0 +1,771 @@
...
+
+    [Fact]
+    public void CreateContext_WithExistingDirectory_AddsRootWatcher()
+    {
+        var tempDirectory = _tempRoot.CreateDirectory();
+        var watcher = new SimpleFileChangeWatcher();
+
+        using var context = watcher.CreateContext([new WatchedDirectory(tempDirectory.Path, extensionFilters: [])]);
+
+        Assert.Equal(1, SimpleFileChangeWatcher.FileChangeContext.TestAccessor.GetSharedWatcherCount((SimpleFileChangeWatcher.FileChangeContext)context));
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]: Rather than the test accessor return the count of watchers, have it return the list of roots. The assert can become Assert.Single(), which might be nicer to debug if for some reason two got created for some reason...

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 12]
```diff
@@ -0,0 +1,771 @@
...
+    }
+
+    [Fact]
+    public void CreateContext_WithNonExistentDirectory_DoesNotAddRootWatcher()
+    {
+        var nonExistentPath = Path.Combine(TempRoot.Root, "NonExistent", "Directory");
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]:
```suggestion
        var nonExistentPath = Path.Combine(TempRoot.Root, "NonExistent", "Directory", Guid.NewGuid().ToString());
```

Lest that folder get created by some other test by accident.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 13]
```diff
@@ -0,0 +1,771 @@
...
+        var otherDir = _tempRoot.CreateDirectory();
+        var filePath = Path.Combine(otherDir.Path, "test.cs");
+        var watcher = new SimpleFileChangeWatcher();
+
+        using var context = watcher.CreateContext([new WatchedDirectory(watchedDir.Path, extensionFilters: [])]);
+        var watchedFile = context.EnqueueWatchingFile(filePath);
+
+        // When a file is not covered, it returns an actual watcher
+        Assert.NotSame(NoOpWatchedFile.Instance, watchedFile);
+        watchedFile.Dispose();
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]: Consider a using rather than this.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs [hunk 14]
```diff
@@ -0,0 +1,771 @@
...
+        var watcher = new SimpleFileChangeWatcher();
+
+        using var context = watcher.CreateContext([]);
+
+        var watcher1 = context.EnqueueWatchingFile(filePath);
+        var watcher2 = context.EnqueueWatchingFile(filePath);
+
+        // Both should be valid individual watchers
+        Assert.NotSame(NoOpWatchedFile.Instance, watcher1);
+        Assert.NotSame(NoOpWatchedFile.Instance, watcher2);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs:138]: Also assert watcher1 and watcher2 are different.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 15]
```diff
@@ -0,0 +1,771 @@
...
+        File.WriteAllText(filePath, "initial content");
+
+        using var context = watcher.CreateContext([new WatchedDirectory(tempDirectory.Path, extensionFilters: [])]);
+
+        var eventSource = new TaskCompletionSource();
+        context.FileChanged += (sender, path) =>
+        {
+            if (path == filePath)
+                eventSource.TrySetResult();
+        };
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]: Consider adding a smaller helper for this. You could also just have it directly return the Task of the TaskCompletionSource because that's all you really need from it.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs [hunk 16]
```diff
@@ -0,0 +1,771 @@
...
+        {
+            if (path == txtFilePath)
+                eventFired |= true;
+        };
+
+        // Create a .txt file (should not match filter)
+        File.WriteAllText(txtFilePath, "content");
+
+        // Wait a bit to ensure no event fires
+        await Task.Delay(TimeSpan.FromSeconds(1));
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs]: Why not use the same timeout you're using for the other tests? It would seem if we feel 10 seconds is needed to be safe for the other tests, shouldn't we be waiting 10 seconds here?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs [hunk 17]
```diff
@@ -0,0 +1,771 @@
...
+
+        File.WriteAllText(file1, "content1");
+        await Task.Delay(100); // Small delay between operations
+        File.WriteAllText(file2, "content2");
+        await Task.Delay(100);
+        File.WriteAllText(file3, "content3");
+
+        // Wait for all events
+        var completed = await Task.WhenAny(allEventsReceived.Task, Task.Delay(TimeSpan.FromSeconds(15)));
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/SimpleFileChangeWatcherTests.cs]: Why 15 here? Or why not use your other helper?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs]: “Default” prefix might be suitable

**Comment by JoeRobich** [comment]
@dibarbet @jasonmalinowski this is ready for another look

**Review by dibarbet — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs [hunk 18]
```diff
@@ -72,4 +82,10 @@ public void Dispose()
             Value.Dispose();
         }
     }
+
+    internal static class TestAccessor
+    {
+        public static IEnumerable<TKey> GetCacheKeys(ReferenceCountedDisposableCache<TKey, TValue> cache)
+            => cache._cache.Keys;
```
Comment (jasonmalinowski) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs]: This needs to take a lock and make a copy of the keys, since otherwise there's a risk this could get mutated asynchronously. The lazy enumeration of the keys too might also break if there was an explicit mutation as well.

File: src/Compilers/Test/Core/TempFiles/TempRoot.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Compilers/Test/Core/TempFiles/TempRoot.cs:24]: Can you add this comment into the code?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.cs [hunk 19]
```diff
@@ -0,0 +1,52 @@
...
+
+    private IReferenceCountedDisposable<ICacheEntry<string, FileSystemWatcher>> GetOrCreateSharedWatcher(string rootPath)
+    {
+        return _sharedRootWatchers.GetOrCreate<object?>(
+            rootPath,
+            static (key, _) => new FileSystemWatcher(key)
+            {
+                IncludeSubdirectories = true,
+                EnableRaisingEvents = true,
+            },
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.cs]: One other use of ReferenceCountedDisposableCache that was using file watchers had a comment that this isn't ideal, since the creation of the file watcher is happening under the lock which might cause slight performance issues since there's I/O implicitly in the creation of this watcher. I don't imagine that'll be much of a problem though, since:

1. Unlike the other case, this isn't happening on a UI thread.
2. We're only explicitly creating a single directory watch (unless that's expensive on Linux/macOS because of the behavior around nested directories?)

It might be worth once we've got this merged to look at a perf trace of this, but for now this is fine.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 20]
```diff
@@ -0,0 +1,136 @@
...
+    /// <remarks>
+    /// Each context tracks which root watchers it has acquired, subscribing to their events
+    /// and unsubscribing when disposed. It also tracks individual files being watched outside
+    /// of directory watches.
+    /// </remarks>
+    internal sealed class FileChangeContext : IFileChangeContext
+    {
+        private readonly DefaultFileChangeWatcher _owner;
+        private readonly ImmutableArray<WatchedDirectory> _watchedDirectories;
+        private readonly ConcurrentDictionary<string, IReferenceCountedDisposable<ICacheEntry<string, FileSystemWatcher>>> _sharedWatchers = new(s_pathStringComparer);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: This should really have a comment for what this key is.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 4 above)
Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: It looks like this would still be unresolved? Because if we are watching two paths that both map to the same root, will we subscribe twice and then raise events twice?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 21]
```diff
@@ -0,0 +1,136 @@
...
+            var rootPath = Path.GetPathRoot(filePath);
+            if (string.IsNullOrEmpty(rootPath) || !Directory.Exists(rootPath))
+                return false;
+
+            var sharedWatcher = _owner.GetOrCreateSharedWatcher(rootPath);
+            sharedWatcher.Target.Value.Changed += RaiseEvent;
+            sharedWatcher.Target.Value.Created += RaiseEvent;
+            sharedWatcher.Target.Value.Deleted += RaiseEvent;
+            sharedWatcher.Target.Value.Renamed += RaiseEvent;
+            _sharedWatchers.TryAdd(rootPath, sharedWatcher);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: It seems very odd to me this is a TryAdd: if that fails, then what is rooting the sharedWatcher we got here? Once that finalizes, won't we end up decrementing the reference count even though we still expected to use it?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 22]
```diff
@@ -0,0 +1,136 @@
...
+                sharedWatcher.Dispose();
+            }
+
+            _sharedWatchers.Clear();
+            _individualWatchedFiles.Clear();
+        }
+
+        private sealed class IndividualWatchedFile(string filePath, FileChangeContext context) : IWatchedFile
+        {
+            public void Dispose() => context.StopWatchingFile(filePath);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: This is not safe in the case of a double dispose.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 23]
```diff
@@ -0,0 +1,136 @@
...
+
+        public IWatchedFile EnqueueWatchingFile(string filePath)
+        {
+            // If this path is already covered by one of our directory watchers, nothing further to do
+            if (WatchedDirectory.FilePathCoveredByWatchedDirectories(_watchedDirectories, filePath, s_pathStringComparison))
+                return NoOpWatchedFile.Instance;
+
+            // Individual files are ref counted so we know when to stop watching them
+            lock (_individualWatchedFiles)
+                _individualWatchedFiles.AddOrUpdate(filePath, 1, (_, count) => count + 1);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: This comment seems out of date -- we're not actually stopping any watching if we hit this point. It's removing it from the map so we don't raise it if the shared watcher sees that file changed. Does the comment need updating?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 24]
```diff
@@ -0,0 +1,136 @@
...
+
+            // Try to acquire a root watcher that covers this file
+            AcquireSharedWatcher(filePath);
+
+            return new IndividualWatchedFile(filePath, this);
+        }
+
+        private void StopWatchingFile(string filePath)
+        {
+            lock (_individualWatchedFiles)
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: It's quite strange here seeing a lock on a ConcurrentDictionary. I guess we still need the concurrency for the ContainsKey() check, but if that's the pattern we should have a lot of commenting here.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 25]
```diff
@@ -0,0 +1,136 @@
...
+                sharedWatcher.Target.Value.Deleted -= RaiseEvent;
+                sharedWatcher.Target.Value.Renamed -= RaiseEvent;
+                sharedWatcher.Dispose();
+            }
+
+            _sharedWatchers.Clear();
+            _individualWatchedFiles.Clear();
+        }
+
+        private sealed class IndividualWatchedFile(string filePath, FileChangeContext context) : IWatchedFile
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Is it easier if IndividualWatchedFile just always acquires a ReferenceCountedDisposable() and then subscribes with a separate handler for just that individual file name? It seems like it'll make it a lot easier to reason about the lifetime semantics, and I think it'd make the _individualWatchedFiles map go away entirely.

It's a little but suboptimal in that we have a lot of subscriptions on the delegate, or some contention on the lock in the ReferenceCountedDisposableCache, but the implementation should be easy I'd think?

**Review by jasonmalinowski — COMMENTED** [review]
Another round; still some concerns in the implementation of FileChangeContext but I'm liking where this is heading.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs (hunk 18 above)
Comment (JoeRobich) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs]: Looks like ConcurrentDictionary is locking and returning a ReadOnlyCollection of Keys - https://github.com/dotnet/runtime/blob/ffb8db274bb2fbfcddc97a62a37bed80f619c2ca/src/libraries/System.Private.CoreLib/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2124

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 4 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Let me change it to an AddOrUpdate where the update simply returns the existing watcher

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 21 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Changing to AddOrUpdate to avoid getting the watcher twice

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 20 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Will add and also rename this to something like `_rootFileSystemWatchers`

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 24 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Removed in latest

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 23 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Removed in latest

File: src/Compilers/Test/Core/TempFiles/TempRoot.cs [hunk 26]
```diff
@@ -19,7 +19,35 @@ public sealed class TempRoot : IDisposable
...
+            // When running on MacOS, `Path.GetTempPath()` will return "/var/folders/..." which is a symlink to "/private/var/folders/...". This
+            // can cause issues when watching files under the temp directory, as the FileSystemWatcher will report changes using the real path.
+            // So, we need to adjust this path by walking up the temp path until we find a directory that is a link and resolve it.
+
+            if (tempDirectory.LinkTarget != null)
+            {
+                tempDirectory = (DirectoryInfo)Directory.ResolveLinkTarget(tempDirectory.FullName, true);
```
Comment (jasonmalinowski) [inline src/Compilers/Test/Core/TempFiles/TempRoot.cs]:
```suggestion
                tempDirectory = (DirectoryInfo)Directory.ResolveLinkTarget(tempDirectory.FullName, returnFinalTarget: true);
```

File: src/Compilers/Test/Core/TempFiles/TempRoot.cs [hunk 27]
```diff
@@ -19,7 +19,35 @@ public sealed class TempRoot : IDisposable
...
+                var parentDirectory = tempDirectory.Parent;
+                while (parentDirectory != null && parentDirectory.LinkTarget == null)
+                {
+                    parentDirectory = parentDirectory.Parent;
+                }
+
+                if (parentDirectory != null)
+                {
+                    var relativePath = Path.GetRelativePath(parentDirectory.FullName, tempDirectory.FullName);
+                    var realPath = Directory.ResolveLinkTarget(parentDirectory.FullName, true).FullName;
```
Comment (jasonmalinowski) [inline src/Compilers/Test/Core/TempFiles/TempRoot.cs]:
```suggestion
                    var realPath = Directory.ResolveLinkTarget(parentDirectory.FullName, returnFinalTarget: true).FullName;
```

File: src/Compilers/Test/Core/TempFiles/TempRoot.cs [hunk 28]
```diff
@@ -19,7 +19,35 @@ public sealed class TempRoot : IDisposable
...
         {
-            Root = Path.Combine(Path.GetTempPath(), "RoslynTests");
+            var tempDirectory = new DirectoryInfo(Path.GetTempPath());
+
+#if NET
+            // When running on MacOS, `Path.GetTempPath()` will return "/var/folders/..." which is a symlink to "/private/var/folders/...". This
+            // can cause issues when watching files under the temp directory, as the FileSystemWatcher will report changes using the real path.
+            // So, we need to adjust this path by walking up the temp path until we find a directory that is a link and resolve it.
+
+            if (tempDirectory.LinkTarget != null)
```
Comment (jasonmalinowski) [inline src/Compilers/Test/Core/TempFiles/TempRoot.cs:29]: It's unfortunate there's not an API we can just call that does this for us.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs (hunk 16 above)
Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs]: Unresolved?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs [hunk 29]
```diff
@@ -0,0 +1,697 @@
...
+        context.FileChanged += (sender, path) =>
+        {
+            lock (changedFiles)
+            {
+                changedFiles.Add(path);
+                // Check if we've seen all 3 files (regardless of how many events each generated)
+                if (changedFiles.Contains(file1) && changedFiles.Contains(file2) && changedFiles.Contains(file3))
+                    allEventsReceived.TrySetResult(true);
+            }
+        };
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs]: Any reason this isn't just using our other helpers to call ListenForFileChangeAsync three times and then wait for all three tasks?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs (hunk 18 above)
Comment (jasonmalinowski) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs]: Oh right this was a ConcurrentDictionary under the covers, my bad.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 30]
```diff
@@ -0,0 +1,163 @@
...
+            var watchedDirectoryBuilder = ImmutableArray.CreateBuilder<WatchedDirectory>(watchedDirectories.Length);
+            foreach (var watchedDirectory in watchedDirectories)
+            {
+                if (!Directory.Exists(watchedDirectory.Path))
+                    continue;
+
+                watchedDirectoryBuilder.Add(watchedDirectory);
+
+                var rootPath = Path.GetPathRoot(watchedDirectory.Path);
+                if (string.IsNullOrEmpty(rootPath) || !Directory.Exists(rootPath))
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: That !Directory.Exists() check here seems odd, since we already verified the directory itself existed. Ditto for GetPathRoot, unless that's a problem for files at the root to start?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 31]
```diff
@@ -0,0 +1,163 @@
...
+                var rootWatcher = _owner.GetOrCreateSharedWatcher(rootPath);
+                rootWatcher.Target.Value.Changed += RaiseEvent;
+                rootWatcher.Target.Value.Created += RaiseEvent;
+                rootWatcher.Target.Value.Deleted += RaiseEvent;
+                rootWatcher.Target.Value.Renamed += RaiseEvent;
+                rootFileSystemWatchersBuilder.Add(rootWatcher);
+            }
+
+            _watchedDirectories = watchedDirectoryBuilder.ToImmutable();
+            _rootFileSystemWatchers = rootFileSystemWatchersBuilder.ToImmutable();
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]:
```suggestion
            _fileSystemWatchersForWatchedDirectories = fileSystemWatchersForWatchedDirectoriesBuilder.ToImmutable();
```

To make the connection bit clearer.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 32]
```diff
@@ -0,0 +1,163 @@
...
+            }
+
+            private void RaiseEvent(object? sender, FileSystemEventArgs e)
+            {
+                if (e.FullPath.Equals(_filePath, s_pathStringComparison))
+                {
+                    _context.FileChanged?.Invoke(this, e.FullPath);
+                }
+                // On Windows we only get a renamed event instead of separate delete/create events, so check
+                // whether the old file path matches.
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Nit: put this inside an else block so that comment doesn't look like it's split up the if conditions entirely.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs [hunk 33]
```diff
@@ -0,0 +1,163 @@
...
+
+            public void Dispose()
+            {
+                if (Interlocked.Exchange(ref _disposed, true) == false)
+                {
+                    _watcher.Target.Value.Changed -= RaiseEvent;
+                    _watcher.Target.Value.Created -= RaiseEvent;
+                    _watcher.Target.Value.Deleted -= RaiseEvent;
+                    _watcher.Target.Value.Renamed -= RaiseEvent;
+                    _watcher.Dispose();
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Consider having a "dispose watcher" helper here and for earlier.

**Review by jasonmalinowski — APPROVED** [review]
Looks good; a few nits here or there but I think this is functionally correct; there's some perf issues (especially given we're having to go to the root) but "slow" is generally better than "crashes", so that's a win.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 30 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: Thanks, I had removed this in the iteration where I made the shared watcher static and forgot to remove it again when I reset the branch.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs (hunk 18 above)
Comment (JoeRobich) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposableCache.cs]: ahhh, whoops. I was wrong. Thinking about wrong TestAccessor, wrong cache. Will add locking and enumerate the keys.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs (hunk 33 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DefaultFileChangeWatcher.FileChangeContext.cs]: jumped through a couple hoops but added helpers for attaching to and disposing the watchers

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs (hunk 16 above)
Comment (JoeRobich) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/DefaultFileChangeWatcherTests.cs]: I fixed up the same code around line 480 and didn't realize there were multiple instances of this.
