### PR TITLE
Make C# and VB CommandLineParser.Script public

### LINKED ISSUE #23402: Make CSharpCommandLineParser.ScriptRunner public
**Version Used**: 
2.4.0

**Steps to Reproduce**:

1. Go to `CSharpCommandLineParser` type

**Expected Behavior**:

`CSharpCommandLineParser.ScriptRunner` is public.

**Actual Behavior**:

`CSharpCommandLineParser.ScriptRunner` is internal. Only `CSharpCommandLineParser.Default` is public.

<hr>

We'd like to use `CSharpCommandLineParser.ScriptRunner` in OmniSharp to support user-defined `.rsp` files for CSX code editing. Since the default C# parser is available, the CSX parser should be available too - especially as there is quite a behavior difference between them. At the moment the workaround is to use reflection to access `CSharpCommandLineParser.ScriptRunner`.

cc @tmat

### PR DESCRIPTION
**Pull request by DustinCampbell**
This change makes our existing internal API for parsing script command-line arguments public for the community to use with custom script runners. In addition, the API has been renamed from `ScriptRunner` to `Script`, since it should be clear to consumers since the API is prefixed by the CommandLineParser class (i.e. `CSharpCommandLineParser.Script` or `VisualBasicCommandLineParser.Script`).

### Customer scenario

A customer is building a custom C# or VB script runner or analyzing C# or VB script code and needs to parse command-line arguments. The OmniSharp community wishes to use this API to parse an `.rsp` file and create a script compilation with the correct options set.

### Bugs this fixes

Fixes #23402

### Workarounds, if any

Duplicate our command-line parsing code or access internal APIs via reflection.

### Risk

Low. This takes an existing internal API, renames it, and makes it public. The change will likely break any customers who were previously accessing this API via reflection.

In addition, note that the API for parsing command-line arguments for `csc.exe` is already public, and this ensures that the API for parsing `csi.exe` arguments is is also public. 

### Performance impact

None

### Is this a regression from a previous update?

No

### How was the bug found?

Customer requested.

### CODE REVIEW

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs [hunk 1]
```diff
@@ -2,30 +2,29 @@
...
 using Roslyn.Utilities;
-using System.Collections.Immutable;
 
 namespace Microsoft.CodeAnalysis
 {
     public abstract class CommandLineParser
     {
         private readonly CommonMessageProvider _messageProvider;
-        internal readonly bool IsScriptRunner;
+        internal readonly bool IsScript;
```
Comment (tmat) [inline src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: I thought you're only gonna rename the property. "IsScript" sounds weird in this context. The parser isn't a script.

Comment (DustinCampbell) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: True, though `IsScriptRunner` was already weird by that logic. The parser isn't a script runner. :smile:

I changed it because I wanted to keep the names consistent. Having the command-line parsers pass along `isScriptRunner: true` as an argument for `Script` seems pretty inconsistent to me. After all, this is about parsing a command-line for "script". Also, I think this reads much better now:

```C#
IsScript ? SourceCodeKind.Script : SourceCodeKind.Regular
```

I'm OK with changing it to something else. Do you have any suggestions? Maybe go with something generic like `InScriptParsingMode`?

Comment (tmat) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: ```IsScriptRunnerCommandLineParser``` was a little bit too long :) 
```IsScriptRunnerMode``` ?

Comment (DustinCampbell) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: You really like this "Runner" notion, huh? :smile: I'll comply but I do feel this makes things arbitrarily inconsistent. Is "Runner" used elsewhere in the code base to strengthen that terminology?

I'll make the change tomorrow when I'm back in the office.

@Pilchie, is this approved for ask mode?

Comment (DustinCampbell) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: FWIW, I'm going to go ahead and use `IsScriptCommandLineParser`. 😀

**Comment by Pilchie** [comment]
Approved pending coming to an agreement on the name.

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs (hunk 1 above)
Comment (tmat) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: Sounds good.

**Comment by tmat** [comment]
👍

**Comment by DustinCampbell** [comment]
> Approved pending coming to an agreement on the name.

Thanks! Note that the discussion isn't about the API name itself.
