### PR TITLE
Out arguments do not contribute val escape

### LINKED ISSUE #56587: Unexpected ref safety errors when a discard is used as an `out` argument
**Note after discussion this issue is meant to be tracking the discard case only**

```
using System;

partial class Test
{
    static void Main(){}
    
    void Test1()
    {
        Span<int> a = stackalloc int[10];
        Span<int> b;
        M(ref a, out b);
    }

    void M(ref Span<int> s, out Span<int> s1) => s1 = s;
}
```

Observed:
```
error CS8352: Cannot use local 'a' in this context because it may expose referenced variables outside of their declaration scope
error CS8350: This combination of arguments to 'Test.M(ref Span<int>, out Span<int>)' is disallowed because it may expose variables referenced by parameter 's' outside of their declaration scope
```

Expected: No errors.

The same behavior is around `out` discard:
```
        Span<int> a = stackalloc int[10];
        M(ref a, out _);
``` 

Note that, when local is initialized with stackalloc the errors go away:
```
        Span<int> a = stackalloc int[10];
        Span<int> b = stackalloc int[10];
        M(ref a, out b);
``` 
but there are errors in this case:
```
        Span<int> a = stackalloc int[10];
        Span<int> c = new int[10];
        M(ref a, out c);
```

### LINKED ISSUE #64783: Out argument val escape should not contribute to invocation escape analysis
https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTBlADhGAHmAE8AXAUwD4ACAWRQAoBKGgb0xq5rwOPOo0INALw0AzmQgBjANYQANgoD20mqUoBtACxIAugG5O3AG4QATjXMUyomgHkYFewFcyvGACUbL8zHEejMpuQsxGGNw0CADsVjbhAL6YOPhEGoJ0SCzsxlwe/JS0wmKSMvJKquoCOvrhkQAqAO7Kru6p4kEhEAA0NMG2+em0wGG5UbHAickYgwK0js5uHt5kvv6B/TypBYIQzJgcEdwA9Mc0AOQxQuc0UOK3ShQA5oo0LjBkUAq3tnd9JhRzI1zFAyJQYGNijQACYUABmEBcCjIdW4V1hCKRKMwSSwGAQ2hoTRaS3anQG2yGQl6m1mhXU+wwh0ipwuUOANwI0IuwDsEE51geCmer3en2+yicNAAFhB7oprBBoSR1BQKDAaMDQeDIXZeWIMYjkVMMEA==

```cs
using System;

Span<byte> M1() {
    Span<byte> a = stackalloc byte[42];
    var ret = OneOutSpanReturnsSpan(out a);
    return ret; // unexpected error is reported
}

Span<byte> M2() {
    Span<byte> a = stackalloc byte[42];
    TwoOutSpans(out a, out Span<byte> b);
    return b; // unexpected error is reported
}

Span<byte> OneOutSpanReturnsSpan(out Span<byte> a)
{
    // 'return a' is illegal until it is overwritten
    a = default;
    return default;
}

void TwoOutSpans(out Span<byte> a, out Span<byte> b)
{
    // 'a = b' and 'b = a' are illegal until one has already been written
    a = b = default;
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #64783
Closes #56587

Although out arguments never contribute their val escape, arguments for `[UnscopedRef] out` parameters can contribute their ref escape. See test LocalScope_DeclarationExpression_07.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -2427,9 +2432,9 @@ void inferDeclarationExpressionValEscape()
                         : GetValEscape(fromArg, scopeOfTheContainingExpression));
                 }
 
-                foreach (var (_, fromArg, _, _) in escapeValues)
+                foreach (var argument in argsOpt)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2435]: Since out arguments are usually not included in `escapeValues`, we needed to change to check `argsOpt` instead. Note that `escapeValues` was probably never the right collection to enumerate, since the same argument can be present multiple times, it just happened to work coincidentally until now.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2430]: Also, although it doesn't look like 'argsOpt' is default-checked on this code path, I actually think that the argument is never default. I'll send a separate PR after this one to add an assertion and rename the parameter.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for review

**Review by jaredpar — APPROVED** [review]

**Review by cston — APPROVED** [review]
