### PR TITLE
Fix an InvalidCastException in simplifier.

### LINKED ISSUE #2232: InvalidCastException from simplifier for erroneous code
Repro: 
1. Type this code in a C# app - "Blah x = new System.Int32.BlahBlah;"
2. Ctrl + . to bring up light bulb
3. The first fix causes a crash the moment its selected
repro

Actual: Below crash
Expected: The error case should be handled gracefully. The above simplification from System.Int32 -> int should probably not be offered in the above case.

Exception Stack Trace: "Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.PredefinedTypeSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.NameSyntax'."

```
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitQualifiedName(Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax node) Line 68619 C#
  Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitQualifiedName(Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax node) Line 66 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 47095 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitObjectCreationExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax node) Line 68954 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 51033 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitEqualsValueClause(Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax node) Line 69186 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 53698 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitVariableDeclarator(Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax node) Line 69179 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 53613 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement<Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax>(Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax node) Line 144 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList<Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax>(Microsoft.CodeAnalysis.SeparatedSyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax> list) Line 197 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitVariableDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax node) Line 69171 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 53522 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitLocalDeclarationStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax node) Line 69163 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept<Microsoft.CodeAnalysis.SyntaxNode>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode> visitor) Line 53423 C#
  Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 23 C#
  Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractExpressionRewriter.VisitNodeOrToken(Microsoft.CodeAnalysis.SyntaxNodeOrToken nodeOrToken, Microsoft.CodeAnalysis.SemanticModel semanticModel, bool simplifyAllDescendants) Line 176 C#
  Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService<Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.CrefSyntax>.ReduceAsync.AnonymousMethod__0() Line 236 C#
  mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 680 C#
  mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861 C#
  mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954 C#
  mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767 C#
  mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704 C#
  mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820 C#
  mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161 C#
```

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
Fixes #2232

Prevent crash by avoiding QualifiedName->PredefinedTypeName simplification inside QualifiedNames.

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@srivatsn @mavasani @jmarolf @tmeschter @heejaechang Could you take a look please? Should be quick to review.

**Comment by mavasani** [comment]
:+1:

File: src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -1331,8 +1331,12 @@ private static int GetNamespaceId(SyntaxList<MemberDeclarationSyntax> members, N
                             return true;
                         }
 
-                        if (PreferPredefinedTypeKeywordInDeclarations(name, optionSet, semanticModel) ||
-                            PreferPredefinedTypeKeywordInMemberAccess(name, optionSet, semanticModel))
+                        // Don't simplify to predefined type if name is part of a QualifiedName.
+                        // QualifiedNames can't contain PredefinedTypeNames (although MemberAccessExpressions can).
+                        // In other words, the left side of a QualifiedName can't be a PredefinedTypeName.
+                        if (!name.Parent.IsKind(SyntaxKind.QualifiedName) &&
```
Comment (heejaechang) [inline src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: do we still need IsKind? with ?. , IsKind might not needed anymore ?

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb [hunk 2]
```diff
@@ -1288,7 +1288,11 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
                     End If
 
                     Dim aliasInfo = semanticModel.GetAliasInfo(name, cancellationToken)
-                    If nameHasNoAlias AndAlso aliasInfo Is Nothing Then
+
+                    ' Don't simplify to predefined type if name is part of a QualifiedName.
+                    ' QualifiedNames can't contain PredefinedTypeNames (although MemberAccessExpressions can).
+                    ' In other words, the left side of a QualifiedName can't be a PredefinedTypeName.
+                    If nameHasNoAlias AndAlso aliasInfo Is Nothing AndAlso Not name.Parent.IsKind(SyntaxKind.QualifiedName) Then
```
Comment (heejaechang) [inline src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: can we reduce number of "If", it has like 4 if and not sure what if affects what.

**Comment by heejaechang** [comment]
:+1:

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb (hunk 2 above)
Comment (shyamnamboodiripad) [inline src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: I won't fix this now since I did not introduce the extra 'if's :) But I agree this code could be better and we should clean it up in the future.
