### PR TITLE
Gate the construction of the singleton RemoteWorkspace

### LINKED ISSUE #22302: SqlConnection.Finalize can cause crashes
**Version Used**: Builds as new as 15.0.26730.15

:link: Internal issue: [DevDiv 490079](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/490079)

**Steps to Reproduce**:

Unknown

**Expected Behavior**:

`SqlConnection` instances are not finalized.

**Actual Behavior**:

`SqlConnection.Finalize()` is getting called on an unknown code path, resulting in a crash.

:memo: This was supposed to be corrected by #20806, but it's still showing up.

### PR DESCRIPTION
**Pull request by sharwell**
`Workspace.Dispose()` doesn't dispose of all the workspace and language services it provides. For items that export `IWorkspaceService` or `ILanguageService` directly, this isn't a problem because those instances are serviced by the underlying MEF catalog and it will dispose of items. However, for items provided by `IWorkspaceServiceFactory`, only the factory is tracked by the underlying MEF catalog and the factory-created instances are part of each workspace. For unit tests, we're good about making sure both the workspace and the MEF catalog are disposed. However, for integration tests things are a bit more relaxed. In **devenv.exe**, we only have one Workspace and one MEF catalog and neither get disposed until VS is shutting down. For the OOP process, however, we have some paths by which more than one `RemoteWorkspace` can get created, and these are not disposed. If more than one `RemoteWorkspace` instance gets created, one of them will be discarded, which can lead to finalization of `SqlConnection` if the discarded workspace performed any database operations. This is an attempt to fix the issue by putting a lock around the `new RemoteWorkspace()` call in `SolutionService.PrimaryWorkspace`.

In addition, two cases in test code where `IPersistentStorage` was not disposed have been corrected.

Fixes #22302

### CODE REVIEW

File: src/Workspaces/Remote/Core/Services/SolutionService.cs [hunk 1]
```diff
@@ -41,10 +46,16 @@ public static RemoteWorkspace PrimaryWorkspace
                 var primaryWorkspace = exportProvider.GetExports<PrimaryWorkspace>().Single().Value;
                 if (primaryWorkspace.Workspace == null)
                 {
-                    // The Roslyn OOP service assumes a singleton workspace exists, but doesn't initialize it anywhere.
-                    // If we get here, code is asking for a workspace before it exists, so we create one on the fly.
-                    // The RemoteWorkspace constructor assigns itself as the new singleton instance.
-                    _ = new RemoteWorkspace();
+                    lock (s_remoteWorkspaceGate)
+                    {
+                        if (primaryWorkspace.Workspace is null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Remote/Core/Services/SolutionService.cs:51]: we used == above, and `is` here :'(

Comment (jaredpar) [reply src/Workspaces/Remote/Core/Services/SolutionService.cs:51]: `is null` FTW 😄

**Comment by CyrusNajmabadi** [comment]
So now i'm sad.  Because this does indicate that the Finalizer was working (in that it notified us that someone was doing something bad)...
