### PR TITLE
Fix handling of SymbolDisplayCompilerInternalOptions.UseArityForGenericTypes option for non-native symbol implementations

### LINKED ISSUE #80165: InvalidCastException in VB SymbolDisplay when using UseArityForGenericTypes option
If you add the following unittest to `SymbolDisplayTests`, you get a cast exception.

```
    System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol'.

  Stack Trace: 
    SymbolDisplayVisitor.AddNameAndTypeArgumentsOrParameters(INamedTypeSymbol symbol, Boolean noEscaping) line 281
```
```vb
        <Theory, CombinatorialData>
        Public Sub UseArityForGenericTypes_CSharpSymbol(useMetadata As Boolean)
            Dim text =
<text>
    <![CDATA[
class C<T>
{
}
    ]]>
</text>.Value

            Dim format = SymbolDisplayFormat.VisualBasicErrorMessageFormat.
                WithCompilerInternalOptions(SymbolDisplayCompilerInternalOptions.UseArityForGenericTypes)

            Dim parseOptions = CSharp.CSharpParseOptions.Default.WithLanguageVersion(CSharp.LanguageVersion.Preview)
            Dim comp As Compilation
            If useMetadata Then
                Dim libComp = CreateCSharpCompilation("c", text, parseOptions:=parseOptions)
                comp = CreateCSharpCompilation("d", code:="", parseOptions:=parseOptions, referencedAssemblies:=libComp.References.Concat(libComp.EmitToImageReference()))
            Else
                comp = CreateCSharpCompilation("c", text, parseOptions:=parseOptions)
            End If

            Dim c = DirectCast(comp.GlobalNamespace.GetMembers("C").Single(), ITypeSymbol)

            ' Tracked by : 
            AssertEx.Equal("C", SymbolDisplay.ToDisplayString(c, format))
        End Sub
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #80165

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler Please review

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 1]
```diff
@@ -9157,6 +9157,83 @@ public void PreprocessingSymbol()
...
+                comp = CreateVisualBasicCompilation("c", text);
+            }
+
+            AssertEx.Equal("A", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("A"), format));
+            AssertEx.Equal("A.B`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("A+B`1"), format));
+            AssertEx.Equal("C`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1"), format));
+            AssertEx.Equal("C`1.D`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1+D`1"), format));
+            AssertEx.Equal("C`1.E", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1+E"), format));
+        }
+
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]:
```suggestion

```

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 2]
```diff
@@ -9157,6 +9157,82 @@ public void PreprocessingSymbol()
...
+            {
+                comp = CreateVisualBasicCompilation("c", text);
+            }
+
+            AssertEx.Equal("A", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("A"), format));
+            AssertEx.Equal("A.B`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("A+B`1"), format));
+            AssertEx.Equal("C`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1"), format));
+            AssertEx.Equal("C`1.D`1", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1+D`1"), format));
+            AssertEx.Equal("C`1.E", SymbolDisplay.ToDisplayString(comp.GetTypeByMetadataName("C`1+E"), format));
+        }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:9235]:
```suggestion
        }

```
