### PR TITLE
Fix VisualBasicSyntaxFactsService.IsLeftSideOfCompoundAssignment

### LINKED ISSUE #40917: Fix VisualBasicSyntaxFactsService.IsLeftSideOfCompoundAssignment
VB supports compound assignments, following should be fixed:
https://github.com/dotnet/roslyn/blob/61761f5fe90ec9cf0bfeb9157aea8f89a1555fc3/src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb#L1336-L1339

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #40917

Addresses feedback from https://github.com/dotnet/roslyn/pull/40896#discussion_r365505109

### CODE REVIEW

**Comment by sharwell** [comment]
Does this impact any of our features?

**Comment by mavasani** [comment]
Not as of now. It is implemented as part of https://github.com/dotnet/roslyn/pull/40896, but the code fix invoking it in that PR can only ever invoke it from C#.

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb [hunk 1]
```diff
@@ -797,11 +797,51 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
...
+        Public Function IsLeftSideOfAnyAssignmentStatement(node As SyntaxNode) As Boolean
+            Return node IsNot Nothing AndAlso
+                node.Parent.IsAnyAssignmentStatement() AndAlso
+                DirectCast(node.Parent, AssignmentStatementSyntax).Left Is node
+        End Function
+
+        <Extension>
+        Public Function IsAnyAssignmentStatement(node As SyntaxNode) As Boolean
+            Return node IsNot Nothing AndAlso
+                SyntaxFacts.IsAssignmentStatement(node.Kind)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: i feel like this would just be `typeof node is assignmentstatementsyntax`, no?

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb [hunk 2]
```diff
@@ -797,11 +797,51 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
...
+        Public Function IsLeftSideOfCompoundAssignmentStatement(node As SyntaxNode) As Boolean
+            Return node IsNot Nothing AndAlso
+                node.Parent.IsCompoundAssignmentStatement() AndAlso
+                DirectCast(node.Parent, AssignmentStatementSyntax).Left Is node
+        End Function
+
+        <Extension>
+        Public Function IsCompoundAssignmentStatement(node As SyntaxNode) As Boolean
+            If node IsNot Nothing Then
+                Select Case node.Kind
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: i thnk you can do `select cast node?.Kind()`.  or does that not work in vb?

**Comment by CyrusNajmabadi** [comment]
thanks for fixin this so quick.

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb (hunk 1 above)
Comment (mavasani) [reply src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: I matched the existing coding patterns used in this file and SyntaxNodeExtensions.cs

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb (hunk 2 above)
Comment (mavasani) [reply src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: I am not sure, this felt more clear to me :-)

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: works for me!

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb]: works for me!

**Comment by mavasani** [comment]
@sharwell Any other feedback?

**Comment by mavasani** [comment]
@dotnet/roslyn-ide for reviews.

File: src/Workspaces/VisualBasicTest/VisualBasicSyntaxFactsServiceTests.vb [hunk 3]
```diff
@@ -530,6 +530,24 @@ End Class"
...
+            Assert.True(IsLeftSideOfCompoundAssignment(WrapInMethod("
+Dim index As Integer = 0
+$$index += 1")))
+        End Sub
+
+        Private Function IsLeftSideOfCompoundAssignment(markup As String) As Boolean
+            Dim code As String = Nothing
+            Dim position As Integer
+            MarkupTestFile.GetPosition(markup, code, position)
+            Dim tree = SyntaxFactory.ParseSyntaxTree(code)
```
Comment (JoeRobich) [inline src/Workspaces/VisualBasicTest/VisualBasicSyntaxFactsServiceTests.vb]: Would `code` still be `Nothing` here or does `MarkupTestFile.GetPosition` populate `code` as well as `position`?

Comment (mavasani) [reply src/Workspaces/VisualBasicTest/VisualBasicSyntaxFactsServiceTests.vb]: It populates both code and position.

**Comment by mavasani** [comment]
Thank you @JoeRobich!
