### PR TITLE
Fix inserting new values with source generators

### LINKED ISSUE #67123: Source generators run very unreliably (especially with multi-targeting)
**Version Used**: 17.4.3 to 17.6 Preview 1

We're seeing multiple issues being reported of the MVVM Toolkit source generators not working correctly, especially in the 8.1 release, which is the first one that uses Roslyn multi-targeting. This is a major issue for us, as it (1) causes frustration to users and sometimes outright prevents them from using the MVVM Toolkit, and (2) leads them to assume the MVVM Toolkit is at fault here, and then report issues in our repo, where there isn't really much we can do (and I suspect the issue is rather somewhere in Roslyn/VS).

The common symptoms are:
- IntelliSense not working correctly (red squiggly lines all over the place for generated members)
- Builds outright being broken with various source generator errors (common one being that they run twice)

We've noticed reports in several configurations, from MAUI to WinUI 3, etc. I have tried to reproduce this and so far I've just been completely unable to do so. This included setting up test projects on various frameworks and inspecting our unit tests. I genuinely have no idea what's going on and why things are breaking up for so many people, and could use some help 🥲

Related issues:
- https://github.com/CommunityToolkit/dotnet/issues/493
- https://github.com/CommunityToolkit/dotnet/issues/584
- https://github.com/CommunityToolkit/dotnet/issues/598
- https://github.com/CommunityToolkit/dotnet/issues/623
- https://github.com/CommunityToolkit/dotnet/issues/625

> **Note**: this seems unrelated to the previous issue caused by CsWin32 bundling `System.Memory` assemblies (which @jaredpar fixed in Roslyn, and the CsWin32 team also addressed on their end), as that was just causing the generators to completely fail to be loaded. This is different: they are loaded but then either result in IntelliSense being broken, or they throw errors, or they just seem to not run at all. I have been unable to find a setup/configuration that consistently reproduces the issue.

Interestingly, several people seem to also report downgrading to 8.0 fixes the issue. The main difference I can see in 8.1 is that we're now using Roslyn multi-targeting. I wonder if there might be some bug in that area that causes Roslyn to sometimes trip up? Not saying this is 100% the cause of the issue, but in some cases it does seem downgrading solves it.

cc. @333fred @sharwell @chsienki

### PR DESCRIPTION
**Pull request by chsienki**
If an upstream node adds more items in the middle of its output, we would incorrectly use a later value as the cached value because the table offset was incorrect. This could lead to the same value being inserted twice and cause the `hintName must be unique` exceptions we see with the MVVM generator.

This fix exposed a slightly incorrect test and required us to properly track the output documents rather than just assuming they are added.

Fixes #67123

### CODE REVIEW

**Comment by chsienki** [comment]
Note: I think we should refactor the API on NodeStateTable so that is has to be correct by construction, rather than relying on callers doing the right things with it. 

That's a much bigger change though, so I've done the smallest change here and will potentially send a bigger refactoring PR out at a later date.

**Comment by jaredpar** [comment]
@333fred, @RikkiGibson PTAL

**Comment by chsienki** [comment]
Believe the failures where just infra issues. Everything seems ok now the infra issue is resolved.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 1]
```diff
@@ -374,17 +373,26 @@ public bool TryModifyEntries(ImmutableArray<T> outputs, IEqualityComparer<T> com
             public void AddEntry(T value, EntryState state, TimeSpan elapsedTime, ImmutableArray<(IncrementalGeneratorRunStep InputStep, int OutputIndex)> stepInputs, EntryState overallInputState)
             {
                 _states.Add(new TableEntry(OneOrMany.Create(value), state));
+                _insertedCount += state == EntryState.Added ? 1 : 0;
```
Comment (333fred) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:376]: Presumably the builder is never multithreaded? Should we add a note mentioning it must not be?

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 2]
```diff
@@ -374,17 +373,26 @@ public bool TryModifyEntries(ImmutableArray<T> outputs, IEqualityComparer<T> com
...
                 var tableEntry = new TableEntry(OneOrMany.Create(values), state);
                 _states.Add(tableEntry);
+                _insertedCount += state == EntryState.Added ? 1 : 0;
                 RecordStepInfoForLastEntry(elapsedTime, stepInputs, overallInputState);
                 return tableEntry;
             }
 
+            private bool TryGetPreviousEntry(out TableEntry previousEntry)
+            {
+                var canUsePrevious = _previous._states.Length > (_states.Count - _insertedCount);
```
Comment (333fred) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:391]: Consider extracting the `states.Count - _insertedCount` into a separate local to share, and writing up a comment on what purpose it's serving.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs [hunk 3]
```diff
@@ -1104,6 +1104,76 @@ public void Node_Table_When_Previous_Was_Larger_Multi()
             AssertTableEntries(table.AsCached(), ImmutableArray.Create(("class1", EntryState.Cached, 0), ("class1.1", EntryState.Cached, 1)));
         }
 
+        [Fact, WorkItem(66451, "https://github.com/dotnet/roslyn/issues/67123")]
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs:1107]: The numbers don't match. Consider using `WorkItem` overload with only the URL string. (Below as well.)

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 4]
```diff
@@ -374,17 +373,26 @@ public bool TryModifyEntries(ImmutableArray<T> outputs, IEqualityComparer<T> com
...
                 _states.Add(new TableEntry(OneOrMany.Create(value), state));
+                _insertedCount += state == EntryState.Added ? 1 : 0;
                 RecordStepInfoForLastEntry(elapsedTime, stepInputs, overallInputState);
             }
 
             public TableEntry AddEntries(ImmutableArray<T> values, EntryState state, TimeSpan elapsedTime, ImmutableArray<(IncrementalGeneratorRunStep InputStep, int OutputIndex)> stepInputs, EntryState overallInputState)
             {
                 var tableEntry = new TableEntry(OneOrMany.Create(values), state);
                 _states.Add(tableEntry);
+                _insertedCount += state == EntryState.Added ? 1 : 0;
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:384]: Won't the problem occur when an entry is inserted with state other than `Added`?

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 5]
```diff
@@ -252,34 +253,32 @@ internal bool TryUseCachedEntries(TimeSpan elapsedTime, ImmutableArray<(Incremen
...
-
                 // Semantics:
                 // For each item in the row, we compare with the new matching new value.
                 // - Cached when the same
                 // - Modified when different
                 // - Removed when old item position > outputs.length
                 // - Added when new item position < previousTable.length
 
-                var previousEntry = _previous._states[_states.Count];
+                if (!TryGetPreviousEntry(out var previousEntry))
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:278]: Does this fix https://github.com/dotnet/roslyn/issues/68392?

Comment (chsienki) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:278]: Sadly not. We can take a look at that next.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs (hunk 4 above)
Comment (chsienki) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:384]: Sort of. AddEntries is used both as `AppendEntries` and also `ReplaceEntries`. When called with `EntryState.Added` it means add a new entry, so we need to track the insertion. Everything else that calls it with a different entry state is replacing the exisitng entry with something else.

It's not a good API (read: it is terribad). I'm planning on refactoring the StateTable API anyway, so it always maintains consistency rather than relying on the callers to it to use it correctly, but that's a bigger change and I want to make the smallest one possible here as a targeted fix.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs (hunk 1 above)
Comment (chsienki) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:376]: Yeah, the builder is absolutely not thread safe. I can add a note on the class summary, but lots of other things would break too.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs [hunk 6]
```diff
@@ -1104,6 +1104,42 @@ public void Node_Table_When_Previous_Was_Larger_Multi()
...
+            ImmutableArray<string> values = ImmutableArray.Create("1", "2");
+            var inputNode = new InputNode<string>(_ => values).WithTrackingName("Input");
+
+            var transformNode = new TransformNode<string, string>(inputNode, (a, ct) =>
+            {
+                return a switch
+                {
+                    "1" => ImmutableArray.Create("1.1", "1.2"),
+                    "2" => ImmutableArray.Create("2.1", "2.2"),
+                    _ => ImmutableArray.Create("1.1", "inserted", "1.2")
```
[the remark this answers is not in the document]
Comment (chsienki) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs:1119]: Good idea, added some more tests that move the insertion around

**Comment by chsienki** [comment]
@jjonescz @333fred Addressed all feedback, ready for re-review. Thanks!

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 7]
```diff
@@ -388,8 +391,12 @@ public TableEntry AddEntries(ImmutableArray<T> values, EntryState state, TimeSpa
 
             private bool TryGetPreviousEntry(out TableEntry previousEntry)
             {
-                var canUsePrevious = _previous._states.Length > (_states.Count - _insertedCount);
-                previousEntry = canUsePrevious ? _previous._states[_states.Count - _insertedCount] : default;
+                // When indexing into the previous table we need to subtract the number of entries that have been explicitly added
+                // to the current table, as they didn't exist in the previous one.
+                var previousTableEntryIndex = _states.Count - _insertedCount;
+
+                var canUsePrevious = _previous._states.Length > (previousTableEntryIndex);
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:398]: Nit:
```suggestion
                var canUsePrevious = _previous._states.Length > previousTableEntryIndex;
```

**Review by jjonescz — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Comment by Sergio0694** [comment]
This is awesome, thank you so much @chsienki for spotting this and for the fix!! 🙌
