### PR TITLE
Fix for split string literals broken with multi-carets

### LINKED ISSUE #39040: VS C# Editor, Advanced, Editor Help, "Split string literals on enter" broken
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752445/vs-c-editor-advanced-editor-help-split-string-lite.html)._

---
&quot;Split string literals on enter&quot; has been broken since it was introduced, and still is in VS2019.

image

Additionally, it's _completely_ broken if you use multi-carets. Then it doesn't even pretent to attempt to &quot;Split string literals on enter&quot;, it just splits and indents each caret without inserting quotes, totally destroying the string literal.

I can be more forgiving about the latter bug, since multi-caret was a later addition to the editor, &lt;rant_mode=&quot;on&quot;&gt;but please - stuff like this needs to be _checked_ before release&lt;rant_mode=&quot;off&quot;&quot;&gt;.
Anyway, it's a clear bug and needs to be fixed. Should be no more than a few minutes of work after the main bug has been fixed.

---
#### Visual Studio Feedback System on 9/28/2019, 09:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #39040

Previously, string literals split with multi-carets were treated as non-string literals. With this fix, when all carets are within string literals, they will be split as string literals.

If the selections are a mix of non-string literals and string literals, they will all be handled as non-string literals.

### CODE REVIEW

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 1]
```diff
@@ -56,18 +56,49 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
-                        return SplitString(textView, subjectBuffer, caret.Value);
+                        var spanStart = spans[spanIndex].Start;
+                        var line = subjectBuffer.CurrentSnapshot.GetLineFromPosition(spanStart);
+                        if (!LineContainsQuote(line, spanStart))
+                        {
+                            return false;
+                        }
+                    }
+
+                    // We now go through the verified string literals and split each of them.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: =-o

Out of curiosity, why do this route?  Why not just disable the feature if this is a multi-caret scenario?

File: src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs [hunk 2]
```diff
@@ -744,5 +752,56 @@ static void Main(string[] args)
...
+        [WorkItem(20258, "https://github.com/dotnet/roslyn/issues/39040")]
+        [WpfFact, Trait(Traits.Feature, Traits.Features.SplitStringLiteral)]
+        public void TestMultiCaretSingleLine()
+        {
+            TestHandled(
+@"class C
+{
+    void M()
+    {
+        var v = ""now is [||]the ti[||]me"";
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs]: =-o

I mean, it's cool this is supported!  but i would be 100% ok with us not doing anything in this case and just passing the `return` on untouched.

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs (hunk 1 above)
Comment (allisonchou) [reply src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: When a user has multiple carets in various string literals and presses enter, I feel like they would typically expect the same behavior as when splitting a point in a single string literal.

Splitting them as non-strings (the existing functionality) doesn't seem like it would be desired in the majority of scenarios, at least from my perspective. Maybe @sharwell has more insight on this?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: i'm not cetain what i would expect in this case.  :)   if this works, great!

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 3]
```diff
@@ -56,18 +56,49 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
             var spans = textView.Selection.GetSnapshotSpansOnBuffer(subjectBuffer);
 
             // Don't split strings if there is any actual selection.
-            if (spans.Count == 1 && spans[0].IsEmpty)
+            // We must check all spans to account for multi-carets.
+            if (!spans.IsEmpty() && spans.All(s => s.IsEmpty))
             {
```
Comment (ivanbasov) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: The if statement becomes too long. It maybe better to inverse the condition for the quick bail out. For readability purposes.

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 4]
```diff
@@ -56,18 +56,49 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
+                        var line = subjectBuffer.CurrentSnapshot.GetLineFromPosition(spanStart);
+                        if (!LineContainsQuote(line, spanStart))
+                        {
+                            return false;
+                        }
+                    }
+
+                    // We now go through the verified string literals and split each of them.
+                    for (var spanIndex = 0; spanIndex < spans.Count; spanIndex++)
+                    {
```
Comment (ivanbasov) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: Would not it be better to merge these loops?

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 5]
```diff
@@ -56,21 +56,53 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
+                    }
+
+                    if (!SplitString(textView, subjectBuffer, spanStart))
+                    {
+                        return false;
+                    }
+                }
+                return true;
+            }
             return false;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: nits, after `}` we generally have a blank line.

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 6]
```diff
@@ -56,21 +56,53 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
+                    {
+                        caret = textView.GetCaretPoint(subjectBuffer);
+                        if (caret == null)
+                        {
+                            return false;
+                        }
+
+                        // We change the span's starting point based on how much space was added from the last split.
+                        var addedSpan = caret.Value.Subtract(spans[spanIndex - 1].Start);
+                        spanStart = new SnapshotPoint(caret.Value.Snapshot, addedSpan.Position + spanStart.Position);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: this should likley be better handled with a mapping point.  @jasonmalinowski can you advise on that?

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 7]
```diff
@@ -56,21 +56,53 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
+                    // Multi-caret case
+                    if (spanIndex > 0)
+                    {
+                        caret = textView.GetCaretPoint(subjectBuffer);
+                        if (caret == null)
+                        {
+                            return false;
+                        }
+
+                        // We change the span's starting point based on how much space was added from the last split.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: an easier way to do things would be to start from the *last* span and go *backwards*.  That way you don't need to update anything since later splits won't affect earlier caret positions.

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 8]
```diff
@@ -56,21 +56,53 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
+            // We must check all spans to account for multi-carets.
+            if (spans.IsEmpty() || !spans.All(s => s.IsEmpty))
             {
-                var caret = textView.GetCaretPoint(subjectBuffer);
-                if (caret != null)
+                return false;
+            }
+
+            var caret = textView.GetCaretPoint(subjectBuffer);
+            if (caret != null)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: invert this as well.  if caret is null just return false immediatey

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs [hunk 9]
```diff
@@ -56,22 +56,40 @@ public bool ExecuteCommandWorker(ReturnKeyCommandArgs args)
...
-                    {
-                        return SplitString(textView, subjectBuffer, caret.Value);
-                    }
+                    return false;
                 }
             }
 
-            return false;
+            // We now go through the verified string literals and split each of them.
+            foreach (var span in spans.Reverse())
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: might want to consider doc'ing why .Reverse is beneficial.

File: src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs [hunk 10]
```diff
@@ -744,5 +752,56 @@ static void Main(string[] args)
...
+@"class C
+{
+    string s = ""hello w"" +
+        ""[||]orld"";
+
+    void M()
+    {
+        var v = ""now is "" +
+            ""[||]the ti"" +
+            ""[||]me"";
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs]: can you have a test where we do this in different styles of strings. i.e.  one part in a normal string, one part in an interpolated string?

File: src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs]: i'm ok with this now.

File: src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs (hunk 1 above)
Comment (tamlin-mike) [reply src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs]: @CyrusNajmabadi Sorry for the very late reply. A very useful scenario is if you have a string with multiple embedded \n. You can then simply select the first one, add carets with Ctrl+Alt+'.', Right, Enter, and voila: properly formatted and indented to more properly reflect how it will be displayed at runtime.

**Comment by tamlin-mike** [comment]
@allisonchou Sorry for late reaction; Thank you very much for the time and effort fixing this. Much appreciated.
