### PR TITLE
Fix a deadlock in the analyzer driver

### LINKED ISSUE #4858: Deadlock in VBCSCompiler.exe building a project with analyzer enabled
Dump: \\DAVKEAN-I7\Shared\VBCSCompiler.exe\VBCSCompiler.dmp

Right now I can repeat this consistently.

__Thread 1:__
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic diagnostic)	Unknown
 	StyleCop.Analyzers.dll!StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented.HandleTypeDeclaration(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext context)	Unknown
 	StyleCop.Analyzers.dll!StyleCop.Analyzers.AnalyzerExtensions.RegisterSyntaxNodeActionHonorExclusions.AnonymousMethod__0(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext c)	Unknown

__Thread 2:__
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic diagnostic)	Unknown
 	StyleCop.Analyzers.dll!StyleCop.Analyzers.OrderingRules.SA1211UsingAliasDirectivesMustBeOrderedAlphabeticallyByAliasName.HandleUsingDirectiveSyntax(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext context)	Unknown
 	StyleCop.Analyzers.dll!StyleCop.Analyzers.AnalyzerExtensions.RegisterSyntaxNodeActionHonorExclusions.AnonymousMethod__0(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext c)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeAction.AnonymousMethod__1()	Unknown

__6 threads:__
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action analyze)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind> syntaxNodeAction, Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerStateOpt)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActions<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.CSharp.SyntaxKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>>> nodeActionsByKind, Microsoft.CodeAnalysis.SemanticModel model, System.Func<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.SyntaxKind> getKind, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerStateOpt)	Unknown

### PR DESCRIPTION
**Pull request by mavasani**
Primary issue is that we currently try to force complete and decode SuppressMessageAttributes in the analyzer callbacks to report a diagnostic. We need to decode these attributes to apply source suppressions to reported diagnostics. However, force completing attributes can lead to us binding more symbols, and subsequently generating more symbol declared events and attempting to callback into the analyzer again.

Fix is to decode the suppress message attributes as a post pass in the analyzer driver and avoid any symbol force completion during analyzer callbacks to report diagnostics.

Fixes #4858

### CODE REVIEW

**Comment by mavasani** [comment]
@JohnHamby @heejaechang @lgolding can you please review?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 1]
```diff
@@ -809,19 +842,9 @@ internal static Action<Diagnostic> GetDiagnosticSinkWithSuppression(Action<Diagn
             };
         }
 
-        private static Diagnostic GetFilteredDiagnostic(Diagnostic diagnostic, Compilation compilation, ISymbol symbolOpt = null)
+        private static Diagnostic GetFilteredDiagnostic(Diagnostic diagnostic, Compilation compilation)
         {
-            var filteredDiagnostic = compilation.Options.FilterDiagnostic(diagnostic);
```
Comment (lgolding) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: This code looks familiar -- I think this change will give a merge conflict with your "emit suppressed issues" work.

**Comment by mavasani** [comment]
FYI: @JohnHamby who is most familiar with this code is OOF. So I plan to check this in today, and address any feedback from him once he is back.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 2]
```diff
@@ -373,7 +373,7 @@ private int RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, Cancellat
                     Action<Diagnostic> addExceptionDiagnostic = diagnostic => analyzerExceptionDiagnostics.Add(diagnostic);
                     var analyzerOptions = new AnalyzerOptions(ImmutableArray<AdditionalText>.CastUp(additionalTextFiles));
                     analyzerDriver = AnalyzerDriver.CreateAndAttachToCompilation(compilation, analyzers, analyzerOptions, analyzerManager, addExceptionDiagnostic, Arguments.ReportAnalyzer, out compilation, analyzerCts.Token);
-                    getAnalyzerDiagnostics = () => analyzerDriver.GetDiagnosticsAsync().Result;
+                    getAnalyzerDiagnostics = () => analyzerDriver.GetDiagnosticsAsync(compilation).Result;
```
Comment (heejaechang) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: is this okay calling Async Result from a thread that is not UI thread? I had this long before in Roslyn and caused thread starvation which caused hundreds of threads to spawn up in certain circumstance.

**Comment by heejaechang** [comment]
:+1:

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 2 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Actually, this API was intended to be async only for public consumers of diagnostics queue from the analyzer driver (when we planned to make it public). Right now its only consumer is the command line compiler, which invokes it after all compilation events have been generated, so we can probably convert the API to sync API. I will do so in a later refactoring.
