### PR TITLE
When assigning decimal/datetime constant fields, the FieldAccess sho…

### LINKED ISSUE #4383: Roslyn VB Compiler Emits Unsupported IL For x86 Static Constructor
This morning I discovered what appears to be a bug in the Roslyn VB compiler.  The result of the bug is that a static constructor for a class will fail with InvalidProgramException and the message "JIT Compiler encountered an internal limitation".

I have narrowed this bug down to the following steps to reproduce:

1.  Must be using Visual Basic and Visual Studio 2015.  The bug does not occur when compiled in Visual Studio 2013 with the former version of the compiler.
2.  Application must target x86, or be set to Prefer 32-bit.  (It appears that the x64 JIT works around this optimization problem)
3.  Optimizations must be enabled
4.  Class must have a static constructor which first initializes a Decimal constant, then initializes a Dictionary.
5.  I have replicated this problem so far targeting both .Net 4.5.2 and .Net 4.6.  This includes replicating it on a machine without .Net 4.6 installed.

An example project which demonstrates this error can be found at https://github.com/brantburnett/RoslynVBError.  Be sure to run in Release mode so that optimizations are enabled to see the error.  There is also a C# project included, which demonstrates that it doesn't have the error.

I have narrowed the specific IL error down to an extra "dup" operation before the final "stsfld" operation:

```
.method private specialname rtspecialname static void .cctor() cil managed
{
    .maxstack 4
    L_0000: ldc.i4 0x177
    L_0005: conv.i8 
    L_0006: newobj instance void [mscorlib]System.Decimal::.ctor(int64)
    L_000b: stsfld valuetype [mscorlib]System.Decimal RoslynTest.ClassWithStaticField::DecimalConstant
    L_0010: newobj instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::.ctor()
    L_0015: dup 
    L_0016: ldstr "String1"
    L_001b: ldc.r4 1
    L_0020: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0025: dup 
    L_0026: ldstr "String2"
    L_002b: ldc.r4 2
    L_0030: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0035: dup 
    L_0036: ldstr "String3"
    L_003b: ldc.r4 3
    L_0040: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0045: dup 
    L_0046: stsfld class [mscorlib]System.Collections.Generic.Dictionary`2<string, float32> RoslynTest.ClassWithStaticField::DictionaryField
    L_004b: ret 
}
```

If the dup operation is removed, then the JIT error does not occur.

Please let me know if there is any additional information I can provide which will be of assistance.

Thanks,
Brant

### PR DESCRIPTION
**Pull request by VSadov**
…uld not be considered a constant.

Fixes #4383

### CODE REVIEW

**Comment by VSadov** [comment]
@gafter @AlekseyTs @jaredpar @agocke - please review.

**Comment by VSadov** [comment]
The problem was that stack scheduler generally ignores expressions that are constants (since they do not affect the stack), but then it saw a const field access on the LHS of an assignment and such things cannot be ignored, so scheduler got confused.
Constant fields typed as decimal/datetime need to be assigned in cctor. In the context of such assignment they should not be treated as constants.

C# already handles this case correctly, but a regression test was added just in case.

**Comment by VSadov** [comment]
Installing 'dnx-coreclr-win-x86 1.0.0-beta5-12101'.
*** Error in `mono': malloc(): memory corruption: 0x00007f6af02b64f2 ***
Stacktrace:


Native stacktrace:

Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
./cibuild.sh: line 86: 53003 Terminated              mono .nuget/NuGet.exe "$@"
[xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern '**/*TestResults.xml' relative to '/mnt/j/workspace/dotnet_roslyn_linux_prtest@2' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?


This is getting annoying. I see this on most PRs at least once now.

**Comment by VSadov** [comment]
retest this please

**Comment by jaredpar** [comment]
@VSadov I just changed the Linux / Mac runs on Friday to reduce the chance we will hit this particular message.  The failure rates should drop down a bit this week.  If they don't well take further action on those runs.

File: src/Compilers/VisualBasic/Portable/BoundTree/BoundFieldAccess.vb [hunk 1]
```diff
@@ -33,6 +33,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Public Overrides ReadOnly Property ConstantValueOpt As ConstantValue
             Get
+                ' decimal and datetime const fields require one-time synthesized assignment in cctor
+                ' when used as a LHS of an assignment, the access is not a const.
+                If _IsLValue Then
+                    Return Nothing
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/BoundFieldAccess.vb]: Consider adding an assert that the field's type is either decimal or datetime.

**Comment by AlekseyTs** [comment]
LGTM. Consider adding an assert suggested in other comment.

File: src/Compilers/VisualBasic/Portable/BoundTree/BoundFieldAccess.vb (hunk 1 above)
Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/BoundTree/BoundFieldAccess.vb]: The field does not need to be decimal or datetime. Any field access that is an lvalue should not have constant value. It just so happens that only decimal and datetime fields can be formally constants while also participating in assignments. An assert for such condition should not be here, but somewhere at node construction. 
I think it is not worth it though, since it would basically guard that we are not assigning to constants in general, which seems improbable for many other reasons.

**Comment by gafter** [comment]
LGTM
