### PR TITLE
#20630 Cast is redundant on attribute with params fix

### LINKED ISSUE #20630: Wrong IDE0004 Cast is redundant when applying attribute with params argument
**Version Used**: 
First seen in VS2015. Subsequently reproduced on:

> VS2017, version 15.2 (26430.14) Release

**Steps to Reproduce**:

Use this complete Console app:

```csharp
using System;
using System.Reflection;

class MarkAttribute : Attribute
{
  public readonly string[] Arr;

  public MarkAttribute(params string[] arr)
  {
    Arr = arr;
  }
}

[Mark((string)null)]   // wrong instance of: IDE0004 Cast is redundant.
static class Program
{
  static void Main()
  {
    var arr = typeof(Program).GetCustomAttribute<MarkAttribute>().Arr;
    Console.WriteLine(arr?.Length ?? int.MinValue);
  }
}
```

When compiled and run, correctly writes 1 to the console.

**Expected Behavior**:

No suggestion to remove cast syntax on null literal in attribute specification on class Program.

**Actual Behavior**:

Cast to string is in a pale text color, and a light bulb suggests, "Remove Unnecessary Cast". If the bad suggestion is followed, program behavior changes from writing 1 into writing -2147483648.

Obviously, the issue is with a params constructor that can apply in either normal form or expanded form.

While this seems _similar_ to other issues, like #18978, I do not know if it is a duplicate of any issue.

### PR DESCRIPTION
**Pull request by MaStr11**
**Customer scenario**

False positive on IDE0004 "Cast is redundant" analyzer

**Bugs this fixes:**

Fixes #20630

**Workarounds, if any**

Disable IDE0004

**Risk**

Code fix changes behavior.

**Performance impact**

Low.

**Is this a regression from a previous update?**

Variation of: #18978
Related: #20741 #20742

**Root cause analysis:**

Analyzer misses test for prams in attribute constructor calls.

**How was the bug found?**

Customer reported

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -177,25 +176,44 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
...
+            return false;
+        }
 
-                    var conversion = semanticModel.Compilation.ClassifyConversion(castType, parameterType);
-                    if (conversion.Exists &&
-                        conversion.IsImplicit)
-                    {
-                        return false;
-                    }
+        private static bool CheckConversionOfParamToParamArray(IParameterSymbol parameter, ITypeSymbol castType, SemanticModel semanticModel)
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: `Check` what?  Is there a name that describes what is true if this method returns true?

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -177,25 +176,44 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
...
+        {
+            if (parameter != null && parameter.IsParams)
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Could just use `parameter?.IsParams`

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 3]
```diff
@@ -177,25 +176,44 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
...
+            {
+                Debug.Assert(parameter.Type is IArrayTypeSymbol);
 
-                    var conversionElementType = semanticModel.Compilation.ClassifyConversion(castType, parameterType.ElementType);
-                    if (conversionElementType.Exists &&
-                        conversionElementType.IsImplicit)
-                    {
-                        return true;
-                    }
+                var parameterType = (IArrayTypeSymbol)parameter.Type;
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Is this correct in broken code?  What if I type a method that says `M(params int something)` Does the symbol still report `IsParams`?

Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: I see this is just moved code, so I assume so, but worth double checking.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs (hunk 1 above)
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Maybe `ParameterTypeMatchesParamsElementType` or something?

**Comment by Pilchie** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Pilchie** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Pilchie** [comment]
Test results were gone :(

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide can we get a second review here?

**Comment by MaStr11** [comment]
@Pilchie 
>Is this correct in broken code? What if I type a method that says M(params int something) Does the symbol still report `IsParams`?

This wasn't covered before by tests. I added tests for method calls and for attributes and it turned out, that both were failing with an `InvalidCastException`. I don't know what is the correct behavior in such a case but I decided to assume that in such cases we return `true` to cancel the analyzer. Unfortunately in this case the `return true` does not reflect what the method name `ParameterTypeMatchesParamsElementType` suggests.

**Comment by Pilchie** [comment]
Thanks!  This looks good to me.  Anyone else from @dotnet/roslyn-ide want to review?

**Comment by Pilchie** [comment]
Ping @dotnet/roslyn-ide for a second review.

**Comment by sharwell** [comment]
@MaStr11 Were you closing this because we were slow or because it was fixed in some other manner?

**Comment by MaStr11** [comment]
Closing the issue was a mistake on my side. I don't know how this could happen. I'm sorry for the inconvenience.

**Comment by sharwell** [comment]
@MaStr11 No problem! Just wanted to make sure I didn't miss something.

**Comment by jinujoseph** [comment]
test windows_release_vs-integration_prtest

**Comment by jinujoseph** [comment]
test windows_coreclr_debug_prtest

**Comment by jinujoseph** [comment]
@Pilchie  for ask mode approval for 15.7 Preview 4

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+namespace Microsoft.CodeAnalysis.CSharp.Extensions
+{
+    internal static class AttributeArgumentSyntaxExtensions
+    {
+        /// <summary>
+        /// Returns the parameter to which this argument is passed. If <paramref name="allowParams"/>
+        /// is true, the last parameter will be returned if it is params parameter and the index of
+        /// the specified argument is greater than the number of parameters.
+        /// </summary>
+        public static IParameterSymbol DetermineParameter(
```
Comment (mavasani) [inline src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: @AlekseyTs @333fred I can't seem to recall: does `GetOperation(AttributeArgumentSyntax)` return an `IArgumentOperation`? If so, we can replace this method with `IArgumentOperation.Parameter`. If not, it would be good to file a tracking issue.

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+            var parameters = symbol.GetParameters();
+
+            // Handle named argument
+            if (argument.NameColon != null && !argument.NameColon.IsMissing)
+            {
+                var name = argument.NameColon.Name.Identifier.ValueText;
+                return parameters.FirstOrDefault(p => p.Name == name);
+            }
+
+            // Handle positional argument
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: what if it is a "Name =" argument?  That would not map to a parameter at all, regardless of position.

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs (hunk 4 above)
Comment (333fred) [reply src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: It doesn't look like we have any tests in this area. We should give it a try and see if it works.

**Comment by Pilchie** [comment]
Approved - thanks @MaStr11 and sorry this took so long to get in.  It's embarrassing! 😊

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs (hunk 4 above)
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: This method is a copy of [ArgumentSyntaxExtensions.DetermineParameter](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs#L46). If we change the logic here, we should also change it there.

> It doesn't look like we have any tests in this area. We should give it a try and see if it works.

That's a confusing statement. I really don't know what I'm supposed to do here, especially given that this PR got approved to merge already.

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs (hunk 5 above)
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: That's right. I addressed this in 514e4fd2:
* Added a test for a cast in a named argument
* added a <remarks> section explaining the handling of named arguments
* Added an return at the top of the method for named arguments.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 6]
```diff
@@ -175,25 +175,48 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
...
+            }
+
+            if (parent is AttributeArgumentSyntax attributeArgument)
+            {
+                if (attributeArgument.Parent is AttributeArgumentListSyntax attributeArgumentList)
                 {
-                    Debug.Assert(parameter.Type is IArrayTypeSymbol);
+                    // We don't check the position of the argument because in attributes it is allowed that 
+                    // params parameter are positioned in between if named arguments are used.
+                    // The *single* argument check above is also broken: https://github.com/dotnet/roslyn/issues/20742
```
[the remark this answers is not in the document]
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: At this position we need to find the parameter that fits to the argument (DetermineParameter). We pass this information to ParameterTypeMatchesParamsElementType which is only interested in `params` parameters. We could avoid the call to DetermineParameter if we are sure that looking at the `attributeArgumentList` and the `attributeArgument` in it we can be sure that it

1. can't be a `params` parameter or
2. if it might be a `params` parameter the argument would be a single element array passed to the parameter.

I don't think it is possible to determine either of that conditions by only looking at the `attributeArgumentList` and the `attributeArgument`.

[the remark this answers is not in the document]
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: I was specifically referring to how this:

> If there are any arguments to the right, we can assume that this is not a *single* argument passed to a params parameter.

Relates to this:

> The *single* argument check above is also broken

It seems that you could identify a single argument as an argument meeting both of the following conditions:

1. The argument appears first in the list
2. The next argument, if any, has a non-null `NameEquals` property, indicating that it is not an argument

[the remark this answers is not in the document]
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: I was specifically referring to how this:

> If there are any arguments to the right, we can assume that this is not a *single* argument passed to a params parameter.

Relates to this:

> The *single* argument check above is also broken

It seems that you could identify a single argument as an argument meeting both of the following conditions:

1. The argument appears first in the list
2. The next argument, if any, has a non-null `NameEquals` property, indicating that it sets a named property instead of a parameter

[the remark this answers is not in the document]
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: ➡️ Filed #25790 as a follow-up

[the remark this answers is not in the document]
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: The *single argument* comment is misleading. It's really asking for a *single argument passed to a params parameter*.

File: src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Extensions/AttributeArgumentSyntaxExtensions.cs]: Thanks!
