### PR TITLE
Fix inserting using inside namespace

### LINKED ISSUE #3080: "Add using" code fix mis-sorts between namespaces sharing a prefix
Roslyn's Add Using code fix adds the new statement with a sort order inconsistent with the Sort Usings refactoring.

Consider a C# console application with this source code:

```csharp
namespace Microsoft.MyApp
{
    using Win32;

    class Program
    {
        static void Main(string[] args)
        {
            SafeRegistryHandle h;
        }
    }
}
```

Position the caret at the `SafeRegistryHandle` line and execute the add using code fix. This changes the using statements at the top to be:

```csharp
    using Win32.SafeHandles;
    using Win32;
```

But this sort order is incorrect. And Roslyn knows it, because then if you execute a Sort Usings command you get the right sort order:

```csharp
    using Win32;
    using Win32.SafeHandles;
```

This repros on VSPro_Platform 22915.00

Note in my experimentation this relies on the `using` statements appearing within a namespace block that starts with `Microsoft` (since `Win32` is shorthand for `Microsoft.Win32`). So in general I think when short-hand namespaces are specified due to overlap with the containing namespace block, that "add using" sorts incorrectly.

### PR DESCRIPTION
**Pull request by jmarolf**
Previously if we added a using inside a namespace we would use a
speculative semantic model determine if we should use the fully qualified
name or not.  What this approach failed to account for was if the name
was going to be simplified further due to the containing namespace.  To
Fix this we run the simplifier over our document and check if there are
any changes made to the namespace.  If this is the case, then we re-sort
the usings according to the simplified name.  

This change also unified add import and sort using code paths.

Fixes #3080

### CODE REVIEW

**Comment by jmarolf** [comment]
@Pilchie @balajikris @dpoeschl @rchande @brettfo @DustinCampbell @basoundr @CyrusNajmabadi

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

File: src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs [hunk 1]
```diff
@@ -465,22 +465,24 @@ protected override string GetDescription(INamespaceOrTypeSymbol namespaceSymbol,
...
-                    if (speculationAnalyzer.ReplacementChangesSemantics())
+                        .DescendantNodes().OfType<UsingDirectiveSyntax>()
+                        .Where(uds => uds.IsEquivalentTo(fullyQualifiedUsingDirective, topLevel: true))
+                        .Single();
+                    newRoot = newRoot.TrackNodes(newUsing);
+                    var options = document.Project.Solution.Workspace.Options;
+                    var documentWithSyntaxRoot = document.WithSyntaxRoot(newRoot);
+                    var simplifiedDocument = await Simplifier.ReduceAsync(documentWithSyntaxRoot, newUsing.Span, options, cancellationToken).ConfigureAwait(false);
+                    newRoot = await simplifiedDocument.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+                    var simplifiedUsing = newRoot.GetCurrentNode(newUsing);
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs]: Are we confident that `TrackNodes` will always preserve this using through simplification?

File: src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs [hunk 2]
```diff
@@ -701,11 +703,11 @@ private bool IsViablePropertyOrField(ISymbol propertyOrField, SyntaxNode express
...
-            var comparisonType = this.IgnoreCase
-                ? StringComparison.OrdinalIgnoreCase
-                : StringComparison.Ordinal;
+            var comparer = this.IgnoreCase
+                ? CaseInsensitiveComparison.Comparer
+                : StringComparer.Ordinal;
 
-            return string.Compare(propertyOrField.ContainingType.Name, leftName.Identifier.Text, comparisonType) == 0;
+            return comparer.Compare(propertyOrField.ContainingType.Name, leftName.Identifier.Text) == 0;
         }
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs]: I assume this goes away with your other change to avoid the check to `IgnoreCase`?

**Comment by Pilchie** [comment]
:+1:
