### PR TITLE
Enforce non-mutating LSP requests to run in parallel.

### LINKED ISSUE #55589: RequestExecutionQueue.ProcessQueueAsync can block for long periods of time interrupting all IntelliSense in LSP scenarios
**Version Used**:  VSMain

**Steps to Reproduce**:

1. Open an enterprise app
2. Enable experimental C# LSP editor
3. Try and acquire completion in a file by repeatedly typing

**Expected Behavior**:
Completion shows up normally

**Actual Behavior**:
Completion doesn't show up until things have colorized. This is due to the [ProcessQueueAsync](https://github.com/dotnet/roslyn/blob/97fe56836f2c9cef67830aeb942dcedd0937113a/src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs#L231) trying to run certain message sin parallel when unintentionally allowing semantic colorization to run synchronously. The synchronous execution of semantic colorization blocks the queue resulting in completion and any other language feature waiting on its result

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- As I was investigating a customer app's performance issues I was met met with C#'s [LSP request handler queue](https://github.com/dotnet/roslyn/blob/909e6dc8eda8ee5898b4e1339c512c44970bcff6/src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs#L199). The queues responsibility is to [await mutating requests](https://github.com/dotnet/roslyn/blob/909e6dc8eda8ee5898b4e1339c512c44970bcff6/src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs#L217) (ones that mutate solution state) and try and [parallelize non-mutating requests](https://github.com/dotnet/roslyn/blob/909e6dc8eda8ee5898b4e1339c512c44970bcff6/src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs#L224-L227). When investigating I found that we weren't truly enforcing the parallelizability of the non-mutating requests which meant if an async operation ran synchronously it would block the entire execution of the queue. Turns out semantic tokens, completion and a few other requests exhibited this behavior. To work around this behavior we now `Task.Run` each work item to ensure they can each operate in parallel.
- Added tests to validate that long-running non-mutating requests don't block queue execution.

Fixes #55589

### CODE REVIEW

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 1]
```diff
@@ -228,7 +228,7 @@ private async Task ProcessQueueAsync()
                         // Non mutating are fire-and-forget because they are by definition readonly. Any errors
                         // will be sent back to the client but we can still capture errors in queue processing
                         // via NFW, though these errors don't put us into a bad state as far as the rest of the queue goes.
-                        _ = ExecuteCallbackAsync(work, context, _cancelSource.Token).ReportNonFatalErrorAsync();
+                        _ = Task.Run(() => ExecuteCallbackAsync(work, context, _cancelSource.Token).ReportNonFatalErrorAsync(), _cancelSource.Token);
```
Comment (ryanbrandenburg) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:231]: Might be helpful to leave a little comment about why Task.Run is not equivalent to just calling the method in question.

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs [hunk 2]
```diff
@@ -0,0 +1,59 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+#nullable disable
```
Comment (ryanbrandenburg) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:5]: Did you mean 
```suggestion
#nullable enable
```

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+        public LongRunningNonMutatingRequestHandlerProvider()
+        {
+        }
+
+        public override ImmutableArray<IRequestHandler> CreateRequestHandlers() => ImmutableArray.Create<IRequestHandler>(new LongRunningNonMutatingRequestHandler());
+    }
+
+    internal class LongRunningNonMutatingRequestHandler : IRequestHandler<TestRequest, TestResponse>
+    {
+        public const string MethodName = nameof(LongRunningNonMutatingRequestHandler);
```
Comment (ryanbrandenburg) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:34]: This name ends up being a lie, but I can see that you're stuck here by IRequestHandler.

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        {
+            do
+            {
+                if (cancellationToken.IsCancellationRequested)
+                {
+                    return Task.FromResult(new TestResponse());
+                }
+
+                Thread.Sleep(100);
+            } while (true);
```
Comment (ryanbrandenburg) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:54]: My first response was "No way" but I see this is test code where you're just trying to force the wait.

**Review by ryanbrandenburg — APPROVED** [review]

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs (hunk 2 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:5]: lmao what the hell. It was an auto-generated class. Kind of shocked it did this 😄

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 1 above)
Comment (dibarbet) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:231]: I _think_ the reportnonfatalerrorasync should move to the Task.Run call, based on similar usages
https://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/EditAndContinue/EditAndContinueSaveFileCommandHandler.cs,50

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs (hunk 4 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:54]: Yup, can't do `await Task.Delay(...)` because that'd yield 😄. Key portion of this test code is that it's doing a synchronous operation and consuming a thread for the entirety of the test

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.Host.Mef;
+using Microsoft.CodeAnalysis.LanguageServer.Handler;
+using Microsoft.VisualStudio.LanguageServer.Protocol;
+using Xunit.Sdk;
+
+namespace Microsoft.CodeAnalysis.LanguageServer.UnitTests.RequestOrdering
+{
+    [Shared, ExportLspRequestHandlerProvider, PartNotDiscoverable]
```
Comment (dibarbet) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:19]: I believe you'll want the new export attribute, e.g. https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/ProtocolUnitTests/Ordering/MutatingRequestHandler.cs#L17

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs [hunk 6]
```diff
@@ -120,6 +121,32 @@ public async Task ThrowingTaskDoesntBringDownQueue()
             Assert.All(responses, r => Assert.True(r.EndTime > r.StartTime));
         }
 
+        [Fact]
+        public async Task LongRunningSynchronousNonMutatingTaskDoesNotBlockQueue()
+        {
+            var requests = new[] {
+                new TestRequest(LongRunningNonMutatingRequestHandler.MethodName),
+                new TestRequest(MutatingRequestHandler.MethodName),
```
Comment (dibarbet) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs:129]: hm- should the mutating request be included?  I guess it doesn't actually matter as previously even the mutating request would be blocked by a long running synchronous non-mutating

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs [hunk 7]
```diff
@@ -120,6 +121,32 @@ public async Task ThrowingTaskDoesntBringDownQueue()
...
+                new TestRequest(NonMutatingRequestHandler.MethodName),
+            };
+
+            using var testLspServer = CreateTestLspServer("class C { }", out _);
+
+            // Cancel all requests if we hang for 5 seconds. This will result in a failed test run.
+            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
```
Comment (dibarbet) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs:136]: The test seems to rely on everything else taking less than 5 seconds, which should usually be true, but seems potentially flaky (for example, a random 5 second gc pause while running).  I wonder if we could make this deterministic by having two handlers - the first request being a long running handler which doesn't finish _until_ a flag is set by the handler handling the second request.  That way we don't have to rely on a specific time span for the test to run (though we may want to cancel with the hang mitigating timeout at some point).

**Comment by dibarbet** [comment]
Thanks for submitting the fix by the way!

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 1 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:231]: Sure can totally add that!

Comment (NTaylorMullen) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:231]: Ah interesting ok!

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs (hunk 6 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs:129]: I figured I'd write one test to encompass interactions with both mutating/non-mutating since prior to this it'd block both 😄

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs (hunk 2 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs:5]: Actually it totally makes sense (learned after trying to change). This is a test class where we aggressively return `null`'s 😄. The project itself is nullable so we have to disable here in order to allow our test classes to be light-weight.

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs (hunk 7 above)
Comment (NTaylorMullen) [reply src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs]: Extended to 1 minute

**Comment by NTaylorMullen** [comment]
🆙 📅

**Review by dibarbet — APPROVED** [review]

**Review by allisonchou — APPROVED** [review]
