### PR TITLE
Make order of extension loading deterministic

### LINKED ISSUE #52035: Different output when using source generators and deterministic compilation
**Version Used**: 

```
 Version:   5.0.201
 Commit:    a09bd5c86c

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295
```
**Steps to Reproduce**:

```
git clone -n https://github.com/zkSNACKs/WalletWasabi.git
git checkout 5167183296e2d6a53d73f127e423e1953976a6c7

cd WalletWasabi

dotnet tool install --global ilspycmd --version 7.0.0.6372-preview3
```

```
git clean -xdf

dotnet publish c:\DOWNLOADS\GitHub-Forks\WalletWasabi\WalletWasabi.Fluent.Desktop\WalletWasabi.Fluent.Desktop.csproj -r win7-x64 --configuration Release --force --self-contained true --output c:/Users/wiesl/Downloads/mk1 --disable-parallel --no-cache /p:VersionPrefix=1.1.113.3 /p:DebugType=none /p:DebugSymbols=false /p:ErrorReport=none /p:DocumentationFile="" /p:Deterministic=true /p:RestoreLockedMode=true /flp:v=diag /flp:logfile="c:/Users/wiesl/Downloads/log1.log"

ilspycmd c:\Users\wiesl\Downloads\mk1\WalletWasabi.Fluent.dll > c:\Users\wiesl\Downloads\WalletWasabi.Fluent.dll.out1.txt
```

```
git clean -xdf

dotnet publish c:\DOWNLOADS\GitHub-Forks\WalletWasabi\WalletWasabi.Fluent.Desktop\WalletWasabi.Fluent.Desktop.csproj -r win7-x64 --configuration Release --force --self-contained true --output c:/Users/wiesl/Downloads/mk2 --disable-parallel --no-cache /p:VersionPrefix=1.1.113.3 /p:DebugType=none /p:DebugSymbols=false /p:ErrorReport=none /p:DocumentationFile="" /p:Deterministic=true /p:RestoreLockedMode=true /flp:v=diag /flp:logfile="c:/Users/wiesl/Downloads/log2.log"

ilspycmd c:\Users\wiesl\Downloads\mk2\WalletWasabi.Fluent.dll > c:\Users\wiesl\Downloads\WalletWasabi.Fluent.dll.out2.txt
```

**Expected Behavior**:

The compilation output is same every time published.

**Actual Behavior**:

The compilation output is not the same every time published.

image

### PR DESCRIPTION
**Pull request by chsienki**
Make analyzer loading return in a deterministic fashion.

This didn't matter for analyzers but has a visible impact when loading multiple generators from the same assembly: given a random order of load, the order in which trees is appended to the compilation can change, leading to different PE output for the same inputs.

Fixes #52035

### CODE REVIEW

**Comment by chsienki** [comment]
@dotnet/roslyn-compiler for review please :)

File: src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs [hunk 1]
```diff
@@ -391,6 +391,77 @@ public class Generator : ISourceGenerator
...
         }
 
+        [Fact]
+        [WorkItem(52035, "https://github.com/dotnet/roslyn/issues/52035")]
+        public void TestLoadedAnalyzerOrderIsDeterministic()
+        {
+            AnalyzerFileReference reference = CreateAnalyzerFileReference(Assembly.GetExecutingAssembly().Location);
+
+            var csharpAnalyzers = reference.GetAnalyzers(LanguageNames.CSharp).Select(a => a.GetType().FullName).ToArray();
+            Assert.Equal(4, csharpAnalyzers.Length);
```
Comment (jaredpar) [inline src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs:401]: This test is only meaningful if the analyzers are emitted in non-alphabetical order. Think we should add a comment on the definitions to indicate that maintaining the existing order is meaningful to tests. Not a strong guard but other than inlining them here not easy to add a strong guard.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs [hunk 2]
```diff
@@ -347,7 +347,7 @@ private sealed class Extensions<TExtension>
             private readonly bool _allowNetFramework;
             private ImmutableArray<TExtension> _lazyAllExtensions;
             private ImmutableDictionary<string, ImmutableArray<TExtension>> _lazyExtensionsPerLanguage;
-            private ImmutableDictionary<string, ImmutableHashSet<string>>? _lazyExtensionTypeNameMap;
+            private ImmutableSortedDictionary<string, ImmutableSortedSet<string>>? _lazyExtensionTypeNameMap;
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:350]: This is a map from language identifier to the set of analyzer / generator type names correct? Can this dictionary ever have more than two keys?

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs (hunk 2 above)
Comment (chsienki) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:350]: Yes, the attribute is actually just a string, so can contain arbitrary values. In the generator tests we have a generator that targets F# to make sure its exercised correctly (and doesn't show up when you filter for CSharp or VB)

Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:350]: It just reminds me of a performance quip I heard a few times. Essentially if you have less than ~10 items or so then you're better off just using an array vs. a map. Not a request for this PR more wanted to make sure I understood everything correctly. 

@sharwell FYI but doubt it meaningfully contributes to performance

File: src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs:401]: I feel like it would be good if we could have a test resource of some kind (i.e. a helper that emits an assembly out to the temp folder which contains some generators) and test the order on that. It feels a little brittle to have to adjust these tests when a new generator is declared in the unit tests source. However, I don't feel strongly about it.

Comment (chsienki) [reply src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs:401]: @RikkiGibson  Yeah, I think we should probably split it up, but I think I'll defer it to the new generator work we're doing down the line, as we'll have a bunch of churn anyway.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs (hunk 2 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:350]: I don't believe this one has been showing up. Also, keep in mind that both `ImmutableDictionary<TKey, TValue>` and `ImmutableHashSet<T>` are sorted - as long as the equality comparer produces deterministic hash codes the result will be deterministic.

**Review by RikkiGibson — APPROVED** [review]

**Comment by wieslawsoltes** [comment]
In what version of .net sdk will this PR be included?

**Comment by RikkiGibson** [comment]
I think it's going into .NET 6 Preview 4.
