### PR TITLE
Fix params array argument operation

### LINKED ISSUE #8520: Opening a C# MVC project crashes Visual Studio due to a null ref in Analyzer core.
Similar to #8511 but a different bug altogether.

1. pull changes from #8517
2. build locally
3. open devenv in RoslynDev hive and open an existing C# MVC proj (or open a new proj).

**Result**: VS crashes due to a null ref.

**Notes**: 

- Repro could be hidden by #8511. So you'd need #8517 to get past it. 
- Dump and symbols at \\\\&lt;internal-fileshare&gt;\public\balajik\dumps\8520

`AnalyzerContextInfo.cs`:
```C#
        public AnalysisContextInfo(Compilation compilation, IOperation operation) :
            this(compilation: compilation, operation: operation, symbol: null, tree: operation.Syntax.SyntaxTree, node: operation.Syntax)
        {
        }

operation = {Microsoft.CodeAnalysis.Semantics.IntegerLiteral}
operation.Syntax = null
operation.Syntax.SyntaxTree = null ref.
```
~~~
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C# 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 770	C#
 	[Resuming Async Method]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo.AnalysisContextInfo(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.Semantics.IOperation operation) Line 45	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationAction(Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction operationAction, Microsoft.CodeAnalysis.Semantics.IOperation operation, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 520	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActions(Microsoft.CodeAnalysis.Semantics.IOperation operation, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 1024	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActions(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Semantics.IOperation> operationsToAnalyze, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 1006	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteBlockActionsCore<Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalyzerAction, Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction, Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData, Microsoft.CodeAnalysis.Semantics.IOperation, int>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalyzerAction> startActions, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction> actions, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction> endActions, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.SyntaxNode declaredNode, Microsoft.CodeAnalysis.ISymbol declaredSymbol, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Semantics.IOperation> executableBlocks, System.Func<System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Semantics.IOperation>, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Semantics.IOperation>> getNodesToAnalyze, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Func<Microsoft.CodeAnalysis.SyntaxNode, int> getKind, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.BlockAnalyzerStateData<Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData> analyzerStateOpt, bool isGeneratedCode) Line 728	C#
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationBlockActions(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalyzerAction> operationBlockStartActions, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction> operationBlockActions, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalyzerAction> operationBlockEndActions, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.SyntaxNode declaredNode, Microsoft.CodeAnalysis.ISymbol declaredSymbol, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Semantics.IOperation> operationBlocks, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Semantics.IOperation> operations, Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxReference declaration, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCode) Line 595	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference decl, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool shouldExecuteSyntaxNodeActions, bool shouldExecuteOperationActions, bool shouldExecuteCodeBlockActions, bool shouldExecuteOperationBlockActions, bool isInGeneratedCode, System.Threading.CancellationToken cancellationToken) Line 1564	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCodeSymbol, System.Threading.CancellationToken cancellationToken) Line 1401	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessSymbolDeclared(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 831	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventCore(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 789	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEvent(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 778	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 765	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 700	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecutePrimaryAnalysisTaskAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool usingPrePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 359	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.AttachQueueAndProcessAllEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 288	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken) Line 685	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync.AnonymousMethod__1() Line 575	C#
~~~

### PR DESCRIPTION
**Pull request by genlu**
The bug causes the Syntax for an `IArgument` of params array kind with only one element to be null. I have manually verified that this fixed #8520.

@JohnHamby @balajikris @srivatsn @davkean @dotnet/roslyn-interactive

### CODE REVIEW

File: src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTestAnalyzer.cs [hunk 1]
```diff
@@ -1303,4 +1304,93 @@ public sealed override void Initialize(AnalysisContext context)
...
+    
+    public class NullOperationSyntaxTestAnalyzer : DiagnosticAnalyzer
+    {
+        private const string ReliabilityCategory = "Reliability";
+
+        // We should not see this warning triggered by any code
+        public static readonly DiagnosticDescriptor NullOperationSyntaxDescriptor = new DiagnosticDescriptor(
+            "NullOperationSyntax",
+            "null operation Syntax found",
+            "An IOperation with Syntax property of value null is found",
```
Comment (genlu) [inline src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTestAnalyzer.cs]: I couldn't create a simplified repro for the MVC template project, so have to came up with this to test if `Syntax == null`.

**Comment by genlu** [comment]
Right now I only fixed and tested C#, I will make sure VB works as well later today.

**Comment by genlu** [comment]
@jaredpar There's an IO error for prtest/determinism
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_determinism/76/

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 2]
```diff
@@ -184,13 +184,15 @@ private static IExpression CreateParamArray(IParameterSymbol parameter, Immutabl
...
+
                 for (int index = firstArgumentElementIndex; index < boundArguments.Length; index++)
                 {
-                    paramArrayArguments.Add(boundArguments[index]);
+                    builder.Add(boundArguments[index]);
                 }
+                var paramArrayArguments = builder.ToImmutableAndFree();
 
-                return new ArrayCreation(arrayType, paramArrayArguments.ToImmutableAndFree(), boundArguments.Length - 1 > firstArgumentElementIndex ? boundArguments[firstArgumentElementIndex].Syntax : null);
+                return new ArrayCreation(arrayType, paramArrayArguments, paramArrayArguments.Length > 0 ? paramArrayArguments[0].Syntax : null);
```
Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: I tried to create a SynxtaxList instead of using he first params array element for it's Syntax, but it doesn't have a location. @srivatsn Is there a way to solve this? 
```cs
var argumentList = SyntaxFactory.List<SyntaxNode>(paramArrayArguments.Select(expression => expression.Syntax));
```

Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: If there is no actual syntax available for the argument (because the paramarray is empty), dropping in the syntax node for the invocation is probably good enough for now.

**Comment by jaredpar** [comment]
@genlu you can ignore the determinism failure.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 2 above)
Comment (srivatsn) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: If I understand Gen correctly - if there's code like `Foo(regularParam, paramsParam1, paramsParam2)` the syntaxtree will only have one SyntaxList for all the arguments and so for this operation what would be the syntax to return - paramsParam1's syntax or a conjured up SyntaxList(paramsParam1, paramsParam2)? 

I don't know if we conjure up new syntax node anywhere for the operation trees - if we don't I wouldn't start doing that now.

Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Yes, what you described is the current behavior for non-empty params array Syntax property. And for empty ones, I wiil change it to provide the invocation node as @JohnHamby suggested.

So @srivatsn you are saying the current behavior is reasonable and we shouldn't change it?

Comment (srivatsn) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Yes

**Comment by genlu** [comment]
@davkean Signed off in person. So I'm merging this.
