### PR TITLE
Fixed incorrect offer to interpolate string if used string.Format with named arguments.

### LINKED ISSUE #19162: Incorrect offer to interpolate string
**Version Used**: 
Current bits
**Steps to Reproduce**:

1.  paste csharp code
```c#
    class Program
    {
        static void Main(string[] args)
        {
            string.Format(arg0: "test", arg1: "also", format: "This {0} $${2} works");
        }
    }
```
2. place carat at $$
3.  Ctrl + dot

**Expected Behavior**:
No offer to interpolate string

**Actual Behavior**:
image

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**

Incorrect offer to interpolate string if used string.Format with named arguments.

**Bugs this fixes:**
Fixes #19162

**Workarounds, if any**
Don't use this refactoring for string.Format with named arguments.

**Risk**
Low

**Performance impact**

**Is this a regression from a previous update?**
No
**Root cause analysis:**
Doesn't implemented support for string.Format with named arguments

**How was the bug found?**

customer reported

### CODE REVIEW

File: src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 1]
```diff
@@ -13,5 +13,15 @@ internal partial class CSharpConvertPlaceholderToInterpolatedStringRefactoringPr
...
             => SyntaxFactory.ParseExpression("$" + text) as InterpolatedStringExpressionSyntax;
+
+        protected override string GetArgumentName(ArgumentSyntax argument)
+        {
+            if (argument == null || argument.NameColon == null)
+            {
+                return null;
+            }
+
+            return argument.NameColon.Name.Identifier.Text;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: nit: consider : => argument?.NameColon?.Name.Identifier.Text

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 2]
```diff
@@ -146,6 +148,28 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
...
+
+        private TArgumentSyntax GetFormatArgument(SeparatedSyntaxList<TArgumentSyntax> arguments)
+        {
+            var index = arguments.IndexOf(argument => GetArgumentName(argument) == StringFormatArguments.FormatArgumentName);
+            return index >= 0 ? arguments[index] : arguments[0];
+        }
+
+        private TArgumentSyntax GetArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, int index)
+        {
+            if (arguments.Count > 4)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: needs explanation.

File: src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: Also, use ISyntaxFactsService.  It already has GetNameForArgument

Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: (can be used directly from base class).

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 2 above)
Comment (zaytsev-victor) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: if argument more than 4 it means that used the following overload ```String.Format(String format, params Object[] args)``` without using named arguments. So we 100% sure in that case that we have no named arguments.

**Comment by zaytsev-victor** [comment]
@CyrusNajmabadi, should we suggest refactoring in this case:
```csharp
void Foo()
{
    string.Format("{0} string", "test");
}
```
?
It will produce a error CS0201

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: i meant: needs explanation in the code (i.e. add a comment) :)

**Comment by CyrusNajmabadi** [comment]
> should we suggest refactoring in this case:

I would be ok with that.  I would also be ok with it not being shown :)

**Comment by sharwell** [comment]
@zaytsev-victor

> should we suggest refactoring in this case:

We could always emit this as `_ = $"..."` (discard). Another option would be allowing this code fix to result in the error, providing a separate general code fix for CS0201 which assigns the value either to a discard or a new variable.

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 3]
```diff
@@ -246,5 +271,19 @@ private class ConvertToInterpolatedStringCodeAction : CodeAction.DocumentChangeA
...
             }
         }
+
+        private static class StringFormatArguments
+        {
+            public const string FormatArgumentName = "format";
+
+            public const string ArgsArgumentName = "args";
+
+            public static readonly Dictionary<int, string> ParamsArgumentNames = new Dictionary<int, string>
```
Comment (sharwell) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: :bulb: If you are just going to index into it (which the code currently is doing), we can benefit from both immutability and performance by changing this to `ImmutableArray<string>`:

```csharp
public static readonly ImmutableArray<string> ParamsArgumentNames =
  ImmutableArray.Create("", "arg0", "arg1", "arg2");
```

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 4]
```diff
@@ -146,6 +146,31 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
             return document.WithSyntaxRoot(newRoot);
         }
 
+        private string GetArgumentName(TArgumentSyntax argument, ISyntaxFactsService syntaxFactsService)
+            => syntaxFactsService.GetNameForArgument(argument);
+
+        private SyntaxNode GetParamsArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, ISyntaxFactsService syntaxFactsService)
+        {
+            var i = arguments.IndexOf(argument => GetArgumentName(argument, syntaxFactsService) == StringFormatArguments.ArgsArgumentName);
```
Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: How will this work in a case-insensitive language like Visual Basic?

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 5]
```diff
@@ -146,6 +146,31 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
...
+            return i >= 0 ? arguments[i] : arguments[1];
+        }
+
+        private TArgumentSyntax GetFormatArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, ISyntaxFactsService syntaxFactsService)
+        {
+            var index = arguments.IndexOf(argument => GetArgumentName(argument, syntaxFactsService) == StringFormatArguments.FormatArgumentName);
```
Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: How will this work in a case-insensitive language like Visual Basic?

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 6]
```diff
@@ -146,6 +146,31 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
...
+        }
+
+        private TArgumentSyntax GetArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, int index, ISyntaxFactsService syntaxFactsService)
+        {
+            if (arguments.Count > 4)
+            {
+                return arguments[index];
+            }
+
+            return arguments.FirstOrDefault(argument => GetArgumentName(argument, syntaxFactsService) == StringFormatArguments.ParamsArgumentNames[index]) ?? arguments[index];
```
Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: How will this work in a case-insensitive language like Visual Basic?

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 7]
```diff
@@ -146,6 +146,27 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
...
         }
 
+        private string GetArgumentName(TArgumentSyntax argument, ISyntaxFactsService syntaxFactsService)
+            => syntaxFactsService.GetNameForArgument(argument);
+
+        private SyntaxNode GetParamsArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, ISyntaxFactsService syntaxFactsService)
+        => arguments.FirstOrDefault(argument => string.Equals(GetArgumentName(argument, syntaxFactsService), StringFormatArguments.FormatArgumentName, StringComparison.OrdinalIgnoreCase)) ?? arguments[1];
+
+        private TArgumentSyntax GetFormatArgument(SeparatedSyntaxList<TArgumentSyntax> arguments, ISyntaxFactsService syntaxFactsService)
+            => arguments.FirstOrDefault(argument => string.Equals(GetArgumentName(argument, syntaxFactsService), StringFormatArguments.FormatArgumentName, StringComparison.OrdinalIgnoreCase)) ?? arguments[0];
```
Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: In VB we want the comparison to be case-insensitive, but I believe we want a case sensitive comparison for C# correct?

Comment (zaytsev-victor) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: @jmarolf Since ```String.Format("{0}", ARg0: 1)``` is incorrect syntax 'convert to interpolate string' refactoring wouldn't be suggested

Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: Just tried it with your changes.  You are correct.
