### PR TITLE
Properly escape ref path names that contain equals

### LINKED ISSUE #71022: Equals sign (`=`) no longer valid in a project name with .net8.0
### Description

With the change to .net8.0 the equals sign (`=`) is no longer valid as part of a file name. 
It was with valid .net7.0 MAUI project and is with other .net8.0 project types.

### Steps to Reproduce

1. Create a File>New MAUI App that includes a `=` sign as part of the name and targets .net8.0
2. Try and build the generated project.
3. See it fails to build

Repeat but target net7.0 and see that it builds without issue.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

.net8.0

### Did you find any workaround?

No workaround, other than don't use this character.

Ok, admittedly, this is a super edge case and I've never seen this character used in a real project but it raises a bunch of questions and concerns:

- Was this deliberate?
  - If so, why?
  - Where is it documented?
- If not deliberate, why was this code changed?
- Are there other characters that are no longer supported?
- Can you please provide an updated list of supported characters as part of a project name in a .NET MAUI app; And explain why it's different from other projects?

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jaredpar**
The `Csc` task was passing references that contains `=` in the paths directly to `/reference` commands. 

```xml
<Reference Include="c:\users\a=b\util.dll" />
```

Was resulting in a `/reference:c:\users\a=b\util.dll` argument being passed to the compiler. That is interpreted as an alias reference due to the `=` instead of a pure path. This PR changes the MSBuild task to properly escape such paths by surrounding them in quotes (prevents them from being treated as aliases).

closes #71022

### CODE REVIEW

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs [hunk 1]
```diff
@@ -110,6 +117,42 @@ internal void AppendSwitchAliased(string switchName, string alias, string parame
...
+        /// Appends a switch with a value that is force quoted. This will quote as if <see cref="CommandLineBuilder.IsQuotingRequired(string)"/>
+        /// returns true for <paramref name="parameter"/>. That means even simple values will be quoted.
+        /// </summary>
+        internal void AppendSwitchForceQuoted(string switchName, string parameter)
+        {
+            AppendSwitch(switchName);
+            _isQuotingRequired = true;
+            try
+            {
+                AppendTextWithQuoting(parameter);
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:148]: Despite the method name saying it will append with quoting the implementation is append with maybe quoting. Have to override `IsQuotingRequired` to force quoting to occur here.

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs [hunk 2]
```diff
@@ -110,6 +117,42 @@
...
+                _isQuotingRequired = false;
+            }
+        }
+
+        /// <summary>
+        /// Appends a switch with a value that is force quoted. This will quote as if <see cref="CommandLineBuilder.IsQuotingRequired(string)"/>
+        /// returns true for <paramref name="parameter"/>. That means even simple values will be quoted.
+        /// </summary>
+        internal void AppendSwitchForceQuoted(string switchName, string parameter)
+        {
```
Comment (jcouv) [inline src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:143]: Can we assert that `_isQuotingRequired` isn't set here?

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs [hunk 3]
```diff
@@ -110,6 +117,42 @@
...
+            {
+                _isQuotingRequired = false;
+            }
+        }
+
+        /// <summary>
+        /// Appends a switch with a value that is force quoted. This will quote as if <see cref="CommandLineBuilder.IsQuotingRequired(string)"/>
+        /// returns true for <paramref name="parameter"/>. That means even simple values will be quoted.
+        /// </summary>
+        internal void AppendSwitchForceQuoted(string switchName, string parameter)
```
Comment (jcouv) [inline src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:142]: >AppendSwitchForceQuoted [](http://example.com/codeflow?start=22&length=23)

nit: is there a reason to use a different naming convention than method above (`Append...WithForceQuoting`)?

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs [hunk 4]
```diff
@@ -110,6 +117,42 @@
             AppendTextWithQuoting(parameter);
         }
 
+        /// <summary>
+        /// Appends a switch with a value that is force quoted. This will quote as if <see cref="CommandLineBuilder.IsQuotingRequired(string)"/>
+        /// returns true for <paramref name="parameter"/>. That means even simple values will be quoted.
+        /// </summary>
+        internal void AppendTextWithForceQuoting(string parameter)
```
Comment (jcouv) [inline src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:124]: Is this method used?

File: src/Compilers/Core/MSBuildTaskTests/TestUtilities/SimpleTaskItem.cs [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System;
+using System.Collections;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using ICSharpCode.Decompiler.Metadata;
```
Comment (jcouv) [inline src/Compilers/Core/MSBuildTaskTests/TestUtilities/SimpleTaskItem.cs:11]: Some unnecessary usings

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4) with some nits

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 6]
```diff
@@ -2622,6 +2622,68 @@ public void ParseReferences()
             // TODO: multiple files, quotes, etc.
         }
 
+        [Fact]
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:2625]: Consider linking the work item in the new tests.

```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/71022")]
```

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 7]
```diff
@@ -2622,6 +2622,68 @@ public void ParseReferences()
...
+        public void ParseReferencesAlias()
+        {
+            Assert.True(parseRef(@"/r:a=util.dll") is
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:2628]: Why not `Assert.Equal`? Seems like that would give better error messages in case it fails.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 8]
```diff
@@ -2622,6 +2622,68 @@ public void ParseReferences()
...
+            });
+
+            Assert.True(parseRef(@"/r:""c:\users\app=exe\util.dll""") is
+            {
+                Reference: @"c:\users\app=exe\util.dll",
+                Properties.Aliases: [],
+                Properties.EmbedInteropTypes: false
+            });
+
+            Assert.True(parseRef(@"/r:a=b=util.dll") is
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:2649]: Consider also testing
```
/r:"a=b"=util.dll
/r:a"b=util.dll"
/r:"a"="util.dll"

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs [hunk 9]
```diff
@@ -17,6 +17,13 @@ namespace Microsoft.CodeAnalysis.BuildTasks
     /// </summary>
     public class CommandLineBuilderExtension : CommandLineBuilder
     {
+        private bool _isQuotingRequired;
+
+        protected override bool IsQuotingRequired(string parameter) => 
+            _isQuotingRequired
+            ? true
+            : base.IsQuotingRequired(parameter);
```
Comment (jjonescz) [inline src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:25]:
```suggestion
        protected override bool IsQuotingRequired(string parameter)
            => _isQuotingRequired || base.IsQuotingRequired(parameter);
```

File: src/Compilers/Core/MSBuildTaskTests/CscTests.cs [hunk 10]
```diff
@@ -568,5 +568,69 @@ public void CommandLineArgs2()
...
+                TaskTestUtil.AssertCommandLine(csc, engine, [.. args, "/out:test.dll", "/target:library", "test.cs"]);
+            }
+        }
+
+        [Fact]
+        public void ReferenceErrors()
+        {
+            parseRef(@"util.dll", "a=b");
+            parseRef(@"util.dll", "a b");
+            parseRef(@"util.dll", "a;b");
```
Comment (jjonescz) [inline src/Compilers/Core/MSBuildTaskTests/CscTests.cs:619]: Consider testing alias containing `"`.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:2628]: Couldn't find a good way to use pattern matching and `Assert.Equal`.

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:142]: The naming convention for these methods is roughly `Append(Switch|Text)?(QuoteStlye)?(IfNotNull)?`. This type is extending `CommandLineBuilder` where conventions like this are established. The current form is matching the style that I see there. 

Consider as an example `CommandLineBuilder.AppendSwitchUnquotedIfNotNull`.

File: src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs:143]: I just need to be calling `AppendTextWithForceQuoting`.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 8 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:2649]: Unescaped quotes are just deleted by the command line parser (historical reasons I cant' explain. So in these cases the quotes don't really impact the output. Not sure if you were aware of that or not when posting the cases here. Added both these versions and the ones where quotes are escaped.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: Hand coded a custom `assert` method for this test.

**Review by jjonescz — APPROVED** [review]
