### PR TITLE
Fix .editorconfig rule dotnet_style_explicit_tuple_names works the same way for true and false

### LINKED ISSUE #27407: EditorConfig: rule dotnet_style_explicit_tuple_names works the same way for true and false
**Version Used**: Visual Studio 15.8.0 Preview 2.0 [27729.1.d15.8]

**Steps to Reproduce**:

1. Create new Console App (.NET Framework 4.7.2) C# project
2. Add to Program.cs to Main method following code:
`// dotnet_style_explicit_tuple_names = true`
`(string name, int age) customer1 = ("Ilya", 22);`
`var name1 = customer1.name;`
` `
`// dotnet_style_explicit_tuple_names = false`
`(string name, int age) customer2 = ("Ilya", 22);`
`var name2 = customer2.Item1;`
3. Add .editorconfig to project:
`root = true`
` `
`[*]`
`dotnet_style_explicit_tuple_names = false:warning`

**Expected Behavior**: `var name2 = customer2.Item1;` is not underlined as warning 
and `var name1 = customer1.name;` is underlined as warning

**Actual Behavior**: `var name2 = customer2.Item1;` is underlined as warning 
and `var name1 = customer1.name;` is not underlined as warning

**Notes**:
* if you change in .editorconfig `dotnet_style_explicit_tuple_names = false:error`
then `var name2 = customer2.Item1;` underlined as error
* if you change in .editorconfig `dotnet_style_explicit_tuple_names = true:error`
then `var name2 = customer2.Item1;` again underlined as error
* the same behavior for Console App (.NET Framework 4.7.2) VB project

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/Ec0n8a7OLAlJp3IdCKtK3lsBfcgkXo26B7AWvMlx9LoYnA?e=RY0eYs)

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #27407.
--
After discussing with @sharwell, the rule "dotnet_style_explicit_tuple_names" at the moment is intended to only be enforced one way (i.e. no diagnostic should be reported if rule is configured to false).

### CODE REVIEW

File: src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -49,7 +49,7 @@ private void AnalyzeOperation(OperationAnalysisContext context)
             var field = fieldReferenceOperation.Field;
             if (field.ContainingType.IsTupleType)
             {
-                if (field.CorrespondingTupleField.Equals(field))
+                if (option.Value && field.CorrespondingTupleField.Equals(field))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs]: it would be better to check this right after getting the option.  with a comment explaining things.

Comment (allisonchou) [reply src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs]: Thanks, fixed!

File: src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -37,35 +37,39 @@ private void AnalyzeOperation(OperationAnalysisContext context)
                 return;
             }
 
+            // We only create a diagnostic if the option's value is set to true.
             var option = optionSet.GetOption(CodeStyleOptions.PreferExplicitTupleNames, context.Compilation.Language);
-            var severity = option.Notification.Severity;
-            if (severity == ReportDiagnostic.Suppress)
+            if (option.Value)
             {
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs]: much much simpler (for diff purposes) to just have:

```
if (!option.Value)
{
    return;
}
```

Comment (allisonchou) [reply src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs]: That's a good point -- cleaned it up :)

**Comment by sharwell** [comment]
Can we get a test added for this?

**Comment by allisonchou** [comment]
Added tests; please let me know if there are any possible improvements!

**Comment by allisonchou** [comment]
Retest windows_release_unit64_prtest please
