### PR TITLE
Avoid renaming methods that don't change return type

### LINKED ISSUE #33082: 'Make method async' breaks overridden methods
**Version Used**: VS 2019 Preview 2.1

**Steps to Reproduce**:

```C#
partial class MyPage : Page
{
    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        await Task.Delay(100);
    }
}
```

**Actual Behavior**:
1. 'Make method async' is offered that changes the return type and renames the method.
2. 'Make method async (stay void) is offered that renames the method.

**Expected Behavior**:
1. Should not be offered as it is not really an option for an overridden method.
2. That is the quick fix I was looking for, but it should not rename the method as it breaks the override.

#20348

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #33082

### CODE REVIEW

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs [hunk 1]
```diff
@@ -93,17 +95,35 @@ private bool IsLikelyEntryPointName(string name, Document document)
...
+                    keepVoid, document, node, methodSymbolOpt, knownTypes, cancellationToken).ConfigureAwait(false);
             }
             else
             {
                 return await AddAsyncTokenAsync(
-                    keepVoid, document, methodSymbolOpt, node, cancellationToken).ConfigureAwait(false);
+                    keepVoid, document, methodSymbolOpt, knownTypes, node, cancellationToken).ConfigureAwait(false);
+            }
+
+            static bool NeedsRename(AbstractMakeMethodAsynchronousCodeFixProvider @this, IMethodSymbol methodSymbol, bool keepVoid, in KnownTypes knownTypes)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: having a static local function that you pass @this to just seems overwrought.  Can you just make a normal instance method in the type?  Since this is all one feature, it seems totally clear to have a helpe rmethod without needing to make it scoped to this one method.

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs [hunk 2]
```diff
@@ -93,17 +95,35 @@ private bool IsLikelyEntryPointName(string name, Document document)
...
             var methodSymbolOpt = semanticModel.GetDeclaredSymbol(node) as IMethodSymbol;
+            var compilation = await document.Project.GetCompilationAsync(cancellationToken).ConfigureAwait(false);
+            var knownTypes = new KnownTypes(compilation);
 
             bool isOrdinaryOrLocalFunction = methodSymbolOpt.IsOrdinaryMethodOrLocalFunction();
-            if (isOrdinaryOrLocalFunction && !methodSymbolOpt.Name.EndsWith(AsyncSuffix) && !isEntryPoint)
+            if (isOrdinaryOrLocalFunction
+                && !methodSymbolOpt.Name.EndsWith(AsyncSuffix)
+                && !isEntryPoint
+                && NeedsRename(this, methodSymbolOpt, keepVoid, in knownTypes))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: alternatively, move the other checks into NeedsRename.  Then the 'if' statement is a bit clearer about whats going on.

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs (hunk 1 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: I'm going to keep this _mostly_ so I can see how I feel about it after some time passes.

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: Updated

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: SGTM.

File: src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs [hunk 3]
```diff
@@ -93,17 +95,49 @@ private bool IsLikelyEntryPointName(string name, Document document)
...
+                if (methodSymbol.ReturnsVoid)
+                {
+                    return !keepVoid;
+                }
+                else
+                {
+                    return !@this.IsAsyncReturnType(methodSymbol.ReturnType, knownTypes);
+                }
             }
         }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs]: thanks!  i like this :)
