### PR TITLE
Fix couple of bugs in the analyzer driver

### LINKED ISSUE #4745: namespace declaration syntax node actions are called multiple times
I just noticed that syntax node actions for NamespaceDeclarationSyntax nodes are called multiple times if the namespace has a qualified name. Repro:

```csharp
using System.Diagnostics;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.CSharp;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class TestAnalyzer : DiagnosticAnalyzer
{
    public const string DiagnosticId = "Foo";
    private const string Title = "Foo";
    private const string MessageFormat = "Foo";
    private const string Category = "Foo";
    private const string Description = "Foo";
    private const string HelpLink = "http://foo.bar";

    private static readonly DiagnosticDescriptor Descriptor =
        new DiagnosticDescriptor(DiagnosticId, Title, MessageFormat, Category, DiagnosticSeverity.Warning, true, Description, HelpLink);

    private static readonly ImmutableArray<DiagnosticDescriptor> supportedDiagnostics =
        ImmutableArray.Create(Descriptor);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
    {
        get
        {
            return supportedDiagnostics;
        }
    }

    public override void Initialize(AnalysisContext context)
    {
        context.RegisterSyntaxNodeAction(this.HandleNamespaceDeclaration, SyntaxKind.NamespaceDeclaration);
    }

    private void HandleNamespaceDeclaration(SyntaxNodeAnalysisContext context)
    {
        Debug.WriteLine("Hit");
    }
}
```
Testcode:
```csharp
namespace Foo.Bar.FooBar { }
```

This will print "Hit" 3 times. The number of calls is the same as the number of identifiers in the name of the namespace declaration.
Im using roslyn 1.0.

### LINKED ISSUE #5463: VB code analyzer doesn't analyze ObjectCreationExpression node in VB when declaring in a named field
@michaelcfanning 

See reproducing code in
https://github.com/qinxgit/roslyn-analyzers-bug

Steps of Repro:
Download the code from the link above, build, and DEBUG the test case TestVBFieldDeclaration from Test Explorer in VS2015.

Expected:
In the debug output window, there should be a line printed:

The ObjectCreationExpression node is analyzed

Actual:
No such a line is printed.

Analysis:
The analyzed code is like this:
Imports System.Xml

Namespace TestNamespace
    Class TestClass
        Public doc As New XmlDocument()
        Public Sub Method1()
            Me.doc.XmlResolver = Nothing
        End Sub
    End Class
End Namespace

When register the analysis action like this, it will not have the ObjectCreationExpression analyzed.

context.RegisterCodeBlockStartAction<SyntaxKind>(
                                (c) =>
                                {
                                    c.RegisterSyntaxNodeAction(AnalyzeNode, SyntaxKind.ObjectCreationExpression);
                                });

On the other hand, 
If register like this, it will have it.
context.RegisterSyntaxNodeAction(AnalyzeNode, SyntaxKind.ObjectCreationExpression);

In CSharp, both cases will have the ObjectCreationExpression. 

The behavior is very different.

### PR DESCRIPTION
**Pull request by mavasani**
1. Fixes #5463: VB field and property declarations don't include the "AsClauseSyntax" node in the node's "Initializer" field, which caused us to miss executing the syntax node actions for AsNewClauseSyntax nodes within code blocks. Now we explicitly account for these initializer nodes.

2. Fixes #4745: C# namespace symbols defined by a qualified name such as "X.Y.Z" within "namespace X.Y.Z {}", all have the same declaring syntax reference. So we need to ensure that we don't make duplicate syntax node callbacks for such namespace declaration nodes.

### CODE REVIEW

File: src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb [hunk 1]
```diff
@@ -151,5 +150,29 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
                 SpecializedCollections.EmptyEnumerable(Of SyntaxNode))
         End Function
+
+        Private Shared Function GetInitializerNodes(propertyStatement As PropertyStatementSyntax) As IEnumerable(Of SyntaxNode)
+            Dim parameterInitializers = GetParameterInitializers(propertyStatement.ParameterList)
+            Dim initializer As SyntaxNode = propertyStatement.Initializer
+            If initializer Is Nothing Then
+                initializer = GetAsNewClauseIntializer(propertyStatement.AsClause)
+            End If
+            Return parameterInitializers.Concat(initializer)
```
Comment (JohnHamby) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: Should there be a check for initializer not being Nothing?

File: src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb [hunk 2]
```diff
@@ -151,5 +150,29 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+            If initializer Is Nothing Then
+                initializer = GetAsNewClauseIntializer(variableDeclarator.AsClause)
+            End If
+
+            Return initializer
+        End Function
+
+        Private Shared Function GetAsNewClauseIntializer(asClause As AsClauseSyntax) As ExpressionSyntax
+            Return If(asClause.IsKind(SyntaxKind.AsNewClause),
+                CType(asClause, AsNewClauseSyntax).NewExpression,
```
Comment (JohnHamby) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: Do we have a convention of preferring CType to DirectCast or vice versa?

**Comment by JohnHamby** [comment]
I sign off.

File: src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb (hunk 1 above)
Comment (mavasani) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: We filter out the null nodes while creating the declaration info: http://source.roslyn.io/#Microsoft.CodeAnalysis/DeclarationComputer.cs,16

Otherwise, we need too many null checks across the declaration computation.

File: src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb (hunk 2 above)
Comment (mavasani) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: I am not sure, probably @AlekseyTs has some recommendation.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: We use DirectCast for identity and box/unbox conversions.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: So, in this case, DirectCast is preferred.

Comment (mavasani) [inline src/Compilers/VisualBasic/BasicAnalyzerDriver/VisualBasicDeclarationComputer.vb]: Thanks, I'll clean it up in the next iteration.
