### PR TITLE
Fix MakeFieldReadonly false positive for ref assignments

### LINKED ISSUE #46785: Make field readonly "IDE0044" false positive when used with ref locals
The failing test is added in https://github.com/dotnet/roslyn/pull/45288/

### LINKED ISSUE #57983: IDE0044 "make field readonly" false positive
**Version Used**: VS 17.0.1

**Steps to Reproduce**:

1. Paste the following code:

```csharp
using System.Runtime.CompilerServices;

public class Test
{
    private ulong nextD3D12ComputeFenceValue;

    internal void Repro()
    {
        ref ulong d3D12FenceValue = ref Unsafe.NullRef<ulong>();

        d3D12FenceValue = ref nextD3D12ComputeFenceValue;

        d3D12FenceValue++;
    }
}
```

2. Observe the "make field readonly" code fix on the `nextD3D12ComputeFenceValue` field. Applying that will result in a compiler error, as we're getting a `ref` to that field within `Repro()`, which will not build if the field was readonly.

**Expected Behavior**:

No diagnostics, this code is fine.

**Actual Behavior**:

IDE0044 is produced on that field.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #46785
Fixes #57983

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs [hunk 1]
```diff
@@ -126,6 +126,12 @@ INegatedPatternOperation or
                     ? ValueUsageInfo.ReadWrite
                     : ValueUsageInfo.Write;
             }
+            else if (operation.Parent is ISimpleAssignmentOperation simpleAssignmentOperation &&
+                simpleAssignmentOperation.Value == operation &&
+                simpleAssignmentOperation.IsRef)
+            {
+                return ValueUsageInfo.ReadableWritableReference;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:133]: if you have: `readonly ref int x = ref y` does this count as a read/write ref now?  or just a read-ref?  It should be the latter.  Can  you check, fix if necessary, and add test?

Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:133]: ➡️ Filed #58466 to resolve this comment

Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:133]: Yep, agreed. This case should be readable reference, I'll make the change
