### PR TITLE
Fix KeyNotFound exception in RemoveUnnecessaryInlineSuppressionsDiagn…

### LINKED ISSUE #46047: Opening multiple split C# editors crashes VS
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1116222/opening-multiple-split-c-editors-crashes-vs.html)._

---
[regression] [worked-in:Earlier builds of 16.8.0 Preview 1.0]
1. Open a solution with C# in Visual Studio (16.8.0 Preview 1.0, latest IntPreview build)
1a. as a note, my projects are ASP .NET Core 3.1, if that helps
2. Open multiple .cs files
3. Split editor panes, i.e. snap out an editor window, create SxS windows
4. Keep opening C# editors, also try snapping out more editors

**Expected:** VS continues to function normally
**Actual:** after opening and interacting with a few editor tabs, Visual Studio will crash

As a general note, the latest 16.7/16.8 IntPreviews have significantly regressed basic features of Visual Studio. I have already reported issues with essential features of the editor and language service. Now, with this bug, Visual Studio is unusable for my dev work.

---
#### Feedback Bot on 7/16/2020, 10:02 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
…osticAnalyzer

Fixes #46047

#45765 enhanced this analyzer to support detecting unnecessary inline SuppressMessageAttribute suppressions. This led to a regression when processing `idToPragmasMap` for unhandled IDs, which is fixed by this change.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs [hunk 1]
```diff
@@ -265,23 +265,34 @@ void M()
...
+            {
+                Pragmas,
+                SuppressMessageAttributes,
+                PragmasAndSuppressMessageAttributes
+            }
+
             [Theory, CombinatorialData]
-            public async Task TestDoNotRemoveUnsupportedDiagnosticSuppression(bool disable)
+            [WorkItem(46047, "https://github.com/dotnet/roslyn/issues/46047")]
+            public async Task TestDoNotRemoveUnsupportedDiagnosticSuppression(bool disable, TestKind testKind)
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs:277]: The exception was being hit for `TestKind.SuppressMessageAttributes` when there are no pragmas in input.

**Comment by mavasani** [comment]
Thanks @sharwell
