### PR TITLE
Change natural type of UTF-8 string literals to `ReadOnlySpan<byte>` and null terminate the underlying blob.

### LINKED ISSUE #60644: "..."u8 prefers byte[] when it should prefer ReadOnlySpan<byte>
**Version Used**: 
https://github.com/dotnet/roslyn/commit/e79be97e37654f8389f9d0d49bb27d39dd413577

**Steps to Reproduce**:
I understand this is currently "by design", but we should revisit the design.  That u8's natural type is byte[] leads to a variety of problems.

For example, this:
```C#
"abcd"u8.Length
```
allocates a `new byte[4]` just to get the length; if this were instead a span, that allocation would be avoided, and even if C# didn't want to recognize this particular pattern of constString.Length, the JIT can:
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUEZgMwAEO5AwkQN5HlOUWwLkCyAFAJTkC8APnIwApgHdyAJVEQAJgHkYAGwCeAZQAOEGAB5gqhKMFcxkg0YDaAXXJ1yXC6J4ByCC7gOnr4B6+HnFwBjP0cA1zkXcgBfHgA6ABlRGABzBAALAG4iaKA==
It's not uncommon to use const strings for their length like this rather than hardcoding a magic constant by manually counting the bytes/characters, e.g.
```C#
ReadOnlySpan<byte> data = ...;
if (data.Slice("prefix"u8.Length).SequenceEquals(...)) { ... }
```
Requiring a cast to `ReadOnlySpan<byte>` here to do the "right thing" is unexpected and unintuitive.

Same goes for other operations on span, like CopyTo.  You want to be able to use UTF8 const strings to populate things, e.g.
```C#
byte[] data = ...;
"suffix"u8.CopyTo(data.Slice(123));
```
but you really don't want to be allocating a byte[] for "suffix" to achieve that.

It's also unfortunate that overload resolution picks `byte[]` over `ReadOnlySpan<byte>`:
```C#
using System;
public class C
{
    public void M() => N("abcd"u8);
    public void N(ReadOnlySpan<byte> bytes){}
    public void N(byte[] bytes){}
}
```
https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBBmABM3AYUwG9NcL88EAWXAWQAoBKXAXgD5cA5RgIgjAAxgBM+AVwAczANzlKOfHV4AlAKYQRAeRgAbAJ4BlAA4QYAHmD6ALmq5XbAZ2YkAvvIqLaPRg7UBtAF1cP2c3TFcgA===
It's common to add span-based overloads to things that currently accept byte[], and even to add both overloads at the same time (in support of languages that don't support spans), and having overload resolution prefer the more expensive thing is problematic.

cc: @MadsTorgersen

### PR DESCRIPTION
**Pull request by AlekseyTs**
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#natural-type-of-utf8-literals
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#should-utf8-literals-be-null-terminated

Related to #61517
Closes #60644

Test plan https://github.com/dotnet/roslyn/issues/58848

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs [hunk 1]
```diff
@@ -737,14 +737,16 @@ class C
     {
         void M()
         {
-            System.Console.WriteLine(""""""
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs:740]: nit: Just curious, do we know if the BCL is planning to add some Console APIs for `ROS<byte>`?

File: src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs [hunk 2]
```diff
@@ -410,6 +411,39 @@ private bool TryEmitReadonlySpanAsBlobWrapper(NamedTypeSymbol spanType, BoundExp
                 return false;
             }
 
+            if (start is null != length is null)
+            {
+                return false;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs:416]: nit: Consider asserting (unreachable at the moment)

File: src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs [hunk 3]
```diff
@@ -2018,7 +1884,7 @@ static void Main()
 }
 ";
             var comp = CreateCompilation(source, targetFramework: TargetFramework.NetCoreApp, options: TestOptions.DebugExe);
-            CompileAndVerify(comp, expectedOutput: @"Span").VerifyDiagnostics();
+            CompileAndVerify(comp, expectedOutput: @"ReadOnlySpan", verify: Verification.Fails).VerifyDiagnostics();
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs:1887]: Why was IL verification succeeding with `Span` but now fails with `ReadOnlySpan` overload and new natural type?

File: src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs (hunk 1 above)
Comment (stephentoub) [reply src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs:740]: Console's APIs are in terms of text, e.g. string.  Adding bytes-based APIs would require knowing what encoding to use to convert those bytes to text.  It may not be the same encoding of the underlying stream.   If you want to work in terms of bytes, you can always get a Stream and write to that, at which point you're saying you know your bytes are appropriate for the underlying encoding, e.g.
```C#
using Stream s = Console.OpenStandardOutput();
s.Write("hello world"u8);
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs [hunk 4]
```diff
@@ -3066,41 +2928,13 @@ Span<byte> Test()
...
-}
-";
-            var comp = CreateCompilation(source, targetFramework: TargetFramework.NetCoreApp, options: TestOptions.DebugDll);
-            var tree = comp.SyntaxTrees.Single();
-            var model = comp.GetSemanticModel(tree);
-            var node = tree.GetCompilationUnitRoot().DescendantNodes().OfType<ReturnStatementSyntax>().Single().Expression;
-
-            var symbolInfo = model.GetSymbolInfo(node);
-            Assert.Equal("System.Span<System.Byte> System.Span<System.Byte>.op_Implicit(System.Byte[]? array)", symbolInfo.Symbol.ToTestDisplayString());
+            Assert.Null(symbolInfo.Symbol);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs:2931]: Consider also verifying diagnostics

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 5]
```diff
@@ -2613,6 +2613,7 @@ internal static uint GetValEscape(BoundExpression expr, uint scopeOfTheContainin
                 case BoundKind.DefaultExpression:
                 case BoundKind.Parameter:
                 case BoundKind.ThisReference:
+                case BoundKind.UTF8String:
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2616]: > Does ```GetRefEscape``` need to be updated too?

Based on the comment in the method, it is supposed to handle "all the possible cases for anything that is not a strict RValue". I think the literal is a strict RValue.

File: src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs:2931]: > Consider also verifying diagnostics

I think other tests provide enough coverage for diagnostics.

**Comment by AlekseyTs** [comment]
@RikkiGibson, @cston, @dotnet/roslyn-compiler For the second review.

**Review by davidwengier — APPROVED** [review]
Thank you for disabling the analyzer

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 6]
```diff
@@ -73,45 +73,73 @@ public override BoundNode VisitConversion(BoundConversion node)
...
+                result = new BoundObjectCreationExpression(node.Syntax, ctor.AsMember((NamedTypeSymbol)node.Type), utf8Bytes, _factory.Literal(0), _factory.Literal(length));
             }
 
-            var builder = ArrayBuilder<BoundExpression>.GetInstance(bytes.Length);
-            foreach (byte b in bytes)
+            _factory.Syntax = save_Syntax;
+
+            return result;
+
+            BoundExpression createUTF8ByteRepresentation(SyntaxNode resultSyntax, SyntaxNode valueSyntax, string value, ArrayTypeSymbol byteArray, out int length)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs:102]: nit: should 'resultSyntax' and 'valueSyntax' be replaced with a single argument here?

File: src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs [hunk 7]
```diff
@@ -1948,41 +1804,51 @@ static void Main()
...
   IL_0001:  newarr     ""byte""
   IL_0006:  dup
-  IL_0007:  ldtoken    ""<PrivateImplementationDetails>.__StaticArrayInitTypeSize=3 <PrivateImplementationDetails>.77AF778B51ABD4A3C51C5DDD97204A9C3AE614EBCCB75A606C3B6865AED6744E""
+  IL_0007:  ldtoken    ""int <PrivateImplementationDetails>.F3D4280708A6C4BEA1BAEB5AD5A4B659E705A90BDD448840276EA20CB151BE57""
   IL_000c:  call       ""void System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(System.Array, System.RuntimeFieldHandle)""
-  IL_0011:  call       ""System.ReadOnlySpan<byte> System.ReadOnlySpan<byte>.op_Implicit(byte[])""
-  IL_0016:  ret
+  IL_0011:  ldc.i4.0
+  IL_0012:  ldc.i4.3
+  IL_0013:  newobj     ""System.ReadOnlySpan<byte>..ctor(byte[], int, int)""
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs:1816]: I am confused about when we do which of the following in various scenarios:
1. create an array, then create a span referencing it (which we do here)
2. create a span referencing a blob (which we do in some of the other tests)

I expected that for UTF-8 string literals, we would only need to do (2) and not (1). Could you please explain?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs:1816]: >I am confused about when we do which of the following in various scenarios:
>1. create an array, then create a span referencing it (which we do here)
>2. create a span referencing a blob (which we do in some of the other tests)
>
>I expected that for UTF-8 string literals, we would only need to do (2) and not (1). >Could you please explain?

Utilizing a blob is an optimization strategy that is applied by emit layer. It is applied conditionally, including some conditions that aren't related to specific array data.   
This can be observed in ```TryEmitReadonlySpanAsBlobWrapper``` helper. For example:
- Is ```_module.SupportsPrivateImplClass``` true
- Is ```WellKnownMember.System_ReadOnlySpan_T__ctor_Pointer``` constructor available

In the emit layer we are trying to optimize usage of other (non-pointer) constructors and some conversions. The ```WellKnownMember.System_ReadOnlySpan_T__ctor_Pointer``` is not used in any other compiler layers.

In lowering, we are always using a constructor that takes array, start and length. Emit layer might or might not optimize it with a blob. This specific test covers scenario when ```WellKnownMember.System_ReadOnlySpan_T__ctor_Pointer``` is unavailable. Note ```comp.MakeMemberMissing(WellKnownMember.System_ReadOnlySpan_T__ctor_Pointer);``` above. This disable the optimization and the usage of the regular constructor survives.

**Review by RikkiGibson — APPROVED** [review]
LGTM, thanks!
