### PR TITLE
Prevent CodeActions commits during Inline Renames

### LINKED ISSUE #554: An active inline rename session is still active
Ported from TFS WorkItem: **1120490**

------------------------------

**Repro Steps:**

Extract local for all occurrences of **this**. May have to try a few times.

&nbsp;

Module M<BR>&nbsp;&nbsp;&nbsp; Friend Function GetInfoAsync() As Dog<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim expression As ExpressionSyntax = Nothing

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim curr = DirectCast(<FONT style="BACKGROUND-COLOR: #ffff00">expression.Parent</FONT>, ExpressionSyntax)<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If curr Is expression.Parent Then<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Return New Dog(**expression.Parent**.Span)<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Return Nothing<BR>&nbsp;&nbsp;&nbsp; End Function<BR>End Module

Friend Class TextSpan<BR>End Class

Friend Class ExpressionSyntax<BR>&nbsp;&nbsp;&nbsp; Public Property Parent As ExpressionSyntax<BR>&nbsp;&nbsp;&nbsp; Public Property Span As TextSpan<BR>End Class

Friend Class Dog<BR>&nbsp;&nbsp;&nbsp; Public Sub New(span As Object)<BR>&nbsp;&nbsp;&nbsp; End Sub<BR>End Class

------------------------------

**Revisions:**

1) Created By Andrew Casey (ROSLYN) (2/5/2015 5:07:26 PM)

(Dump available, see TFS WorkItem 1120490)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/10/2015 9:15:05 AM)

Can you take a look at this dump and see if you can figure out what's up?

------------------------------

### PR DESCRIPTION
**Pull request by dpoeschl**
Fix #554: This fixes a crash that was caused by invoking a lightbulb
item that caused an Inline Rename session to launch when there's already
an inline rename session active. We now check for inline rename sessions
during lightbulb commit. If an inline rename session is active, we halt
the lightbulb commit and tell the user to complete their rename session.

This only prevents one (but probably the most frequent) manifestation of
a larger problem in which rename is trying to perform a series of
changes to the workspace that can be interrupted by some other feature
applying its changes to the workspace. This larger design problem is
tracked as #681.

### CODE REVIEW

**Comment by dpoeschl** [comment]
@heejaechang @shyamnamboodiripad For now I'm just preventing lightbulb items from being committed while Inline Rename is up (to prevent this actual known crash) while we think through the larger problem. Does this look okay?

File: src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs [hunk 1]
```diff
@@ -86,8 +87,18 @@ public SolutionPreviewResult GetPreviews(Workspace workspace, IEnumerable<CodeAc
...
         }
 
-        public void Apply(Workspace workspace, Document fromDocument, IEnumerable<CodeActionOperation> operations, string title, CancellationToken cancellationToken)
+        public void Apply(Workspace workspace, Document fromDocument, IEnumerable<CodeActionOperation> operations, string title, INotificationService notificationService, CancellationToken cancellationToken)
         {
+            if (_renameService.ActiveSession != null)
+            {
+                if (notificationService != null)
+                {
+                    notificationService.SendNotification(EditorFeaturesResources.CannotApplyOperationWhileRenameSessionIsActive, severity: NotificationSeverity.Error);
```
Comment (Pilchie) [inline src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs]: `notificationService?.SendNotification(...);`

**Comment by Pilchie** [comment]
:shipit:

**Comment by mattwar** [comment]
:+1:

**Comment by shyamnamboodiripad** [comment]
Do you have a story tracking the bigger work item to disallow two consumers from forking a Workspace (per the discussion we had offline). In another offline discussion with Sri and HeeJae, looks like we are going to need that for other cases too... Light bulb will be the main consumer for this right now - but I think this is something we need more generally to avoid problems like this.

File: src/EditorFeatures/Test2/Utilities/TestNotificationService.vb [hunk 2]
```diff
@@ -0,0 +1,33 @@
+﻿' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+Imports Microsoft.CodeAnalysis.Notification
+
+Namespace Microsoft.CodeAnalysis.Editor.UnitTests.Utilities
+    Friend Class TestNotificationService
+        Implements INotificationService
```
Comment (brettfo) [inline src/EditorFeatures/Test2/Utilities/TestNotificationService.vb]: Rather than implement this, you can use the real `EditorNotificationService` and cast to the internal `INotificationServiceCallback` interface which lets you set an `Action<>` `NotificationCallback` to be invoked instead of the real notification getting fired.  `INotificationServiceCallback` was created specifically for testing.

**Comment by dpoeschl** [comment]
@shyamnamboodiripad Yep, #681 (it's also mentioned in the commit comment so people can find it from here in the future). The issue is mostly a placeholder for now, but we can adjust it & fill in the details. I also had some more conversations with @mattwar and the IDE team about this yesterday, so let's combine ideas over at #681.

File: src/EditorFeatures/Test2/Utilities/TestNotificationService.vb (hunk 2 above)
Comment (dpoeschl) [inline src/EditorFeatures/Test2/Utilities/TestNotificationService.vb]: Amusingly, we already had 3 test implementations of this! Will switch to the INotificationServiceCallback approach. Thanks!

**Comment by shyamnamboodiripad** [comment]
@dpoeschl  #681 seems to specifically talk about rename. However, the workspace ownership is a general problem in other scenarios too. For example, when a debug session is active but code is not at a breakpoint we have similar problem where light bulb offers fixes - but fixes silently fail because workspace refuses to apply the changes in this mode. If we had a mechanism to track workspace ownership, then we could just hide the light bulb in such cases / at least avoid failing silently (we could say that debugger owns the workspace and hence a fix can't modify it). I'll add same comment in #681 too.

**Comment by heejaechang** [comment]
:+1:
