### PR TITLE
Ensure placeholders and locals are registered in RefSafetyAnalysis before escape analysis

### LINKED ISSUE #67070: `NullReferenceException` in `RefSafetyAnalysis.GetValEscape`
**Version Used**: 4.5.0-3.23070.7 (5964d1a8) - the version from SDK 7.0.200 shipped with VS 17.5

I got the following stack trace with my project:

```
Process terminated. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringHandlerConversionEscapeScope(BoundExpression expression, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringPlaceholders(ArrayBuilder`1 placeholders, InterpolatedStringHandlerData& interpolationData, BoundExpression receiver, ImmutableArray`1 arguments)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetArgumentPlaceholders(BoundExpression receiverOpt, ImmutableArray`1 arguments)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity, Boolean)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportAndPropagateUnlessCanceled(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression, UInt32)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray`1<Int32>, UInt32, Boolean)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray`1<Int32>, UInt32, Boolean)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression, UInt32)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringHandlerConversionEscapeScope(Microsoft.CodeAnalysis.CSharp.BoundExpression, UInt32)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression, UInt32)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray`1<Int32>, UInt32, Boolean)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray`1<Int32>, UInt32, Boolean)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression, UInt32)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringPlaceholders(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<System.ValueTuple`2<Microsoft.CodeAnalysis.CSharp.BoundValuePlaceholderBase,UInt32>>, Microsoft.CodeAnalysis.CSharp.InterpolatedStringHandlerData ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetArgumentPlaceholders(Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32 ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Immutable.ImmutableArray`1<System.__Canon>)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Analyze(Microsoft.CodeAnalysis.CSharp.CSharpCompilation, Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.BoundNode, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.BoundNode, Boolean, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, Boolean ByRef, InitialState ByRef)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringHandlerConversionEscapeScope(BoundExpression expression, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringPlaceholders(ArrayBuilder`1 placeholders, InterpolatedStringHandlerData& interpolationData, BoundExpression receiver, ImmutableArray`1 arguments)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetArgumentPlaceholders(BoundExpression receiverOpt, ImmutableArray`1 arguments)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
```

I reproduced it on the current main branch at 4641f2bff815fb7743be8aa2bdafe82b74a1f756, and I'm getting an assertion failure:

```
Process terminated. Assertion failed.
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetPlaceholderScope(BoundValuePlaceholderBase placeholder) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 223
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 3432
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 1763
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 1652
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 3583
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringHandlerConversionEscapeScope(BoundExpression expression, UInt32 scopeOfTheContainingExpression) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 1610
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 3616
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeWithUpdatedRules(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 1763
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInvocationEscapeScope(Symbol symbol, BoundExpression receiver, ImmutableArray`1 parameters, ImmutableArray`1 argsOpt, ImmutableArray`1 argRefKindsOpt, ImmutableArray`1 argsToParamsOpt, UInt32 scopeOfTheContainingExpression, Boolean isRefEscape) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 1652
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\Binder.ValueChecks.cs:line 3485
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetInterpolatedStringPlaceholders(ArrayBuilder`1 placeholders, InterpolatedStringHandlerData& interpolationData, BoundExpression receiver, ImmutableArray`1 arguments) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 620
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetArgumentPlaceholders(BoundExpression receiverOpt, ImmutableArray`1 arguments) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 575
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitCall(BoundCall node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 583
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 5908
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 88
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 242
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 216
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 75
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 245
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9588
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 3408
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 245
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9532
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitBlock(BoundBlock node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 231
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 3052
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 245
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 10207
   at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 8235
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Visit(BoundNode node) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 245
   at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, BindingDiagnosticBag diagnostics) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Binder\RefSafetyAnalysis.cs:line 26
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1835
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1044
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 530
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 424
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Dev\GitHub\dotnet\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 139
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

Looks like the NRE is right here:

https://github.com/dotnet/roslyn/blob/4641f2bff815fb7743be8aa2bdafe82b74a1f756/src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs#L221-L225

This is a regression: the project compiles fine on version 4.4.0-6.22580.4 (d7a61210) from SDK 7.0.102

Here is a repro, building the following code causes the exception:

```C#
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApp;

public static class Program
{
    public static void Main()
    {
        var str = new MutableString();

        str.Edit()
           .Append($"[{42}]")
           .Append($"[{"foo".AsSpan()}]");
    }
}

public sealed class MutableString
{
    public Editor Edit()
        => new();

    public readonly ref struct Editor
    {
        public Editor Append([InterpolatedStringHandlerArgument("")] InterpolatedStringHandler handler)
            => this;
    }

    [InterpolatedStringHandler]
    public readonly ref struct InterpolatedStringHandler
    {
        public InterpolatedStringHandler(int literalLength, int formattedCount, Editor editor)
        {
        }

        public void AppendLiteral(string value)
        {
        }

        public void AppendFormatted<T>(T value)
        {
        }

        public void AppendFormatted(ReadOnlySpan<char> value)
        {
        }
    }
}
```

Zip file: [ConsoleApp.zip](https://github.com/dotnet/roslyn/files/10841687/ConsoleApp.zip)

### LINKED ISSUE #67493: No ref safety error reported for switch expression with locals used in switch statement or foreach statement expression
**Version Used**: 
https://github.com/dotnet/roslyn/commit/d17f741546fad2786cbd6394d08619544e53a36d

**Steps to Reproduce**:
```csharp
ref struct R1
{
    public R2 F;
    public R1(ref int i) { F = new R2(ref i); }
}

ref struct R2
{
    ref int _i;
    public R2(ref int i) { _i = ref i; }
}

class Program
{
    static R2 F()
    {
        int i = 0;
        var x = new R1(ref i);
        switch (x switch { { F: R2 y } => y })
        {
            case R2 z:
                return z;
        }
    }
}
```

**Expected Behavior**:
error CS8352: Cannot use variable 'z' in this context because it may expose referenced variables outside of their declaration scope

**Actual Behavior**:
No errors

Similar issue with `switch` expression with locals used in `foreach` statement expression.

### PR DESCRIPTION
**Pull request by cston**
Updates `RefSafetyAnalysis` to ensure that expressions are visited before calling `GetValEscape()`, `GetRefEscape()`, `CheckValEscape()`, or `CheckRefEscape()`, so that the escape scopes of placeholders and locals are registered with the visitor for those calls.

Fixes #67070
Fixes #67493

_The first commit is a port of https://github.com/dotnet/roslyn/commit/bcbb2d7e056217b17afce0a2fabcd6f9a907380c from `release/dev17.5-vs-deps` since that branch has not flowed into `main` yet._

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 1]
```diff
@@ -564,24 +644,90 @@ private void SetPatternLocalScopes(BoundObjectPattern pattern)
...
+                Visit(arg);
             }
-            return new PlaceholderRegion(this, placeholders);
         }
 
         public override BoundNode? VisitCall(BoundCall node)
         {
-            using var _ = GetArgumentPlaceholders(node.ReceiverOpt, node.Arguments);
-            base.VisitCall(node);
+            VisitArgumentsAndGetArgumentPlaceholders(node.ReceiverOpt, node.Arguments);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:730]: >VisitArgumentsAndGetArgumentPlaceholders [](http://example.com/codeflow?start=12&length=40)

The original bug was here. Preceding arguments should be visited before evaluating the escape scope of subsequent placeholders.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 2]
```diff
@@ -564,24 +644,90 @@ private void SetPatternLocalScopes(BoundObjectPattern pattern)
             return null;
         }
 
-        private PlaceholderRegion GetArgumentPlaceholders(BoundExpression? receiverOpt, ImmutableArray<BoundExpression> arguments)
+        public override BoundNode? VisitInterpolatedString(BoundInterpolatedString node)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:647]: >VisitInterpolatedString [](http://example.com/codeflow?start=35&length=23)

Interpolated string handler placeholders were not added correctly in all cases previously which was caught by additional asserts.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 3]
```diff
@@ -192,26 +205,34 @@ public void Dispose()
 
         private (uint RefEscapeScope, uint ValEscapeScope) GetLocalScopes(LocalSymbol local)
         {
-            Debug.Assert(_localEscapeScopes is { });
-            return _localEscapeScopes[local];
+            Debug.Assert(_localEscapeScopes?.ContainsKey(local) == true);
+
+            return _localEscapeScopes.TryGetValue(local, out var scopes)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:210]: >return _localEscapeScopes.TryGetValue(local, out var scopes) [](http://example.com/codeflow?start=12&length=60)

Allow missing locals in release build, even though that case is unexpected.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 4]
```diff
@@ -220,10 +241,33 @@ private void RemovePlaceholderScope(BoundValuePlaceholderBase placeholder)
 
         private uint GetPlaceholderScope(BoundValuePlaceholderBase placeholder)
         {
-            Debug.Assert(_placeholderScopes is { });
-            return _placeholderScopes[placeholder];
+            Debug.Assert(_placeholderScopes?.ContainsKey(placeholder) == true);
+
+            return _placeholderScopes?.TryGetValue(placeholder, out var scope) == true
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:246]: >return _placeholderScopes?.TryGetValue(placeholder, out var scope) == true [](http://example.com/codeflow?start=12&length=74)

Allow missing placeholders in release build, although that case is unexpected.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 5]
```diff
@@ -192,26 +205,37 @@ public void Dispose()
 
         private (uint RefEscapeScope, uint ValEscapeScope) GetLocalScopes(LocalSymbol local)
         {
-            Debug.Assert(_localEscapeScopes is { });
-            return _localEscapeScopes[local];
+            Debug.Assert(_localEscapeScopes?.ContainsKey(local) == true);
+
+            return _localEscapeScopes?.TryGetValue(local, out var scopes) == true
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:210]: >return _localEscapeScopes?.TryGetValue(local, out var scopes) == true [](http://example.com/codeflow?start=12&length=69)

Allow missing locals in release build, although that case is unexpected.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 6]
```diff
@@ -2084,8 +2091,14 @@ bool isRefEscape
                                         _compilation.IsPeVerifyCompatEnabled,
                                         stackLocalsOpt: null))
                     {
+#if DEBUG
+                        CheckVisited(receiver);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2095]: nit: consider marking the method itself with Conditional attribute (and if we do that maybe the method name could be updated to "AssertVisited").

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 7]
```diff
@@ -82,6 +84,11 @@ private static bool InUnsafeMethod(Symbol symbol)
         private Dictionary<LocalSymbol, (uint RefEscapeScope, uint ValEscapeScope)>? _localEscapeScopes;
         private Dictionary<BoundValuePlaceholderBase, uint>? _placeholderScopes;
         private uint _patternInputValEscape;
+#if DEBUG
+        private const int MaxTrackVisited = 100; // Avoid tracking if too many expressions.
+        private readonly HashSet<BoundExpression> _visited;
+        private bool _trackVisited;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:90]: There's an issue with `_trackVisited` (discussed offline)

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 8]
```diff
@@ -101,6 +108,9 @@ private static bool InUnsafeMethod(Symbol symbol)
             // the same depth as parameters, _localScopeDepth is initialized to one less.
             _localScopeDepth = CurrentMethodScope - 1;
             _localEscapeScopes = localEscapeScopes;
+#if DEBUG
+            _visited = new HashSet<BoundExpression>();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:112]: nit: consider using a field initializer to simplify code a bit

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 9]
```diff
@@ -82,6 +84,11 @@ private static bool InUnsafeMethod(Symbol symbol)
         private Dictionary<LocalSymbol, (uint RefEscapeScope, uint ValEscapeScope)>? _localEscapeScopes;
         private Dictionary<BoundValuePlaceholderBase, uint>? _placeholderScopes;
         private uint _patternInputValEscape;
+#if DEBUG
+        private const int MaxTrackVisited = 100; // Avoid tracking if too many expressions.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:88]: Just curious, why put this limit?

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 10]
```diff
@@ -220,9 +240,34 @@ private void RemovePlaceholderScope(BoundValuePlaceholderBase placeholder)
...
+
+#if DEBUG
+        private bool ContainsPlaceholderScope(BoundValuePlaceholderBase placeholder)
+        {
+            if (_placeholderScopes?.ContainsKey(placeholder) == true)
+            {
+                return true;
+            }
+
+            switch (placeholder)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:258]: If I understand properly, we have a few grandfathered exceptions. Consider putting a comment here to that effect (we should strive not to add new ones)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2095]: I've renamed to `AssertVisited()`. I think I'd prefer to leave as conditionally compiled though, so it's clear at the call-sites that this does not affect release builds.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 11]
```diff
@@ -220,9 +240,34 @@ private void RemovePlaceholderScope(BoundValuePlaceholderBase placeholder)
...
-            return _placeholderScopes[placeholder];
+            Debug.Assert(_placeholderScopes?.ContainsKey(placeholder) == true);
+
+            return _placeholderScopes?.TryGetValue(placeholder, out var scope) == true
+                ? scope
+                : CallingMethodScope;
+        }
+
+#if DEBUG
+        private bool ContainsPlaceholderScope(BoundValuePlaceholderBase placeholder)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:248]: nit: this method is only used in asserts, consider renaming this method `AssertContainsPlaceholderScope` and making it void-returning and conditional, with assertions instead of return statements for failure cases.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 9 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:88]: I was concerned about the overhead of creating large dictionaries for verification, for instance in unit tests with long array initializers.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 12]
```diff
@@ -234,17 +279,50 @@ private uint GetPlaceholderScope(BoundValuePlaceholderBase placeholder)
...
         {
 #if DEBUG
-            if (node is BoundValuePlaceholderBase placeholder
-                // CheckValEscapeOfObjectInitializer() does not use BoundObjectOrCollectionValuePlaceholder.
-                // CheckInterpolatedStringHandlerConversionEscape() does not use BoundInterpolatedStringHandlerPlaceholder.
-                && node is not (BoundObjectOrCollectionValuePlaceholder or BoundInterpolatedStringHandlerPlaceholder))
+            if (node is BoundExpression expr)
+            {
+                bool added = MarkVisited(expr);
+                if (!added)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:284]: Is this case (when `MarkVisited` returns false) because a placeholder could appear multiple times within a bound node? 
If so, maybe `MarkVisited` should just skip placeholders.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 13]
```diff
@@ -234,17 +279,50 @@ private uint GetPlaceholderScope(BoundValuePlaceholderBase placeholder)
...
             }
 #endif
             return base.Visit(node);
         }
 
+#if DEBUG
+        private void CheckVisited(BoundExpression expr)
+        {
+            if (expr is BoundValuePlaceholderBase placeholder
+                && placeholder is not BoundCapturedReceiverPlaceholder)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:301]: A comment on BoundCapturedReceiverPlaceholder would be useful (why we have this exception).

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 14]
```diff
@@ -2084,8 +2091,14 @@ bool isRefEscape
...
+#endif
                         // Equivalent to a non-ref local with the underlying receiver as an initializer provided at declaration 
                         receiver = new BoundCapturedReceiverPlaceholder(receiver.Syntax, receiver, _localScopeDepth, receiver.Type).MakeCompilerGenerated();
+#if DEBUG
+                        MarkVisited(receiver);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2103]: Consider removing this call if we end up having `MarkVisited` be a no-op on placeholders.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 15]
```diff
@@ -298,6 +376,9 @@ private void VisitFieldOrPropertyInitializer(BoundInitializer initializer)
         {
             using var _ = new LocalScope(this, node.Locals);
 
+            this.Visit(node.DeclarationsOpt);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:378]: Out-of-scope for this PR, but this made me wonder whether the placeholder discipline could be enforced/factored into the base type, so it would apply to all our bound node visitors.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 16]
```diff
@@ -405,8 +491,15 @@ private void AddLocalScopes(LocalSymbol local, uint refEscapeScope, uint valEsca
...
+            Debug.Assert(_localEscapeScopes?.ContainsKey(local) != true);
+
+            AddOrSetLocalScopes(local, refEscapeScope, valEscapeScope);
+        }
+
+        private void AddOrSetLocalScopes(LocalSymbol local, uint refEscapeScope, uint valEscapeScope)
+        {
             _localEscapeScopes ??= new Dictionary<LocalSymbol, (uint RefEscapeScope, uint ValEscapeScope)>();
-            _localEscapeScopes.Add(local, (refEscapeScope, valEscapeScope));
+            _localEscapeScopes[local] = (refEscapeScope, valEscapeScope);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:501]: This used to only add only, but now can also set. What's the scenario where we need to set the scopes of a local more than once?

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 17]
```diff
@@ -605,6 +703,7 @@ private PlaceholderRegion GetArgumentPlaceholders(BoundExpression? receiverOpt,
             ArrayBuilder<(BoundValuePlaceholderBase, uint)> placeholders,
             in InterpolatedStringHandlerData interpolationData,
             BoundExpression? receiver,
+            int nArgumentsVisited,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:705]: >nArgumentsVisited [](http://example.com/codeflow?start=16&length=17)

nit: consider spelling out "n" to "number" or "count"

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 11 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:248]: I think I'd rather leave as a `bool` returning method where the callers assert.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 6 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: That's okay, but if the method is called "Assert..." then I think it's clear that it's a conditional method. Up to you...

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 12 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:284]: What was the resolution?

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 16 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:501]: > What's the scenario where we need to set the scopes of a local more than once?

I don't think there are valid scenarios where the local is added twice or set twice. A local will be added and set separately though - the local is added when visiting the containing block, and set when visiting the initializer. The callers assert that the local is missing or not missing depending on the context. But the change here, from add to set, was from [https://github.com/dotnet/roslyn/pull/67092](https://github.com/dotnet/roslyn/pull/67092) to allow this to be more forgiving in the unexpected case where the local is added twice.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 18]
```diff
@@ -234,17 +279,50 @@ private uint GetPlaceholderScope(BoundValuePlaceholderBase placeholder)
         public override BoundNode? Visit(BoundNode? node)
         {
 #if DEBUG
-            if (node is BoundValuePlaceholderBase placeholder
-                // CheckValEscapeOfObjectInitializer() does not use BoundObjectOrCollectionValuePlaceholder.
-                // CheckInterpolatedStringHandlerConversionEscape() does not use BoundInterpolatedStringHandlerPlaceholder.
-                && node is not (BoundObjectOrCollectionValuePlaceholder or BoundInterpolatedStringHandlerPlaceholder))
+            if (node is BoundExpression expr)
+            {
+                bool added = MarkVisited(expr);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:283]: nit: there's something slightly odd about marking as visited before we've completed the visiting, but I understand this helps for checks in `Get/CheckEscape` methods...

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 19]
```diff
@@ -82,6 +84,11 @@ private static bool InUnsafeMethod(Symbol symbol)
         private Dictionary<LocalSymbol, (uint RefEscapeScope, uint ValEscapeScope)>? _localEscapeScopes;
         private Dictionary<BoundValuePlaceholderBase, uint>? _placeholderScopes;
         private uint _patternInputValEscape;
+#if DEBUG
+        private const int MaxTrackVisited = 100; // Avoid tracking if too many expressions.
+        private readonly HashSet<BoundExpression> _visited = new HashSet<BoundExpression>();
+        private bool _trackVisited = true;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:90]: nit: we could do without this bool. Just set `_visited` to `null` when we want to disable tracking

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 7)

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 12 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs]: > What was the resolution?

Inlined `MarkVisited()` and skipped adding placeholders to `_visited`.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 20]
```diff
@@ -225,14 +236,39 @@ private void RemovePlaceholderScope(BoundValuePlaceholderBase placeholder)
...
+            {
+                return true;
+            }
+
+            // _placeholderScopes should contain all placeholders that may be used by GetValEscape() or CheckValEscape().
+            // The following placeholders are not needed by those methods and can be ignored, however.
+            switch (placeholder)
+            {
+                case BoundObjectOrCollectionValuePlaceholder:
+                    return true; // CheckValEscapeOfObjectInitializer() does not use BoundObjectOrCollectionValuePlaceholder.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:259]: >// CheckValEscapeOfObjectInitializer() does not use BoundObjectOrCollectionValuePlaceholder. [](http://example.com/codeflow?start=33&length=92)

We don't visit member initializers?

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 21]
```diff
@@ -82,6 +84,10 @@ private static bool InUnsafeMethod(Symbol symbol)
         private Dictionary<LocalSymbol, (uint RefEscapeScope, uint ValEscapeScope)>? _localEscapeScopes;
         private Dictionary<BoundValuePlaceholderBase, uint>? _placeholderScopes;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:85]: >uint [](http://example.com/codeflow?start=54&length=4)

I thought the idea for the long term fix was to substitute placeholders with expressions they represent.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 22]
```diff
@@ -580,24 +645,27 @@ private void SetPatternLocalScopes(BoundObjectPattern pattern)
...
+            for (int i = 0; i < arguments.Length; i++)
             {
+                var arg = arguments[i];
                 if (arg is BoundConversion { ConversionKind: ConversionKind.InterpolatedStringHandler, Operand: BoundInterpolatedString or BoundBinaryOperator } conversion)
                 {
                     var interpolationData = conversion.Operand.GetInterpolatedStringHandlerData();
-                    GetInterpolatedStringPlaceholders(placeholders, interpolationData, receiverOpt, arguments);
+                    var placeholders = ArrayBuilder<(BoundValuePlaceholderBase, uint)>.GetInstance();
+                    GetInterpolatedStringPlaceholders(placeholders, interpolationData, receiverOpt, i, arguments);
+                    _ = new PlaceholderRegion(this, placeholders);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:660]: >_ = new PlaceholderRegion(this, placeholders); [](http://example.com/codeflow?start=20&length=46)

Are we relying on side-effects of this constructor? Consider extracting a reusable helper with meaningful name and using it instead.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 20 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:259]: We visit member initializers here in the call to `Visit(node.InitializerExpressionOpt)` in `VisitObjectCreationExpressionBase()`, but we don't add the `Placeholder` to the `_placeholders` collection, we simply visit the `Initializers`. And, as mentioned in the comment, `CheckValEscapeOfObjectInitializer()` does not use the escape scope of `Placeholder`.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs (hunk 21 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs:85]: We could store the replacement expression in the dictionary rather than the escape scope, and evaluate the escape scope of the replacement lazily, when it is used, rather than eagerly, when the placeholder is registered. However, that would mean ensuring `GetValEscape()` does not rely on mutable state in the visitor such as `_localScopeDepth` or `_inUnsafeRegion`. Given that, evaluating the escape scope eagerly seemed like a simpler alternative.

**Comment by AlekseyTs** [comment]
It looks like this PR also addresses a problem with tracking locals, consider reflecting that in the title. 

As I mentioned in an offline conversation, though this change is an improvement towards correct behavior, I think that each walker should be responsible for managing its own map of locals and placeholders, instead of relying on another component to walk the same node beforehand and building the maps. Hopefully, addressing #65961 will get us there.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 9)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 9)
