### PR TITLE
Account for bulk configuration editorconfig entries for computing eff…

### LINKED ISSUE #47160: Severity applied via bulk configuration should be reflected in analyzer icon and properties in Visual Studio UI
**Version Used**: 
Visual Studio 16.7.2

**Steps to Reproduce**:

1. Create a solution with an `.editorconfig` file and a project configured to use at least one Roslyn analyzer package that contains bulk configurable rule(s).
2. Add a bulk configuration for error severity to `.editorconfig` that should change the effective severity of at least one rule (e.g.: `dotnet_analyzer_diagnostic.severity = error` or `dotnet_analyzer_diagnostic.category-<some category>.severity = error`).
3.  Save the `.editorconfig` file.
4.  Examine a rule (e.g.: CA1820) whose severity should have been adjusted under the `Dependencies\Analyzers` node of the project in the Visual Studio solution explorer.

**Expected Behavior**:
The rule icon should reflect the severity applied via bulk configuration, as should the "Effective severity" item in the diagnostic properties sheet, as it is when a rule is configured using a rule-specific `.editorconfig` entry (e.g.: `dotnet_diagnostic.CA1820.severity = error`).

image

**Actual Behavior**:
Neither the rule icon nor the effective severity property display change to reflect the severity applied via bulk configuration.

image

**Additional Notes**:
This issue seems to hint that the logic used to determine effective severity is not fully shared between the execution engine and the UI.  While the current UI behaviour is inconvenient, any mismatches between applied and displayed severity will potentially become much more problematic when/if the `.editorconfig` editor UI (#40365) becomes available.  If the current discrepancy is indeed the result of a lack of centralized logic for determining effective severity, might it make sense to invest in centralizing the logic that so users can feel confident in the information provided to them by the eventual editor?

### PR DESCRIPTION
**Pull request by mavasani**
…ective descriptor severity in IDE

Fixes #47160

### CODE REVIEW

File: src/Workspaces/Core/Portable/Shared/Extensions/DiagnosticDescriptorExtensions.cs [hunk 1]
```diff
@@ -3,30 +3,90 @@
...
             return effectiveSeverity;
         }
+
+        /// <summary>
+        /// Tries to get configured severity for the given <paramref name="descriptor"/>
+        /// from bulk configuration analyzer config options, i.e.
+        ///     'dotnet_analyzer_diagnostic.category-%RuleCategory%.severity = %severity%'
+        ///         or
+        ///     'dotnet_analyzer_diagnostic.severity = %severity%'
+        /// </summary>
```
Comment (mavasani) [inline src/Workspaces/Core/Portable/Shared/Extensions/DiagnosticDescriptorExtensions.cs:52]:
```suggestion
        /// Docs: https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file for details
        /// </summary>
```

**Review by jmarolf — APPROVED** [review]
