### PR TITLE
🦔 Improved nullable constructor analysis

### LINKED ISSUE #33391: CS8618 (uninitialized field) when checking for null
**Version Used**: 
16.0.0 Preview 3

**Steps to Reproduce**:

```csharp
class C
{
    readonly string s;
    C(bool a) // CS8618
    {
        if (a)
            s = "";
        if (s == null)
            throw new InvalidOperationException();
    }
}
```
This is similar to #25529.
After possibly setting the the field, the code checks if the field is still default-initialized and throws if not. After that, `s` is definitely non-null.

**Expected Behavior**:
The constructor either initializes or throws, so there shouldn't be a warning.

**Actual Behavior**:
CS8618 for the constructor

### LINKED ISSUE #37138: Unexpected uninitialized warning on [AllowNull] field
**Version Used**: 
3.3.0-beta1-19354-02+c82dbc6503182784647003a4fce50ef56d680037

**Steps to Reproduce**:
```C#
#nullable enable

using System.Diagnostics.CodeAnalysis;

class Program
{
    static void Main() { }
}

class C<T>
{
    [AllowNull] public T Value;

    public C() { }
}
```

**Expected Behavior**:
No warning.

**Actual Behavior**:
Produces a warning "Non-nullable field 'Value' is uninitialized".  But adding `= default` on `Value` suppresses that warning.  These are semantically equivalent, so it's odd that there's a warning without the `= default`.

### LINKED ISSUE #39740: CS8618 should not be generated on constructors that throw if a property is null
**Version Used**: 3.3.1-beta3-19461-02 (2fd12c21)

```csharp
#nullable enable
public class TestClass {
	public string TestString { get; private set; }
	
	public TestClass() {
		// Some code that may or may not initialize TestString
		// For example a foreach that looks for the right item to use for TestString
		
		if (TestString == null) {
			throw new Exception();
		}
	}
}
```

**Expected Behavior**: No warning is emitted as there is no way for the constructor to return normally without having initialized `TestString`.

**Actual Behavior**: A CS8618 (Non-nullable property is uninitialized) warning is emitted on the constructor.

### LINKED ISSUE #41110: Roslyn should track properties' nullability the same as fields' when processing member initializers
**Version Used**: 
```
commit 1d4cf98ece59ab4365adcc7d414d3c758010d698
Merge: 1302d42173 26187bd0d8
Author: Jason Malinowski <jason.malinowski@microsoft.com>
Date:   Mon Jan 13 12:18:17 2020 -0800

    Merge pull request #40897 from jasonmalinowski/null-annotate-quick-info

    Null annotate Quick Info
```

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
class C
{
  static string? P1 { get; set; } = "";
  
  static string P2 { get; set; } = P1; // warning
  static string f1 = P1; // warning
}

class D
{
  static string? f1 = "";
  
  static string f2 = f1;
  static string P1 { get; set; } = f1;
}
```

**Expected Behavior**:
Fields and properties are treated the same.
Since static properties cannot be overriden and Roslyn doesn't take possible overrides into account in other places I believe that this code sample shouldn't have any warnings at all.

**Actual Behavior**:
Roslyn reports warnings for non-nullable fields and properties initialized with `P1` in `C`

**Notes**
It seems that Roslyn doesn't store actual nullability of properties based on the values they are initialized with but does this for fields.

### LINKED ISSUE #41296: Field assigned with non-nullable `out` in constructor should count as initialized
The following should not produce any warning.

[update jcouv: fixed repro to actually repro the issue I meant]

``` csharp
#nullable enable

using System;
public class C 
{
    string field; // warning CS8618: Non-nullable field 'field' is uninitialized. Consider declaring the field as nullable.
    
    public C() 
    {
        try 
        {
            M2(out field); 
        }
        catch (Exception)
        {
           if (field is null)
           {
              field  =  "";   
           }
        }
    }
    
    static void M2(out string s) => throw null!;
}
```

This was encountered while annotating `PEFieldSymbol`.

FYI @sharwell @cston

### LINKED ISSUE #41306: Roslyn should assume fields without initializers contain default value when inspectring constructors
**Version Used**: 
```
commit 1d4cf98ece59ab4365adcc7d414d3c758010d698
Merge: 1302d42173 26187bd0d8
Author: Jason Malinowski <jason.malinowski@microsoft.com>
Date:   Mon Jan 13 12:18:17 2020 -0800

    Merge pull request #40897 from jasonmalinowski/null-annotate-quick-info

    Null annotate Quick Info
```

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
class C
{
  string f;
  public C()
  {
    f.ToString();
    f = "";
  }
}
```

**Expected Behavior**:
Warning for `f.ToString()` since `f` is not initialized.

**Actual Behavior**:
No warnings. The constructor crashes at runtime with a `NullReferenceException`

**Notes**
Roslyn know that constructors must initialize non-nullable fields and warns if you don't do it. However the current set of warnings only verifies that you initialize non-nullable fields and don't assign them with nulls before dereferencing but misses the order between these two. 

Since Roslyn already requires such fields to be initialized in constructors I believe it would be consistent to consider them containing a null value prior to initialization.

### LINKED ISSUE #43215: Static field assigned by out parameter in static initializer is treated as uninitialized, results in CS8618
**Version Used**: 

.NET Core 3.1.201, C# 8.0

**Steps to Reproduce**:

```csharp
#nullable enable

using System;

namespace ClassLibrary5
{
    public static class Class1<T>
    {
        public static readonly T t;
        public static readonly bool f = Get(out t);

        private static bool Get(out T t)
        {
            t = Activator.CreateInstance<T>();
            return true;
        }
    }
}
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

Class1.cs(9, 34): [CS8618] Non-nullable field 't' is uninitialized. Consider declaring the field as nullable.

### LINKED ISSUE #43523: Suppressing non-nullable field unitialized with Debug.Assert(field != null) in ctor
Debug.Assert assuming that field is not null after the black box call (InitializeFoo) should be treated the same as writing non-null to that field by the compiler.

**Version Used**: 

Package version: 3.6.0-2.20166.2

**Steps to Reproduce**:

```csharp
#nullable enable
using System;
using System.Diagnostics;
public class C {
    public Object Foo;
    
    public C() // Non-nullable field 'Foo' is uninitialized. Consider declaring field as nullable.
    {
        InitializeFoo(); // same warning with or without it
        Debug.Assert(Foo != null);
    }

    public void InitializeFoo()
    {
        Foo = "not null";
    }
}
```

**Expected Behavior**:

No warnings/errors

**Actual Behavior**:

```
Non-nullable field 'Foo' is uninitialized. Consider declaring field as nullable.
```

cc: @jcouv @stephentoub @buyaa-n

### LINKED ISSUE #44046: CS8618 warning analysis ignores exceptional path in some cases
**Version Used**: 

```
csc: 3.2.0-beta2-19303-01 (c9689b7a)
dotnet: 3.1.100
```

**Steps to Reproduce**:

Build the following program with `dotnet build /p:Nullable=enable`

```c#
class X
{
   static bool Condition() => true;

   string fieldA;

   X() // CS8618 reported on this line
   {
       if (Condition()) fieldA = string.Empty;
       if (fieldA == default) throw new System.Exception("invalid setup");
   }
}
```

**Expected Behavior**:

No warning.

**Actual Behavior**:

> X.cs(7,4): warning CS8618: Non-nullable field 'fieldA' is uninitialized. Consider declaring the field as nullable.

Replacing `if (fieldA == default)` with `else` fixes the warning.

### LINKED ISSUE #44180: Roslyn ignores [MemberNotNull] annotation when checking properties initialization in constructors
**Version Used**: 

```
commit 7b27ca3b7722c5e56910a6cfba837e6a9d352d4f
Author: Tom<C3><A1><C5><A1> Matou<C5><A1>ek <tmat@users.noreply.github.com>
Date:   Mon May 11 19:17:04 2020 -0700

    Fixes PathMap parsing to support all paths (#43706)
```

**Steps to Reproduce**:

Compile the following code
```cs
using System.Diagnostics.CodeAnalysis;

class Property
{
  public string P { get; set; }

  public Property() { Init(); P.ToString(); } // false CS8618: Non-nullable property 'P' is uninitialized. Consider declaring the property as nullable.

  [MemberNotNull(nameof(P))]  void Init() => P = "";
}

class Field
{
  public string F;
  
  public Field() { Init(); F.ToString(); }

  [MemberNotNull(nameof(F))] void Init() => F = "";
}
```

**Expected Behavior**:
No warnings. Both classes calls members that guarantee to initialize their members in constructors and nullable inspector recognizes it and doesn't issue warnings for their dereferences.

**Actual Behavior**:
`CS8618: Non-nullable property 'P' is uninitialized. Consider declaring the property as nullable.` is reported for the constructor in class `Property`

### LINKED ISSUE #44212: Roslyn doesn't recognize properties' accesses in ??= assignments when checking initialization of non-nullable members
**Version Used**: 

```
commit 7b27ca3b7722c5e56910a6cfba837e6a9d352d4f
Author: Tom<C3><A1><C5><A1> Matou<C5><A1>ek <tmat@users.noreply.github.com>
Date:   Mon May 11 19:17:04 2020 -0700

    Fixes PathMap parsing to support all paths (#43706)
```

**Steps to Reproduce**:

Compile the following code
```cs
using System.Diagnostics.CodeAnalysis;
#nullable enable
class C
{
  string f;
  
  public C() // CS8618: Non-nullable field 'f' is uninitialized. Consider declaring the field as nullable.
  {
    Prop ??= "";
    f.ToString(); // no warnings
  }
  
  public C(byte b) // no warnings
  {
    if (Prop == null)
    {
      Prop = "";
    }
    f.ToString(); // no warnings
  }
  
  [MemberNotNull(nameof(f))]
  string? Prop
  {
    get => f = "";
    set => f = value ?? "";
  }
}
```

**Expected Behavior**:
No warnings in both constructors. Their code is equivalent.

**Actual Behavior**:
` CS8618: Non-nullable field 'f' is uninitialized. Consider declaring the field as nullable.` is reported for the first constructor only.

### LINKED ISSUE #44786: C# nullable not detecting issue correctly?
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/999596/c-nullable-not-detecting-issue-correctly.html)._

---
<p>I'm working on migrating a project to support C# 8.0 nullable but I ran into a situation where it looks like Visual Studio isn't detecting a null value correctly. If you look at the code below in the TestClass constructor the Console.WriteLine method will throw a NullReferenceException because this.Value is null and hasn't been assigned yet. There are no warnings or errors from VS though, it thinks everything is fine here. Am I missing something, shouldn't VS be warning about this? The value is definitely null here. Thanks!</p><pre>#nullable enable

namespace TestNullable
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            TestClass test = new TestClass(&quot;MyString&quot;);
        }

        public class TestClass
        {
            private readonly string Value;
            public TestClass(string value)
            {
                System.Console.WriteLine(this.Value.Length.ToString());
                this.Value = value;
            }
        }
    }
}

</pre>

---
#### Visual Studio Feedback System on 4/21/2020, 01:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/28/2020, 08:00 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

### LINKED ISSUE #46121: Compiler Should Not Raise CS8618 When Static, Non-Nullable Variable Initialized by Static Constructor in Different File
**Version Used**:  Visual C# Compiler Version 3.6.0-4.20251.5 (910223b6), used with Visual Studio 2019 (v16.6.2) and C#8 with nullable contexts enabled

**Steps to Reproduce**:
```cs
// File A
namespace Example {
    public partial class Foo {
        private static readonly string SOME_STRING;
    }
}

// File B
namespace Example {
    public partial class Foo {
        static Foo() {
            SOME_STRING = "something";
        }
    }
}
```
The above files are in the same C# .NET CORE 3.1 class library project, in the same directory. I haven't tested to see what happens if they're in different directories, but I can't imagine that it would result in a different behavior.

**Expected Behavior**:
Compiler does not raise CS8618 for `SOME_STRING` because it is, in fact, initialized to a non-null value by the static constructor Foo.

**Actual Behavior**:
Compiler raises CS8618 for `SOME_STRING`

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #43215
Closes #44046
Closes #44786
Closes #43523
Closes #33391
Closes #39740
Closes #41110
Closes #44180
Closes #41296
Closes #41306
Closes #37138
Closes #46121
Closes #44212

(some of these are dupes, but it felt easier to just tag all the issues instead of plumbing through which ones are duping which.)

Implementation for https://github.com/dotnet/csharplang/blob/master/proposals/nullable-constructor-analysis.md

Some pieces are missing. This includes:
- [x] warnings should be given at return points. In this PR we give warnings on the signature in order to match the previous analysis. This is a lot of test churn, so I wanted to push it to a subsequent PR to improve reviewability. *This will happen in a subsequent PR.* #46718
- [x] non-nullable reference type fields should have a maybe-null starting state in a struct constructor with a `: this()` initializer referencing the default value type constructor. It's not very common to delegate to the default value type constructor so maybe we can just do it in this PR. *This has been addressed.*
- [x] Semantic model is wrong. I think when we do nullable analysis within MemberSemanticModel, we might have to first bind and analyze the initializers within the type (if the member is a constructor which needs initializers to be analyzed to determine its initial state). *This has now been addressed.*

### CODE REVIEW

**Comment by RikkiGibson** [comment]
This PR still has some issues, particularly related to semantic model and some still prototype-quality code, but I think it is now ready to review.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 1]
```diff
@@ -978,19 +973,25 @@ public override object VisitField(FieldSymbol symbol, TypeCompilationState argum
...
+                        analyzedInitializers = InitializerRewriter.RewriteConstructor(processedInitializers.BoundInitializers, methodSymbol);
+                        processedInitializers.HasErrors = processedInitializers.HasErrors || analyzedInitializers.HasAnyErrors;
                     }
 
-                    if (body != null && methodSymbol.IsConstructor())
+                    if (methodSymbol.IsConstructor() && processedInitializers.AfterInitializersState is null)
                     {
-                        UnassignedFieldsWalker.Analyze(_compilation, methodSymbol, body, diagsForCurrentMethod);
+                        // TODO: should there be a state which indicates that we don't have an after initializers state and also don't want one?
+                        NullableWalker.AnalyzeIfNeeded(_compilation, methodSymbol, analyzedInitializers ?? BoundBlock.SynthesizedNoLocals(methodSymbol.GetNonNullSyntaxNode()), diagsForCurrentMethod, useConstructorExitWarnings: false, initialNullableState: null, out processedInitializers.AfterInitializersState);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:989]: >BoundBlock.SynthesizedNoLocals(methodSymbol.GetNonNullSyntaxNode()) [](start = 107, length = 67)

Can we just pass `null` instead?

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 2]
```diff
@@ -1763,6 +1762,11 @@ internal static BoundBlock BindMethodBody(MethodSymbol method, TypeCompilationSt
                 body = null;
             }
 
+            if (method.IsConstructor() && method.IsImplicitlyDeclared && nullableInitialState is object)
+            {
+                NullableWalker.AnalyzeIfNeeded(compilationState.Compilation, method, body ?? BoundBlock.SynthesizedNoLocals(method.GetNonNullSyntaxNode()), diagnostics, useConstructorExitWarnings: true, nullableInitialState, out _);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:1767]: >BoundBlock.SynthesizedNoLocals(method.GetNonNullSyntaxNode()) [](start = 93, length = 61)

This is repeated several times in the class, for methods and containing type. Consider extracting a helper method.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs [hunk 3]
```diff
@@ -11,6 +11,14 @@ namespace Microsoft.CodeAnalysis.CSharp
 {
     internal partial class LocalDataFlowPass<TLocalState, TLocalFunctionState>
     {
+
+        protected static bool HasInitializer(Symbol field) => field switch
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs:15]: Unnecessary blank line before the method, missing blank line after.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -559,14 +668,59 @@ void makeNotNullMembersMaybeNull()
...
+                                    this.State[memberSlot] = type.IsPossiblyNullableReferenceTypeTypeParameter() ? NullableFlowState.MaybeDefault : NullableFlowState.MaybeNull;
+                                }
+                            }
+                        }
+                    }
+                    else
+                    {
+                        do
+                        {
+                            makeMembersMaybeNull(method, method.NotNullMembers);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:717]: >makeMembersMaybeNull(method, method.NotNullMembers); [](start = 28, length = 52)

Shouldn't we execute this, even for constructors?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs:15]: Ah, yes, I used the "pull member to base" refactoring to do this and didn't look carefully at the results. I think this member maybe belongs in a different partial declaration of `LocalDataFlowPass`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:717]: Constructors are not a supported target for the `MemberNotNullAttribute`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -559,14 +668,59 @@ void makeNotNullMembersMaybeNull()
...
+                                var memberSlot = getSlotForFieldOrPropertyOrEvent(memberToInitialize);
+                                if (memberSlot > 0)
+                                {
+                                    var type = memberToInitialize switch
+                                    {
+                                        FieldSymbol f => f.Type,
+                                        PropertySymbol p => p.Type,
+                                        EventSymbol e => e.Type,
+                                        _ => throw ExceptionUtilities.UnexpectedValue(memberToInitialize)
+                                    };
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:707]: `var type = memberToInitialize.GetTypeOrReturnType().Type;`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -689,6 +843,36 @@ bool parameterHasBadConditionalState(ParameterSymbol parameter, bool sense, Loca
...
+            int getSlotForFieldOrPropertyOrEvent(Symbol member)
+            {
+                if (member.Kind != SymbolKind.Field &&
+                    member.Kind != SymbolKind.Property &&
+                    member.Kind != SymbolKind.Event)
+                {
+                    return -1;
+                }
+
+                int thisSlot = -1;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:856]: >thisSlot [](start = 20, length = 8)

This has changed in `getSlotForFieldOrProperty`. Please consider merging the two local functions.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -989,9 +1196,16 @@ private static BoundNode Rewrite(ImmutableDictionary<BoundExpression, (Nullabili
                                             analyzedNullabilityMapOpt,
                                             snapshotBuilderOpt);
 
+            finalNullableState = null;
             try
             {
                 Analyze(walker, symbol, diagnostics, initialState, snapshotBuilderOpt);
+                // we only go to the trouble of saving the final state if we're analyzing field initializers
+                if (symbol is MethodSymbol method && method.IsConstructor() && initialState is null && !useConstructorExitWarnings)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1204]: >symbol is MethodSymbol method && method.IsConstructor() && initialState is null && !useConstructorExitWarnings [](start = 20, length = 110)

Should the caller pass in a `bool generateFinalState`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -20247,9 +20247,9 @@ public class C
 ", MemberNotNullAttributeDefinition }, parseOptions: TestOptions.RegularPreview);
 
             c.VerifyDiagnostics(
-                // (10,12): warning CS8618: Non-nullable field 'field3' is uninitialized. Consider declaring the field as nullable.
-                //     public C() // 1
-                Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("field", "field3").WithLocation(10, 12),
+                // (15,9): warning CS8602: Dereference of a possibly null reference.
+                //         field3.ToString(); // 1
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "field3").WithLocation(15, 9),
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:20252]: 👍

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 9]
```diff
@@ -20388,6 +20394,60 @@ public void M()
...
+
+    public Program()
+    {
+        Prop.ToString();
+    }
+}
+";
+            var comp = CreateNullableCompilation(new[] { source });
+            comp.VerifyDiagnostics();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:20449]: >} [](start = 8, length = 1)

Consider moving these new tests outside the block of "MemberNotNull_" tests.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:1767]: Is the suggestion to create a local function in here like `BoundBlock getSynthesizedEmptyBody() => BoundBlock.SynthesizedNoLocals(method.GetNonNullSyntaxNode())`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 9 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs]: The suggestion was a `static BoundBlock GetSynthesizedEmptyBody(Symbol symbol) { ... }` method which could be used for methods and containing types.

---
In reply to: [468253616](https://github.com/dotnet/roslyn/pull/46441#discussion_r468253616) [](ancestors = 468253616)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs]: Done

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs]: Fixed

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 10]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                    return;
+                }
+                var symbol = member switch
+                {
+                    FieldSymbol { AssociatedSymbol: PropertySymbol p } => p,
+                    _ => member
+                };
+                var annotations = symbol.GetFlowAnalysisAnnotations();
+                if ((annotations & FlowAnalysisAnnotations.MaybeNull) != 0
+                    || (annotations & FlowAnalysisAnnotations.AllowNull) != 0)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:578]:
```suggestion
                if ((annotations & (FlowAnalysisAnnotations.MaybeNull | FlowAnalysisAnnotations.AllowNull)) != 0)
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                if (!fieldType.NullableAnnotation.IsNotAnnotated())
+                {
+                    return;
+                }
+                var symbol = member switch
+                {
+                    FieldSymbol { AssociatedSymbol: PropertySymbol p } => p,
+                    _ => member
+                };
+                var annotations = symbol.GetFlowAnalysisAnnotations();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:576]: Under the hood this is doing yet another `switch` on the types. This one may be cleaner to keep in but want to make sure you considered it.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 12]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                        }
+                        break;
+                    default:
+                        return;
+                }
+                if (field.IsConst)
+                {
+                    return;
+                }
+                if (fieldType.Type.IsValueType || fieldType.Type.IsErrorType())
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:563]: Do we need to handle when `field.Type is null`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 13]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                }
+
+                var memberState = state[slot];
+                var badState = fieldType.Type.IsPossiblyNullableReferenceTypeTypeParameter() ? NullableFlowState.MaybeDefault : NullableFlowState.MaybeNull;
+                if (memberState != badState)
+                {
+                    return;
+                }
+
+                Diagnostics.Add(ErrorCode.WRN_UninitializedNonNullableField, exitLocation ?? symbol.Locations.FirstOrNone(), symbol.Kind.Localize(), symbol.Name);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:597]:
```suggestion
                if (memberState == badState)
                {
                     Diagnostics.Add(ErrorCode.WRN_UninitializedNonNullableField, exitLocation ?? symbol.Locations.FirstOrNone(), symbol.Kind.Localize(), symbol.Name);
                }

               
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 14]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                    return;
+                }
+                var slot = GetOrCreateSlot(symbol, thisSlot);
+                if (slot < 0)
+                {
+                    return;
+                }
+
+                var memberState = state[slot];
+                var badState = fieldType.Type.IsPossiblyNullableReferenceTypeTypeParameter() ? NullableFlowState.MaybeDefault : NullableFlowState.MaybeNull;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:591]: This seems like it could be stronger if we checked for definitely null like `IsNullableTypeOrTypeParameter` and used `MaybeNull` for that and `MaybeDefault` for the rest.

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:591]: Hmm, seems like this pattern exists a bit in the code so probably okay.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 15]
```diff
@@ -1506,6 +1506,9 @@ public static void Main()
 ";
             var comp = CreateCompilation(src);
             comp.VerifyDiagnostics(
+                // (5,25): warning CS0067: The event 'C.X' is never used
+                //     public event Action X;
+                Diagnostic(ErrorCode.WRN_UnreferencedEvent, "X").WithArguments("C.X").WithLocation(5, 25)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1511]: What part of the change caused us to start firing these diagnostics?

File: src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs [hunk 16]
```diff
@@ -425,7 +425,9 @@ internal static FlowAnalysisAnnotations GetFlowAnalysisAnnotations(this Symbol?
             return symbol switch
             {
                 MethodSymbol method => method.ReturnTypeFlowAnalysisAnnotations,
-                PropertySymbol property => property.GetOwnOrInheritedGetMethod()?.ReturnTypeFlowAnalysisAnnotations ?? FlowAnalysisAnnotations.None,
+                PropertySymbol property =>
+                    (property.GetOwnOrInheritedGetMethod()?.ReturnTypeFlowAnalysisAnnotations ?? FlowAnalysisAnnotations.None)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs:429]: The pattern of `property.GetOwnOrInheritedGetMethod()?.ReturnTypeFlowAnalysisAnnotations ?? FlowAnalysisAnnotations.None` seems like it's repeated a bit in our code. It's here now as well as being inside of `SymbolExtensions.GetFlowAnalysisAnnotations`. Why do we not just have this as a property on `PropertySymbol` as we do for `MethodSymbol`? Feels wrong to have it repeated (avenue for future bugs if we only fix one instance of it)

File: src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs [hunk 17]
```diff
@@ -1532,6 +1741,142 @@ internal C(char c)
...
+           }
+        }
+    }
+
+    static void M2(out string s) => throw null!;
+}";
+            var comp = CreateCompilation(source, options: WithNonNullTypesTrue());
+            comp.VerifyDiagnostics();
+        }
+
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1879]: Think we need a test case like the following:

```cs
using System;
using System.Diagnostics.CodeAnalysis;
#nullable enable
public class C {

    static string Field1 = M(Field2);
    static string Field2 = M(Field1);
    
    [return: NotNullIfNotNull("input")]
    public static string? M(string? input) => input;
}
```

Based on the language rules (static fields initializers are executed in order) this should warn. Should probably add some variations which do not warn as well.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 18]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                var isStatic = !constructor.RequiresInstanceReceiver();
+                if (member.IsStatic != isStatic)
+                {
+                    return;
+                }
+
+                // This is not required for correctness, but in the case where the member has
+                // an initializer, we know we've assigned to the member and
+                // have given any applicable warnings about a bad value going in.
+                // Therefore we skip this check when the member has an initializer to reduce noise.
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:535]: If it is set in the constructor body, we know we will give a warning at the point that a bad value goes in.

File: src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs [hunk 19]
```diff
@@ -365,6 +365,39 @@ internal static bool IsConstructor(this MethodSymbol method)
             }
         }
 
+        /// <summary>
+        /// Returns true if the method is a constructor and has a this() constructor initializer.
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs:369]: When does a constructor have an implicit `this()` initializer? (distinct from an implicit `base()` initializer)

File: src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs [hunk 20]
```diff
@@ -19,6 +19,7 @@ internal struct ProcessedFieldInitializers
         {
             internal ImmutableArray<BoundInitializer> BoundInitializers { get; set; }
             internal BoundStatement? LoweredInitializers { get; set; }
+            internal NullableWalker.VariableState AfterInitializersState;
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs:22]: It represents the state after field initializers run.

File: src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs (hunk 19 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs:369]: ... it doesn't. This is what happens when I review code at 6am without drinking coffee.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 15 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1511]: IIRC these diagnostics started appearing once I deleted the UninitializedFieldsWalker--for much of my work, I simply commented out the part of that walker that gives the CS8618 diagnostic.

File: src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs [hunk 21]
```diff
@@ -365,6 +365,39 @@ internal static bool IsConstructor(this MethodSymbol method)
...
+        /// </summary>
+        internal static bool HasThisConstructorInitializer(this MethodSymbol method)
+        {
+            if ((object)method != null && method.MethodKind == MethodKind.Constructor)
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs:373]: This method was moved from MethodCompiler into an extension method without modifying implementation.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:563]: I do not think so because UninitializedFieldsWalker did not and I can't find any code paths through `FieldSymbol.TypeWithAnnotations` that give a result containing a null `Type`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 22]
```diff
@@ -186,6 +192,11 @@ public VisitArgumentResult(VisitResult visitResult, Optional<LocalState> stateFo
         /// </summary>
         private readonly bool _isSpeculative;
 
+        /// <summary>
+        /// True if this walker was created using an initial state.
+        /// </summary>
+        private readonly bool _hasInitialState = false;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:198]:
```suggestion
        private readonly bool _hasInitialState;
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:198]: Since this field is always initialized in the constructor.

File: src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs (hunk 16 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs:429]: It does feel like the implementation in here should be consolidated with NullableWalker.GetLValueAnnotations.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 23]
```diff
@@ -471,19 +489,114 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                {
+                    return;
+                }
+                if (!fieldType.NullableAnnotation.IsNotAnnotated())
+                {
+                    return;
+                }
+                var symbol = member switch
+                {
+                    FieldSymbol { AssociatedSymbol: PropertySymbol p } => p,
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:573]: Done

File: src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs (hunk 16 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs]: I implemented it as an extension method for expediency. It feels like properties are special because we usually only get their flow analysis annotations from the accessors, and only in the special case of assigning to a read-only auto-property in a constructor do we look at the property itself to learn its flow analysis annotations.

File: src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs (hunk 17 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1879]: Added some tests based on this example.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 11 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:574]: Yeah, I think it's best to keep it in this case.

**Comment by RikkiGibson** [comment]
@cston @jaredpar I believe I have addressed all your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 24]
```diff
@@ -471,19 +489,113 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                        var thisSlot = 0;
+                        if (method.RequiresInstanceReceiver)
                         {
-                            enforceMemberNotNullOnMember(syntaxOpt, state, method, memberName);
+                            method.TryGetThisParameter(out var thisParameter);
+                            Debug.Assert(thisParameter is object);
+                            thisSlot = GetOrCreateSlot(thisParameter);
                         }
+                        // https://github.com/dotnet/roslyn/issues/46718: give diagnostics on return points, not constructor signature
+                        var exitLocation = (method.DeclaringSyntaxReferences.IsEmpty ? null : method.Locations.FirstOrDefault());
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:502]: >( [](start = 43, length = 1)

Minor: Parentheses are not necessary.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 25]
```diff
@@ -769,12 +962,47 @@ private void EnforceDoesNotReturn(SyntaxNode? syntaxOpt)
...
+        internal static VariableState? GetAfterInitializersState(CSharpCompilation compilation, Symbol? symbol)
+        {
+            if (symbol is MethodSymbol method
+                && method.IncludeFieldInitializersInBody()
+                && method.ContainingType is SourceMemberContainerTypeSymbol containingType)
+            {
+                var unusedDiagnostics = DiagnosticBag.GetInstance();
+
+                Binder.ProcessedFieldInitializers initializers = default;
+                Binder.BindFieldInitializers(compilation, null, method.IsStatic ? containingType.StaticInitializers : containingType.InstanceInitializers, unusedDiagnostics, ref initializers);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:985]: >Binder.BindFieldInitializers [](start = 16, length = 28)

Are we binding the initializers a second time, in addition to initial binding?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 26]
```diff
@@ -769,12 +962,47 @@ private void EnforceDoesNotReturn(SyntaxNode? syntaxOpt)
...
+                NullableWalker.AnalyzeIfNeeded(
+                    compilation,
+                    method,
+                    InitializerRewriter.RewriteConstructor(initializers.BoundInitializers, method),
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:989]: >InitializerRewriter.RewriteConstructor(initializers.BoundInitializers, method) [](start = 20, length = 78)

Why rewrite?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 25 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:985]: In SemanticModel use cases this may be the first time we bind the initializers, but we will have to bind initializers again to get all diagnostics from the semantic model.

After chat with @333fred we decided that this was a reasonable first resort. We could also consider caching the bound initializers or the `AfterInitializersState` for a set of classes on a semantic model if we found there was a significant performance drag from doing it this way.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 26 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:989]: In MethodCompiler we flow-analyze initializers after rewriting them, so we need to do it here too to get the same behavior when flow-analyzing for the semantic model.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 24 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:502]: Fixed

**Comment by RikkiGibson** [comment]
The last commit is related to some new warnings we saw when test inserting to VS. It looks like someone adopted nullable in a project just yesterday using `<Nullable>warnings</Nullable>` and we started giving new warnings inside one of their constructors.

I am modifying the proposal so that fields whose types have oblivious nullability are not initialized to the `default` state. https://github.com/dotnet/csharplang/pull/3794

File: src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs [hunk 27]
```diff
@@ -1532,6 +1741,356 @@ internal C(char c)
...
+    public C(byte b)
+    {
+        if (Prop == null)
+        {
+            Prop = """";
+        }
+        f.ToString();
+    }
+
+    [MemberNotNull(nameof(f))]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1906]: >[MemberNotNull(nameof(f))] [](start = 4, length = 26)

Does this apply to both accessors? If so, are the calls to the setter above important, or would `if (Prop == null) { }` be sufficient to initialize `f`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1906]: I think it does apply to both accessors. This test was taken from a bug report, and I think it was originally intended to demonstrate the incongruity between MemberNotNull analysis and uninitialized fields analysis.

It might make sense to edit out or split the MemberNotNull related parts, since the point now is to demonstrate that non-nullable fields can be initialized using `if (field is null) field = value;` (which didn't work before this change) or `field ??= value`.

**Comment by RikkiGibson** [comment]
Val build before the oblivious change: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/267255
Val build after the oblivious change: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/267366

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 28]
```diff
@@ -976,32 +978,40 @@ public override object VisitField(FieldSymbol symbol, TypeCompilationState argum
...
                     }
 
-                    if (body != null && methodSymbol.IsConstructor())
+                    if (includeInitializersInBody && processedInitializers.AfterInitializersState is null)
                     {
-                        UnassignedFieldsWalker.Analyze(_compilation, methodSymbol, body, diagsForCurrentMethod);
+                        NullableWalker.AnalyzeIfNeeded(
+                            _compilation,
+                            methodSymbol,
+                            analyzedInitializers ?? GetSynthesizedEmptyBody(methodSymbol),
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:996]: This is how we report the exit warnings on things you were supposed to initialize

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (333fred) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:535]: It feels like this is inconsistent about warnings: if I assign a bad value in the constructor, I get a warning where that was assigned. However, depending on whether the property had an initializer or not, I may get an additional warning about the state at the end of the constructor body. I think we should be consistent here: either we always warn at the end of a body (the easier to implement approach), or we only warn if we didn't warn about a bad value going in (the harder approach). Doing otherwise will feel like a bug from the user's perspective IMO.

---
In reply to: [469259612](https://github.com/dotnet/roslyn/pull/46441#discussion_r469259612) [](ancestors = 469259612)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 29]
```diff
@@ -471,16 +489,106 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                }
+
+                // This is not required for correctness, but in the case where the member has
+                // an initializer, we know we've assigned to the member and
+                // have given any applicable warnings about a bad value going in.
+                // Therefore we skip this check when the member has an initializer to reduce noise.
+                if (HasInitializer(member))
+                {
+                    return;
+                }
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:539]: Consider some newlines for clarity.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 30]
```diff
@@ -471,16 +489,106 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                if (!fieldType.NullableAnnotation.IsNotAnnotated())
+                {
+                    return;
+                }
+                var annotations = symbol.GetFlowAnalysisAnnotations();
+                if ((annotations & (FlowAnalysisAnnotations.MaybeNull | FlowAnalysisAnnotations.AllowNull)) != 0)
+                {
+                    // We assume that if a member allows null input then the user
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:577]: >input [](start = 62, length = 5)

Or output?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 31]
```diff
@@ -471,16 +489,106 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                if (slot < 0)
+                {
+                    return;
+                }
+
+                var memberState = state[slot];
+                var badState = fieldType.Type.IsPossiblyNullableReferenceTypeTypeParameter() ? NullableFlowState.MaybeDefault : NullableFlowState.MaybeNull;
+                if (memberState == badState)
+                {
+                    Diagnostics.Add(ErrorCode.WRN_UninitializedNonNullableField, exitLocation ?? symbol.Locations.FirstOrNone(), symbol.Kind.Localize(), symbol.Name);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:591]: >OrNone [](start = 119, length = 6)

Are there cases when there are actually none?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 32]
```diff
@@ -556,17 +664,74 @@ bool memberHasBadState(Symbol member, LocalState state)
...
+                        return false;
+                    }
+
+                    if (!method.HasThisConstructorInitializer() && (!method.ContainingType.IsValueType || method.IsStatic))
+                    {
+                        return true;
+                    }
+
+                    return methodMainNode is BoundConstructorMethodBody ctorBody
+                        && ctorBody.Initializer?.Expression.ExpressionSymbol is MethodSymbol delegatedCtor
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:733]: >ctorBody.Initializer?.Expression.ExpressionSymbol is MethodSymbol delegatedCtor [](start = 27, length = 79)

Nit: this could be a pattern in the `is`

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:733]: I did actually do this at one point before committing and I was put off by the amount of curly brace pairs.
`methodMainNode is BoundConstructorMethodBody { Initializer: { Expression: { ExpressionSymbol: MethodSymbol delegatedCtor } } } ctorBody`

It does make me wonder if in a future language version it would make sense to support a "property path" shorthand in recursive patterns, e.g.

`methodMainNode is BoundConstructorBody { Initializer.Expression.ExpressionSymbol: MethodSymbol delegatedCtor }`

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 33]
```diff
@@ -24045,6 +24069,60 @@ void Init()
...
+
+        [Fact]
+        public void ConstMembersUseDeclaredNullability()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24091]: >ConstMembersUseDeclaredNullability [](start = 20, length = 34)

Consider showing what would happen if a const member was declared as `string?` but initialized with a non-null string.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 34]
```diff
@@ -24045,6 +24069,60 @@ void Init()
...
+    {
+    }
+}
+";
+            var comp = CreateNullableCompilation(new[] { source });
+            comp.VerifyDiagnostics();
+        }
+
+        [Fact]
+        public void ComputedPropertiesUseDeclaredNullability()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24109]: Consider adding a second, nullable computed property.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 35]
```diff
@@ -24045,6 +24069,60 @@ void Init()
                 );
         }
 
+        [Fact]
+        public void ConstructorUsesStateFromInitializers()
+        {
+            var source = @"
+public class Program
+{
+    public string Prop { get; set; } = null!;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24078]: >null [](start = 39, length = 4)

Consider using a constant value that is easily visible as non-null.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 36]
```diff
@@ -1506,6 +1506,9 @@ public static void Main()
 ";
             var comp = CreateCompilation(src);
             comp.VerifyDiagnostics(
+                // (5,25): warning CS0067: The event 'C.X' is never used
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1509]: This is just wrong? It's used.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs [hunk 37]
```diff
@@ -4584,5 +4584,133 @@ static T F2<T>(T x2)
...
+            var tree = comp.SyntaxTrees.Single();
+            var model = comp.GetSemanticModel(tree);
+
+            var memberAccesses = tree.GetRoot().DescendantNodes().OfType<MemberAccessExpressionSyntax>().ToArray();
+            Assert.Equal(2, memberAccesses.Length);
+
+            var receiver = memberAccesses[0].Expression;
+            var info = model.GetTypeInfo(receiver);
+            Assert.Equal(PublicNullableAnnotation.NotAnnotated, info.Type.NullableAnnotation);
+            Assert.Equal(PublicNullableFlowState.NotNull, info.Nullability.FlowState);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:4618]: >Nullability.FlowState [](start = 63, length = 21)

Please verify the nullable state on the type symbol. We really need to deprecate these apis.

**Comment by 333fred** [comment]
Done review pass (commit 13)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 36 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1509]: My impression is that just assigning a field-like event is not sufficient to remove this warning. See for example

```cs
using System;
class C
{
    public event Action X; // warning: the event 'C.X' is never used
    public static void Main()
    {
        var c = new C();
        c.X += () => {};
    }
}
```

The fact that my PR *introduces* the warning is interesting. I am assuming it is a side effect of removing the UnassignedFieldsWalker.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1509]: OK, some of the existing behaviors in master are mystifying me.

[This](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoPAAgGESBvEs+s7AZjLgDc4A7GR/XMgBoBuMgHpRZAO4QEnAJacA5iDIwAFnDIAzOXAA2KMgHIKAOgFGycqGWhQ5iznEPAArjzkwbbCHtebrMicOBDJXKGc6BjxcKPpaYgYksh9QgGMyAF4guElKAAoASiE45LTzLKDXPT0SxIYAXxIGoA===) warns, which seems good:
```cs
using System;
class C
{
    public event Action X; // warning: the field 'C.X' is assigned but its value is never used
    public static void Main()
    {
        var c = new C();
        c.X = null;
    }
}
```

[This](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoPAAgGESBvEs+s7AZjLgDc4A7GR/XMgBoBuMgHpRZTgHsyAdwgJOAS04BzAPx0GeXFvq1iDI2TYKyAYzIBeSXFmUAFAEohe4+YB0A62WfWAfGTUAL6uhgzBJMFAA=) does not warn. What?
```cs
using System;
class C
{
    public event Action X; // no warning?
    public static void Main()
    {
        var c = new C();
        c.X = () => {};
    }
}
```

[This](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoPAAgGESBvEs+s7AZjLgDc4A7GR/XMgBoBuMgHpRZTgHsyAdwgJOAS04BzAPx0GzXgDZGAFjIBZfAApsfMhACUW+rWINnZNgrIBjMgF5JcWZRmNkL2Lh4AdAI+1iFODAC+JPFAA==) also does not warn. So I don't think it's related to some kind of capturing bug..?
```cs
using System;
class C
{
    public event Action X; // no warning?
    public static void M1(Action a)
    {
        var c = new C();
        c.X = a;
    }
}
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs (hunk 37 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:4618]: > Please verify the nullable state on the type symbol.

Is that the same thing as checking `info.Type.NullableAnnotation` which is done on the previous line?

> We really need to deprecate these apis.

Is this in reference to the 'Nullability' property entirely?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:535]: The main fallout of this is a lot of test churn, so I'd like to do it in a follow-up if that's acceptable.

[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:535]: Probably at the same time that I move the location of uninitialized field warnings. #46718

File: src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs (hunk 20 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs:22]: Assuming some of these comments are resolved, feel free to mark un-resolved if you want to follow up.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs (hunk 37 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:4618]: Ah, yes, I misread that. And yes, I mean we should really deprecate the `Nullability` property.

---
In reply to: [470190746](https://github.com/dotnet/roslyn/pull/46441#discussion_r470190746) [](ancestors = 470190746)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (333fred) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:535]: That's fine with me.

---
In reply to: [470202737](https://github.com/dotnet/roslyn/pull/46441#discussion_r470202737) [](ancestors = 470202737)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 36 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1509]: Probably worth an email discussion on what the correct behavior is.

---
In reply to: [470185248](https://github.com/dotnet/roslyn/pull/46441#discussion_r470185248) [](ancestors = 470185248)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 31 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:591]: I will say that no tests fail when replacing `.FirstOrNone()` with `.First()`. But the original UnassignedFieldsWalker uses `.FirstOrNone()` and I am inclined to leave it that way.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 33 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24091]: Added test `ConstMembersUseDeclaredNullability_02`

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 34 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24109]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 35 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24078]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 36 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:1509]: Happy to follow up and examine these behaviors more closely in an email thread. I will leave these baselines as they currently stand in this PR.

**Comment by RikkiGibson** [comment]
@jaredpar @333fred I believe I have addressed all your comments. Please let me know if you have any others.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 30 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Fixed comment

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 29 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:539]: Added a newline after this closing brace.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 38]
```diff
@@ -471,16 +489,107 @@ void enforceMemberNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
+                        field = e.AssociatedField;
+                        symbol = e;
+                        if (field is null)
+                        {
+                            return;
+                        }
+                        break;
+                    default:
+                        return;
+                }
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:562]: I meant throughout the rest of the body too, but it's fine to cover in a followup.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 32 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:734]: I'm fairly certain such an issue exists somewhere, but I'm not finding it.

---
In reply to: [470168683](https://github.com/dotnet/roslyn/pull/46441#discussion_r470168683) [](ancestors = 470168683)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 39]
```diff
@@ -24045,6 +24069,88 @@ void Init()
...
+    const string? s1 = ""hello"";
+
+    public Program()
+    {
+        var x = s1.ToString(); // 1
+    }
+}
+";
+            // Arguably we could just see through to the constant value and know it's non-null,
+            // but it feels like the user should just fix the type of their 'const' in this scenario.
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24123]: It feels very weird that this would give a warning, but this does not:
```cs
public class Program
{
    public string? Prop { get; set; } = ""a"";
    public Program()
    {
        Prop.ToString();
    }
}
```

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24123]: Also, it's certainly possible that the user _can't_ change the type, because in some `#if`s it's actually null.

---
In reply to: [470284592](https://github.com/dotnet/roslyn/pull/46441#discussion_r470284592) [](ancestors = 470284592)

**Comment by RikkiGibson** [comment]
When this change flows into VS, it will be necessary to cherry pick the manually-added commit in [this validation PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/267366?_a=overview) in order to fix the 1 new warning they have as a result of this change.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 39 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:24123]: Opened a follow-up issue #46805
