### PR TITLE
Propagate InvolvesNarrowingFromNumericConstant flag for tuple conversions.

### LINKED ISSUE #14473: Passing a Tuple literal as an argument causes an unexpected failure in emit.
```
        <Fact>
        Public Sub NarrowingFromNumericConstant_06()

            Dim comp = CreateCompilationWithMscorlibAndVBRuntime(
<compilation>
    <file name="a.vb">
Option Strict On

Public Class C

    Shared Sub M2 (x as Byte?)
        System.Console.WriteLine("Byte")
    End Sub

    Shared Sub M5 (x as (Byte?, Byte?))
        System.Console.WriteLine("Byte")
    End Sub

    Shared Sub Main()
        Dim a as Byte? = 1
        Dim b as (Byte?, Byte?) = (1, 1)
        M2(1)
        M5((1, 1))
    End Sub
End Class
    </file>
</compilation>,
options:=TestOptions.ReleaseExe.WithOverflowChecks(True), additionalRefs:=s_valueTupleRefs)

            AssertTheseDiagnostics(comp, <expected></expected>)

            CompileAndVerify(comp, expectedOutput:=
"Byte
Byte")
        End Sub
```

error BC36970: Failed to emit module 'a0b4d275-d8a2-4343-8785-311269516478.exe'.

@VSadov, @jcouv FYI

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #14255.
Fixes #14473.

@dotnet/roslyn-compiler, @VSadov, @jcouv Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler, @VSadov, @jcouv Please review.

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_InterpolatedString.vb [hunk 1]
```diff
@@ -50,7 +50,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Private Function RewriteInterpolatedStringConversion(conversion As BoundConversion) As BoundExpression
 
-            Debug.Assert(conversion.ConversionKind = ConversionKind.InterpolatedString)
+            Debug.Assert((conversion.ConversionKind And ConversionKind.InterpolatedString) = ConversionKind.InterpolatedString)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_InterpolatedString.vb]: That would be incorrect - ConversionKind.InterpolatedString is a combination of bits, we are checking all of them. I believe other instances are of the same nature.

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb [hunk 2]
```diff
@@ -1261,12 +1263,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                     Return Nothing 'ConversionKind.NoConversion
                 End If
 
+                involvesNarrowingFromNumericConstant = involvesNarrowingFromNumericConstant Or elementConversion
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: I would either rename the "involvesNarrowing..." and "allNarrowing..." locals to "involvedConversions" and "commonConversions", or apply the mask `ConversionKind.InvolvesNarrowingFromNumericConstant` up here.

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_InterpolatedString.vb (hunk 1 above)
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_InterpolatedString.vb]: Never mind, we discussed this will help avoid mistakes between C# and VB.

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb [hunk 3]
```diff
@@ -1261,12 +1263,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+
                 If IsNarrowingConversion(elementConversion) Then
+                    allNarrowingIsFromNumericConstant = allNarrowingIsFromNumericConstant And elementConversion
                     result = narrowingConversion
                 End If
             Next
 
-            Return result
+            Return result Or
+                   (involvesNarrowingFromNumericConstant And allNarrowingIsFromNumericConstant And ConversionKind.InvolvesNarrowingFromNumericConstant)
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: I didn't understand the contribution of `involvesNarrowingFromNumericConstant` here. Isn't `allNarrowingIsFromNumericConstant` always a subset of those flags?

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: As we discussed offline, I will add a comment for the locals explaining the effect of optimization on the values that they contain.

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: If allNarrowingIsFromNumericConstant is "true", then involvesNarrowingFromNumericConstant is not necessary "true". That is because we may never enter the "narrowing" if.

**Comment by AlekseyTs** [comment]
@MattGertz For ask mode approval.

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb [hunk 4]
```diff
@@ -1579,7 +1579,7 @@ DoneWithDiagnostics:
 
             ' We have a successful tuple conversion rather than producing a separate conversion node 
             ' which is a conversion on top of a tuple literal, tuple conversion is an element-wise conversion of arguments.
-            Dim isNullableTupleConversion = (convKind = ConversionKind.WideningNullable) Or (convKind = ConversionKind.NarrowingNullable)
+            Dim isNullableTupleConversion = (convKind And ConversionKind.Nullable) <> 0
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb]: It may be more robust to have extension methods like "IsNullable".
Possibly applies to InterpolatedString as well

Could be done as a separate fix/issue, but it seems a good thing to do.

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb [hunk 5]
```diff
@@ -1246,6 +1246,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
             ' check arguments against flattened list of target element types 
             Dim result As ConversionKind = wideningConversion
+            Dim involvesNarrowingFromNumericConstant As ConversionKind = Nothing
+            Dim allNarrowingIsFromNumericConstant = ConversionKind.InvolvesNarrowingFromNumericConstant
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: There is another ClassifyTupleConversion method that classifies conversions from type. I assume that one does not need aggregation for this bit since this bit can only happen in a conversion from a literal.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: That is correct.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb [hunk 6]
```diff
@@ -2494,6 +2494,747 @@ End Class
...
+        Dim x06 As (Integer, Byte) = (1, 300)
+        Dim x07 As (Byte, Long) = (300, 1)
+        Dim x08 As (Long, Byte) = (1, 300)
+        Dim x09 As (Long, Long) = (1, 300)
+        Dim x10 As (Byte, Byte) = (1, 300)
+        Dim x11 As (Byte, Byte) = (300, 1)
+        Dim one As Integer = 1
+        Dim x12 As (Byte, Byte, Byte) = (one, 300, 1)
+        Dim x13 As (Byte, Byte, Byte) = (300, one, 1)
+        Dim x14 As (Byte, Byte, Byte) = (300, 1, one)
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: Do we get expected result in cases like 
```VB
Dim x14nullable  As (Byte, Byte, Byte)? = (300, 1, one)
```

Comment (VSadov) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: And
```VB
Dim x14nullable2  As (Byte?, Byte?, Byte?)? = (300, 1, one)
```

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: Yes, TupleConvertedType01 covers that. The ```?``` inside the tuple type isn't that interesting for the testing merging, in my opinion.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb [hunk 7]
```diff
@@ -2494,6 +2494,747 @@ End Class
...
+        System.Console.WriteLine("Short")
+    End Sub
+
+    Shared Sub M8 (x as (Byte, Byte)?, y as Byte)
+        System.Console.WriteLine("Byte")
+    End Sub
+    Shared Sub M8 (x as (Byte, Byte)?, y as Short)
+        System.Console.WriteLine("Short")
+    End Sub
+
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: Perhaps add a couple nested cases like ```x as (Byte, (Byte, Byte))```   just to see the bit floats through more than one tuple

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb (hunk 7 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: I will add a test like that in the next PR.

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb]: Opened https://github.com/dotnet/roslyn/issues/14517
