### PR TITLE
Fixes IDE0059 (Remove redundant assignment) incorrectly copies leading trivia

### LINKED ISSUE #48070: IDE0059 (Remove redundant assignment) incorrectly copies leading trivia
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1195636/quick-action-offers-bad-code-recommendation.html)._

---
I do not know how to reproduce as this is the first time I have seen it BUT as can be seen in the attached screenshot it SHOULD be offering to remove the **_= null_** initialization but instead offers to add an **_#endregion_** instead which produces a compile error.

---
#### Feedback Bot on 9/23/2020, 08:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/25/2020, 02:42 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by MartynJones87**
Changed the `AbstractRemoveUnusedValuesCodeFixProvider.cs` class to filter out Leading Trivia that comes before a Directive. This avoids duplicating an #endregion whilst applying this code fix.

Hopefully this fixes #48070

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48252) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48252) before we can accept your contribution.<br/><br/>:x: MartynJones87 [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48252)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=48252) it.</sub>

File: src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs [hunk 1]
```diff
@@ -133,6 +133,53 @@ int M()
...
+        System.Console.WriteLine(x);
+    }
+}";
+            var fixedSource =
+@"class C {
+    void M()
+    {
+        #region
+        int value = 3;
+
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs:163]: spacing is def a bit weird here.would ideally have the #endregion stay where it was.  is that not doable?

File: src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs [hunk 2]
```diff
@@ -674,7 +674,28 @@ void InsertLocalDeclarationStatement(TLocalDeclarationStatementSyntax declaratio
...
+                            var lastDirectiveTriviaIndex = 0;
+                            for (var i = 0; i < leadingTrivia.Count; i++)
+                            {
+                                if (leadingTrivia[i].IsDirective)
+                                {
+                                    lastDirectiveTriviaIndex = i;
+                                }
+                            }
+
+                            declarationStatement = declarationStatement.WithLeadingTrivia(insertionNode.GetLeadingTrivia().Skip(lastDirectiveTriviaIndex + 1));
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs:692]: this feels like this could be simplified to just initially do:

```
var lastDirective = leadingTrivia.LastOrDefault(t => t.IsDirective);
if (lastDirective == default)
   // normal case
else
   // consume trivia after last directive
```

**Comment by CyrusNajmabadi** [comment]
Hi @MartynJones87 thanks for the contribution :)  definitely will take this.  However, i think things can be cleaned up a bit, and there's an open question i have about the test result that you specified.  Thanks!

**Review by CyrusNajmabadi — APPROVED** [review]
