### PR TITLE
Fix convert-to-switch handling of comments at the end of blocks

### LINKED ISSUE #46863: 'Convert to switch' mishandles comments at the end of blocks
**Version Used**: 16.7.1

🛠 Convert to 'switch' statement:

```cs
class C
{
    void M(int p)
    {
        [||]if (p == 1)
        {
            Console.WriteLine("A");
            // Comment about why A doesn't need something here
        }
        else if (p == 2)
        {
            Console.WriteLine("B");
            // Comment about why B doesn't need something here
        }
    }
}
```

**Actual:**

```cs
        switch (p)
        {
            case 1:
                Console.WriteLine("A");
                break;
            case 2:
                Console.WriteLine("B");
                break;
                // Comment about why A doesn't need something here
        }
```

**Expected:**

```cs
        switch (p)
        {
            case 1:
                Console.WriteLine("A");
                // Comment about why A doesn't need something here
                break;
            case 2:
                Console.WriteLine("B");
                // Comment about why B doesn't need something here
                break;
        }
```

**Diff from actual to expected:**

```diff
        switch (p)
        {
            case 1:
                Console.WriteLine("A");
+               // Comment about why A doesn't need something here
                break;
            case 2:
                Console.WriteLine("B");
+               // Comment about why B doesn't need something here
                break;
-               // Comment about why A doesn't need something here
        }
```

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #46863

~~The last commit is a WIP that I either would like input on or would be happy to drop, leaving VB as-is. The problem with the commit is that the test fails due to the formatter not indenting one of the comments. The formatter for C# is not behaving this way. What approach would you take?~~

```diff
 Class C
     Sub M(p As Integer)
         Select p
             Case 1
                 DoA()
-                ' Comment about why A doesn't need something here
+            ' Comment about why A doesn't need something here
             Case 2
                 DoB()
                 ' Comment about why B doesn't need something here
         End Select
     End Sub
 
     Sub DoA()
     End Sub
     Sub DoB()
     End Sub
 End Class
```

/cc @CyrusNajmabadi

### CODE REVIEW

File: src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb [hunk 1]
```diff
@@ -29,7 +29,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ConvertIfToSwitch
 
         Public Overrides Function AsSwitchSectionStatements(operation As IOperation) As IEnumerable(Of SyntaxNode)
             Dim node = operation.Syntax
-            Return If(node.IsStatementContainerNode(), node.GetStatements(), SpecializedCollections.SingletonEnumerable(node))
+            Dim statements = If(node.IsStatementContainerNode(), DirectCast(node.GetStatements(), IEnumerable(Of SyntaxNode)).ToArray(), {node})
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb:32]: the cast to IEnumerable seems really strange.  why is it necessary?

File: src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb [hunk 2]
```diff
@@ -29,7 +29,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ConvertIfToSwitch
...
+
+            Dim lastStatement = statements.LastOrDefault()
+            If lastStatement IsNot Nothing Then
+                statements(statements.Length - 1) = lastStatement.WithAppendedTrailingTrivia(lastStatement.GetLastToken().GetNextToken().LeadingTrivia)
+            End If
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb:37]: in the vb case, wouldn't this duplicate since you'recopying the trivia to something else, but not removing from teh thing you're copying from?

File: src/EditorFeatures/CSharpTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchTests.cs [hunk 3]
```diff
@@ -691,6 +691,7 @@ void M(object o)
         {
             case string s when s.Length > 5 && s.Length < 10:
                 M(o: 0);
+
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchTests.cs:694]: note: i woudl likely only preserve trivia if there's something non-whitespace in it.

**Comment by CyrusNajmabadi** [comment]
I would just drop the vb support for now

File: src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb (hunk 2 above)
Comment (jnm2) [reply src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb:37]: The thing it's copying from is the `ElseIf` or `End If` statement which is currently being deleted.

File: src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb (hunk 1 above)
Comment (jnm2) [reply src/Features/VisualBasic/Portable/ConvertIfToSwitch/VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb:32]: Oh, this is a leftover from when I was using .ToImmutableArray(). `ImmutableArray<StatementSyntax>` conflicted with `ImmutableArray<SyntaxNode>`, and `.ToImmutableArray(Of SyntaxNode)()` caused a VB error.

File: src/EditorFeatures/CSharpTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchTests.cs (hunk 3 above)
Comment (jnm2) [reply src/EditorFeatures/CSharpTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchTests.cs:694]: I'm somewhat on the fence, maybe leaning the other way. Can we do the most simple thing possible until someone requests a change?

**Comment by jnm2** [comment]
> I would just drop the vb support for now

Done.

File: src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs [hunk 4]
```diff
@@ -77,7 +77,7 @@ public override SyntaxNode CreateSwitchStatement(IfStatementSyntax ifStatement,
                 closeParenToken: ifStatement.CloseParenToken.WithPrependedLeadingTrivia(ElasticMarker),
                 openBraceToken: block?.OpenBraceToken ?? Token(SyntaxKind.OpenBraceToken),
                 sections: List(sectionList.Cast<SwitchSectionSyntax>()),
-                closeBraceToken: block?.CloseBraceToken ?? Token(SyntaxKind.CloseBraceToken));
+                closeBraceToken: block?.CloseBraceToken.WithLeadingTrivia(SyntaxTriviaList.Empty) ?? Token(SyntaxKind.CloseBraceToken));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: I think we have WithoutLeadingTrivia

Comment (jnm2) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: I tried that first and it did not appear in intellisense. I'll try again.

Comment (jnm2) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: @CyrusNajmabadi It's defined on SyntaxNode only, not SyntaxToken. Should I create new extension methods?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: yup!

Comment (jnm2) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: Internal or public API?

Comment (jnm2) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs:80]: InternalsVisibleTo doesn't seem to be in place.

Comment (jnm2) [reply src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs]: Done.

File: src/Compilers/Core/Portable/PublicAPI.Unshipped.txt [hunk 5]
```diff
@@ -28,6 +28,8 @@ const Microsoft.CodeAnalysis.WellKnownMemberNames.TopLevelStatementsEntryPointTy
 Microsoft.CodeAnalysis.CompilationOptions.SyntaxTreeOptionsProvider.get -> Microsoft.CodeAnalysis.SyntaxTreeOptionsProvider
 Microsoft.CodeAnalysis.CompilationOptions.WithSyntaxTreeOptionsProvider(Microsoft.CodeAnalysis.SyntaxTreeOptionsProvider provider) -> Microsoft.CodeAnalysis.CompilationOptions
 Microsoft.CodeAnalysis.Operations.IPatternOperation.NarrowedType.get -> Microsoft.CodeAnalysis.ITypeSymbol
+static Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithoutLeadingTrivia(this Microsoft.CodeAnalysis.SyntaxToken token) -> Microsoft.CodeAnalysis.SyntaxToken
+static Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithoutTrailingTrivia(this Microsoft.CodeAnalysis.SyntaxToken token) -> Microsoft.CodeAnalysis.SyntaxToken
```
Comment (jnm2) [inline src/Compilers/Core/Portable/PublicAPI.Unshipped.txt:32]: InternalsVisibleTo didn't seem to be in place.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/PublicAPI.Unshipped.txt:32]: i would do this in the IDE layer.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/PublicAPI.Unshipped.txt:32]: can you moved these @jnm2 ?

Comment (jnm2) [reply src/Compilers/Core/Portable/PublicAPI.Unshipped.txt]: Done. Had no idea if you'd like it if I added an unused extension method, so I didn't.

**Comment by CyrusNajmabadi** [comment]
LGTM.  can you ping me when this passes?

**Comment by jnm2** [comment]
@CyrusNajmabadi it passed

**Comment by CyrusNajmabadi** [comment]
Merged.  THanks!
