### PR TITLE
Smart format Try block without catch/finally block

### LINKED ISSUE #6645: try formatting does not put { on new line
Automatic brace completion setting off. All new line settings default.
```C#
try {
|
```
Type `}`. Actual:
```C#
try {
}|
```
Expected:
```C#
try
{
}|
```
like in Visual Studio 2013.

This breaks the workflow when you hit up arrow key and enter, expecting to end up writing the body of the try block.

When you format the document, the brackets go where expected, suggesting that "Automatically format completed block on }" does not work for the case of `try`.

### PR DESCRIPTION
**Pull request by basoundr**
Fixes #6645

Format try block on typing the close brace of the try block even if
there is no catch/finally block to make the try-catch-finally block
syntactically complete without diagnostics.

Review: @dotnet/roslyn-ide

### CODE REVIEW

File: src/EditorFeatures/CSharp/Formatting/Indentation/SmartTokenFormatter.cs [hunk 1]
```diff
@@ -48,15 +48,25 @@ internal class SmartTokenFormatter : ISmartTokenFormatter
 
             var smartTokenformattingRules = _formattingRules;
             var common = startToken.GetCommonRoot(endToken);
-            if (common.ContainsDiagnostics)
+
+            // if there are errors, do not touch lines
+            // Exception: In the case of try-catch-finally block, a try block without a catch/finally block is considered incomplete
+            //            but we would like to apply line operation in a completed try block even if there is no catch/finally block
+            if (common.ContainsDiagnostics && !CloseBraceOfTryBlock(endToken))
```
Comment (balajikris) [inline src/EditorFeatures/CSharp/Formatting/Indentation/SmartTokenFormatter.cs]: what if the diagnostic was for something else and not for the absence of catch block?

Comment (basoundr) [inline src/EditorFeatures/CSharp/Formatting/Indentation/SmartTokenFormatter.cs]: still the case is, it is a try block which is trying to get formatted on close brace token and we should format. I cannot think of a common(or a complicated) diagnostic case which will result in unwanted formatting

Comment (balajikris) [inline src/EditorFeatures/CSharp/Formatting/Indentation/SmartTokenFormatter.cs]: sure, the comment above makes it sound like it is trying to format in just this particular error case of missing the catch block, while that is not the case. It will format the try block regardless of what the diagnostic is for.

**Comment by balajikris** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Do we need to have a similar check around do/while loops, since they're another construct where there's more expected after the { }?

**Comment by basoundr** [comment]
Nice catch @jasonmalinowski. This is another case where we will have to make a similar exception.
