### PR TITLE
Correct an off-by-one error in the precedence for is-pattern parsing.

### LINKED ISSUE #15734: Incorrect precedence of `is` operator
```C#
class Program
{
    static void Main(string[] args)
    {
        if (args is string[] || args.Length > 0) // ok
        {
        }

        if (args is null || args.Length > 0) // error
        {
        }
    }
}
```

**Actual result**

```Operator '||' cannot be applied to operands of type '<null>' and 'bool'```

**Expected result**

No error.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use the new pattern-matching `is` operator in a more complex expression, such as `e1 is null || e2`

In that case the compiler gets the precedence wrong.

**Bugs this fixes:** 

Fixes #15734

**Workarounds, if any**

Add redundant parens when the compiler gets the precedence wrong (if you notice).

In some circumstances, the compiler will produce executable code with no error, but generate code that is incorrect because of the precedence. Because of that, this should be fixed sooner rather than later.

**Risk**

Low; fix is localized to the relevant parsing code.

**Performance impact**

None. We parse the same way as before, but with the correct precedence.

**Is this a regression from a previous update?**

No. This is an error in the implementation of a new feature.

**Root cause analysis:**

We had a test hole for this particular combination of features. This PR adds a number of precedence tests for the feature so that the bug cannot recur undetected.

**How was the bug found?**

Customer report.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 1]
```diff
@@ -532,5 +532,379 @@ public void TypeDisambiguation_03()
...
+                    N(SyntaxKind.IdentifierToken, "B");
+                }
+            }
+            EOF();
+        }
+
+        [Fact, WorkItem(15734, "https://github.com/dotnet/roslyn/issues/15734")]
+        public void PatternExpressionPrecedence04()
+        {
+            UsingExpression("A is null & B");
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: You added tests with operators ==, <, <<, & and &&.
Would it make sense to have tests for other (higher-precedence) operators like + or *?
What about another `is` (although that doesn't seem very useful)?

**Comment by gafter** [comment]
@MattGertz May I please have approval? I crave approval.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 2]
```diff
@@ -39,67 +41,40 @@ private CSharpSyntaxNode ParseTypeOrPattern()
...
-                            node = _syntaxFactory.DeclarationPattern(type, designation);
-                        }
+                        var designation = ParseSimpleDesignation();
+                        return _syntaxFactory.DeclarationPattern(type, designation);
                     }
 
-                    if (node == null)
+                    tk = this.CurrentToken.ContextualKind;
+                    if ((!IsExpectedBinaryOperator(tk) || GetPrecedence(SyntaxFacts.GetBinaryExpression(tk)) <= precedence) &&
+                        // member selection is not formally a binary operator but has higher precedence than relational
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: An is pattern expression is a kind of relational expression, however, "relational expression" refers to a precedence level.

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: No, I don't think so. I tested for a couple of examples on each side of the precedence table, including the immediate neighbors and operators at the same precedence. We do not have exhaustive testing for other operators, and I don't think there is value to doing that here.

Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: By the way, we actually do have tests for `+` and `*` on the right of a pattern-matching `is` elsewhere in the test suite.

**Comment by gafter** [comment]
@MattGertz @kevinpi @ManishJayaswal May I please have approval? I crave approval.

**Comment by gafter** [comment]
@MattGertz @kevinpi @ManishJayaswal @jaredpar May I please have approval? I crave approval.

**Comment by gafter** [comment]
@srivatsn May I please have approval?
