### PR TITLE
Fix negation of is true and is false patterns with non-Boolean values

### LINKED ISSUE #64292: VS refactor suggests an incorrect pattern matching for `!(a?b is true | false)`
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-refactor-suggests-an-incorrect-patter/10156290)._

---
VS refactor suggests expression like `!(a?.b is true)` to `a?.b is false`, which is incorrect because of nonequivalent. 

---
#### Feedback Bot on 9/25/2022, 06:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by kimsey0**
Fixes #64292.

@CyrusNajmabadi, you seem to have written this negation code originally. Can you consult on this pull request? It's my first one to the Roslyn repository, and despite reading all the documentation on contributing, I'm still a bit unsure about the exact way forward.

### CODE REVIEW

**Comment by kimsey0** [comment]
(I'm off for tonight, so I'll see any comments in the morning.)

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs [hunk 1]
```diff
@@ -48,6 +48,18 @@ internal static partial class SyntaxGeneratorExtensions
             SemanticModel semanticModel,
             bool negateBinary,
             CancellationToken cancellationToken)
+        {
+            return Negate(generator, generatorInternal, expressionOrPattern, semanticModel, negateBinary, swapBooleans: true, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:52]: I'm curious why we're always passing true here, instead of basing it off of the expression being negated.  Could we do that?  If not, could you doc the reasoning here?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Looking really good!

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs (hunk 1 above)
Comment (kimsey0) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:52]: The idea was just to keep the existing behavior, except for calls from `GetNegationOfIsPatternExpression` where we know whether swapping `true` and `false` is valid or not based on the value type in the is pattern. I don't really know how we would base the `swapBooleans` argument here on the expression, since the analysis of the expression that determines that happens inside the `Negate` method we are calling. Maybe I'm misunderstanding you?

An alternative could be to remove the `swapBooleans` parameter again and just check for constant patterns in `GetNegationOfIsPatternExpression` and directly call `GetNegationOfConstantPattern` with `swapBooleans: true`. I'll just look into whether a similar problem exists for inequality patterns, as suggested by @jnm2 [here](https://github.com/dotnet/roslyn/issues/64292#issuecomment-1269181687), and how that affects this code.

Comment (kimsey0) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:52]: On a related note, if we keep this parameter, maybe it should be called `allowSwappingBooleans` instead.

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:52]: i think i get it :)  this seems reasonable.

> aybe it should be called allowSwappingBooleans instead.

i like that :)   could you make that change?  i'll sign off and merge then :)

Comment (kimsey0) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs]: Thanks! Done.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs [hunk 2]
```diff
@@ -229,7 +241,10 @@ private static SyntaxNode GetNegationOfIsPatternExpression(SyntaxNode isExpressi
             if (syntaxFacts.SupportsNotPattern(semanticModel.SyntaxTree.Options))
             {
                 // We do support 'not' patterns.  So attempt to push a 'not' pattern into the current is-pattern RHS.
-                negatedPattern = generator.Negate(generatorInternal, pattern, semanticModel, cancellationToken);
+                // If the value isn't a Boolean and the pattern `is true/false`, swapping to `is false/true` is incorrect since non-Booleans match neither.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:244]: nit: it's often good to add an example to demonstrate the problem.  but not required.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs (hunk 2 above)
Comment (kimsey0) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:244]: We can just add one if you'd like.

```suggestion
                // If the value isn't a Boolean and the pattern `is true/false`, swapping to `is false/true` is incorrect since non-Booleans match neither.
                // As an example, `!(new object() is true)` is equivalent to `new object() is not true` but not `new object() is false`.
```

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs:244]: perfect, thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks very much!
