### PR TITLE
display the class's doc comment in attribute quick info

### LINKED ISSUE #1696: QuickInfo and Doc comments for Attributes
Ported from TFS WorkItem: **766371**

------------------------------

**Repro Steps:**

I'm sure this must have come up before but I wanted to double check. 

Consider the following piece of code, In Roslyn, TestClass and TestMethod binds to their ctors and hence quick info shows the ctor's doc comment which is always

> Initializes a new instance of some class.

Whereas the really useful comment is the Class' summary itself. something like used to identify test methods and this class cannot be inherited etc.

While we may be more accurate in binding to the right symbol, I feel that the doc comment in quick info for attributes is now useless?

``` C#
[TestClass]
public class UnitTest1 
{
    [TestMethod]
    public void TestMethod1()
    {
    }
} 
```

------------------------------

**Revisions:**

1) Created By Balaji Krishnan (8/22/2013 7:16:57 PM)

------------------------------

2) Edited By Prakash Balasubramanian (4/17/2014 9:59:06 AM)

Do you have any ideas on what we could show here? Maybe concatenating the comments?

------------------------------

3) Edited By Kevin Pilch-Bisson (2/20/2015 3:17:56 PM)

Let's just special case attributes and go back to what Dev12 did.

------------------------------

### PR DESCRIPTION
**Pull request by brettfo**
When displaying quick info for attributes, the attribute binds to the constructor symbol so that's where the doc comment is pulled from.  As discussed in the bug, this fix is to special-case attributes to show the type's doc comment instead of the .ctor.

Fixes #1696.

Tagging @Pilchie @dpoeschl @jasonmalinowski @rchande @balajikris @basoundr for review.

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/Providers/AbstractSemanticQuickInfoProvider.cs [hunk 1]
```diff
@@ -231,7 +233,17 @@ internal abstract partial class AbstractSemanticQuickInfoProvider : AbstractQuic
             {
                 var symbol = symbols.First().OriginalDefinition;
 
-                var documentation = symbol.GetDocumentationParts(semanticModel, position, formatter, cancellationToken);
+                // if generating quick info for an attribute, bind to the class instead of the constructor
+                if (token.GetAncestors(t => IsAttributeSyntax(t)).Any())
+                {
+                    var attributeType = semanticModel.Compilation.GetTypeByMetadataName("System.Attribute");
```
Comment (rchande) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/Providers/AbstractSemanticQuickInfoProvider.cs]: Might as well use ITypeSymbolExtensions.IsAttribute, since that's good enough everywhere else.

Comment (rchande) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/Providers/AbstractSemanticQuickInfoProvider.cs]: ISyntaxFactsServices.IsAttributeName(token.Parent)?

**Comment by rchande** [comment]
:+1:

**Comment by dpoeschl** [comment]
retest this please

**Comment by brettfo** [comment]
Updated with @rchande's suggestions.

**Comment by dpoeschl** [comment]
retest this please

**Comment by brettfo** [comment]
Ping for senior level sign-off.

**Comment by Pilchie** [comment]
:+1:
