### PR TITLE
"Add null check" inserts single line statements if preferred

### LINKED ISSUE #52385: Support single-line null checks for 'Add null check'
**Version Used**: VS 16.9.3

This is the most frequent ReSharper command that I use. Roslyn's code fix requires tedious cleanup because it generates five lines per parameter. The chances are not high that I'm going to start being okay with five lines per parameter. The contrast in friction  is significant for me; with ReSharper, I'm not always cleaning up after I click.

```cs
using System;

public class C
{
    public void M(object first, object second, object third)
    {
        if (first is null)
        {
            throw new ArgumentNullException(nameof(first));
        }

        if (second is null)
        {
            throw new ArgumentNullException(nameof(second));
        }

        if (third is null)
        {
            throw new ArgumentNullException(nameof(third));
        }

        Console.WriteLine($"{first}: {second} ({third})");
    }
}
```

I want exactly what ReSharper does with a single command (except I have to insert the blank line myself, so Roslyn could even beat ReSharper here):

```cs
using System;

public class C
{
    public void M(object first, object second, object third)
    {
        if (first is null) throw new ArgumentNullException(nameof(first));
        if (second is null) throw new ArgumentNullException(nameof(second));
        if (third is null) throw new ArgumentNullException(nameof(third));

        Console.WriteLine($"{first}: {second} ({third})");
    }
}
```

### PR DESCRIPTION
**Pull request by MaStr11**
Fixes #52385

* [x] Respect `csharp_prefer_braces`
* [x] Respect `csharp_style_allow_embedded_statements_on_same_line_experimental`
* [x] string.IsNullOrEmpty is handled also
* [ ] What about https://github.com/dotnet/roslyn/issues/52385#issuecomment-812893055

### CODE REVIEW

**Comment by MaStr11** [comment]
It seems, `csharp_prefer_braces` is already respected in `CodeAction.PostProcessChangesAsync`. Braces are removed by `Simplifier.ReduceAsync` here:

https://github.com/dotnet/roslyn/blob/9dad013b7a3fabeb1b4f36e260ed9c6e3344548e/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs#L283-L297

Afterwards the document looks like this (`syntaxRoot.ToFullString()`):
```CS

using System;

class C
{
    public C(object o)
    {
if(oisnull)thrownew ArgumentNullException(nameof(o));    }
}
```

The next change happens in `Formatter.FormatAsync(SyntaxAnnotation.ElasticAnnotation)` afterwards it looks like this:

```CS

using System;

class C
{
    public C(object o)
    {
        if (o is null)
            throw new ArgumentNullException(nameof(o));
    }
}
```

It seems `csharp_style_allow_embedded_statements_on_same_line_experimental` is not respected by `Formatter.FormatAsync(document, SyntaxAnnotation.ElasticAnnotation)`.

**Comment by CyrusNajmabadi** [comment]
> csharp_style_allow_embedded_statements_on_same_line_experimental is not respected by Formatter.FormatAsync(document, 

'Allow' does not mean 'require'. It just means it is on if the user does that. 

The fix is to check for both of these and not have elastic trivia after the close paren or before the throw keyword. Thanks!

**Comment by MaStr11** [comment]
> 'Allow' does not mean 'require'. It just means it is on if the user does that.

But shouldn't `Formatter.FormatAsync(SyntaxAnnotation.ElasticAnnotation)` respect `csharp_style_allow_embedded_statements_on_same_line_experimental`?

> The fix is to check for both of these and not have elastic trivia after the close paren or before the throw keyword. Thanks!

I tried to find the `SyntaxAnnotation.ElasticAnnotation` on any of the descendants nodes and tokens of the generated if statement but couldn't find any. So I think the `Formatter.FormatAsync(SyntaxAnnotation.ElasticAnnotation)` needs to be touched, or do I miss something?

**Comment by MaStr11** [comment]
Okay. I found the `ElasticAnnotation`s in the trivia. Overall there are 49 such annotations (empty whitespace with the elastic marker). Do I really need to remove it? The problem is that the statement syntax tree is generated in a language neutral manner, so I can't influence the ElasticAnnotation placement there:

https://github.com/dotnet/roslyn/blob/95bcec2dab1ff0984cf581fd2d404739eebf5ded/src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs#L376-L377

**Comment by CyrusNajmabadi** [comment]
> But shouldn't Formatter.FormatAsync(SyntaxAnnotation.ElasticAnnotation) respect csharp_style_allow_embedded_statements_on_same_line_experimental?

No.  Because the general pattern in the ecosystem is to still place them on multiple lines.  This is jsut a way for clients to say if it's should be considered *illegal* to be on the same line.  Not that it is *preferred* that they be on the same line.  They're very different concepts.

**Comment by CyrusNajmabadi** [comment]
>  Do I really need to remove it?

Yes.  i would not include the trivia between those two tokens.  :)  I wouldn't remove them after the fact, i woudl just not add them in the first place.

**Comment by MaStr11** [comment]
> Yes. i would not include the trivia between those two tokens. :) I wouldn't remove them after the fact, i woudl just not add them in the first place.

I finally got this approach working. 0f157af5 shows that the close brace and the throw keyword need both trivia handling to avoid the line break/indentation. I think the way forward here is to move away from `SyntaxGenerator`. Am I right, or should we add overloads for trivia handling?

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs [hunk 1]
```diff
@@ -190,11 +190,20 @@ private static SyntaxNode CreateNewArgumentNullException(SyntaxGenerator factory
...
                 SpecializedCollections.SingletonEnumerable(
-                    factory.ThrowStatement(CreateNewArgumentNullException(
-                        factory, semanticModel.Compilation, parameter))));
+                    throwStatement));
+
+            var close = ifStatement.FindToken(10);
+            var newClose = close.WithoutTrailingTrivia();
+            ifStatement = ifStatement.ReplaceToken(close, newClose);
+
+            return ifStatement;
```
Comment (MaStr11) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs:206]: Both, the `throw` keywords leading trivia and the `)` of the if condition need their respective trivia `SyntaxAnnotation.ElasticAnnotation` removed.

**Comment by CyrusNajmabadi** [comment]
> I think the way forward here is to move away from SyntaxGenerator and use abstract methods in AbstractAddParameterCheckCodeRefactoringProvider instead. Am I right, or should we add overloads for trivia handling?

This seems reasonable.

File: src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs [hunk 2]
```diff
@@ -2046,5 +2046,219 @@ public C(string s)
...
+    {
+        if (o is null)
+            throw new ArgumentNullException(nameof(o));
+    }
+}",
+                Options =
+                {
+                    { CSharpCodeStyleOptions.PreferThrowExpression, false, NotificationOption2.Silent },
+                    { CSharpCodeStyleOptions.PreferBraces, PreferBracesPreference.None, NotificationOption2.Silent },
+                    { CSharpCodeStyleOptions.AllowEmbeddedStatementsOnSameLine, false, NotificationOption2.Silent },
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs:2080]: We can simplify this by just using the default severity.

```suggestion
                    { CSharpCodeStyleOptions.PreferThrowExpression, false },
                    { CSharpCodeStyleOptions.PreferBraces, PreferBracesPreference.None },
                    { CSharpCodeStyleOptions.AllowEmbeddedStatementsOnSameLine, false },
```

File: src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs [hunk 3]
```diff
@@ -2046,5 +2046,219 @@ public C(string s)
...
+        public async Task SingleLineStatement_NullCheck_BracesNone_SameLineFalse()
+        {
+            await new VerifyCS.Test
+            {
+                TestCode = @"
+using System;
+
+class C
+{
+    public C([||]object o)
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs:2061]:
```suggestion
    public C($$object o)
```

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs [hunk 4]
```diff
@@ -190,11 +190,20 @@ private static SyntaxNode CreateNewArgumentNullException(SyntaxGenerator factory
...
+            throwStatement = throwStatement.WithLeadingTrivia(factory.Whitespace(" ")).WithoutAnnotations(SyntaxAnnotation.ElasticAnnotation);
+
+            var ifStatement = factory.IfStatement(
                condition,
                 SpecializedCollections.SingletonEnumerable(
-                    factory.ThrowStatement(CreateNewArgumentNullException(
-                        factory, semanticModel.Compilation, parameter))));
+                    throwStatement));
+
+            var close = ifStatement.FindToken(10);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs:202]: > 10

😕

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs [hunk 5]
```diff
@@ -190,11 +190,20 @@ private static SyntaxNode CreateNewArgumentNullException(SyntaxGenerator factory
                 : factory.ReferenceEqualsExpression(identifier, nullExpr);
 
             // generates: if (s == null) throw new ArgumentNullException(nameof(s))
-            return factory.IfStatement(
+            var throwStatement = factory.ThrowStatement(CreateNewArgumentNullException(
+                                    factory, semanticModel.Compilation, parameter));
+            throwStatement = throwStatement.WithLeadingTrivia(factory.Whitespace(" ")).WithoutAnnotations(SyntaxAnnotation.ElasticAnnotation);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs:195]: > `factory.Whitespace(" ")`

💭 Can we not use `SyntaxFactory.Space` for this?

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs [hunk 6]
```diff
@@ -190,11 +190,20 @@ private static SyntaxNode CreateNewArgumentNullException(SyntaxGenerator factory
...
+            var ifStatement = factory.IfStatement(
                condition,
                 SpecializedCollections.SingletonEnumerable(
-                    factory.ThrowStatement(CreateNewArgumentNullException(
-                        factory, semanticModel.Compilation, parameter))));
+                    throwStatement));
+
+            var close = ifStatement.FindToken(10);
+            var newClose = close.WithoutTrailingTrivia();
+            ifStatement = ifStatement.ReplaceToken(close, newClose);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs:204]: Is this not the same?

```
ifStatement = ifStatement.WithoutTrailingTrivia();
```

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs (hunk 4 above)
Comment (MaStr11) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs:202]: This whole approach was just to see which elastic markers need to be removed to get the whole thing through the formatter. It also shows that the language agnostic syntax generator approach is just not working is this case.

**Comment by MaStr11** [comment]
@CyrusNajmabadi and @sharwell Ready for review.

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb [hunk 7]
```diff
@@ -54,5 +54,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
         Protected Overrides Function EscapeResourceString(input As String) As String
             Return input.Replace("""", """""")
         End Function
+
+        Protected Overrides Function CreateParameterCheckIfStatement(options As DocumentOptionSet, condition As ExpressionSyntax, ifTrueStatement As StatementSyntax) As StatementSyntax
+            Return SyntaxFactory.MultiLineIfBlock(
```
Comment (sharwell) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb:59]: 💭 Technically we could do the same thing here, but I'm not sure it's common enough to need to. I'd be fine leaving it as a follow-up, especially considering `AllowEmbeddedStatementsOnSameLine` would need to be moved to the shared options first.

**Review by sharwell — CHANGES_REQUESTED** [review]
The implementation seems fine. I would like to see new tests added for the "Fix All" case before merging.

File: src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs [hunk 8]
```diff
@@ -1748,7 +1748,8 @@ public C(string s)
 }",
                 Options =
                 {
-                    { CSharpCodeStyleOptions.PreferBraces, new CodeStyleOption2<PreferBracesPreference>((PreferBracesPreference)preferBraces, NotificationOption2.Silent) }
+                    { CSharpCodeStyleOptions.PreferBraces, new CodeStyleOption2<PreferBracesPreference>((PreferBracesPreference)preferBraces, NotificationOption2.Silent) },
+                    { CSharpCodeStyleOptions.AllowEmbeddedStatementsOnSameLine, false },
```
[the remark this answers is not in the document]
Comment (MaStr11) [reply src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs]: Done in 7205621

File: src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs [hunk 9]
```diff
@@ -2046,5 +2047,441 @@ public C(string s)
     }
 }");
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInitializeParameter)]
+        [WorkItem(52385, "https://github.com/dotnet/roslyn/issues/52385")]
+        public async Task SingleLineStatement_NullCheck_BracesNone_SameLineFalse()
```
[the remark this answers is not in the document]
Comment (MaStr11) [reply src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs:2051]: Done in 0318ce5

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb:59]: agreed.

fwiw, we don't check AllowEmbeddedStatementsOnSameLine  in vb at all.  it was really intended for the C# case (and may just be a c# option currently).  we have very little use of this pattern in vb.

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb [hunk 10]
```diff
@@ -54,5 +54,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
...
+                SyntaxFactory.IfStatement(SyntaxFactory.Token(SyntaxKind.IfKeyword), condition, SyntaxFactory.Token(SyntaxKind.ThenKeyword)),
+                New SyntaxList(Of StatementSyntax)(ifTrueStatement),
+                Nothing,
+                Nothing)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb:63]: nit: named parameters plz.

**Review by CyrusNajmabadi — APPROVED** [review]
Thanks!  @jnm2 will appreciate this a lot :)

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb (hunk 10 above)
Comment (MaStr11) [reply src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb]: Done in a557a4a

**Review by sharwell — APPROVED** [review]
