### PR TITLE
Fix Extract Method and Generate Variables in Conditional Access Expressions

### LINKED ISSUE #751: Extract Method incorrect selection expansion in Null propagation causes Assert fail followed by null ref exception at binder "SyntaxFactory.FindConditionalAccessNodeForBinding"
Ported from TFS WorkItem: **1103283**

------------------------------

**Repro Steps:**

1. open VS.

2. paste the following code..

3. Select highlighted code and hit Ctrl + .

&nbsp;

Note that this would repro only the first time in VS since this was triggered by a code action and we immediately disable faulty code actions. One needs to restart VS to repro again.

&nbsp;

code:
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">;</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">static</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">string</SPAN><SPAN style="COLOR: black">[]</SPAN> <SPAN style="COLOR: black">args</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: #2b91af">A</SPAN> <SPAN style="COLOR: black">a</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: blue">new</SPAN> <SPAN style="COLOR: #2b91af">A</SPAN><SPAN style="COLOR: black">();</SPAN>
        <SPAN style="COLOR: blue">var</SPAN> <SPAN style="COLOR: black">l</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: black">a</SPAN><SPAN style="COLOR: black">?.</SPAN><SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #ffff00">Prop</FONT></SPAN><SPAN style="COLOR: black">?.</SPAN><SPAN style="COLOR: black">Length</SPAN> <SPAN style="COLOR: black">??</SPAN> <SPAN style="COLOR: black">0</SPAN><SPAN style="COLOR: black">;</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">A</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: #2b91af">B</SPAN> <SPAN style="COLOR: black">Prop</SPAN> <SPAN style="COLOR: black">{</SPAN> <SPAN style="COLOR: blue">get</SPAN><SPAN style="COLOR: black">;</SPAN> <SPAN style="COLOR: blue">set</SPAN><SPAN style="COLOR: black">;</SPAN> <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">B</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">Length</SPAN> <SPAN style="COLOR: black">{</SPAN> <SPAN style="COLOR: blue">get</SPAN><SPAN style="COLOR: black">;</SPAN> <SPAN style="COLOR: blue">set</SPAN><SPAN style="COLOR: black">;</SPAN> <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

------------------------------

**Revisions:**

1) Created By Balaji Krishnan (1/7/2015 11:51:33 AM)

System.Exception: binding should be enclosed in a conditional access <br>1/7/2015 11:46:10 AM<br>Source:&nbsp;&nbsp;&nbsp; at  at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Syntax\SyntaxFactory.cs:line 1676<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6368<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6337<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 457<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2813<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 76<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2056<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2042<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean generateDebugInfo, ConsList`1&amp; debugImports) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1407<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers&amp; processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 838<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 442<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.&lt;&gt;c__DisplayClass4.&lt;CompileNamedTypeAsTask&gt;b__5() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 342<br>&nbsp;&nbsp; at System.Threading.Tasks.Task`1.InnerInvoke()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.Execute()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)<br>&nbsp;&nbsp; at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)<br>&nbsp;&nbsp; at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)<br>&nbsp;&nbsp; at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)<br>&nbsp;&nbsp; at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.WrappedTryRunInline()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 256<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 142<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2050<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2218<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 127<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.&lt;HasAnyErrors&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Shared\Extensions\DocumentExtensions.cs:line 101<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.HasAnyErrors(Document document, CancellationToken cancellationToken, List`1 ignoreErrorCode)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.&lt;ReduceAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\AbstractSimplificationService.cs:line 60<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.ReduceAsync(Document document, IEnumerable`1 spans, OptionSet optionSet, IEnumerable`1 reducers, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.Simplifier.ReduceAsync(Document document, IEnumerable`1 spans, OptionSet optionSet, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\Simplifier.cs:line 117<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.Simplifier.&lt;ReduceAsync&gt;d__2.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\Simplifier.cs:line 99<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.Simplifier.ReduceAsync(Document document, SyntaxAnnotation annotation, OptionSet optionSet, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.CodeGenerator.cs:line 93<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync(CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\CSharp\ExtractMethod\CSharpMethodExtractor.CSharpCodeGenerator.cs:line 32<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateAsync(InsertionPoint insertionPoint, SelectionResult selectionResult, AnalyzerResult analyzerResult, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.GenerateCodeAsync(InsertionPoint insertionPoint, SelectionResult selectionResult, AnalyzerResult analyzeResult, CancellationToken cancellationToken) in E:\Roslyn\Main\Closed\Features\CSharp\ExtractMethod\CSharpMethodExtractor.cs:line 73<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.cs:line 56<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\AbstractExtractMethodService.cs:line 39<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodService.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\ExtractMethodService.cs:line 13<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;GetCodeActionAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 61<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.GetCodeActionAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;ComputeRefactoringsAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 46<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;GetRefactoringFromProviderAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 107<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan state, CodeRefactoringProvider provider, IExtensionManager extensionManager, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;&gt;c__DisplayClass12.&lt;&lt;GetRefactoringsAsync&gt;b__14&gt;d__0.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 70<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;&gt;c__DisplayClass12.&lt;GetRefactoringsAsync&gt;b__14()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task`1.InnerInvoke()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.Execute()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)<br>&nbsp;&nbsp; at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)<br>&nbsp;&nbsp; at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()<br>&nbsp;&nbsp; at System.Threading.ThreadPoolWorkQueue.Dispatch()<br>&nbsp;&nbsp; at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

StackTrace: 

&nbsp;

&nbsp;

=========================================================

&nbsp;

&nbsp;

System.NullReferenceException: Object reference not set to an instance of an object.<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Syntax\SyntaxFactory.cs:line 1678<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6368<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6337<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 457<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2813<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 76<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2056<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2042<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean generateDebugInfo, ConsList`1&amp; debugImports) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1407<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers&amp; processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 838<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 442<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.&lt;&gt;c__DisplayClass4.&lt;CompileNamedTypeAsTask&gt;b__5() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 342<br>&nbsp;&nbsp; at System.Threading.Tasks.Task`1.InnerInvoke()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.Execute()<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 256<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 142<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2050<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2218<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 127<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.&lt;HasAnyErrors&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Shared\Extensions\DocumentExtensions.cs:line 101<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.&lt;ReduceAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\AbstractSimplificationService.cs:line 60<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.Simplifier.&lt;ReduceAsync&gt;d__2.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\Simplifier.cs:line 99<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.CodeGenerator.cs:line 93<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\CSharp\ExtractMethod\CSharpMethodExtractor.CSharpCodeGenerator.cs:line 32<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.cs:line 56<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\AbstractExtractMethodService.cs:line 39<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;GetCodeActionAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 61<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;ComputeRefactoringsAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 46<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;GetRefactoringFromProviderAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 108<br>1/7/2015 11:46:10 AM<br>Source: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: Microsoft.CodeAnalysis.CSharp<br>StackTrace:&nbsp;&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Syntax\SyntaxFactory.cs:line 1678<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6368<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6337<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 457<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2813<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 76<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2056<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2042<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean generateDebugInfo, ConsList`1&amp; debugImports) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1407<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers&amp; processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 838<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 442<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.&lt;&gt;c__DisplayClass4.&lt;CompileNamedTypeAsTask&gt;b__5() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 342<br>&nbsp;&nbsp; at System.Threading.Tasks.Task`1.InnerInvoke()<br>&nbsp;&nbsp; at System.Threading.Tasks.Task.Execute()<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 256<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 142<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2050<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2218<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 127<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.&lt;HasAnyErrors&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Shared\Extensions\DocumentExtensions.cs:line 101<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.&lt;ReduceAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\AbstractSimplificationService.cs:line 60<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Simplification.Simplifier.&lt;ReduceAsync&gt;d__2.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Simplification\Simplifier.cs:line 99<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.CodeGenerator.cs:line 93<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.&lt;GenerateAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\CSharp\ExtractMethod\CSharpMethodExtractor.CSharpCodeGenerator.cs:line 32<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\MethodExtractor.cs:line 56<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.&lt;ExtractMethodAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\ExtractMethod\AbstractExtractMethodService.cs:line 39<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;GetCodeActionAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 61<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.&lt;ComputeRefactoringsAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 46<br>--- End of stack trace from previous location where exception was thrown ---<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()<br>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;GetRefactoringFromProviderAsync&gt;d__1.MoveNext() in E:\Roslyn\Main\Closed\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 108

------------------------------

2) Edited By Aleksey Tsingauz (1/7/2015 1:54:15 PM)

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font size=3><font color="#000000"><font face=Calibri>It looks like IDE code creates malformed syntax tree and gives it to compiler (MemberBindingExpression is used as an expression for return statement):</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri>privatestaticglobal::BNewMethod(){return<span style="BACKGROUND:yellow;">.Prop</span>;}}</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>&nbsp;</font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font size=3><font color="#000000"><font face=Calibri>Here is a call stack when such node is created for the first time:</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.ReturnStatementSyntax.ReturnStatementSyntax(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CSharpSyntaxNode green, Microsoft.CodeAnalysis.SyntaxNode parent, int position) Line 54138<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ReturnStatementSyntax.CreateRed(Microsoft.CodeAnalysis.SyntaxNode parent, int position) Line 11725<span style="">&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GreenNode.CreateRed() Line 728<span style="">&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ReturnStatement(Microsoft.CodeAnalysis.SyntaxToken returnKeyword, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, Microsoft.CodeAnalysis.SyntaxToken semicolonToken) Line 72563<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ReturnStatement(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression) Line 72569<span style="">&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri>&gt;<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetInitialStatementsForMethodDefinitions() Line 111<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.CreateMethodBody(System.Threading.CancellationToken cancellationToken) Line 209<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateMethodDefinition(System.Threading.CancellationToken cancellationToken) Line 83<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator&lt;Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax,Microsoft.CodeAnalysis.SyntaxNode&gt;.GenerateAsync(System.Threading.CancellationToken cancellationToken) Line 86<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateAsync(Microsoft.CodeAnalysis.ExtractMethod.InsertionPoint insertionPoint, Microsoft.CodeAnalysis.ExtractMethod.SelectionResult selectionResult, Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.AnalyzerResult analyzerResult, System.Threading.CancellationToken cancellationToken) Line 32<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.GenerateCodeAsync(Microsoft.CodeAnalysis.ExtractMethod.InsertionPoint insertionPoint, Microsoft.CodeAnalysis.ExtractMethod.SelectionResult selectionResult, Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.AnalyzerResult analyzeResult, System.Threading.CancellationToken cancellationToken) Line 73<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(System.Threading.CancellationToken cancellationToken) Line 56<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService&lt;Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator,Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor,Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionResult&gt;.ExtractMethodAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 39<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodService.ExtractMethodAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 13<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.GetCodeActionAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) Line 61<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringContext context) Line 46<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan state, Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider provider, Microsoft.CodeAnalysis.Extensions.IExtensionManager extensionManager, System.Threading.CancellationToken cancellationToken) Line 107<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt 0.5in;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;</span><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringsAsync() Line 70<span style="">&nbsp; </span>C#</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>&nbsp;</font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>The same problem probably exists for ElementBindingExpression. Should check behavior for VB in similar scenarios (?., ?(), ?!).</font>

------------------------------

3) Edited By Balaji Krishnan (1/7/2015 2:10:44 PM)

Its ExtractMethod's fault then. should probably expand selection to be&nbsp;a?.Prop.

------------------------------

4) Edited By Balaji Krishnan (1/7/2015 2:12:34 PM)

didnt intend to file in RC. clearing Triage field so that triage gets to take a look.

------------------------------

5) Edited By Kevin Pilch-Bisson (2/15/2015 8:50:53 PM)

Move to GitHub

------------------------------

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #751.

Properly handle `ConditionalAccessExpressions` in `ExpressionSyntaxExtensions::CanReplaceWithLValue`. When conditional access expressions begin with some form of member binding expression (starts with the dot operator), they cannot be replaced with an LValue. @jmarolf contributed commit cf3dd54

This issue does not affect VB as VB language parses this differently than C#.

### CODE REVIEW

File: src/Features/CSharp/GenerateMember/GenerateVariable/CSharpGenerateVariableService.cs [hunk 1]
```diff
@@ -121,6 +121,11 @@ protected override bool ContainingTypesOrSelfHasUnsafeKeyword(INamedTypeSymbol c
                 return false;
             }
 
+            if (expression.IsParentKind(SyntaxKind.ConditionalAccessExpression))
+            {
+                return true;
+            }
+
```
Comment (jmarolf) [inline src/Features/CSharp/GenerateMember/GenerateVariable/CSharpGenerateVariableService.cs]: We now explicitly check since we know that the generate variable state machine can handle this case and bypass CanReplaceWithLValue entirely.

**Comment by balajikris** [comment]
tagging potential code reviewers @basoundr @brettfo @dpoeschl @rchande @Pilchie

**Comment by Pilchie** [comment]
:+1:

**Comment by brettfo** [comment]
:shipit:

**Comment by balajikris** [comment]
test this please
