### PR TITLE
Checking for writeable indexers in Use Range Operator feature

### LINKED ISSUE #43202: Use Range Operator should check for writable indexer
**Version Used**: 16.6 Preview 2

**Steps to Reproduce**:

```csharp
struct S
{
  public ref S Slice(int start, int length) => throw null;
  public int Length { get; }
  public S this[System.Range r] { get => default; }
}

class C
{
    void Goo(S s)
    {
        s.Slice(1, s.Length - 2) = default;
    }
}
```

**Expected Behavior**:

No code fix is offered to convert the `Slice` call to a range operator.

**Actual Behavior**:

The call is converted to this:

```csharp
s[1..^1] = default;
```

The result does not compile because the indexer is read only.

> error CS0200: Property or indexer 'S.this[Range]' cannot be assigned to -- it is read only

### PR DESCRIPTION
**Pull request by m-redding**
fixes #43202 

CC: @JavierMatosD 

@sharwell Could you take a look at the changes made to test case "TestNonStringType_Assignment"? The original version seemed to contradict the bug fix we made, but we want to be sure that the test case is not still valid under the new expected behavior.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=44951) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=44951) before we can accept your contribution.<br/><br/>:x: m-redding [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=44951)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=44951) it.</sub>

**Comment by jmarolf** [comment]
>         [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]

I would add `[WorkItem(43202, "[https://github.com/dotnet/roslyn/issues/43202](https://github.com/dotnet/roslyn/issues/43202) ")]` at the top so that we can find why this change was made

---
Refers to: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:323 in 5351a55. [](commit_id = 5351a5530c54a413e1953fd97a4dde86588a4235, deletion_comment = False)

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 1]
```diff
@@ -479,5 +468,32 @@ void Goo(Span<int> s)
                 FixedCode = fixedSource,
             }.RunAsync();
         }
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
+        public async Task TestWritableType()
```
Comment (jmarolf) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:472]: I do not think this test is necessary since its exactly matches the updated test up above

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 2]
```diff
@@ -330,25 +330,14 @@ class C
 {
     void Goo(S s)
     {
-        s.Slice([|1, s.Length - 2|]) = default;
+        s.Slice(1, s.Length - 2) = default;
```
Comment (jmarolf) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:333]: I would add [WorkItem(43202, "[https://github.com/dotnet/roslyn/issues/43202](https://github.com/dotnet/roslyn/issues/43202) ")] at the top so that we can find why this change was made

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 3]
```diff
@@ -479,5 +468,32 @@ void Goo(Span<int> s)
                 FixedCode = fixedSource,
             }.RunAsync();
         }
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:471]:
```suggestion

        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
```

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 4]
```diff
@@ -330,25 +330,14 @@ class C
...
-        s[1..^1] = default;
-    }
-}";
-
             await new VerifyCS.Test
             {
                 ReferenceAssemblies = ReferenceAssemblies.NetCore.NetCoreApp31,
                 TestCode = source,
-                FixedCode = fixedSource,
+                FixedCode = source,
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:340]: this is a regression.  We should update this code.  It's fine to assign in this case because the indexer returns by-ref as well.

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -130,6 +131,13 @@ protected override void InitializeWorker(AnalysisContext context)
                 return null;
             }
 
+            // If the target method is writeable then we need to make sure we do not change a writeable 
+            // indexer to a read-only indexer, otherwise it will cause compiler errors
+            if (invocation.TargetMethod.IsReadOnly == false && invocation.Parent != null && invocation.Syntax.IsLeftSideOfAnyAssignExpression())
+            {
+                return null;
+            }
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:139]: i don't think this is the right fix.  The check we should be making is that the original Slice/indexer match in by-ref semantics.

**Comment by CyrusNajmabadi** [comment]
Thanks for the contribution!

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -130,6 +131,14 @@ protected override void InitializeWorker(AnalysisContext context)
                 return null;
             }
 
+            var theIndexer = GetIndexer(targetMethod.ContainingType, infoCache.RangeType, targetMethod.ContainingType);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:134]:
```suggestion
            var indexer = TryGetIndexer(targetMethod.ContainingType, infoCache.RangeType, targetMethod.ContainingType);
```

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 7]
```diff
@@ -130,6 +131,14 @@ protected override void InitializeWorker(AnalysisContext context)
...
+            // If the slice-like method is being written to and returns a reference, we need to make sure that
+            // the range method to substitute also returns a reference that can be written to
+            if (invocation.Syntax.IsLeftSideOfAnyAssignExpression() && invocation.TargetMethod.ReturnsByRef == true && theIndexer != null && theIndexer.ReturnsByRef == false)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:137]:
```suggestion
            if (indexer != null && indexer.ReturnsByRef !=invocation.TargetMethod.ReturnsByRef &&  invocation.Syntax.IsLeftSideOfAnyAssignExpression())
```

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 8]
```diff
@@ -479,5 +478,33 @@ void Goo(Span<int> s)
                 FixedCode = fixedSource,
             }.RunAsync();
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:482]: needs WorkItem attribute thanks!

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:137]: although, my preference is simply that we update ComputeMemberInfo to only return an indexer if it matches the byref semantics of hte slice method.  i.e. the code to update would be hereish:

```
                // https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md#implicit-range-support
                if (sliceLikeMethod.ReturnType.Equals(containingType))
                {
                    // it's a method like:  MyType MyType.Get(int start, int length).  Look for an
                    // indexer like  `MyType MyType.this[Range range]`.
                    var indexer = GetIndexer(containingType, RangeType, containingType);
```

GetIndexer should probalby take a ReturnsByRef and only provides indexers that match.

**Comment by CyrusNajmabadi** [comment]
Can we fixul the titel of this PR to be clearer?  Thanks!

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs [hunk 9]
```diff
@@ -93,9 +93,16 @@ private MemberInfo ComputeMemberInfo(IMethodSymbol sliceLikeMethod, bool require
                 // https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md#implicit-range-support
                 if (sliceLikeMethod.ReturnType.Equals(containingType))
                 {
+                    var indexer = GetIndexer(containingType, RangeType, containingType);
+                    // If the slice like method and the indexer don't both return a Ref or not, then don't
+                    // convert
+                    if (indexer != null && indexer.ReturnsByRef != sliceLikeMethod.ReturnsByRef)
+                    {
+                        return default;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs:101]: i don't think we want to bail out.  we'd want to perform the rest of hte if-check still right?

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 10]
```diff
@@ -124,12 +125,22 @@ protected override void InitializeWorker(AnalysisContext context)
...
-                !infoCache.TryGetMemberInfo(targetMethod, out var memberInfo))
+                !valid)
             {
                 return null;
             }
 
+            // Need to make sure that if we are assigning values to the slice that both the slice-like method and the
+            // indexer are references
+            if (invocation.Syntax.IsLeftSideOfAnyAssignExpression() &&
+                !valid)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:138]: don't need multiple checks of `!valid`.  can be hoisted once after the TryGetMemberInfo right?

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 11]
```diff
@@ -479,5 +478,34 @@ void Goo(Span<int> s)
...
+        s.Slice(1, s.Length - 2) = default;
+    }
+}";
+
+            await new VerifyCS.Test
+            {
+                ReferenceAssemblies = ReferenceAssemblies.NetCore.NetCoreApp31,
+                TestCode = source,
+                FixedCode = source,
+            }.RunAsync();
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:508]: do we have a test where both indexer/method are by-ref?  If not, please add.  THanks!

Comment (m-redding) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:508]: Yes, It's on line 324.
`public async Task TestNonStringType_Assignment()
        {
            var source =
@"
struct S { public ref S Slice(int start, int length) => throw null; public int Length { get; } public ref S this[System.Range r] { get => throw null; } }
class C
{
    void Goo(S s)
    {
        s.Slice([|1, s.Length - 2|]) = default;
    }
}";
            var fixedSource =
@"
struct S { public ref S Slice(int start, int length) => throw null; public int Length { get; } public ref S this[System.Range r] { get => throw null; } }
class C
{
    void Goo(S s)
    {
        s[1..^1] = default;
    }
}";`

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 12]
```diff
@@ -124,12 +125,22 @@ protected override void InitializeWorker(AnalysisContext context)
...
+            {
+                return null;
+            }
+
+
```
Comment (jmarolf) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:143]: remove extra blank line

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 13]
```diff
@@ -479,5 +478,64 @@ void Goo(Span<int> s)
...
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
+        public async Task TestWritableType()
+        {
+            var source =
+@"
+using System;
+struct S { 
+    public ref S Slice(int start, int length) => throw null; 
+    public int Length { get; } 
+    public S this[System.Range r] { get => default; }
```
Comment (sharwell) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:492]: 💡 Also add a test just like this one, but with the argument to the indexer being `int` instead of `Range`. The refactoring should work in this case because the indexer syntax will continue to use the `Slice` method instead of the indexer with the wrong type.

Comment (sharwell) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:492]: 💡 Also add a test like this one, where the property is a read/write property (as opposed to a ref-returning property):

```
public S this[System.Range r] { get => default; set { } }
```

**Comment by m-redding** [comment]
Copying here to make this clearer: As stated in commit (https://github.com/dotnet/roslyn/pull/44951/commits/b08833b2870e688e3aab0b81caa14eecf5374fb3) I attempted to move the if-statement to the ComputeMemberInfo method, however it seems that the necessary information for the IsLeftSideOfAnyAssignExpression() can only been found in the Analyzer, so I decided to keep the if-statement where it was previously.

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs (hunk 7 above)
Comment (m-redding) [reply src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs]: I tried quite a few different approaches to accessing the same information through ComputeMemberInfo but I wasn't able to get the IsLeftSideOfAnyAssignExpression information without adding some kind of argument to the method so I decided to keep it as is.

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs [hunk 14]
```diff
@@ -128,9 +128,10 @@ private MemberInfo ComputeMemberInfo(IMethodSymbol sliceLikeMethod, bool require
                 // https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md#implicit-range-support
                 if (sliceLikeMethod.ReturnType.Equals(containingType))
                 {
+                    var indexer = GetIndexer(containingType, RangeType, containingType);
+
                     // it's a method like:  MyType MyType.Get(int start, int length).  Look for an
                     // indexer like  `MyType MyType.this[Range range]`.
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs:134]:
```suggestion
                    // it's a method like:  MyType MyType.Get(int start, int length).  Look for an
                    // indexer like  `MyType MyType.this[Range range]`.
                    var indexer = GetIndexer(containingType, RangeType, containingType);
```

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs [hunk 15]
```diff
@@ -165,8 +166,17 @@ protected override void InitializeWorker(AnalysisContext context)
             // Second arg needs to be a subtraction for: `end - e2`.  Once we've seen that we have
             // that, try to see if we're calling into some sort of Slice method with a matching
             // indexer or overload
+            var valid = infoCache.TryGetMemberInfo(targetMethod, out var memberInfo);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs:169]: why was this extracted?

Comment (m-redding) [reply src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs]: Just fixed, I had been using valid for something else later but then removed it
