### PR TITLE
ToBadExpression() checking incorrect HasAnyErrors API

### LINKED ISSUE #26516: Exception binding bad ref
Consider the following code:

``` c#
using System;
public class C {
    void G() { } 
    public void M() {
        int x = 42;
        G(ref void = ref x);
    }
}
```

This causes a cash in `BindAssignment` because it ends up calling `GetRefKind` on the void expression. 

``` txt
ystem.InvalidOperationException: Unexpected value 'TypeExpression' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionExtensions.GetRefKind(BoundExpression node) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\BoundTree\BoundExpressionExtensions.cs:line 34
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1315
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 404
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(DiagnosticBag diagnostics, ExpressionSyntax argumentExpression, RefKind refKind, Boolean allowArglist) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2494
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2270
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2235
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 148
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 384
```

### LINKED ISSUE #26978: Binding DynamicMemberAccess expressions crashes VS
```csharp
class C
{
    void M(dynamic x)
    {
        x.test = ref x;
    }
}
```
Result on latest master:
```
System.InvalidOperationException: Unexpected value 'DynamicMemberAccess' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionExtensions.GetRefKind(BoundExpression node) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\BoundTree\BoundExpressionExtensions.cs:line 34
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1315
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 404
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 329
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 566
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 559
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1599
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 43
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3073
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3021
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, ValueTuple`3& forSemanticModel) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1622
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 943
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 494
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 384
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #26516 
Fixes #26978

Bound nodes have two APIs to check for errors:
* `HasErrors` which is a fast flag that is set during creating the bound node (if an obvious semantic error). It does not guarentee that there are not other syntactical errors associated with the node.
* `HasAnyErrors` is slower, and used during binding to do a full check on including associated syntax nodes.

When calling the API `Binder.ToBadExpression()`, the caller should expect the returned `BoundBadExpression` to have `HasErrors` as true. However, as an optimization, this method checks the node if it `HasAnyErrors`, and returns it unchanged if so. Because of this mismatch, it will incorrectly return a node with `HasErrors=false` and `HasAnyErrors=true`, which violates the contract.

cc @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by jaredpar** [comment]
approved

**Comment by OmarTawfik** [comment]
I fixed a couple of bound nodes where they were not setting the flag correctly. That had a few tests failing because of my change.
Additionally, there was a few tests where these bound nodes were not initialized correctly, thus we were emitting more diagnostics than we intended. I'm fixing these now.

File: src/Compilers/CSharp/Portable/BoundTree/Constructors.cs [hunk 1]
```diff
@@ -406,7 +406,7 @@ internal sealed partial class BoundCompoundAssignmentOperator
     internal sealed partial class BoundParameter
     {
         public BoundParameter(SyntaxNode syntax, ParameterSymbol parameterSymbol, bool hasErrors = false)
-            : this(syntax, parameterSymbol, parameterSymbol.Type, hasErrors)
+            : this(syntax, parameterSymbol, parameterSymbol.Type, hasErrors || parameterSymbol.Type.IsErrorType())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/Constructors.cs]: >|| parameterSymbol.Type.IsErrorType() [](start = 76, length = 37)

I do not understand the motivation for the changes in the second commit and I am not sure they are necessary.

Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/BoundTree/Constructors.cs]: Discussed offline. There are ~200 tests failing because of the fix, and most of them just need updating the baseline. I'm reviewing the rest now.

**Comment by etbyrd** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by etbyrd** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by etbyrd** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by etbyrd** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by OmarTawfik** [comment]
@AlekseyTs @jcouv @gafter This is now ready for review.

I undid the original fix (filed #27299 for it), and did a simple workaround now. The original fix creeped to hundreds of test failures and thousands of changes that we need to investigate accordingly, and I don't think we can fit it in the 15.8 time frame.

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

**Comment by OmarTawfik** [comment]
@jcouv @gafter can I get a second review?

**Comment by OmarTawfik** [comment]
@jcouv @gafter can I get a second review?

**Comment by jcouv** [comment]
@OmarTawfik What's the status on this PR?

**Comment by OmarTawfik** [comment]
@jcouv thanks for the review!
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-infrastructure a [transient failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/1986/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpReplIdeFeatures/HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnUnsubmittedText/)
