### PR TITLE
fix: raising of CS8618 on static members

### LINKED ISSUE #78152: CS8618 suggests using `required` on static properties
**Version Used**: 4.14.0-3.25178.1 (`1a06295e`)

Both the warning message and code fix for CS8616 (non-nullable prop must be non-null after ctor) recommend using `required` on the property, even when it wouldn't be valid, like for static properties:

**Steps to Reproduce**:

[SharpLab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABAzAAgwJhwGEcBvAWACgca9cMBGJPBgBhwBUYEAXMnAOYweAbhwBnYWIC+VWjgD0Cui2awAjgFcAlrAAmLdl178hoiVJyzK0oA===)

```cs
public class C {
    public static string Text { get; set; }
    // CS8616: Non-nullable property 'Text' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.
}
```

The code-fix suggests the following (invalid) code:

```cs

public class C {
    public static required string Text { get; set; }
    // CS0106: The modifier 'required' is not valid this item
}
```

**Diagnostic Id**: CS8618 ("Non-nullable property must contain a non-null value when exiting constructor.")

**Expected Behavior**:

**Actual Behavior**:

### PR DESCRIPTION
**Pull request by Thomas-Shephard**
Fixes https://github.com/dotnet/roslyn/issues/78152
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/83146)

### CODE REVIEW

File: src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs [hunk 1]
```diff
@@ -60,6 +60,9 @@ public override async Task RegisterCodeFixesAsync(CodeFixContext context)
         var fieldOrPropertySymbol = semanticModel.GetDeclaredSymbol(node, cancellationToken);
```
Comment (akhera99) [inline src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs:60]: Could you remove the IsStatic checks below and just do a singular check on the fieldOrPropertySymbol instead?

File: src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs [hunk 2]
```diff
@@ -58,6 +58,9 @@ public override async Task RegisterCodeFixesAsync(CodeFixContext context)
         }
 
         var fieldOrPropertySymbol = semanticModel.GetDeclaredSymbol(node, cancellationToken);
+        if (fieldOrPropertySymbol is null || fieldOrPropertySymbol.IsStatic)
```
Comment (akhera99) [inline src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs]:
```suggestion
        if (fieldOrPropertySymbol?.IsStatic == true)
```

to keep consistent with the check in the fixall

**Comment by akhera99** [comment]
Thanks for your contribution!

**Review by akhera99 — APPROVED** [review]
