### PR TITLE
Properly unwrap faulted tasks in AsyncLazy<T>

### LINKED ISSUE #7438: Switching AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult from WpfFact causes it to fail
I tried changing this test from `WpfFact` -> `Fact` and it failed this way:

```
Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult
      System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.AggregateException'.
      Stack Trace:
        src\EditorFeatures\Test\Utilities\AsyncLazyTests.cs(53,0): at Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueOrGetValueAsyncStillCachesResultCore(Func`3 doGetValue, Boolean includeSynchronousComputation)
        src\EditorFeatures\Test\Utilities\AsyncLazyTests.cs(18,0): at Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult()
```

This is suspicious -- I can't imagine why the test would change exception types depending upon the thread. We might have a very subtle bug.

### PR DESCRIPTION
**Pull request by sharwell**
Also closes #7438

### CODE REVIEW

File: src/EditorFeatures/Test/Utilities/AsyncLazyTests.cs [hunk 1]
```diff
@@ -74,5 +73,33 @@ public void SynchronousRequestShouldCacheValueWithAsynchronousComputeFunction()
 
             Assert.Same(secondRequestResult, firstRequestResult);
         }
+
+        [Theory]
+        [CombinatorialData]
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Utilities/AsyncLazyTests.cs:78]: Nice use of the theory!
