### PR TITLE
Do not try to add argument names on tuple elements

### LINKED ISSUE #19758: CSharpUseNamedArgumentsCodeRefactoringProvider crash with tuples
**Repro Steps**:
1. Copy this code into a C# project (you'll need ValueTuple installed):
```C#
using System.Collections.Generic;
using System.Linq;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Test()
        {
            var list1 = new List<object>();
            var list2 = new List<object>();
            var zip = list1.Zip(list2, (p1, p2) =>  (/* Cursor start */p1, p2 /* Cursor end */));
        }
    }
}
```
2. Put cursor in the tuple creation of the Zip call (in-between the cursor start/end comments).

**Expected**:
No Crash

**Actual**:
Refactoring provider crash.

**Stack Trace**:
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.TupleExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseArgumentListSyntax'.
   at async Microsoft.CodeAnalysis.CodeRefactorings.UseNamedArguments.AbstractUseNamedArgumentsCodeRefactoringProvider.Analyzer`3.ComputeRefactoringsAsync[TBaseArgumentSyntax,TArgumentSyntax,TArgumentListSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.UseNamedArguments.AbstractUseNamedArgumentsCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Fyi @CyrusNajmabadi.

### PR DESCRIPTION
**Pull request by alrz**
Fixes #19758

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for reviews.

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -95,28 +94,36 @@ protected abstract class Analyzer<TBaseArgumentSyntax, TArgumentSyntax, TArgumen
...
                 }
 
-                var argumentName = parameters[index].Name;
-                context.RegisterRefactoring(
-                    new MyCodeAction(
-                        string.Format(FeaturesResources.Add_argument_name_0, argumentName),
-                        c => AddNamedArgumentsAsync(root, document, argument, parameters, index)));
+                for (var i = argumentIndex; i < argumentCount; i++)
+                {
+                    if (!(arguments[i] is TArgumentSyntax))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: This can happen?!

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -195,8 +196,8 @@ protected abstract class Analyzer<TBaseArgumentSyntax, TArgumentSyntax, TArgumen
 
         private class MyCodeAction : CodeAction.DocumentChangeAction
         {
-            public MyCodeAction(string title, Func<CancellationToken, Task<Document>> createChangedDocument)
-                : base(title, createChangedDocument)
+            public MyCodeAction(string argumentName, Func<CancellationToken, Task<Document>> createChangedDocument)
+                : base(string.Format(FeaturesResources.Add_argument_name_0, argumentName), createChangedDocument)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: nit: we don't generally do this.  We usually just pass the title along and do the stirng.Format from the caller.

**Comment by CyrusNajmabadi** [comment]
Thanks!  Do we need a VB test as well?

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs (hunk 1 above)
Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: This was there (added by you) and I *think* it ensures that there is no trailing omitted args.

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: Ah, i think we need to call this TSimpleArgumentSyntax then to better convey how it will be instantiated and what it is expected to match against.

**Comment by alrz** [comment]
>Do we need a VB test as well?

Test added. ready for review.

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
NavigateTo flakeyness.

**Comment by CyrusNajmabadi** [comment]
Retest windows_release_vs-integration_prtest  please

**Comment by CyrusNajmabadi** [comment]
NavigateTo flakeyness

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 


**Customer scenario**

Customer brings up lightbulb in a tuple and invokes, or just selects the 'use named argument' refactoring.  nonfatalwatson/goldbar occurs.

**Bugs this fixes:**

Fixes #19758

**Workarounds, if any**

None.

**Risk**

low.

**Performance impact**

low.

**Is this a regression from a previous update?**

no.

**Root cause analysis:**

When we wrote hte 'add named argument' feature, we forgot that 'arguments' are also what we use in tuples.  The code wasn't equipped to handle that and it crashes.

**How was the bug found?**

Customer report.

**Comment by CyrusNajmabadi** [comment]
Thanks!
