### PR TITLE
Disallow calling generic local function with dynamic

### LINKED ISSUE #21317: Calling a generic local function with a dynamic parameter produces a BadImageFormatException
**Version Used**: Roslyn 2.0

**Steps to Reproduce**:

1. Write the following lines of code in a method
```
GenericLocal((dynamic)"");
void GenericLocal<T>(T val) {}
```
2. Invoke the method

**Expected Behavior**:

GenericLocal should be invoked, with `string` as `T`.

**Actual Behavior**:

BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

------

I described this on a [StackOverflow post](https://stackoverflow.com/questions/45495869) and the general consensus was that I'd found a bug. Note that the stacktrace shows the exception being thrown inside the method with this code, but no code actually gets run before the exception occurs.

### PR DESCRIPTION
**Pull request by khyperia**
Resolves #21317.

After discussion with @agocke, we've decided to ban this scenario - allowing this requires local functions to be constructed dynamically at runtime, something we explicitly decided not to do for local functions.

@dotnet/roslyn-compat-council This is technically a breaking change, as code that used to compile no longer does so. However, the IL generated in this scenario was broken, and the assembly could never load (not even a case of "fails when the code is executed", but "fails immediately when the assembly itself loads")

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 1]
```diff
@@ -3163,5 +3163,56 @@ static void M()
...
+                // (20,9): error CS8322: Cannot pass argument with dynamic type to generic parameter 'y' of local function 'L2'.
+                //         L2(1, val);
+                Diagnostic(ErrorCode.ERR_DynamicLocalFunctionTypeParameter, "L2(1, val)").WithArguments("y", "L2").WithLocation(20, 9),
+                // (27,9): error CS0411: The type arguments for method 'L3<T>(List<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
+                //         L3(dynamicList);
+                Diagnostic(ErrorCode.ERR_CantInferMethTypeArgs, "L3").WithArguments("L3<T>(System.Collections.Generic.List<T>)").WithLocation(27, 9),
+                // (23,14): warning CS8321: The local function 'L3' is declared but never used
+                //         void L3<T>(List<T> x)
+                Diagnostic(ErrorCode.WRN_UnreferencedLocalFunction, "L3").WithArguments("L3").WithLocation(23, 14)
+                );
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Do we allow `L1<dynamic>(val);`? If so, the error message from `L1(val);` seems misleading. Please add a test for this case.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -2801,7 +2801,8 @@ private RefKind GetEffectiveParameterRefKind(ParameterSymbol parameter, RefKind
             EffectiveParameters effectiveParameters;
             if (member.Kind == SymbolKind.Method && (method = (MethodSymbol)(Symbol)member).Arity > 0)
             {
-                if (typeArgumentsBuilder.Count == 0 && arguments.HasDynamicArgument && !inferWithDynamic)
+                var isLocalFunction = ((MethodSymbol)(Symbol)member).MethodKind == MethodKind.LocalFunction;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: `... = method.MethodKind == ...`

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 1 above)
Comment (khyperia) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Yes, we allow it. Do you have suggestions of what the message could be? Some thoughts:

> `Cannot pass argument with dynamic type to generic parameter 'x' of local function 'L1'. Try specifying the type arguments explicitly.`
> `Cannot pass argument with dynamic type to inferred generic parameter 'x' of local function 'L1'.`

I took the original wording from `ERR_DynamicLocalFunctionParamsParameter`: `Cannot pass argument with dynamic type to params parameter '{0}' of local function '{1}'.`

(Test added, will push once the message is updated too)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 3]
```diff
@@ -682,6 +682,34 @@ private static bool HasApplicableConditionalMethod(OverloadResolutionResult<Meth
...
+            // dynamically dispatch the call (as the function must be constructed at runtime).
+            // Check for the situation where a dynamic argument influences a type parameter,
+            // and disallow it.
+            if (boundMethodGroup.TypeArgumentsOpt.IsDefaultOrEmpty && localFunction.IsGenericMethod)
+            {
+                var originalLocalFunction = localFunction.OriginalDefinition;
+                for (int i = 0; i < args.Length; ++i)
+                {
+                    var argument = args[i];
+                    var parameter = originalLocalFunction.Parameters[methodResult.ParameterFromArgument(i)];
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Are we testing the `params` case?
```
void Local<T>(params T[] args) { }
Local("", (dynamic)"");
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: The first of those two suggestions sounds reasonable to me.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 4]
```diff
@@ -682,6 +682,34 @@ private static bool HasApplicableConditionalMethod(OverloadResolutionResult<Meth
...
+                    if (argument.HasDynamicType() &&
+                        parameter.Type.ContainsTypeParameter(parameterContainer: originalLocalFunction))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Is it necessary that the corresponding parameter type contains a type parameter. It looks like the following fails at runtime.
```
        Local((dynamic)"", "");
        void Local<T>(object x, T y) { }
```

Comment (khyperia) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Yes - and interesting, it looks like this PR actually fixes scenarios as well as banning others. You can see the `L2<T>(int x, T y)` test addresses this scenario, and it passes. This is due to the change in `OverloadResolution.cs` - I can explain why it fixes it if you'd like (it may be better to explain in-person, however).

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Or just `if (member is MethodSymbol `...

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 5]
```diff
@@ -3446,6 +3446,51 @@ Action<int> L5(int x)
         }
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: I think we should have a test for calling a non-generic local function with a dynamic param in a generic type (which should succeed).

**Comment by khyperia** [comment]
Pushed a commit that should address all feedback.

As discussed after standup, the new PR now disallows any type argument inference when combined with any dynamic argument.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 6]
```diff
@@ -5109,6 +5109,6 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
     <value>Unable to read debug information of method '{0}' (token 0x{1:X8}) from assembly '{2}'</value>
   </data>
   <data name="ERR_DynamicLocalFunctionTypeParameter" xml:space="preserve">
-    <value>Cannot pass argument with dynamic type to generic parameter '{0}' of local function '{1}'.</value>
+    <value>Cannot pass argument with dynamic type to generic local function '{0}'. Try specifying the type arguments explicitly.</value>
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: How about "Cannot pass argument with dynamic type to generic local function with inferred type arguments"?

**Comment by khyperia** [comment]
@agocke Updated message. Also, the latest commit updates two tests to add this diagnostic - it would be good to review those changes to make sure it's something we're okay with.

(I believe it's a case of "if those tests actually did compile (magically lacked the errors they're testing for), they would fail at runtime, due to this bug", so the "breaking change" is okay)

**Comment by agocke** [comment]
@khyperia Sounds good, although I think it would be good to run that those tests without your change and confirm that CompileAndVerify throws a BadImageLoadException.

Also, please hold off on merging this until we can run it by compat council.

**Comment by khyperia** [comment]
> run that those tests without your change and confirm that CompileAndVerify throws a BadImageLoadException.

Just did so on sharplab - changed the test to have an explicit cast to make it compile (`L(m => L((Func<dynamic, object>)(d => d), m), null);`), sharplab goes poof with a IL loading error :smile:

[Link to sharplab code](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoOAmJAYRwG8ckKkBnYAQ2AEsBjFAFiQFlaGoAKASnKUy2SmKQATAJ5RaAW2ZIAMgB4AKgD5ecAKwrpshUwA0STUmCmA9gCMAVgFMmwJAAd+SALwa3WUeIolXjkvHyCJUMlTKAgAG1j+aLiEvwDA4Mig7T0DeWZreydgDX5eCO9JRKQ5Kpj4/lTKAF8cJqA) (likely won't be a future-proof link, as once this merges and sharplab picks it up, it should produce the diagnostic introduced in this PR instead)

**Comment by khyperia** [comment]
retest windows_release_vs-integration_prtest please

**Comment by khyperia** [comment]
retest windows_release_vs-integration_prtest please

**Comment by khyperia** [comment]
Failure that prompted the first retest:

    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpExtractMethod.ExtractViaCodeAction

Failure that prompted the second retest:

    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigationBar.VerifyOption
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigationBar.VerifyNavBar2

**Comment by AlekseyTs** [comment]
>             // https://github.com/dotnet/roslyn/issues/10708

It feels like this comment is no longer accurate, consider adjusting.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:638 in 2c64cf2. [](commit_id = 2c64cf285ba3e5eac95ad8f9a6ce88dc6f6816ab, deletion_comment = False)
