### PR TITLE
Get compilation from symbol instead of having it passed into SymbolKey.Create

### LINKED ISSUE #11092: NRE at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>
I do not have a repro, but am hitting this NRE very often while typing. It seems to be from RenameTrackingTaggerProvider.

I have InstallDogfood bits from master which are a day old (1.03.0.60503)

Dump saved at: `\\<%Internal_Share%>\public\dumps\11092\devenv.dmp`

Message: `Object reference not set to an instance of an object.`

Call stack:
>    at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>d__5.MoveNext()
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1..ctor(TSymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(ILocalSymbol localSymbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20.MoveNext()

### PR DESCRIPTION
**Pull request by jmarolf**
Before this change there was a rare case where we would visit `NonDeclarationSymbolKey` within the constructor of `SymbolKey` with a null compilation causing a crash.  We now get the compilation from the symbol itself so this case cannot happen. See [this](https://github.com/dotnet/roslyn/issues/11092#issuecomment-218362553) comment for more information.

Fixes #11092

### CODE REVIEW

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide

File: src/Workspaces/Core/Portable/SymbolId/SymbolKey.BodyLevelSymbolKey.cs [hunk 1]
```diff
@@ -30,6 +30,9 @@ internal NonDeclarationSymbolKey(TSymbol symbol, Visitor visitor)
                 _containingKey = GetOrCreate(containingSymbol, visitor);
                 _localName = symbol.Name;
 
+                Contract.ThrowIfNull(
+                    visitor.Compilation,
+                    message: $"visitor cannot be created with a null compilation and visit a {nameof(NonDeclarationSymbolKey<TSymbol>)}.");
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/SymbolId/SymbolKey.BodyLevelSymbolKey.cs]: Newline after this?

Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/SymbolId/SymbolKey.BodyLevelSymbolKey.cs]: Also `nameof(Visitor)`.

**Comment by jasonmalinowski** [comment]
:+1:. We're still tracking the investigation of why `GetCompilationAsync` failed us?

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jmarolf** [comment]
@jasonmalinowski Turns out `GetCompilationAsync ` succeeded, it was passing in a null compilation in the `SymbolId` constructor that caused the crash, not the subsequent calls
