### PR TITLE
Add support for Suppression/Configuration fixes for build-only diagno…

### LINKED ISSUE #50035: Allow suppression and configuration of compilation level diagnostics
We have had a lot of people complaining about the lack of auto-suppression for `CA1812`. 

From @mavasani comment it seems that this is a known limitation due to performance, see:

> `CA1812` is a compilation level diagnostic - basically it needs analyzing the whole project before it can be reported. For compilation level diagnostics, we do not run these in live analysis while typing + do not compute code fixes for them on Ctrl + Dot (including suppression fixes). The core reason is performance - we do not want to analyze the entire project every time you press Ctrl + Dot, that will block light bulb for a significant time and not be a good experience. You should treat `CA1812` as a build-only diagnostic which only gets reported and refreshes after doing an explicit build.

I understand the performance issue but I don't think the user experience is nice. I even forgot about this and couldn't understand what was going-on on some projects.

First of all I don't understand why we don't see at least the `Configure` part as it shouldn't have any performance impact.

Second, don't you think it would be possible to show the menu with the `Suppress` part allowing ONLY suppression of current issue?. This way you shouldn't have the performance penalty of having to process the full compilation. Or are you talking about the fact that we will have to recompile to be able to remove the issue after the suppression is applied? If so can't we simply hook like issue suppressions are doing? 

We could event think about having a different entry for `Document`, `Project` and `Assembly` where there would be an extra description warning the user that this might be a long running operation that will force the recompilation of the project. Personally, I wouldn't mind to have to wait if that's something I am intentionally doing. 

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn-analyzers/issues/3210#issuecomment-747455459_

See https://github.com/dotnet/roslyn-analyzers/issues/2891 and https://github.com/dotnet/roslyn-analyzers/issues/3210

### PR DESCRIPTION
**Pull request by mavasani**
…stics

Fixes #50035

We have received multiple requests off late to support configuration and suppression code fixes from the light bulb as well as error list for build-only diagnostics. Without this tooling support, the user has to manually write up the pragma/suppress message attribute suppression for these diagnostics, which can be pretty tedious.

image

**NOTE:** We cannot implicitly add regular code fix support for build-only diagnostics as the fixer might be depending on the the `Properties` bag or the `AdditionalLocations` attached to diagnostics produced during live analysis, which will be missing on the diagnostics from build.

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313 @Evangelink @omghb

**Review by Youssef1313 — APPROVED** [review]
🎉

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+                    case WorkspaceChangeKind.ProjectRemoved:
+                        ClearDiagnostics(e.OldSolution.GetProject(e.ProjectId));
+                        break;
+
+                    case WorkspaceChangeKind.DocumentRemoved:
+                    case WorkspaceChangeKind.DocumentReloaded:
+                    case WorkspaceChangeKind.AdditionalDocumentRemoved:
+                    case WorkspaceChangeKind.AdditionalDocumentReloaded:
+                    case WorkspaceChangeKind.AnalyzerConfigDocumentRemoved:
+                    case WorkspaceChangeKind.AnalyzerConfigDocumentReloaded:
```
Comment (Evangelink) [inline src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:58]: I am not familiar with how this works but is it ok to only update current document in such case? Adding or removing an additional document could have a project level impact, isn't it?

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+
+                lock (_gate)
+                {
+                    _projectDiagnostics.Remove(project.Id);
+                    foreach (var documentId in project.DocumentIds)
+                        _documentDiagnostics.Remove(documentId);
+                }
+            }
+
+            public void ClearBuildOnlyDiagnostics(Solution solution, ProjectId? projectId, DocumentId? documentId)
```
Comment (Evangelink) [inline src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:112]: Same question about having 2 overloads.

**Review by Evangelink — COMMENTED** [review]
That's a great improvement! I have added some comments.

**Comment by mavasani** [comment]
@dotnet/roslyn-ide for reviews

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:58]: Good point, let me ensure we clear entire project diagnostics for this case.

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+                    case WorkspaceChangeKind.AdditionalDocumentRemoved:
+                    case WorkspaceChangeKind.AdditionalDocumentReloaded:
+                    case WorkspaceChangeKind.AnalyzerConfigDocumentRemoved:
+                    case WorkspaceChangeKind.AnalyzerConfigDocumentReloaded:
+                        ClearDiagnostics(e.DocumentId);
+                        break;
+                }
+            }
+
+            public void AddBuildOnlyDiagnostics(Solution solution, ProjectId? projectId, DocumentId? documentId, ImmutableArray<DiagnosticData> diagnostics)
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:64]: Sounds good

**Comment by mavasani** [comment]
@jmarolf Can you please take a look? Thanks

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+            private readonly object _gate = new();
+            private readonly Dictionary<DocumentId, ImmutableArray<DiagnosticData>> _documentDiagnostics = new();
+            private readonly Dictionary<ProjectId, ImmutableArray<DiagnosticData>> _projectDiagnostics = new();
+
+            public BuildOnlyDiagnosticsService(Workspace workspace)
+            {
+                workspace.WorkspaceChanged += OnWorkspaceChanged;
+            }
+
+            private void OnWorkspaceChanged(object? sender, WorkspaceChangeEventArgs e)
```
Comment (jmarolf) [inline src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:37]: My expectation is that once the workspace is changed in any way then the diagnostics are stale. In practice I would expect the set of build-only diagnostics to be less likly to be impacted by a document change but it is a question of how long we want stale diagnostics to stick around for.

There seems to be two possibilities here:

1. You build, get a diagnostics and they don't do away until you either rebuild or unload/reload the document that they were trigger for (or project if they are project level diagnostics)
2. You build, get a diagnostics and they go away as soon as anything changes.

(2) seems bad because then the diagnostics are too ephemeral. (1) seems fine since I want the diagnostics to stick around at least long enough for me to fix them. Ideally we could track the location of build-only diagnostics and remove them when edits to a file overlap them. My main concern is that its not clear to users that they will need to do another build to clear out build-only diagnostics.

**Review by jmarolf — APPROVED** [review]

**Comment by jmarolf** [comment]
@mavasani this approach matches the general way we do diagnostics for other build-only sources so I have no objections here. Still, it would be nice if I say, deleted the method that contained the diagnostics, they went away without me needing to rebuild, though I wouldn't block this PR on that.

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs (hunk 4 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:37]: Thanks, I filed https://github.com/dotnet/roslyn/issues/64659 to track this work. We have seen bunch of reports already about stale build-only diagnostics after the code has been updated or fixed. For example, unused field compiler diagnostic hangs around after you remove the field or add a read/write to the field. We definitely need to improve the experience here.

File: src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:64]: @mavasani Feel free to close/ignore my comment.

[the remark this answers is not in the document]
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs:64]: Yeah, I am going to retain the API shape as these are internal APIs.

**Review by Evangelink — APPROVED** [review]
