### PR TITLE
Fix wrong symbol comparisons

### LINKED ISSUE #58966: LSP Editor doesn't render documentation comments properly
**Version Used**: 

main

**Steps to Reproduce**:

```csharp
internal class C
{
    public static void M()
    {
        var a = new Test<int>();
        var b = a.Clone();
    }
}
internal class Test<T> : ICloneable<Test<T>>
{
    /// <inheritdoc/>
    public Test<T> Clone() => new();
}
/// <summary>A type that has clonable instances.</summary>
/// <typeparam name="T">The type of instances that can be cloned.</typeparam>
internal interface ICloneable<T>
{
    /// <summary>Clones a <typeparamref name="T"/>.</summary>
    /// <returns>A clone of the <typeparamref name="T"/>.</returns>
    T Clone();
}
```

**Expected Behavior**:

image

**Actual Behavior**:

image

**More information**:

This works if LSP editor is disabled, and was handled in https://github.com/dotnet/roslyn/pull/54164.

*Originally reported by @ZacharyPatten in https://github.com/dotnet/roslyn/issues/54069#issuecomment-1014958482*

### LINKED ISSUE #62368: `#nullable enable` adds a "not CLS-compliant" diagnostic
Extracted from test `WRN_CLS_BadArgType_ConstructedTypeAccessibility`:

```csharp
#nullable enable
[assembly: System.CLSCompliant(true)]
public class C<T>
{
    protected class N { }
    protected void M1(C<int>.N n) { }	// Not CLS-compliant - C<int>.N not 
    // accessible from within C<T> in all languages
    protected void M2(C<T>.N n) { }	    // CLS-compliant - C<T>.N accessible inside C<T>
}
```

The above produces warnings for M1 and M2:

```csharp
warning CS3001: Argument type 'C<int>.N' is not CLS-compliant
warning CS3001: Argument type 'C<T>.N' is not CLS-compliant
```

If `#nullable enable` is changed to `#nullable disable`, only warning for M1 is produced.

The root cause is very likely the same as https://github.com/dotnet/roslyn/issues/58966.

This issue was actually part of my investigation to figure out a compiler scenario for the fix I've for #58966

### LINKED ISSUE #65428: `ERR_AssgReadonlyStatic` only under `#nullable enable`
@jcouv This is *likely* symbol comparison we discussed before for https://github.com/dotnet/roslyn/issues/58966 and https://github.com/dotnet/roslyn/issues/62368. You were interested in a more important scenario, and I think there is one. The following test fails with nullable enabled.

```csharp
        [Theory]
        [InlineData(NullableContextOptions.Disable)]
        [InlineData(NullableContextOptions.Enable)]
        public void TestSymbolComparison(NullableContextOptions nullableContextOptions)
        {
            var text =
@"
class C<T>
{
    public static readonly int X;

    static C()
    {
        C<T>.X = 100;
    }
}
";

            CreateCompilation(text, options: TestOptions.ReleaseDll.WithNullableContextOptions(nullableContextOptions), parseOptions: TestOptions.Regular.WithStrictFeature()).VerifyDiagnostics();
        }
```

image

Thanks @Sergio0694 for the repro! 🎉

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #62368
Fixes #58966
Fixes #65428

cc @333fred @jcouv @AlekseyTs 

Keeping draft until the behavior of `ConsiderEverything` (and the fact that we create `ConstructedNamedTypeSymbol` under `#nullable enable`, and `SourceNamedTypeSymbol` otherwise) is confirmed as a correct behavior. Otherwise, the fix will be much more involving.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -1039,9 +1039,9 @@ private bool CheckFieldValueKind(SyntaxNode node, BoundFieldAccess fieldAccess,
                         fieldIsStatic == containing.IsStatic &&
                         (fieldIsStatic || fieldAccess.ReceiverOpt.Kind == BoundKind.ThisReference) &&
                         (Compilation.FeatureStrictEnabled
-                            ? TypeSymbol.Equals(fieldSymbol.ContainingType, containing.ContainingType, TypeCompareKind.ConsiderEverything2)
+                            ? TypeSymbol.Equals(fieldSymbol.ContainingType, containing.ContainingType, TypeCompareKind.AllNullableIgnoreOptions)
                             // We duplicate a bug in the native compiler for compatibility in non-strict mode
-                            : TypeSymbol.Equals(fieldSymbol.ContainingType.OriginalDefinition, containing.ContainingType.OriginalDefinition, TypeCompareKind.ConsiderEverything2)))
+                            : TypeSymbol.Equals(fieldSymbol.ContainingType.OriginalDefinition, containing.ContainingType.OriginalDefinition, TypeCompareKind.ConsiderEverything)))
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1044]: As we are comparing containing type original definitions, I don't think there can be nullability differences. So I'm changing `ConsiderEverything2` to `ConsiderEverything`.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 2]
```diff
@@ -1039,9 +1039,9 @@ private bool CheckFieldValueKind(SyntaxNode node, BoundFieldAccess fieldAccess,
                         fieldIsStatic == containing.IsStatic &&
                         (fieldIsStatic || fieldAccess.ReceiverOpt.Kind == BoundKind.ThisReference) &&
                         (Compilation.FeatureStrictEnabled
-                            ? TypeSymbol.Equals(fieldSymbol.ContainingType, containing.ContainingType, TypeCompareKind.ConsiderEverything2)
+                            ? TypeSymbol.Equals(fieldSymbol.ContainingType, containing.ContainingType, TypeCompareKind.AllNullableIgnoreOptions)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: >AllNullableIgnoreOptions [](http://example.com/codeflow?start=119&length=24)

I think we should use ```AllIgnoreOptions``` here.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1044]: >ConsiderEverything [](http://example.com/codeflow?start=157&length=18)

Here as well, even though ```TypeCompareKind``` should make no difference when we compare definitions.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: Does it matter for the purpose of this specific check?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: >Equals [](http://example.com/codeflow?start=41&length=6)

It looks like there is a somewhat similar logic in ```Binder.AccessingAutoPropertyFromConstructor```. We might want to align it.

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs [hunk 3]
```diff
@@ -1090,7 +1090,7 @@ private static bool IsInaccessibleBecauseOfConstruction(NamedTypeSymbol type, Na
                     NamedTypeSymbol containingType;
                     if (containingTypes.TryGetValue(contextBaseType.OriginalDefinition, out containingType))
                     {
-                        return !TypeSymbol.Equals(containingType, contextBaseType, TypeCompareKind.ConsiderEverything2);
+                        return !TypeSymbol.Equals(containingType, contextBaseType, TypeCompareKind.AllNullableIgnoreOptions);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs:1093]: >AllNullableIgnoreOptions [](http://example.com/codeflow?start=99&length=24)

Can we use ```AllIgnoreOptions``` here? What are we trying to detect?

File: src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs [hunk 4]
```diff
@@ -187,7 +187,7 @@ public override object VisitNamedType(NamedTypeSymbol symbol, StringBuilder buil
                 {
                     // Special case: dev11 treats types instances of the declaring type in the parameter list
                     // (and return type, for conversions) as constructed with its own type parameters.
-                    if (!_inParameterOrReturnType && TypeSymbol.Equals(symbol, symbol.ConstructedFrom, TypeCompareKind.ConsiderEverything2))
+                    if (!_inParameterOrReturnType && TypeSymbol.Equals(symbol, symbol.ConstructedFrom, TypeCompareKind.AllNullableIgnoreOptions))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs:190]: >AllNullableIgnoreOptions [](http://example.com/codeflow?start=119&length=24)

Can we use ```AllIgnoreOptions``` here?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs:190]: Is this change covered by a test?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: > Does it matter for the purpose of this specific check?

The question is what else ignorable do we want to take into account and why. We want to make a change that is good enough for the future as well. If we remove ```ConsiderEverything2```, it will be unlikely that we will focus on this line any time soon. Imagine we will add another feature similar to nullable. Is this line going to break again? We should pick an option that matches what we are trying to accomplish as close as possible, not one that merely makes a test to pass.

File: src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs:190]: Not yet. I'll add one

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs:190]: @AlekseyTs Do you have a scenario in mind where it matters?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: Sure. Though `AccessingAutoPropertyFromConstructor` appears to be behaving correctly already.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1042]: @AlekseyTs Got it. I asked in case there is already a scenario I should test.

File: src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs:190]: > Do you have a scenario in mind where it matters?

See my other comment. Usually, when we are replacing ```ConsiderEverything2```, we should demonstrate that options that we are not ignoring matter, Not the other way around.

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: It is not obvious to me what we are trying to detect here. And we need to understand that before picking the ```TypeCompareKind```. For example, should dynamic vs. object make a difference here? If you have an understanding of our intent here, please share it, Otherwise, we need to get this understanding.

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentIDTests.cs [hunk 5]
```diff
@@ -396,5 +396,25 @@ class C<TC1, TC2>
...
         }
+
+        [Theory]
+        [CombinatorialData]
+        public void Generic(NullableContextOptions nullableContextOptions)
+        {
+            var source = @"
+internal class Test<T> : ICloneable<Test<T>>
+{
+    public Test<T> Clone() => new();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentIDTests.cs:407]: >T [](http://example.com/codeflow?start=16&length=1)

Consider explicitly testing scenario with ```T?``` here.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3)

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs (hunk 3 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: @AlekseyTs I don't have too much info here. I thought that we might not be caring about `object` vs `dynamic` since they are both System.Object in the resulting IL. I think CLS compliance is more about "is this assembly (resulting IL) compliant with some rules?" though I'm not sure if there might be something in these rules that might be concerned with the extra "DynamicAttribute" produced.

Revisiting the behavior when nullable is disabled:

```csharp
#nullable disable

[assembly: System.CLSCompliant(true)]

public class Base<T>
{
    protected class Nested { }
}

public class C<T> : Base<object>
{
    protected void M(Base<dynamic>.Nested c) // CLS compliance warning
    {
    }
}
```

I haven't confirmed yet, but I think `AllIgnoreOptions` might affect this scenario and remove the warning.

I guess we could use `AllNullableIgnoreOptions`. I know that this won't be revisited since it's no longer `ConsiderEverything2`, but I also think `ConsiderEverything2` was introduced specifically when doing nullability work. So `AllNullableIgnoreOptions` should just be good.

What do you think @AlekseyTs ?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: > What do you think ?

1. I would start with understanding the rule that we are trying to implement. What does it say exactly? Let's find this out.
2. I would try to figure out whether tuple names and dynamic differences matter for the purpose of the rule. It doesn't look like other options should matter, or corresponding differences could be detected by native compilers. But I could be wrong.
3. I would explicitly include options that we care about rather than using ```AllNullableIgnoreOptions```.
4. The legacy native compiler supported dynamic. It would be good to check its behavior around dynamic vs. object difference.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: > * I would start with understanding the rule that we are trying to implement. What does it say exactly? Let's find this out.

@AlekseyTs Where can I find the whole rules spec'ed precisely? The rule intended to be implemented here per the doc comment is "Rule 46":

https://github.com/dotnet/roslyn/blob/33c8ae8c67e6f3c9f2daffa8a0fe7210056f60bb/src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs#L1049

But I don't know where can I see what the "rule 46" says exactly. The brief about the rule in the comment is that a constructed generic type `C<type1>` can't access protected members of a constructed generic type `C<type2>`. I think `C<object>` and `C<dynamic>` are both the exact same type from the point of view of another language consuming this assembly (they are both C<System.Object>`). It doesn't seem like the attribute on the type parameter will matter for the ability to access members in other languages.

---

> The legacy native compiler supported dynamic. It would be good to check its behavior around dynamic vs. object difference.

I'll see if I can download VS 2013 and test that. Is there an easier way to get the native compiler other than using VS 2013?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: > I'll see if I can download VS 2013 and test that. Is there an easier way to get the native compiler other than using VS 2013?

It comes with desktop framework. If you have it installed, you should be able to find it in a folder like  c:\Windows\Microsoft.NET\Framework\v4.0.30319

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: > Where can I find the whole rules spec'ed precisely? The rule intended to be implemented here per the doc comment is "Rule 46"

I assume it is the rule specified in section I.10.7.5 of ECMA-335 specification:

CLS Rule 46: The visibility and accessibility of members (including nested types) in an
instantiated generic type shall be considered to be scoped to the specific instantiation rather than
the generic type declaration as a whole. Assuming this, the visibility and accessibility rules of
CLS rule 12 still apply.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: Ok. I am comfortable going with ```AllIgnoreOptions``` here. Assuming legacy compiler didn't care about object/dynamic difference. Let's confirm that.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: @MadsTorgersen, @dotnet/roslyn-compiler

> I am comfortable going with ```AllIgnoreOptions``` here. Assuming legacy compiler didn't care about object/dynamic difference. Let's confirm that

It looks like legacy compiler cares about object/dynamic difference.
```
[assembly: System.CLSCompliant(true)]

public class C<T>
{
    protected class N { }
}

public class D : C<object>
{
    protected void M4(C<dynamic>.N n) { }
}
```

Observed:
```
(10,23): warning CS3001: Argument type 'C<dynamic>.N' is not CLS-compliant
```

Should we preserve this behavior?

Comment (333fred) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: CLS compliance is not considered by any modern framework, and is broken in a number of ways today. Preserving that warning does not concern me.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: @Youssef1313 We discussed this issue internally and reached consensus that it would be fine dropping this warning. Let's add test for this scenario, add test suggested at https://github.com/dotnet/roslyn/pull/65430#discussion_r1025249635 and move this PR forward.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)

**Comment by jcouv** [comment]
Thanks @Youssef1313 !
