### PR TITLE
Making stack scheduling optimizations more robust and fixing #4828

### LINKED ISSUE #4828: Compiler emits invalid MSIL
I have a problem with the compiler in VS2015. The following code will crash the application with an InvalidProgramException. (But only if /optimize+ is passed). Is this a bug in the compiler, or am I doing something wrong?

**Compiler command line:**
```
"C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe" /nostdlib+ /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll  /optimize+ /out:App.exe /target:exe Program.cs
```

**Contents of Program.cs:**
```
namespace App
{
    class Program
    {
        static void Main(string[] args)
        {
            int a = 0;
            int b = a + a / 1;
        }
    }
}
```

**Emitted MSIL of the method that fails:**
```
.method private hidebysig static void  Main(string[] args) cil managed
{
  .entrypoint
  // Code size       7 (0x7)
  .maxstack  8
  IL_0000:  ldc.i4.0
  IL_0001:  pop
  IL_0002:  dup
  IL_0003:  ldc.i4.1
  IL_0004:  div
  IL_0005:  pop
  IL_0006:  ret
} // end of method Program::Main
```

**Exception message:**
```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at App.Program.Main(String[] args)
```

**Output from PEVerify.exe:**
```
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\PEVerify.exe" /nologo App.exe
[IL]: Error: [C:\Src\OutsideTFS\RslnBug\RslnBug\App\App.exe : App.Program::Main][offset 0x00000002] Stack underflow.
1 Error(s) Verifying App.exe
```

### PR DESCRIPTION
**Pull request by VSadov**
Stack scheduler performs two kinds of transformations -
1) it turns local slots into ephemeral locals that live on the evaluation stack.
2) It also tries to Dup previous expressions when the next one is exactly the same and other condittions allow.

The operation # 2 is basically a workaround for cases like

   temp = ...
   result = temp + temp;

Since ephemeral locals are modeled as occupying the space "below" the eval values, having temp on eval stack prevents that same temp from loading as a stack local.
The self-interference situations like above are fairly common, so the stack scheduler tries to reduce some of the cases by attempting a peephole optimization where value of previous expression could be Dup-ed if the following one is the same. (thus in our example it would look like the second load of the temp does not happen at all).

This # 2 optimization has numerous conditions where it is not applicable and as bug #4828 shows it is still fairly fragile. It relies on the presence of the value produced by the previous expression and that is not always guaranteed to be there if the expression has no sideeffects.

Instead of adding more conditions, I am removing the # 2 entirely.

It appears that it can be removed without any serious regression in # 1 as long as we track not only the depth of the eval stack but also what we have on it. That way we can detect self-interference cases by just examining our best knowledge of the stack and handle definite self-interference cases as not prohibiting.

The result of this change is that many dups have disappeared from the code, but in most cases they were dups of trivial local/parameter loads and as such are not a concern.
On the other hand most cases where local slots can be optimized away are still there and in some cases we actually are slightly better.

The most important part is that the whole scheduling got simpler and uses fewer assumptions about what emit might do.

Fixes #4828

### CODE REVIEW

**Comment by VSadov** [comment]
Will do the same change to VB separately.

**Comment by VSadov** [comment]
@AlekseyTs @gafter @agocke @jaredpar - please review

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs [hunk 1]
```diff
@@ -1601,6 +1480,15 @@ private void RecordVarRead(LocalSymbol local)
             locInfo.LocalDefs.Add(locDef);
         }
 
+        private bool EvalStackHasLocal(LocalSymbol local)
+        {
+            var top = _evalStack.Last();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: Should we check if the stack is empty?

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: No, the need for this call only arises when current stack is deeper than at declaration of the local, so it cannot be empty.

**Comment by VSadov** [comment]
@dotnet-bot retest this

**Comment by VSadov** [comment]
@dotnet-bot test this
