### PR TITLE
Calculate snippet $end$ location based on column, not line length

### LINKED ISSUE #4652: Snippet end location incorrectly placed in virtual space with Keep Tabs enabled
Split from internal bug 1212312

1. Create a new C# Console Application.
2. Turn on "Keep Tabs" (Tools | Options | Text Editor | C# | Tabs | Keep tabs)
3. Inside Main, type **for&lt;tab&gt;&lt;tab&gt;**
4. Hit enter to "complete" the snippet and move the caret to the $end$ location.

**Expected**: The caret should be placed 4 *tabs* in.
**Actual**: The caret is placed 4 *spaces* in.

The bug is in [AbstractSnippetExpansionClient.CleanUpEndLocation](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Snippets/AbstractSnippetExpansionClient.cs,172), where it assumes the formatted blank line *length* (regardless of what kind of white space is involved) can be used as the position of the virtual snapshot point where the caret is moved to (measured in spaces/columns).

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #4652

When an expanded snippet's $end$ position ends up on its own line after formatting (potentially with leading whitespace), we calculate & store its indentation level and then remove any leading whitespace. Then when the snippet is completed (either automatically or after field editing is complete), we position the caret in virtual space at this stored indentation level. The bug here was one of mismatched units. Specifying the position in virtual space is done in columns, but the indentation was being stored as a count of characters. When the "Keep Tabs" option is enabled, an intended indentation of 3 tabs (12 spaces if the tab size is 4) would result in the caret being positioned at column 3 in virtual space instead of column 12.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Reviewers: @Pilchie @DustinCampbell @davkean @jasonmalinowski @balajikris @brettfo @CyrusNajmabadi @jmarolf @rchande

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 1]
```diff
@@ -169,7 +170,20 @@ private void CleanUpEndLocation(ITrackingSpan endTrackingSpan)
...
                 {
                     indentCaretOnCommit = true;
-                    indentDepth = lineText.Length;
+
+                    var document = this.SubjectBuffer.CurrentSnapshot.GetOpenDocumentInCurrentContextWithChanges();
+                    if (document != null)
+                    {
+                        var optionService = document.Project.Solution.Workspace.Services.GetService<IOptionService>();
+                        var tabSize = optionService.GetOption(FormattingOptions.TabSize, document.Project.Language);
+                        indentDepth = Microsoft.CodeAnalysis.Shared.Extensions.StringExtensions.GetColumnFromLineOffset(lineText, lineText.Length, tabSize);
```
Comment (DustinCampbell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: Any reason why you decided to fully-qualify this rather than call it as an extension method on string?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 2]
```diff
@@ -169,7 +170,20 @@ private void CleanUpEndLocation(ITrackingSpan endTrackingSpan)
...
+                    }
+                    else
+                    {
+                        // If we don't have a document, then just guess the typical default TabSize value.
+                        indentDepth = Microsoft.CodeAnalysis.Shared.Extensions.StringExtensions.GetColumnFromLineOffset(lineText, lineText.Length, tabSize: 4);
```
Comment (DustinCampbell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: ditto

**Comment by DustinCampbell** [comment]
:+1:

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs (hunk 1 above)
Comment (dpoeschl) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: Oops. I was having trouble using the extension method so I just did this to get past that problem, but then forgot to revisit it. Will investigate.

Comment (dpoeschl) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: Add Using wasn't working here, because it already thought ```GetLineOffsetFromColumn``` was supposed to be the ITextSnapshotLineExtensions one. :disappointed: Adding the using manually works, of course.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 3]
```diff
@@ -169,7 +169,20 @@ private void CleanUpEndLocation(ITrackingSpan endTrackingSpan)
                 if (lineText.Trim() == string.Empty)
                 {
                     indentCaretOnCommit = true;
-                    indentDepth = lineText.Length;
+
+                    var document = this.SubjectBuffer.CurrentSnapshot.GetOpenDocumentInCurrentContextWithChanges();
+                    if (document != null)
+                    {
+                        var optionService = document.Project.Solution.Workspace.Services.GetService<IOptionService>();
+                        var tabSize = optionService.GetOption(FormattingOptions.TabSize, document.Project.Language);
```
Comment (dpoeschl) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: @jasonmalinowski - I remember you said something about maybe not needing to access the option setting directly. Is there a better way of doing this?

**Comment by Pilchie** [comment]
:+1:

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: Oh that should be fine, I just didn't want you trying to implement GetColumnFromLineOffset yourself since that's tricky.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 4]
```diff
@@ -169,7 +169,20 @@ private void CleanUpEndLocation(ITrackingSpan endTrackingSpan)
...
+                        indentDepth = lineText.GetColumnFromLineOffset(lineText.Length, tabSize);
+                    }
+                    else
+                    {
+                        // If we don't have a document, then just guess the typical default TabSize value.
+                        indentDepth = lineText.GetColumnFromLineOffset(lineText.Length, tabSize: 4);
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: The text buffer has a property as well you could read in this case.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 5]
```diff
@@ -169,7 +169,20 @@ private void CleanUpEndLocation(ITrackingSpan endTrackingSpan)
...
                 {
                     indentCaretOnCommit = true;
-                    indentDepth = lineText.Length;
+
+                    var document = this.SubjectBuffer.CurrentSnapshot.GetOpenDocumentInCurrentContextWithChanges();
+                    if (document != null)
+                    {
+                        var optionService = document.Project.Solution.Workspace.Services.GetService<IOptionService>();
+                        var tabSize = optionService.GetOption(FormattingOptions.TabSize, document.Project.Language);
+                        indentDepth = lineText.GetColumnFromLineOffset(lineText.Length, tabSize);
```
Comment (brettfo) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: Move the `indentDepth = ...` line outside the `if` and only assign `tabSize` here, since both calls are identical.
