### PR TITLE
Fix UseExpressionBodyHelper.GetDiagnosticLocation for indexer declara…

### LINKED ISSUE #31308: "Use expression body for indexers" throws exception on expression-bodied indexer accessors when their diagnostic severity is not Hidden
**Version used**: VS 15.9.2, with Roslyn built from `master`.

**Steps to Reproduce**:

1. Create a C# project.
2. Add the source code below, as well as the EditorConfig file.
3. Let VS analyze the source file. (Or invoke Quick Actions on the indexer.)

```c#
class C
{
    C this[int index]
    {
        get => default;
    }
}
```

```ini
root = true

[*.cs]
csharp_style_expression_bodied_indexers = when_on_single_line:none
csharp_style_expression_bodied_accessors = when_on_single_line:none
```

**Expected Behavior**: No NRE is thrown, no AD0001 is shown.

**Actual Behavior**: The analyzer crashes with an AD0001 warning. The code fix still works, though.

```
Exception occurred with following context:
Compilation: repro-project
SyntaxTree: [redacted]\Class1.cs
SyntaxNode: public C this[int i] { get => null ... [IndexerDeclarationSyntax]@[16..72) (2,4)-(5,5)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.UseExpressionBody.UseExpressionBodyHelper`1.GetDiagnosticLocation(TDeclaration declaration)
   at Microsoft.CodeAnalysis.CSharp.UseExpressionBody.UseExpressionBodyHelper`1.GetDiagnosticLocation(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.UseExpressionBody.UseExpressionBodyDiagnosticAnalyzer.AnalyzeSyntax(OptionSet optionSet, SyntaxNode declaration, UseExpressionBodyHelper helper)
   at Microsoft.CodeAnalysis.CSharp.UseExpressionBody.UseExpressionBodyDiagnosticAnalyzer.AnalyzeSyntax(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Notes:**

* The `null` comes from ``UseExpressionBodyHelper`1.GetBodyFromSingleGetAccessor(AccessorListSyntax)``, because `Body` is null when it has no braces, according to the docs.
* The default severity (see also the local variable `severity` in `UseExpressionBodyDiagnosticAnalyzer.AnalyzeSyntax`) seems to be Hidden. With the EditorConfig file (I don't know if you need both lines or just one, but it's 1am), `severity` is Suppressed, so the control flow then goes to `helper.GetDiagnosticLocation()`, from where the exception will happen further down the call chain.

### PR DESCRIPTION
**Pull request by mavasani**
…tions

Port existing override [UseExpressionBodyForPropertiesHelper.GetDiagnosticLocation](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/UseExpressionBody/Helpers/UseExpressionBodyForPropertiesHelper.cs,76) to `UseExpressionBodyForIndexersHelper`

Fixes #31308

### CODE REVIEW

File: src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForIndexersHelper.cs [hunk 1]
```diff
@@ -71,5 +71,17 @@ protected override IndexerDeclarationSyntax WithBody(IndexerDeclarationSyntax de
...
+        protected override Location GetDiagnosticLocation(IndexerDeclarationSyntax declaration)
+        {
+            var body = GetBody(declaration);
+            if (body != null)
+            {
+                return base.GetDiagnosticLocation(declaration);
+            }
+
+            var getAccessor = GetSingleGetAccessor(declaration.AccessorList);
+            return getAccessor.ExpressionBody.GetLocation();
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForIndexersHelper.cs]: i assume we won't even get here if the indexer only has a setter?

Comment (mavasani) [reply src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForIndexersHelper.cs]: Yes, that seems to the implementation for the property helper too.

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal for approval

**Comment by mavasani** [comment]
@dotnet/roslyn-ide for an additional review.
