### PR TITLE
Restore caret position when undoing a Complete Statement operation

### LINKED ISSUE #43400: Semicolon insertion does not work properly with Undo
**Version Used**: 16.6 Preview 2

**Steps to Reproduce**:

1. Type `;` at the location indicated by `$$`:

    ```
    Method(condition ? whenTrue $$)
    ```

2. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd>

**Expected Behavior**:

```
Method(condition ? whenTrue ;$$)
```

**Actual Behavior**:

```
Method(condition ? whenTrue )$$
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #43400

### CODE REVIEW

File: src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs [hunk 1]
```diff
@@ -36,43 +38,67 @@ namespace Microsoft.CodeAnalysis.Editor.CSharp.CompleteStatement
...
+
+            var willMoveSemicolon = BeforeExecuteCommand(speculative: true, args: args, executionContext: executionContext);
+            if (!willMoveSemicolon)
+            {
+                // Pass this on without altering the undo stack
+                nextCommandHandler();
+                return;
+            }
+
+            using var transaction = new HACK_TextUndoTransactionThatRollsBackProperly(history.CreateTransaction(nameof(CompleteStatementCommandHandler)));
```
Comment (Cosifne) [inline src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs:69]: Is there any reason to use this transaction rather than [caretPreseringEditTransaction](http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Utilities/CaretPreservingEditTransaction.cs,b47abaeeb8c84813)?

**Comment by Cosifne** [comment]
Just have one question about this PR. Overall looks good

**Review by genlu — APPROVED** [review]
:shipit:

File: src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs]: ➡️ Now simplified using `CaretPreservingEditTransaction`
