### PR TITLE
IDE0056, IDE0057: Move language version check to compilation start, minor cleanup

### LINKED ISSUE #59514: ID0056 bad suggestion in netstandard2.0
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.4

**Steps to Reproduce**:

1. Create netstandard2.0 project
2. Paste this snippet of code:
```csharp
int[] arr = { 1,2,3};
_ = arr[arr.Length - 1];
```
3. An IDE0056 suggestion will appear as a warning, to simplify the indexing.
The proposed solution is:
```csharp
_ = arr[^1];
```
which is not supported by the C# version.

***Note***: The solution has another project targeting .NET5

Full csproj content, in case it might be usefull:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
	  <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
	  <LangVersion>preview</LangVersion>
	  <nullable>enable</nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>

</Project>
```

**Expected Behavior**: 
No warning appearing at all. 
Note that possibly there are other bugs related to the System.Index typed introduced in a later version of the language.

**Actual Behavior**:
Bad suggestion, with a code fix that doesn't compile.

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #59514 (the issue itself was already fixed and tested - I'm only addressing https://github.com/dotnet/roslyn/issues/59514#issuecomment-1037265798)

### CODE REVIEW

File: src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -56,12 +56,17 @@ public CSharpUseIndexOperatorDiagnosticAnalyzer()
 
         protected override void InitializeWorker(AnalysisContext context)
         {
-            context.RegisterCompilationStartAction(startContext =>
+            context.RegisterCompilationStartAction(context =>
```
Comment (Youssef1313) [inline src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs:59]: **Below callbacks were originally registered using the `AnalysisContext` rather than the `CompilationStartAnalysisContext`**

I'm not sure if this makes any different, but we should be using the most-nested context anyway, so shadowing is very intended.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks!
