### PR TITLE
Fix analysis of parameter default values

### LINKED ISSUE #48844: Delegate parameter default values should affect lambda parameter initial state
**Version Used**: d5931e08dd388356176821aa25df094d0e9e94a8

**Steps to Reproduce**:

```cs
#nullable enable

public delegate void Del<T>(T t = default);

public class C<T>
{
    public void M0(T t) { }

    // Behavior for member methods, for comparison
    public void M1(T t = default)
    {
        M0(t); // warning CS8604: Possible null reference argument
    }
    
    public void M2()
    {
        Del<T> del = t => M0(t); // expected warning, but didn't get one
        Del<T> del1 = t => { t = default; M0(t); }; // warning CS8604: Possible null reference argument
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFBUACAzIQCZwEDmE8hNALIQCIsAPABUAfAAphhGIQC8TOADMI2GAEoA3FVoMaAJkIBhEaKoBvKoStddvALIAGSdLWEzhAL7bK1wgHo/QgAhOAALCAA3AEsAewRCRTjCMDgwYERkuBhQmMYoABoEpIBjGLAABwgEKKgYtEtrei57AEZnGXlmZVU1BqsLH19rR3F1DX9AgHcqtCi0ViMAZQAOADYHbhBCAAUYqCgo/CJMHEIEJUQSYqIq1gwUtBg+z2fnpp5COz1xXsH+598AiwJgUWDk0jkok+TjGE2IAA9ynBivBGIRpghZvNCsAMDJGFFGGgAOQyVhZQh1OAA6xAkHMLAtcEdKHuDoKbpYGDjEawjzjALomZzBaGFbrTY7PYHI6EE5g86KS5oa6EW73EhPP4vSgeIA=)

**Expected Behavior**: Warnings on all 3 commented lines

**Actual Behavior**: Warnings on 2 commented lines

I might be able to fix this with my "put parameter default values in the bound tree" work. Not yet sure.

edit: Expected behavior of this scenario has changed based on the proposal [nullable-parameter-default-value-analysis.md](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-parameter-default-value-analysis.md)

### LINKED ISSUE #48847: Abstract method parameter default values do not get nullability warnings
**Version Used**: d5931e08dd388356176821aa25df094d0e9e94a8

**Steps to Reproduce**:

```cs
#nullable enable

public abstract class C
{
    public abstract void M1(string s = null);
}

public delegate void Del1(string s = null);
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFBUACAzIQCZwEDmE8hNALIQCIsAPABUAfAAphhGIQC8TOADMI2GAEoA3FVoMaAJkIBhEaKoBvKoStddvALIAGSdLWEzhAL7bK1wgHo/QgAhOAALCAA3AEsAewRCRTjCMDgwYERkuBhQmMYoABoEpIBjGLAABwgEKKgYtEtrei57AEZnGXlmZVU1BqsLH19rR3F1DX9AgHcqtCi0ViMAZQAOADYHbhBCAAUYqCgo/CJMHEIEJUQSYqIq1gwUtBg+z2fnpp5COz1xXsH+598AiwJgUWDk0jkok+TjGE2IAA9ynBivBGIRpghZvNCsAMDJGFFGGgAOQyVhZQh1OAA6xAkHMLAtcEdKHuDoKbpYGDjEawjzjALomZzBaGFbrTY7PYHI6EE5g86KS5oa6EW73EhPP4vSgeIA=)

**Expected Behavior**: Warnings on the parameter default values for `M1` and `Del1`.

**Actual Behavior**: No warnings.

Basically, it seems that when the method has no body, we entirely fail to analyze its parameter default values. It suggests that the approach to synthesize the parameter default values and pretend to assign them in NullableWalker is not quite right. When a parameter default value is included in syntax, it may be associated directly with a varying number of method bodies:

- 0 for delegates and abstract methods
- 1 for ordinary methods
- 2 for indexers with get and set accessors

edit: Expected behavior of this scenario has changed based on the proposal [nullable-parameter-default-value-analysis.md](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-parameter-default-value-analysis.md)

### LINKED ISSUE #48848: Override method parameter initial state should be affected by base method parameter default values
**Version Used**: d5931e08dd388356176821aa25df094d0e9e94a8

**Steps to Reproduce**:

```cs
#nullable enable

public class Base<T> {
    public virtual void M0(T t = default)
    {
        M1(t); // warning CS8604: Possible null reference argument
    }
    
    public void M1(T t) { }
}

public class Derived<T> : Base<T>
{
    public override void M0(T t)
    {
        M1(t); // expected warning, but got none
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFBUACAzITQEyEBC0cAPACoB8hAbyqERjBgDcAlghgYIWRgBZCAWQAMACm6EYhALyEAJnABmEbDACUw0UMqiHqgIwarAbkIB6T4QDuEBDRJNABzQgBhAGUADgA2NUUQQgAFAHsoKEl8IkwcQgRTRBIAYyIAkIwwEhgbEQBfWsJG+iVnLR1LQUIGyh7aBmZCABFESXE4Qx5+JPYoLj4qOwcW1PGEBEljVvV2q0alxxEVF3cvHzgADwAHOGL4Qz8AoNCAGkJgDF0Q1N00VLQ4I0enUgA===)

**Expected Behavior**: Warnings on both commented lines

**Actual Behavior**: Warning on only one commented line

edit: Expected behavior of this scenario has changed based on the proposal [nullable-parameter-default-value-analysis.md](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-parameter-default-value-analysis.md)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #48844
Closes #48847
Closes #48848
(note that these are really just 3 test cases, and expected behavior stated in the issues is not met by this PR. We changed the expectation as described in [nullable-parameter-default-value-analysis.md](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-parameter-default-value-analysis.md))

Related to #47352

Summary: parameter default values no longer affect initial state. A parameter default value which is incompatible with the parameter type is always a safety warning.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 1]
```diff
@@ -223,11 +223,52 @@ private ConstantValue DefaultSyntaxValue
...
+            var parameterSyntax = this.CSharpSyntaxNode;
+            var binder = GetBinder(parameterSyntax);
+
+            var parameterEqualsValue = new BoundParameterEqualsValue(
+                parameterSyntax,
+                this,
+                ImmutableArray<LocalSymbol>.Empty,
+                // note that if the parameter type conflicts with the default value from attributes,
+                // we will just get a bad constant value above and return early.
+                new BoundLiteral(parameterSyntax, DefaultValueFromAttributes, Type));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:261]: >DefaultValueFromAttributes [](start = 50, length = 26)

`defaultValue`

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Oh, we introduced new warnings in Roslyn :)

```
error CS8625: Cannot convert null literal to non-nullable reference type.
```

https://github.com/dotnet/roslyn/blob/d8eb54d3c56f3b8415eb713b94759bce085e13c7/src/Workspaces/Core/Portable/Shared/TestHooks/IAsynchronousOperationListener.cs#L11

**Review by jasonmalinowski — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 2]
```diff
@@ -206,9 +204,15 @@ private ConstantValue DefaultSyntaxValue
 
                     if (Interlocked.CompareExchange(
                         ref _lazyDefaultSyntaxValue,
-                        MakeDefaultExpression(diagnostics, ParameterBinderOpt),
+                        MakeDefaultExpression(diagnostics, out var binder, out var parameterEqualsValue),
                         ConstantValue.Unset) == ConstantValue.Unset)
                     {
+                        if (binder is not null && parameterEqualsValue is not null && !_lazyDefaultSyntaxValue.IsBad)
+                        {
+                            NullableWalker.AnalyzeIfNeeded(binder, parameterEqualsValue, diagnostics);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:212]: Why are we analyzing here and below?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 3]
```diff
@@ -223,44 +227,87 @@ private ConstantValue DefaultSyntaxValue
...
+                var binderFactory = compilation.GetBinderFactory(syntax.SyntaxTree);
+                binder = binderFactory.GetBinder(syntax);
+            }
+            Debug.Assert(binder.GetBinder(syntax) == null);
+            return binder;
+        }
+
+        private void NullableAnalyzeParameterDefaultValueFromAttributes(DiagnosticBag diagnostics)
         {
+            var defaultValue = DefaultValueFromAttributes;
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:249]: Consider skipping all this work if we don't need to do nullable analysis.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 4]
```diff
@@ -223,44 +227,87 @@ private ConstantValue DefaultSyntaxValue
...
+            // needs to wait until the attributes are populated on the parameter symbol.
+            var parameterEqualsValue = new BoundParameterEqualsValue(
+                parameterSyntax,
+                this,
+                ImmutableArray<LocalSymbol>.Empty,
+                // note that if the parameter type conflicts with the default value from attributes,
+                // we will just get a bad constant value above and return early.
+                new BoundLiteral(parameterSyntax, defaultValue, Type));
+
+            NullableWalker.AnalyzeIfNeeded(binder, parameterEqualsValue, diagnostics);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:278]: How is this information getting to the semantic model? IE, hovering over the `default` keyword for a NRT should have a nullable state of MaybeNull, are there tests for this?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -68101,12 +68114,15 @@ static void M()
                 // (6,34): warning CS1066: The default value specified for parameter 'x' will have no effect because it applies to a member that is used in contexts that do not allow optional arguments
                 //     static partial void G(object x = null, object? y = null) { }
                 Diagnostic(ErrorCode.WRN_DefaultValueForUnconsumedLocation, "x").WithArguments("x").WithLocation(6, 34),
+                // (6,38): warning CS8625: Cannot convert null literal to non-nullable reference type.
+                //     static partial void G(object x = null, object? y = null) { }
+                Diagnostic(ErrorCode.WRN_NullAsNonNullable, "null").WithLocation(6, 38),
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:68119]: I assume you have a test insertion, since we're adding new warnings?

**Review by 333fred — COMMENTED** [review]
Done review pass (commit 12)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:212]: In this implementation, _lazyDefaultSyntaxValue must be initialized on parameters before performing nullable analysis to avoid a stack overflow.

In my subsequent PR #49186 I modify `DefaultSyntaxValue` to return `ConstantValue.Unset` if we have not finished initializing the default value, for example when binding the default argument to `F()` in `void F(object param = F()) { }`.

Given that, we could clean this up to move analysis of the syntax value to within `MakeDefaultExpression` and move analysis of the attribute value to perhaps `GetAttributesBag` on this symbol in a follow-up.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:68119]: I kicked it off now, thanks. I'll link the insertion once it gets created.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:278]: I actually have no idea, but I will try to add some tests that I think cover this gap for this as well as for attributes which use a similar approach for nullable analysis.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:249]: Happy to do this in the follow-up at the same time as moving this check to a more appropriate spot.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:68119]: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/286574

Looks like there are 8 new nullable warnings. Some require just adding ? to a CallerMemberName parameter. The rest probably require adding a `!` e.g. `M<T>(T defaultValue = default!)`, because the project targets C# 8 and nullability attributes don't appear to be available.

**Review by 333fred — APPROVED** [review]
