### PR TITLE
Separate the process of creating an event accessor parameter and the process of figuring out its type.

### LINKED ISSUE #71400: Roslyn Compilation, 160 errors and process terminated due to NullReferenceException when a class with primary constructor implements INotifyPropertyChanged
**Version Used**: 
C# 12, dotnet SDK version 8.0.100, MSBuild version 17.8.3+195e7f5a3 for .NET,  Visual Studio Professional 2022 Version 17.8.3
Also occurs when using Rider version 2023.3.2

**Steps to Reproduce**:
1- Create a C# file with the following code and try to compile it. 
```csharp
using System.ComponentModel;

internal class MyClass(MyOtherClass otherClass, string key, int value) : INotifyPropertyChanged
{
    public string MyProperty { get; private set; } = GetValue(otherClass.MyProperty, key, value);
    private PropertyChangedEventHandler? _propertyChanged;


    private static string GetValue(string myProperty, string key, int value)
    {
        throw new NotImplementedException();
    }

    public event PropertyChangedEventHandler? PropertyChanged
    {
        add
        {
            lock (this)
            {
                if (_propertyChanged is null)
                {
                    otherClass.SomethingChanged += OnSomethingChanged;
                }
                _propertyChanged += value;

            }
        }
        remove
        {
            lock (this)
            {
                if (_propertyChanged is null)
                {
                    return;
                }
                _propertyChanged -= value;
                if (_propertyChanged is null)
                {
                    otherClass.SomethingChanged -= OnSomethingChanged;
                }
            }
        }
    }

    private void OnSomethingChanged(object? sender, EventArgs e)
    {
        throw new NotImplementedException();
    }
}

internal class MyOtherClass
{
    public event EventHandler? SomethingChanged;
    public string MyProperty { get; set; }
}

```

**Expected Behavior**:
The code should compile without error.

**Actual Behavior**:

- When building from the command line (`dotnet build`), the C# compiler produces 160 errors the crashes with error `C:\Program Files\dotnet\sdk\8.0.100\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Process terminated. System.NullReferenceException: Object reference not set to an instance of an object. [D:\source\my\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]` (This is a partial log of the error which is very big, the entire error log is attached [here](https://github.com/dotnet/roslyn/files/13751763/result.txt)).
- When building in Visual Studio I get `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -2146232797.`

Moreover, when working with either Visual Studio or Rider, the C# analyzers and generators stop working (apparently because of the Roslyn process crashing). While this may not be apparent in my sample reproduction, it occurs in my actual project, but I kept the reproduction to minimum and excluded irrelevant code. 

This seems to be similar to #50198, however the old issue is resolved (may be this is a regression?) and old one was related to records and not primary constructors.

**Workaround**:

Using a normal constructor instead of a primary constructor with that class fixed the issue and allowed me to continue my work.

### PR DESCRIPTION
**Pull request by AlekseyTs**
This allows us to perform lookup operations within the accessor without triggering the process of determining whether the event is a WINMD event. That process could request the list of containing type members while we are building the list, thus causing an unexpected circularity and an unexpected reentrancy into  SourceMemberMethodSymbol.LazyMethodChecks on the same thread.

Fixes #71400.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review, please.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs [hunk 1]
```diff
@@ -122,9 +121,6 @@ protected sealed override void MethodChecks(BindingDiagnosticBag diagnostics)
 
                         _lazyReturnType = TypeWithAnnotations.Create(eventTokenType);
                         this.SetReturnsVoid(returnsVoid: false);
-
-                        var parameter = new SynthesizedAccessorValueParameterSymbol(this, _event.TypeWithAnnotations, 0);
-                        _lazyParameters = ImmutableArray.Create<ParameterSymbol>(parameter);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs:127]: Should we assert here that the types remain as expected? For example here:

```cs
Debug.Assert(_parameters is [var p] && p.TypeWithAnnotations == _event.TypeWithAnnotation);
```

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs:127]: > Should we assert here and below that the types remain as expected? For example here

While we could do that. There will be a downside. That will mean that in DEBUG we will be synchronizing two processes that are going to be fully asynchronous in RELEASE, which might lead to a noticeable difference in behavior between the flavors. So, I am reluctant to add an assert like that.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs:127]: However, If you feel strongly about having the assert, I will add it.

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs:127]: Thanks for the explanation - now I think it's better without an assert here then.
