### PR TITLE
Fix extract local in base initializer

### LINKED ISSUE #50495: "Extract local function" generates broken code when applied to base constructor calls
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Extract-local-function-generates-broke/1295410)._

---
[severity:It bothers me. A fix would be nice]
When code inside a `base` call in a constructor is highlighted, the "Extract local function" refactoring option is displayed. However, applying this refactor generates code that does not compile, since the generated `static` local function cannot be called from the base constructor initializer.

Sample

```
    public abstract class SomeBaseClass
    {
        private readonly int value;

public SomeBaseClass(int value) =>
            this.value = value;
    }

public sealed class SomeInheritedClass : SomeBaseClass
    {
        public SomeInheritedClass()
            : base("123456". Length)
        {
        }
    }
```

When the `"123456". Length` code is selected and quick actions is activated, the "Extract Local Function" option appears:

! [image.png] (https://aka.ms/dc/image?name=B668565d1389147c1b0fc08d886321fd6637443499191782568_20201223-165157-image.png&tid=668565d1389147c1b0fc08d886321fd6637443499191782568)

After applying the refactoring, this is the generated code:

```
    public sealed class SomeInheritedClass : SomeBaseClass
    {
        public SomeInheritedClass()
            : base(GetLength())
        {
            static int GetLength()
            {
                return "123456". Length;
            }
        }
    }
```

Which fails to compile due to multiple errors:

- Error	CS8321	The local function 'GetLength' is declared but never used	
! [image.png] (https://aka.ms/dc/image?name=B870e76cf981548a2b1a9df17f6ef3e9b637443501085368287_20201223-165507-image.png&tid=870e76cf981548a2b1a9df17f6ef3e9b637443501085368287)

- Error	CS0103	The name 'GetLength' does not exist in the current context	
! [image.png] (https://aka.ms/dc/image?name=Baf5181ee5e634dbca0894f768a85ea5e637443500744836074_20201223-165432-image.png&tid=af5181ee5e634dbca0894f768a85ea5e637443500744836074)

---
#### Feedback Bot on 12/23/2020, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #50495

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs [hunk 1]
```diff
@@ -5234,5 +5234,30 @@ string NewMethod(object a)
 }";
             await TestAsync(code, expected, TestOptions.Script.WithLanguageVersion(LanguageVersion.CSharp7), index: CodeActionIndex);
         }
+
+        [Fact]
+        public async Task TestExtracLocalFunction_MissingInBase()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs:5239]:
```suggestion
        public async Task TestExtractLocalFunction_MissingInBase()
```

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs [hunk 2]
```diff
@@ -5234,5 +5234,30 @@ string NewMethod(object a)
...
+                class C : Base
+                {
+                    public C(int y)
+                        : base([|y + 1|])
+                    {
+                    }
+                }
+                """;
+
+            await TestMissingAsync(code, codeActionIndex: CodeActionIndex);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs:5260]: do we have a test for extract method though?

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx [hunk 3]
```diff
@@ -632,4 +632,7 @@
   <data name="Apply_readonly_struct_preferences" xml:space="preserve">
     <value>Apply 'readonly struct' preferences</value>
   </data>
+  <data name="Selection_cannot_be_in_base_constructor_initialize" xml:space="preserve">
+    <value>Selection cannot be in base constructor initializer</value>
+  </data>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CSharpFeaturesResources.resx:637]: do we have a test for extracting a method?

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx [hunk 4]
```diff
@@ -632,4 +632,7 @@
   <data name="Apply_readonly_struct_preferences" xml:space="preserve">
     <value>Apply 'readonly struct' preferences</value>
   </data>
+  <data name="Selection_cannot_be_in_base_constructor_initialize" xml:space="preserve">
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CSharpFeaturesResources.resx:635]:
```suggestion
  <data name="Selection_cannot_be_in_base_constructor_initializer" xml:space="preserve">
```

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs [hunk 5]
```diff
@@ -5234,5 +5234,30 @@ string NewMethod(object a)
...
+                    public Base(int x)
+                    {
+                        _x = x;
+                    }
+                }
+
+                class C : Base
+                {
+                    public C(int y)
+                        : base([|y + 1|])
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs:5254]: test for `this(...)` initializer as well?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs:5254]: test where there's a lambda being passed upwards and someone wants to extract a local function *inside* the lambda body.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs [hunk 6]
```diff
@@ -117,6 +117,11 @@ private static SelectionInfo ApplySpecialCases(SelectionInfo selectionInfo, Sour
                 }
             }
 
+            if (_localFunction && selectionInfo.CommonRootFromOriginalSpan.AncestorsAndSelf().Any(c => c.IsKind(SyntaxKind.BaseConstructorInitializer)))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs:120]: generally, walking up arbitrary heights is not good.  because it breaks legal cases (like a lambda in the this/base which might have code to extract into a local function).  so try to walk up and see if you have some AnonmousMethodSyntax above  you, and allow extraction then (we may have helpers for this, not sure).

**Comment by CyrusNajmabadi** [comment]
Done with pass :)

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx (hunk 3 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/CSharpFeaturesResources.resx:637]: I'll check. It should be valid for those cases.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs (hunk 6 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs:120]: Ah I see... didn't think about anonymouse method within. Lambdas 🤦

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs (hunk 1 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs:5239]: Apparently typing is hard today

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx (hunk 3 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/CSharpFeaturesResources.resx:637]: I added for extract method and found some bugs. Filed them as follow up and noted in the tests that are skipped

File: src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs [hunk 7]
```diff
@@ -117,6 +115,22 @@ private static SelectionInfo ApplySpecialCases(SelectionInfo selectionInfo, Sour
...
+            if (_localFunction)
+            {
+                foreach (var ancestor in selectionInfo.CommonRootFromOriginalSpan.AncestorsAndSelf())
+                {
+                    if (ancestor.IsKind(SyntaxKind.BaseConstructorInitializer) || ancestor.IsKind(SyntaxKind.ThisConstructorInitializer))
+                    {
+                        return selectionInfo.WithStatus(s => s.With(OperationStatusFlag.None, CSharpFeaturesResources.Selection_cannot_be_in_constructor_initializer));
+                    }
+
+                    if (ancestor.Kind() is SyntaxKind.AnonymousMethodExpression or SyntaxKind.ParenthesizedLambdaExpression or SyntaxKind.SimpleLambdaExpression)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs:127]:
```suggestion
                    if (ancestor is AnonymousFunctionExpressionSyntax)
```

Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs:127]: nit, consider doc'ing.

**Review by CyrusNajmabadi — APPROVED** [review]
