### PR TITLE
Fix #33560 Handle equal tokens where Text is not available.

### LINKED ISSUE #33560: 'Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Unexpected true'
**Version Used**: 

VS 2019 preview 3

```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Unexpected true'.	

Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: SwitchToSource.CLI
SyntaxTree: C:\Users\Documents\Sources\Command.List.cs
SyntaxNode: else System.Console.WriteLine($" ... [ElseClauseSyntax]@[2781..2931) (54,40)-(55,144)

System.InvalidOperationException: Unexpected true
   at Roslyn.Utilities.Contract.ThrowIfTrue(Boolean condition, String message)
   at Microsoft.CodeAnalysis.Shared.Utilities.CommonFormattingHelpers.AppendTextBetween(SyntaxToken token1, SyntaxToken token2, StringBuilder builder)
   at Microsoft.CodeAnalysis.CSharp.Utilities.FormattingRangeHelper.AreTwoTokensOnSameLine(SyntaxToken token1, SyntaxToken token2)
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesDiagnosticAnalyzer.IsConsideredMultiLine(SyntaxNode statement, SyntaxNode embeddedStatement)
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesDiagnosticAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

The code around the error (The line comments are not in the original code)

```csharp
          packageToDisplayList.ForEach(listedPackage => // line 48
          {
              System.Console.WriteLine($"- {listedPackage.PackageId}");
              foreach (var versionInfo in listedPackage.Versions)
              {
                  if (versionInfo.Reason == NonSwitchableReason.None)
                      System.Console.WriteLine($"   * {versionInfo.Version} [{versionInfo.State}]"); // line 54
                  else
                      System.Console.WriteLine($"   * {versionInfo.Version} [{versionInfo.State}: {versionInfo.Reason}]");
              }
          });
```

### PR DESCRIPTION
**Pull request by Andrew-Hanlon**
Fixes #33560
I updated the helper method `AreTwoTokensOnSameLine` to exit early when the provided tokens are equal. This prevents an exception from being thrown when equal tokens are provided and the `SyntaxTree` is null or the `SyntaxTree.TryGetText()` call fails. I added unit tests to cover basic regressions as well as the erroneous case above.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs [hunk 1]
```diff
@@ -288,6 +288,8 @@ private static SyntaxToken GetPreviousTokenIfNotFirstTokenInTree(SyntaxToken tok
 
         public static bool AreTwoTokensOnSameLine(SyntaxToken token1, SyntaxToken token2)
         {
+            if (token1 == token2) return true;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: nit: could you write this as:

```c#
if (token1 == token2)
{
    return true;
}
```

Tnx! :)

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for approval

File: src/Workspaces/CoreTest/UtilityTest/FormattingRangeHelperTests.cs [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+using Microsoft.CodeAnalysis.CSharp;
+using Microsoft.CodeAnalysis.CSharp.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.UnitTests.UtilityTest
+{
+    public class FormattingRangeHelperTests
+    {
+        [Fact]
+        public void TestAreTwoTokensOnSameLineTrue()
```
Comment (sharwell) [inline src/Workspaces/CoreTest/UtilityTest/FormattingRangeHelperTests.cs]: 💡 Can you include `[WorkItem]` attributes so these tests link back to the original bug? At minimum, you want to include this attribute on all tests which fail without your change above. However, it would be fine to include the attribute for all tests you added here, even if some of them worked before and after the change.

File: src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs (hunk 1 above)
Comment (genlu) [inline src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]:
```suggestion
            if (token1 == token2)
            {
                return true;
            }
```

File: src/Workspaces/CoreTest/UtilityTest/FormattingRangeHelperTests.cs (hunk 2 above)
Comment (Andrew-Hanlon) [reply src/Workspaces/CoreTest/UtilityTest/FormattingRangeHelperTests.cs]: Thanks, I have added the WorkItem attribution to the tests.

File: src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs (hunk 1 above)
Comment (Andrew-Hanlon) [reply src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: Thanks @CyrusNajmabadi for the formatting style suggestion. Thanks @genlu for addressing this, I applied the suggested change.

**Comment by CyrusNajmabadi** [comment]
Thank you @Andrew-Hanlon ! :)

**Comment by sharwell** [comment]
@jinujoseph for approval

**Comment by sharwell** [comment]
Thank you @Andrew-Hanlon !
