### PR TITLE
Avoid duplicate analyzer callbacks for PrimaryConstructorBaseTypeSyntax and BaseListSyntax nodes

### LINKED ISSUE #70488: Duplicate syntax node callbacks for PrimaryConstructorBaseType
**Version Used**:  Latest Main

**Steps to Reproduce**:

1. Create a syntax node analyzer and register for `SyntaxKind.PrimaryConstructorBaseType`
2. Analyze:
```cs
    class Base(int a) { }

    class Derived(int a) : Base(a);
```

**Expected Behavior**:

The callback is only called once for `Base(a)`

**Actual Behavior**:

The callback is called twice.

This behavior is already documented in

https://github.com/dotnet/roslyn/blob/3c17539d0469a782882b5efac9e72d63e7643fd4/src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs#L3857-L3880

The callback is called with different `ContainingSymbol`
1. the containing type (`INamedTypeSymbol { Name: Derived }`)
2. the primary constructor of derived (`IMethodSymbol { MethodKind: Constructor, Name: Derived.ctor }`)

It is also called twice if `class` is replaced by `record`.

This is comparable to what we have seen in https://github.com/dotnet/roslyn/issues/53136 for RecordDeclaration which was fixed in #58482

Back then the PrimaryConstructorBaseType was already mentioned:
https://github.com/dotnet/roslyn/pull/58482#pullrequestreview-842740772
and identified as problematic:
https://github.com/dotnet/roslyn/pull/58482#issuecomment-1007287329

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #70488

Fix is on the same lines as #58482. We have common syntax nodes shared between two symbols and we need to ensure that we do not make duplicate callbacks for nodes when processing symbol declared events for these symbols.

- We analyze `BaseListSyntax` when processing the named type symbol, but skip it when processing the primary constructor symbol.
- We analyze `PrimaryConstructorBaseTypeSyntax` when processing the primary constructor symbol, but skip it when processing the named type symbol. Note that this is required as `PrimaryConstructorBaseTypeSyntax` is the topmost node for the primary constructor executable code block, and we already make CodeBlock and OperationBlock callbacks with this node as the block root.  Attempting to do it the other way caused a large number of unit test failures.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 1]
```diff
@@ -2514,22 +2514,42 @@ internal override Symbol RemapSymbolIfNecessaryCore(Symbol symbol)
...
+                            // We will analyze this node when analyzing the type declaration type symbol.
+                            return true;
+                    }
+
+                    break;
 
-                    case CompilationUnitSyntax:
-                        // Skip compilation unit syntax node when analyzing synthesized top level entry point method
+                case SymbolKind.NamedType:
+                    if (node is PrimaryConstructorBaseTypeSyntax)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2544]: >if (node is PrimaryConstructorBaseTypeSyntax) [](http://example.com/codeflow?start=20&length=45)

Is it possible to subscribe to an event for one of the constituents of this node? For example, for the `ArgumentList` or one of the arguments. How many call backs are we going to get then?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 2]
```diff
@@ -2514,22 +2514,42 @@ internal override Symbol RemapSymbolIfNecessaryCore(Symbol symbol)
...
+                            // We will analyze this node when analyzing the type declaration type symbol.
+                            return true;
+
+                        case CompilationUnitSyntax:
+                            // Skip compilation unit syntax node when analyzing synthesized top level entry point method
+                            // to avoid duplicate syntax node callbacks.
+                            // We will analyze this node when analyzing the global namespace symbol.
+                            return true;
+
+                        case BaseListSyntax:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2534]: >BaseListSyntax [](http://example.com/codeflow?start=29&length=14)

Is it possible to subscribe to an event for items other that the first one in this list? How many call backs are we going to get for them in presence of a primary constructor?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2544]: What about other parts of the type declaration header?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2534]: What about other parts of the type declaration header?

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 3]
```diff
@@ -4009,6 +4009,46 @@ public record A(int X, int Y);";
...
+            public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get { return ImmutableArray.Create(Rule); } }
+
+            public override void Initialize(AnalysisContext context)
+            {
+                context.RegisterSyntaxNodeAction(AnalyzePrimaryConstructorBaseType, SyntaxKind.BaseList, SyntaxKind.PrimaryConstructorBaseType);
+            }
+
+            private static void AnalyzePrimaryConstructorBaseType(SyntaxNodeAnalysisContext context)
+            {
+                var diagnostic = CodeAnalysis.Diagnostic.Create(Rule, context.Node.GetLocation());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs:4031]: >var diagnostic = CodeAnalysis.Diagnostic.Create(Rule, context.Node.GetLocation()); [](http://example.com/codeflow?start=16&length=82)

Consider also verifying symbol associated with the context.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2544]: > Is it possible to subscribe to an event for one of the constituents of this node? For example, for the ArgumentList or one of the arguments. How many call backs are we going to get then?

Thanks, I enhanced the added unit test to verify we get single callbacks for all the descendants of BaseListSyntax. There is existing code which ensures we only analyze ArgumentList and its descendants when processing the primary constructor method symbol: https://github.com/dotnet/roslyn/blob/c5d20779f421caafbd4e18e3bfc5c0320a0a29f8/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L2432-L2505

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 3 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs]: Done

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 2 above)
Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2534]: Enhanced the added unit test

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

File: src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs [hunk 4]
```diff
@@ -3866,9 +3864,6 @@ protected void Handle5(SyntaxNodeAnalysisContext context)
                             case "B..ctor([System.Int32 Y = 1])":
                                 Interlocked.Increment(ref FireCount9);
                                 break;
-                            case "B":
-                                Interlocked.Increment(ref FireCount17);
-                                break;
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs:3871]: > Why remove this case, rather than update the expected number of hits in the tests?

I think removal is preferred. We do not expect any hits and the `default` case verifies that in a reliable way.

**Review by cston — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks
