### PR TITLE
Fix symbol end action not completing for symbols with non-implicit me…

### LINKED ISSUE #30309: Debug integration test assertion in symbol end verification
Excuse the blurry image. MS Teams hangs if I try to view, copy, or save a non-blurry one.

image

### PR DESCRIPTION
**Pull request by mavasani**
…mbers that have no source location.

In VB, MyApplication type has a Main method which is not marked as IsImplicitlyDeclared but has no source locations (it has a MyTemplateLocation). Due to the latter, VB never generates symbol declared events for such a Main method, causing the symbol end action to never run for it's container. This assert fires intermittently in an [integration test](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.IntegrationTests/VisualBasic/BasicAddMissingReference.cs,151), but does not repro when the project is manually opened. Verified the assert does not fire for multiple iterations of the same integration test after this fix.

 Fixes #30309

### CODE REVIEW

File: src/Compilers/Core/Portable/Symbols/ISymbolExtensions.cs [hunk 1]
```diff
@@ -96,5 +96,18 @@ internal static INamespaceSymbol GetNestedNamespace(this INamespaceSymbol contai
 
         internal static bool IsNetModule(this IAssemblySymbol assembly) =>
             assembly is ISourceAssemblySymbol sourceAssembly && sourceAssembly.Compilation.Options.OutputKind.IsNetModule();
+
+        internal static bool HasSourceLocation(this ISymbol symbol)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Symbols/ISymbolExtensions.cs]: >HasSourceLocation [](start = 29, length = 17)

IsInSource?

**Comment by mavasani** [comment]
> Is it possible to add targeted test for the scenario?

I spent nearly a day trying to get a unit test that fails in this scenario, but was unable to do so. Also note that I was unable to repro it by manually opening the solution used in the integration test where this assert frequently fired, even after multiple attempts.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb [hunk 2]
```diff
@@ -1535,5 +1535,31 @@ Block[B2] - Exit
                 ControlFlowGraphVerifier.VerifyGraph(compilation, expectedFlowGraph, actualFlowGraph)
             Next
         End Sub
+
+        <Fact, WorkItem(30309, "https://github.com/dotnet/roslyn/issues/30309")>
+        Public Sub TestSymbolStartAnalyzer_MyApplication()
+
+            Dim sources = <compilation>
+                              <file name="a.vb"><![CDATA[
+Namespace My
```
Comment (mavasani) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb]: @AlekseyTs Thanks for pointing to the VB MyTemplate code file. That helped me write this test correctly.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for an additional review.

**Comment by mavasani** [comment]
retest ubuntu_16_debug_prtest please

**Comment by mavasani** [comment]
retest windows_coreclr_debug_prtest please

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb [hunk 3]
```diff
@@ -1672,18 +1672,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         End Sub
 
         Friend Function ShouldAddEvent(symbol As Symbol) As Boolean
-            If EventQueue Is Nothing Then
-                Return False
-            End If
-
-            For Each location As Location In symbol.Locations
-                If location.SourceTree IsNot Nothing Then
-                    Debug.Assert(AllSyntaxTrees.Contains(location.SourceTree))
```
Comment (333fred) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Is there any way to preserve this assert?

Comment (mavasani) [reply src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Doesn't seem so because `AllSyntaxTrees` is internal to VisualBasicCompilation.

**Comment by mavasani** [comment]
@jinujoseph for approval
