### PR TITLE
[Ask Mode] Prevent a set of crashes in IOperation implementations

### LINKED ISSUE #8774: IOperation: VB - BoundCall.IIsVirtual should probably do a null check for ReceiverOpt
```
        Private ReadOnly Property IIsVirtual As Boolean Implements IInvocationExpression.IsVirtual
            Get
                Dim method As IMethodSymbol = Me.Method

                Return (method.IsVirtual OrElse method.IsAbstract OrElse method.IsOverride) AndAlso Me.ReceiverOpt.Kind <> BoundKind.MyBaseReference AndAlso Me.ReceiverOpt.Kind <> BoundKind.MyClassReference
            End Get
        End Property
```

### PR DESCRIPTION
**Pull request by JohnHamby**
FIxes #8774 #8829 #8848 #8849 #9018

The edits all involve hardening IOperation implementations against structural surprises in the bound trees that can arise in compiling malformed input programs.

Some of the issues were found by actual testing and are covered by tests there. Others @AlekseyTs found by inspection and have so far eluded simple testing.

@genlu @AlekseyTs @MattGertz @ManishJayaswal , please?

### CODE REVIEW

**Comment by genlu** [comment]
:+1:

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 1]
```diff
@@ -41,9 +41,9 @@ internal partial class BoundCall : IInvocationExpression
     {
         IMethodSymbol IInvocationExpression.TargetMethod => this.Method;
 
-        IOperation IInvocationExpression.Instance => this.Method.IsStatic ? null : this.ReceiverOpt;
+        IOperation IInvocationExpression.Instance => (this.Method == null || this.Method.IsStatic) ? null : this.ReceiverOpt;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: In C#, when symbols are compared with null, they should be converted to object. The motivation is to bypass a call for an overloaded equality operator.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 2]
```diff
@@ -48,6 +48,19 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         Public MustOverride Overloads Sub Accept(visitor As OperationVisitor) Implements IOperation.Accept
 
         Public MustOverride Overloads Function Accept(Of TArgument, TResult)(visitor As OperationVisitor(Of TArgument, TResult), argument As TArgument) As TResult Implements IOperation.Accept
+
+        Protected Shared Function GetBadChild(parent As BoundNode, index As Integer) As IOperation
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I think the name is misleading, the child isn't necessary bad, its parent is bad though. I'd use name "GetChildOfBadExpression" or something similar.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 1 above)
Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Fair enough. Thanks!

We should have an analyzer to catch this.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 3]
```diff
@@ -769,42 +792,39 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                Else
+                    Return GetBadChild(Me.UnderlyingExpression, 1)
+                End If
             End Get
         End Property
 
         Private ReadOnly Property IHasOperatorMethodExpression_OperatorMethod As IMethodSymbol Implements IHasOperatorMethodExpression.OperatorMethod
             Get
-                Return Me.Call.Method
+                Return If(TypeOf Me.UnderlyingExpression Is BoundCall, Me.Call.Method, Nothing)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: In compiler codebase, we prefer kind checks to TypeOf checks.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 4]
```diff
@@ -109,7 +122,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         Private ReadOnly Property IHasOperatorMethodExpression_UsesOperatorMethod As Boolean Implements IHasOperatorMethodExpression.UsesOperatorMethod
             Get
                 If ExpressionKind() = OperationKind.CompoundAssignmentExpression Then
-                    Return TypeOf Me.Right Is BoundUserDefinedBinaryOperator
+                    Dim rightBinary As IBinaryOperatorExpression = TryCast(Me.Right, IBinaryOperatorExpression)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I believe, Me.Right can be a conversion on top of the binary operator.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 5]
```diff
@@ -126,7 +140,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
             Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = TryCast(Me.Right, BoundUserDefinedBinaryOperator)
             If rightOperatorBinary IsNot Nothing Then
-                If TypeOf rightOperatorBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
+                If TypeOf DirectCast(rightOperatorBinary, IBinaryOperatorExpression).LeftOperand Is BoundCompoundAssignmentTargetPlaceholder Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: This is possibly better than before, but the whole logic in this method is too complex and is incorrect in general. I opened a special issue regarding this.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 4 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: That can lead to incorrect behavior in that something can appear to be invalid that is actually valid, but it doesn't crash, and so isn't necessarily an Update 2 issue. This needs to be correct, but it doesn't need to be correct now.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 5 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Agreed. The goal for Update 2 is to avoid crashes, and to handle simple cases correctly. For Update 3 this needs to be completely correct.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 3 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I will change the code to use Kind tests throughout this file.

**Comment by JohnHamby** [comment]
I've pushed a new commit that includes casting symbols to object before comparing to null, using Kind tests instead of type tests, and a method renaming suggested by @AlekseyTs .

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 6]
```diff
@@ -119,14 +133,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-                If TypeOf rightBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
+                If rightBinary.Left.Kind = BoundKind.CompoundAssignmentTargetPlaceholder Then
                     Return OperationKind.CompoundAssignmentExpression
                 End If
             End If
 
             Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = TryCast(Me.Right, BoundUserDefinedBinaryOperator)
             If rightOperatorBinary IsNot Nothing Then
-                If TypeOf rightOperatorBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
+                If DirectCast(rightOperatorBinary, IBinaryOperatorExpression).LeftOperand.Kind = BoundKind.CompoundAssignmentTargetPlaceholder Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I don't think this compares the right Kind now. Does IOperation.Kind returns BoundKind? Either both sides should be in BoundNode universe, or in IOperation universe.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 7]
```diff
@@ -624,24 +639,28 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
             End Get
         End Property
 
         Private ReadOnly Property IUnaryOperatorExpression_Operand As IOperation Implements IUnaryOperatorExpression.Operand
             Get
-                Return Me.Operand
+                If Me.UnderlyingExpression.Kind = BoundKind.Call Then
+                    Return Me.Operand
+                Else
+                    Return GetChildOfBadExpression(Me.UnderlyingExpression, 0)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Do we test that this is the right node?

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 8]
```diff
@@ -724,7 +743,11 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Private ReadOnly Property IBinaryOperatorExpression_LeftOperand As IOperation Implements IBinaryOperatorExpression.LeftOperand
             Get
-                Return Me.Left
+                If Me.UnderlyingExpression.Kind = BoundKind.Call Then
+                    Return Me.Left
+                Else
+                    Return GetChildOfBadExpression(Me.UnderlyingExpression, 0)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Do we have a test verifying that this is the right node?

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 7 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: It looks like GetChildOfBadExpression can return null. Is it Ok for this API to return null?

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 9]
```diff
@@ -769,42 +792,39 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
         End Property
 
         Private ReadOnly Property IBinaryOperatorExpression_RightOperand As IOperation Implements IBinaryOperatorExpression.RightOperand
             Get
-                Return Me.Right
+
+                If Me.UnderlyingExpression.Kind = BoundKind.Call Then
+                    Return Me.Right
+                Else
+                    Return GetChildOfBadExpression(Me.UnderlyingExpression, 1)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Do we have a test verifying that this is the right node?

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 6 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Wow. You are correct. It's disappointing that this compiles without a warning.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 7 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: GetChildOfBadExpression cannot return null.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: You are correct, my memory failed me.

**Comment by JohnHamby** [comment]
I've pushed a new commit that includes more robust testing and fixes the enum type pun @AlekseyTs pointed out.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 9 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Yes, now.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 8 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Yes, now.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 7 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: We do not have a test that verifies that this is the correct node, because I have not been able to construct a test for which this code executes. Anyone have a suggestion for some source that will compile to a BoundUserDefinedUnaryOperator with a bad underlying expression?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Try to add throw in the relevant part of implementation and run semantics tests.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: It doesn't look like we have an existing compiler unit-test hitting that specific error code path, but this test hits it, I believe:
```
        <Fact>
        Public Sub Test()
            Dim compilationDef =
<compilation>
    <file name="a.vb">
Class C1
    Public Shared Operator -(x As C1) As C1
        Return Nothing
    End Operator

    Public Shared Operator -(x As C1) As C1
        Return Nothing
    End Operator

    Sub Test()
        Dim x = -Me
    End Sub
End Class
    </file>
</compilation>

            Dim compilation = CreateCompilationWithMscorlibAndVBRuntime(compilationDef, options:=TestOptions.ReleaseExe)
            compilation.GetSemanticModel(compilation.SyntaxTrees.Single()).GetDiagnostics().AssertTheseDiagnostics(<![CDATA[
BC30269: 'Public Shared Operator -(x As C1) As C1' has multiple definitions with identical signatures.
    Public Shared Operator -(x As C1) As C1
                           ~
BC30521: Overload resolution failed because no accessible '-' is most specific for these arguments:
    'Public Shared Operator -(x As C1) As C1': Not most specific.
    'Public Shared Operator -(x As C1) As C1': Not most specific.
        Dim x = -Me
                ~~~
]]>)
        End Sub
```

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 10]
```diff
@@ -119,14 +133,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-                If TypeOf rightBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
+                If rightBinary.Left.Kind = BoundKind.CompoundAssignmentTargetPlaceholder Then
                     Return OperationKind.CompoundAssignmentExpression
                 End If
             End If
 
             Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = TryCast(Me.Right, BoundUserDefinedBinaryOperator)
             If rightOperatorBinary IsNot Nothing Then
-                If TypeOf rightOperatorBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
+                If DirectCast(rightOperatorBinary, IBinaryOperatorExpression).LeftOperand.Kind = OperationKind.PlaceholderExpression Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: It doesn't look like BoundCompoundAssignmentTargetPlaceholder returns this OperationKind. The fact that we cannot get this line of code right after two attempts shows that we have a test gap, which we are not trying to close. Let's close it, let's test the code that we are writing.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: @JohnHamby If my observation about OperationKind is correct, before making another round of changes here, let's discuss what it might look like offline.

**Comment by JohnHamby** [comment]
I've pushed a new commit that includes some realistic testing. @AlekseyTs prevailed upon me to start on a path of testing IOperation like a compiler representation rather than just as analyzer infrastructure.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 7 above)
Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: We now have a test that verifies that the operand is correct.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by JohnHamby** [comment]
@MattGertz ?
