### PR TITLE
Preserve local function preceding whitespace for Issue #35489

### LINKED ISSUE #35489: [C# 8.0] Make local function static removes preceding blank line
**Version Used**: 
Version 16.1.0 Preview 4.0 [28901.261.d16.1stg]

**Steps to Reproduce**:

``` C#
            return Task.FromResult(result);

            (bool designTime, bool designTimeShared) GetDesignTimePropsForItem(IImmutableDictionary<string, string> item)
            {
              
            }
```

**Expected Behavior**:
``` C#
            return Task.FromResult(result);

            static (bool designTime, bool designTimeShared) GetDesignTimePropsForItem(IImmutableDictionary<string, string> item)
            {
       
            }
```
**Actual Behavior**:
``` C#
            return Task.FromResult(result);
            static (bool designTime, bool designTimeShared) GetDesignTimePropsForItem(IImmutableDictionary<string, string> item)
            {
       
            }
```

### PR DESCRIPTION
**Pull request by gnovack**
This resolves #35489 by preserving the original trivia in the 'Make local function static' code fix.

### CODE REVIEW

File: src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs [hunk 1]
```diff
@@ -44,7 +44,7 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
                     localFunction,
                     (current, generator) => generator.WithModifiers(
                         current,
-                        generator.GetModifiers(current).WithIsStatic(true)));
+                        generator.GetModifiers(current).WithIsStatic(true)).WithTriviaFrom(localFunction));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs]: it feels like this s a bug in WithModifiers itself.  If i *anyone* adds the 'static' modifier to a local function, using the generator, i think they would expect leading trivia to be preserved.

Comment (gnovack) [reply src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs]: Ah, good point. I'll look again to see if there is a way to resolve this without explicitly copying the trivia.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs]: Note: you may have to copy the trivia.  It's just that that copying should likely happen inside the generator.  Indeed, i think it's supposed to do that.  But it may be the case that it was never updated to handle the local-function case.  Thanks!

**Comment by gnovack** [comment]
Have a pretty good idea what's happening, but I need some clarification on a few behaviors:

The removal of blank lines as described in #35489 occurs also when executing 'Add readonly modifier', 'Add accessibility modifiers', and probably others that call `WithModifiers`. 

**Example**:

Before:
```csharp
class MyClass
{
        int int1;

        int int2;
}
```
After executing 'Add accessibility modifiers' code fix on `int2`:
```csharp
class MyClass
{
        int int1;
        private int int2;
}
```
Also, executing the same code fix on a method declaration removes all but one blank line.

**Example**: 
Before (note two blank lines between method declarations):
```csharp
class MyClass
{
        void M1()
        {
        }


        void M2()
        {
        }
}
```
After executing 'Add accessibility modifiers' code fix on `M2()`:
```csharp
class MyClass
{
        void M1()
        {
        }

        private void M2()
        {
        }
}
```
**Questions**:
1. Which, if either, of these behaviors (removal of all blank lines for fields, removal of all but one blank line for method declarations) is expected?
2. If the current behavior for method declarations is expected, should local functions behave in the same way, removing all but one preceding blank line?

**Comment by sharwell** [comment]
@gnovack I would be fine with _either_ of the following:

* Local functions preserves all existing blank lines
* Local functions removes all but one existing blank lines

In addition:

1. It would be acceptable, but definitely not required and perhaps not preferable, for the "Add accessibility modifiers" to change behavior and start preserving all blank lines
2. It would be acceptable, but not required, for the "Add readonly modifier" code fix to change behavior and start preserving all blank lines

I'm hoping this leaves you with a bit of flexibility to implement a solution in a relatively clean and consistent manner. Please let me know if you have any more questions.

**Comment by gnovack** [comment]
Thanks @sharwell 

9760868c28eba500f5e44c07e44ec63e2254d2aa aligns the treatment of blank lines preceding local functions with that of blank lines preceding method declarations (i.e. one blank line will always be preserved)

I did not make any changes to the other code fixes mentioned previously.

If you'd like, I can definitely add some more tests for 'Make local function static' to cover cases outside of the one mentioned in the original issue, as that only covers one path that the formatter can take.

**Comment by sharwell** [comment]
@gnovack Here are some additional test cases I would like to see:

1. Local function at the beginning of a method (first item inside the `{`)

2. Expression-bodied local functions in sequence, e.g.

    ```csharp
    bool IsFirst() => true;
    bool IsLast() => false;
    ```

3. Block-bodied local functions in sequence

4. Local functions that are documented with a comment

    ```csharp
    // This is a local function
    void someLocalFunction() { }
    ```

For most of the above, it would be good to test cases with and without a blank line preceding the local function. You may be able to do this easily with a `[Theory]` and an interpolated string:

```
[Theory]
[InlineData("")]
[InlineData("\r\n")]
public void MyTest(string precedingTrivia)
{
  var testCode = $"
class Class
{{
  void Method()
  {{
{precedingTrivia}    void LocalFunction()
    {{
    }}
  }}
}}
";
}
```

File: src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs [hunk 2]
```diff
@@ -191,26 +207,156 @@ void M()
...
+        }}
+    }}
+}}",
+$@"using System;
+
+class C
+{{
+    void M()
+    {{
+        //Local function comment{leadingTrivia}
```
Comment (gnovack) [inline src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs]: Probably worth noting that no changes are made to blank lines when the local function is preceded by a comment, meaning that all blank lines will be preserved, and no blank lines will be inserted. I confirmed that normal method declarations have the same behavior.

File: src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs [hunk 3]
```diff
@@ -176,6 +176,187 @@ static async Task<int> fibonacci(int n)
...
+        public async Task TestLeadingTriviaAfterComment(string leadingTrivia)
+        {
+            await TestInRegularAndScriptAsync(
+$@"using System;
+
+class C
+{{
+    void M()
+    {{
+        //Local function comment{leadingTrivia}
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs]: 💡 It would be good to have one more where the blank lines precede the comment

Comment (gnovack) [reply src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs]: Were you thinking something like this?

```csharp
void M()
{{{leadingTrivia}
   //Comment
   void localFunction() ...
```
