### PR TITLE
Make AnalyzerActions a value type

### LINKED ISSUE #39102: Use a singleton for AnalyzerActions.Empty
**Version Used**: Unknown

:link: https://developercommunity.visualstudio.com/content/problem/531240/occasional-outofmemoryexception.html

One of the heap dumps showed 3,486,047 instances of Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, but at most 5,000 were not empty. Using a singleton for the empty case would save a large amount of memory.

As a step past this, we could attempt avoid placing empty items in the dictionary at all, and internally treat missing the same as empty.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #39102

Reduces allocations during analysis of Roslyn.sln by many GB (6 GB, ~2.4%).

Baseline (c0c68fcb7acef68ea8f078ec519a5183e3276ce1):

```
Found 486295 diagnostics in 390792ms (248890727112 bytes allocated)
```

Updated (c0c68fcb7acef68ea8f078ec519a5183e3276ce1 + 4c37d9a19ad1f9e514ce71b06d119250411e6e58)

```
Found 486290 diagnostics in 391640ms (242634251728 bytes allocated)
```

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 1]
```diff
@@ -89,6 +89,8 @@ internal abstract partial class AnalyzerDriver : IDisposable
         /// </summary>
         private ImmutableDictionary<DiagnosticAnalyzer, GeneratedCodeAnalysisFlags> _generatedCodeAnalysisFlagsMap;
 
+        private AnalyzerActions _analyzerActions;
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Please add a comment, everything else in the driver has one.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 2]
```diff
@@ -1341,7 +1343,7 @@ private async ValueTask<EventProcessedState> TryProcessSymbolDeclaredAsync(Symbo
                 var skipDeclarationAnalysis = AnalysisScope.ShouldSkipDeclarationAnalysis(symbol);
                 var hasPerSymbolActions = AnalyzerActions.SymbolStartActionsCount > 0 && (!skipSymbolAnalysis || !skipDeclarationAnalysis);
 
-                AnalyzerActions perSymbolActions = hasPerSymbolActions ?
+                AnalyzerActions? perSymbolActions = hasPerSymbolActions ?
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Consider making this not nullable, and just use `Diagnostics.AnalyzerActions.Empty` for the false case, to remove the multiple `GetValueOrDefault` calls below.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs [hunk 3]
```diff
@@ -143,10 +143,10 @@ public AnalyzerManager(DiagnosticAnalyzer analyzer)
         /// the actions registered during <see cref="CompilationStartAnalyzerAction"/> for the given compilation.
         /// </summary>
         [PerformanceSensitive("https://github.com/dotnet/roslyn/issues/23582", OftenCompletesSynchronously = true)]
-        public async ValueTask<AnalyzerActions> GetAnalyzerActionsAsync(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
+        public async ValueTask<AnalyzerActions?> GetAnalyzerActionsAsync(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
         {
             var sessionScope = await GetSessionAnalysisScopeAsync(analyzer, analyzerExecutor).ConfigureAwait(false);
-            if (sessionScope.GetAnalyzerActions(analyzer).CompilationStartActions.Length > 0 && analyzerExecutor.Compilation != null)
+            if (sessionScope.GetAnalyzerActions(analyzer).GetValueOrDefault(AnalyzerActions.Empty).CompilationStartActionsCount > 0 && analyzerExecutor.Compilation != null)
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs]: >GetValueOrDefault(AnalyzerActions.Empty) [](start = 58, length = 40)

We're doing a lot of this. Worth an extension `GetValueOrEmpty()` imo.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs [hunk 4]
```diff
@@ -160,12 +160,12 @@ public async ValueTask<AnalyzerActions> GetAnalyzerActionsAsync(DiagnosticAnalyz
         /// These are the actions registered during the various RegisterSymbolStartAction method invocations for the given symbol on different analysis contexts.
         /// </summary>
         [PerformanceSensitive("https://github.com/dotnet/roslyn/issues/23582", OftenCompletesSynchronously = true)]
-        public async ValueTask<AnalyzerActions> GetPerSymbolAnalyzerActionsAsync(ISymbol symbol, DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
+        public async ValueTask<AnalyzerActions?> GetPerSymbolAnalyzerActionsAsync(ISymbol symbol, DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
         {
             var analyzerActions = await GetAnalyzerActionsAsync(analyzer, analyzerExecutor).ConfigureAwait(false);
-            if (analyzerActions.SymbolStartActionsCount > 0)
+            if (analyzerActions.GetValueOrDefault(AnalyzerActions.Empty).SymbolStartActionsCount > 0)
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs]: >GetValueOrDefault(AnalyzerActions.Empty) [](start = 32, length = 40)

Could just make this `?.`

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs [hunk 5]
```diff
@@ -383,22 +384,22 @@ public HostCompilationStartAnalysisScope(HostSessionStartAnalysisScope sessionSc
...
-        public override AnalyzerActions GetAnalyzerActions(DiagnosticAnalyzer analyzer)
+        public override AnalyzerActions? GetAnalyzerActions(DiagnosticAnalyzer analyzer)
         {
-            AnalyzerActions compilationActions = base.GetAnalyzerActions(analyzer);
-            AnalyzerActions sessionActions = _sessionScope.GetAnalyzerActions(analyzer);
+            AnalyzerActions? compilationActions = base.GetAnalyzerActions(analyzer);
+            AnalyzerActions? sessionActions = _sessionScope.GetAnalyzerActions(analyzer);
 
-            if (sessionActions.IsEmpty)
+            if (sessionActions.GetValueOrDefault(AnalyzerActions.Empty).IsEmpty)
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: >GetValueOrDefault(AnalyzerActions.Empty) [](start = 31, length = 40)

IMO this would read cleaner as `?.`  and `== true`

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs [hunk 6]
```diff
@@ -471,41 +472,41 @@ public void RegisterOperationAction(DiagnosticAnalyzer analyzer, Action<Operatio
...
     internal abstract class HostAnalysisScope
     {
-        private readonly ConcurrentDictionary<DiagnosticAnalyzer, AnalyzerActions> _analyzerActions = new ConcurrentDictionary<DiagnosticAnalyzer, AnalyzerActions>();
+        private readonly ConcurrentDictionary<DiagnosticAnalyzer, StrongBox<AnalyzerActions>> _analyzerActions = new ConcurrentDictionary<DiagnosticAnalyzer, StrongBox<AnalyzerActions>>();
 
-        public virtual AnalyzerActions GetAnalyzerActions(DiagnosticAnalyzer analyzer)
+        public virtual AnalyzerActions? GetAnalyzerActions(DiagnosticAnalyzer analyzer)
         {
-            return this.GetOrCreateAnalyzerActions(analyzer);
+            return this.GetOrCreateAnalyzerActions(analyzer)?.Value;
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: >?.Value [](start = 60, length = 7)

Why not just return directly?

Comment (333fred) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: Ah, it's a `StrongBox`, not a nullable type.

---
In reply to: [362576725](https://github.com/dotnet/roslyn/pull/40691#discussion_r362576725) [](ancestors = 362576725)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs [hunk 7]
```diff
@@ -628,126 +629,188 @@ protected AnalyzerActions GetOrCreateAnalyzerActions(DiagnosticAnalyzer analyzer
...
+        public readonly int OperationActionsCount { get { return _operationActions.Length; } }
+        public readonly int OperationBlockStartActionsCount { get { return _operationBlockStartActions.Length; } }
+        public readonly int OperationBlockEndActionsCount { get { return _operationBlockEndActions.Length; } }
+        public readonly int OperationBlockActionsCount { get { return _operationBlockActions.Length; } }
+        public readonly int CodeBlockStartActionsCount { get { return _codeBlockStartActions.Length; } }
+        public readonly int CodeBlockEndActionsCount { get { return _codeBlockEndActions.Length; } }
+        public readonly int CodeBlockActionsCount { get { return _codeBlockActions.Length; } }
+        public readonly bool Concurrent => _concurrent;
+        public bool IsEmpty { readonly get; private set; }
+        public readonly bool IsDefault => _compilationStartActions.IsDefault;
```
Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: This does not seem correct. Either it should be checking all fields, or we should have some sentinel `_isDefault` that is always set.

**Comment by 333fred** [comment]
Done review pass (commit 7)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs (hunk 7 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: There is no need to check all fields. There is no way to partially construct this type - it is either fully initialized or it is `default`.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs (hunk 5 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: This is now simplified.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs]: This is now simplified.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs (hunk 3 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs]: This is now simplified.

**Comment by sharwell** [comment]
The initially observed regression turned out to be a bug in .NET Core: https://github.com/dotnet/runtime/issues/1713.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 2 above)
Comment (333fred) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: @sharwell this can still be simplified by simply using `AnalyzerActions.Empty` as the false case here, and removing the coalescing entirely.

---
In reply to: [362572645](https://github.com/dotnet/roslyn/pull/40691#discussion_r362572645) [](ancestors = 362572645)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: @sharwell this was not addressed.

---
In reply to: [362572236](https://github.com/dotnet/roslyn/pull/40691#discussion_r362572236) [](ancestors = 362572236)

**Comment by 333fred** [comment]
Done review pass (commit 9)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Correct, comments in my pull requests that are not marked resolved have not been addressed unless you see a ➡️ reply with a stated follow-up action item.

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Comment is now added

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 2 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: The code now uniformly uses `AnalyzerActions.Empty` (removed uses of both `null` and `default(AnalyzerActions)`.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs [hunk 8]
```diff
@@ -628,126 +628,187 @@ protected AnalyzerActions GetOrCreateAnalyzerActions(DiagnosticAnalyzer analyzer
     // moves from an analyzer-centric model to an action-centric model. For example, the driver would need to stop asking
     // if a particular analyzer can analyze syntax trees, and instead ask if any syntax tree actions are present. Also,
     // the driver needs to apply all relevant actions rather then applying the actions of individual analyzers.
-    internal sealed class AnalyzerActions
+    internal struct AnalyzerActions
```
Comment (agocke) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: Can this be a readonly struct with `IsEmpty` and Concurrent moved to a With-ing pattern?

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: No, this is still a mutable struct. It would be a decent size change to convert all the remaining mutation methods to immutable transforms.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs [hunk 9]
```diff
@@ -628,126 +628,187 @@ protected AnalyzerActions GetOrCreateAnalyzerActions(DiagnosticAnalyzer analyzer
...
-        private ImmutableArray<CodeBlockAnalyzerAction> _codeBlockEndActions = ImmutableArray<CodeBlockAnalyzerAction>.Empty;
-        private ImmutableArray<CodeBlockAnalyzerAction> _codeBlockActions = ImmutableArray<CodeBlockAnalyzerAction>.Empty;
-        private ImmutableArray<OperationBlockStartAnalyzerAction> _operationBlockStartActions = ImmutableArray<OperationBlockStartAnalyzerAction>.Empty;
-        private ImmutableArray<OperationBlockAnalyzerAction> _operationBlockEndActions = ImmutableArray<OperationBlockAnalyzerAction>.Empty;
-        private ImmutableArray<OperationBlockAnalyzerAction> _operationBlockActions = ImmutableArray<OperationBlockAnalyzerAction>.Empty;
-        private ImmutableArray<AnalyzerAction> _syntaxNodeActions = ImmutableArray<AnalyzerAction>.Empty;
-        private ImmutableArray<OperationAnalyzerAction> _operationActions = ImmutableArray<OperationAnalyzerAction>.Empty;
+        public static readonly AnalyzerActions Empty = new AnalyzerActions(concurrent: false);
+
+        private ImmutableArray<CompilationStartAnalyzerAction> _compilationStartActions;
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs]: The `Add*` methods mutate these fields in the current revision. A future change could make this struct immutable.
