### PR TITLE
Fix that unverifiable IL is generated for switch over Nullable<Int64> and Nullable<UInt64>

### LINKED ISSUE #7625: Unverifiable IL generated for switch over Nullable<Int64> and Nullable<UInt64>
Found while working on expression trees for statement nodes, where Roslyn produced different evaluation results compared to compiled expression tree code.

Consider the following piece of code:

```csharp
// repro.cs
public static class C
{
    public static bool F(long? x)
    {
        switch (x)
        {
            case 1:
                return true;
            default:
                return false;
        }
    }
}
```

Compile it with:

```
> csc /t:library repro.cs
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

And run peverify.exe as follows:

```
> peverify repro.dll
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\temp\repro.dll : C::F][offset 0x00000018][found Long][expected Int32] Non-compatible types on the stack.
1 Error(s) Verifying repro.dll
```

When trying to invoke the function with a value of `1L`, it prints `false` incorrectly. Changing `case 1:` to `case 1L:` makes the problem disappear. Changing the signature from `long?` to `long` also causes the problem to go away.

The issue is a missing `conv.i8` instruction, which is present when switching over `long` or when using the `1L` literal:

```
.method public hidebysig static bool  F(valuetype [mscorlib]System.Nullable`1<int64> x) cil managed
{
  // Code size       27 (0x1b)
  .maxstack  2
  .locals init (valuetype [mscorlib]System.Nullable`1<int64> V_0,
           int64 V_1)
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloca.s   V_0
  IL_0004:  call       instance bool valuetype [mscorlib]System.Nullable`1<int64>::get_HasValue()
  IL_0009:  brfalse.s  IL_0019
  IL_000b:  ldloca.s   V_0
  IL_000d:  call       instance !0 valuetype [mscorlib]System.Nullable`1<int64>::GetValueOrDefault()
  IL_0012:  stloc.1
  IL_0013:  ldloc.1
  IL_0014:  ldc.i4.1
  // needs conv.i8
  IL_0015:  bne.un.s   IL_0019
  IL_0017:  ldc.i4.1
  IL_0018:  ret
  IL_0019:  ldc.i4.0
  IL_001a:  ret
} // end of method C::F
```

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #7625.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 1]
```diff
@@ -205,7 +205,29 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
...
+                var operand = ((BoundConversion)convertedCaseExpression).Operand;
+
+                if (operand.ConstantValue.IsIntegral)
+                {
+                    // We have to make sure we convert numerics correctly
+                    //public static bool F(int? x)
+                    //{
+                    //    switch (x)
+                    //    {
+                    //        // '1' has to be converted from Int32 to Int64 here
```
Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Inconsistent with parameter

Comment (pdelvo) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Thanks. fixed.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 2]
```diff
@@ -205,7 +205,29 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
 
             if (switchGoverningType.IsNullableType() && convertedCaseExpression.Kind == BoundKind.Conversion)
             {
-                constantValueOpt = ((BoundConversion)convertedCaseExpression).Operand.ConstantValue;
+                var underlyingType = switchGoverningType.GetNullableUnderlyingType();
```
Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: This should probably be moved inside the if block.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 3]
```diff
@@ -205,7 +205,29 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
...
+                    //    switch (x)
+                    //    {
+                    //        // '1' has to be converted from Int32 to Int64 here
+                    //        case 1:
+                    //            return true;
+                    //        default:
+                    //            return false;
+                    //    }
+                    //}
+                    constantValueOpt = FoldConstantConversion(convertedCaseExpression.Syntax, operand, Conversion.ImplicitNumeric, underlyingType, diagnostics);
```
Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Can `FoldConstantNumericConversion` not just be used here?

Comment (pdelvo) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: It is inaccessible in this constant (it is private) and I did not want to change that

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs (hunk 2 above)
Comment (pdelvo) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: fixed

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by davkean** [comment]
@dotnet-bot test eta please

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 4]
```diff
@@ -205,7 +205,28 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
 
             if (switchGoverningType.IsNullableType() && convertedCaseExpression.Kind == BoundKind.Conversion)
             {
-                constantValueOpt = ((BoundConversion)convertedCaseExpression).Operand.ConstantValue;
+                var operand = ((BoundConversion)convertedCaseExpression).Operand;
+
+                if (operand.ConstantValue.IsIntegral)
+                {
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: May need to check enums as well. Also need test with enums

**Comment by VSadov** [comment]
VB seems to be handling this scenario correctly, however i cannot find any tests. Could you add VB counterparts of the tests?  
Thanks!!

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs (hunk 4 above)
Comment (pdelvo) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: I dont really understand what you mean by that.To repro this you need a different type as the argument then you have in the case switch. How do you want to do that with enums without casing a CS0266?

This does not compile:
```csharp
// repro.cs
public static class C
{
    public static bool F(long? x)
    {
        switch (x)
        {
            case Foo.X:
                return true;
            default:
                return false;
        }
    }
    public enum Foo : int { X  = 1 }
}
```

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Yes, you would need to do something like:
```C#
                    case (int)Foo.X:
                        return true;
```

I assume that works with this fix. As long as (int) is not getting dropped, it would not be a new case.

Just wanted to be sure we do not need to handle enums as well. They are often a missing case in fixes like this.

**Comment by pdelvo** [comment]
I added two more tests

**Comment by VSadov** [comment]
LGTM

**Comment by VSadov** [comment]
Thanks!!

**Comment by AlekseyTs** [comment]
@pdelvo The test proves that the issue is addressed. However, it is not obvious what was going wrong. Could you please explain what was the code behavior for the scenario before the change, what problems did it create, and how it is different now? Why do integral types are the only types that need special treatment? In what scenarios do we get into the ```else``` block?

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 5]
```diff
@@ -205,7 +205,28 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
 
             if (switchGoverningType.IsNullableType() && convertedCaseExpression.Kind == BoundKind.Conversion)
             {
-                constantValueOpt = ((BoundConversion)convertedCaseExpression).Operand.ConstantValue;
+                var operand = ((BoundConversion)convertedCaseExpression).Operand;
+
+                if (operand.ConstantValue.IsIntegral)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Is there a guarantee that ConstantValue is not null? Even in error scenarios?

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 6]
```diff
@@ -205,7 +205,28 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
...
+                    //    switch (x)
+                    //    {
+                    //        // '1' has to be converted from Int32 to Int64 here
+                    //        case 1:
+                    //            return true;
+                    //        default:
+                    //            return false;
+                    //    }
+                    //}
+                    constantValueOpt = FoldConstantConversion(convertedCaseExpression.Syntax, operand, Conversion.ImplicitNumeric, switchGoverningType.GetNullableUnderlyingType(), diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Rather than guessing what the conversion should be (Conversion.ImplicitNumeric), I would suggest to bind conversion from the operand to the new target type as we normally would and getting constant value from the result. It also feels that that should be done unconditionally, regardless whether ```operand.ConstantValue.IsIntegral```.

**Comment by pdelvo** [comment]
The compiler tries to create a conversion of the expression on the case switch label to the type that is switched on. if the parameter is a Nullable<T> this doesnt work and it assumed that the type is compatible with the underlying type of the Nullable expression. this is not the case if we have Nullable<long> and an integer on the case switch.

You are right that the way I was doing it would throw a NRE if the expression on the case switch label is not a constant. I fixed that by using CreateConversion instead.

**Comment by AlekseyTs** [comment]
Please make sure to include the explanation into the commit description/comment.
The code change looks better now. I think we should add some unit-tests targeting error scenarios. For example:
- when original case expression is not a constant;
- when original case expression is not convertible to the switch type, we should also ensure that we don't get duplicate/misleading diagnostics in this case.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 7]
```diff
@@ -205,7 +205,8 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
 
             if (switchGoverningType.IsNullableType() && convertedCaseExpression.Kind == BoundKind.Conversion)
             {
-                constantValueOpt = ((BoundConversion)convertedCaseExpression).Operand.ConstantValue;
+                var operand = ((BoundConversion)convertedCaseExpression).Operand;
+                constantValueOpt = CreateConversion(operand, switchGoverningType.GetNullableUnderlyingType(), diagnostics).ConstantValue;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: We are probably never interested in errors reported by CreateConversion here, I suggest suppressing them by passing new diagnostics bag to the method.

**Comment by pdelvo** [comment]
I updated this PR

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 8]
```diff
@@ -1947,6 +1947,160 @@ .maxstack  2
...
+        }
+    }
+    static void Main()
+    {
+        System.Console.WriteLine(F(1));
+    }
+}";
+            var compilation = base.CreateCSharpCompilation(text);
+
+            var expected = Diagnostic(ErrorCode.ERR_ConstantExpected, "case i:");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: Please use baseline style as in CS0469_NoImplicitConversionWarning method for example, i.e.
```
            // (10,17): warning CS0469: The 'goto case' value is not implicitly convertible to type 'System.DayOfWeek'
            //                 goto case 1; // warning CS0469: The 'goto case' value is not implicitly convertible to type 'System.DayOfWeek'
                Diagnostic(ErrorCode.WRN_GotoCaseShouldConvert, "goto case 1;").WithArguments("System.DayOfWeek"))
```

If you run test without passing any arguments to VerifyDiagnostics, the test will fail and it will print reported diagnostics in the form that you can simply copy and paste as the baseline.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs [hunk 9]
```diff
@@ -203,9 +203,17 @@ private BoundExpression ConvertCaseExpression(TypeSymbol switchGoverningType, CS
                 convertedCaseExpression = this.CreateConversion(caseExpression, conversion, switchGoverningType, diagnostics);
             }
 
-            if (switchGoverningType.IsNullableType() && convertedCaseExpression.Kind == BoundKind.Conversion)
+            if (switchGoverningType.IsNullableType()
+                && convertedCaseExpression.Kind == BoundKind.Conversion
+                // Null is a special case here because we want to compare null to the Nullable<T> itself, not to the underlying type.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Is there an existing unit-test that was failing without the special case for the null value? If not, please add one.

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit32 please.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs (hunk 9 above)
Comment (pdelvo) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs]: Yes there were failing tests

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 10]
```diff
@@ -1947,6 +1947,160 @@ .maxstack  2
 ");
         }
 
+        [Fact]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: Consider adding WorkItem attribute for new tests, i.e.
```
        [WorkItem(7625, "https://github.com/dotnet/roslyn/issues/7625")]
```

**Comment by pdelvo** [comment]
Sorry that this took so many iterations. I added the comments and added WorkItem attributes

**Comment by AlekseyTs** [comment]
@pdelvo Many iterations is not a problem at all.

**Comment by AlekseyTs** [comment]
LGTM. Thank you for the contribution!
