### PR TITLE
Check that constant patterns are constant

### LINKED ISSUE #8778: Some unit tests disabled for pattern-matching branch
Some unit tests are disabled for the pattern-matching branch future/patterns. They will be marked with this issue number. They are being disabled so that issues with those tests can be addressed separately from development of the rest of the feature.

The specific issue that is a problem in that branch is getting a speculative semantic model for a statement that is a local declaration.

### LINKED ISSUE #10459: Compiler crash switching on a value of type System.Type
Reported in https://github.com/dotnet/roslyn/issues/8194#issuecomment-207867184:

> Seems you can do it in future branch
snip_20160410064405
But the compiler will crash when compiling it :(

### PR DESCRIPTION
**Pull request by gafter**
- Check that constant patterns are constant
- Fix check for cross-assembly pattern-matching operators.
- Fixes #10459 #10364
- Closes #8778 #9284
- Add a flag to the constant pattern binder to distinguish switch from other contexts because the LDM is grandfathering the conversions that the switch statement already does.

### CODE REVIEW

**Comment by gafter** [comment]
@AlekseyTs @agocke Please review
@dotnet/roslyn-compiler FYI

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -522,20 +523,22 @@ private bool ApplicableOperatorIs(MethodSymbol candidate, CSharpSyntaxNode node,
...
+        internal BoundPattern BindConstantPattern(
             CSharpSyntaxNode node,
             BoundExpression left,
             TypeSymbol leftType,
             ExpressionSyntax right,
             bool hasErrors,
             DiagnosticBag diagnostics,
-            out bool wasExpression)
+            out bool wasExpression,
+            bool wasSwitch)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I am not sure what was the purpose of adding this unused parameter.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: It is needed in order to distinguish the way constant patterns are type checked in switch versus all other pattern contexts. There is a PROTOTYPE comment saying where it will be used. I'm laying the groundwork for it here, since I'm sharing the functions that bind the constants now.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -7684,57 +7684,69 @@ void Test16(int val)
...
+                Diagnostic(ErrorCode.ERR_ConstantExpected, "y15").WithLocation(127, 18),
+                // (138,25): error CS0841: Cannot use local variable 'y16' before it is declared
+                //             case 0 when y16 > 0:
+                Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y16").WithArguments("y16").WithLocation(138, 25),
+                // (140,18): error CS0841: Cannot use local variable 'y16' before it is declared
+                //             case y16: 
+                Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y16").WithArguments("y16").WithLocation(140, 18),
+                // (140,18): error CS0150: A constant value is expected
+                //             case y16: 
+                Diagnostic(ErrorCode.ERR_ConstantExpected, "y16").WithLocation(140, 18)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Please revert the change, if there is no change, or restore the alignment so the diff would be easier to comprehend.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -15249,5 +15261,106 @@ public static void Main()
...
+            compilation.VerifyDiagnostics(
+                // (9,18): error CS0150: A constant value is expected
+                //             case typeof(string):
+                Diagnostic(ErrorCode.ERR_ConstantExpected, "typeof(string)").WithLocation(9, 18),
+                // (12,18): error CS0150: A constant value is expected
+                //             case typeof(string[]):
+                Diagnostic(ErrorCode.ERR_ConstantExpected, "typeof(string[])").WithLocation(12, 18)
+                );
+            // If we decide to support switching on System.Type, the following line would be appropriate.
+            // CompileAndVerify(compilation, expectedOutput: @"string[]");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Either remove the commented out code, or add PROTOTYPE marker.

**Comment by AlekseyTs** [comment]
@gafter I am done with review pass.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: The name of the parameter feels too vague, lots of things can be in switch. Would name isSwitchCaseLabel accurately reflect what this parameter is supposed to convey?

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Sure, I'll change that when I start implementing it. Right now I have more PRs queued up after this and I'd rather not introduce more merge conflicts.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: The addition is all of the "constant value expected" lines. I'd rather keep the alignment that is both consistent with the code and the alignment produced by running the test when it fails.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: The comment is correct. This is not prototype code, it explains the current behavior.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Our policy is to not submit commented out code. If you want to keep it (the commented out code) because this is a prototype and we would come back to it. Please mark it with a PROTOTYPE marker so that we wouldn't forget to come back to it and uncomment or delete it.

**Comment by AlekseyTs** [comment]
LGTM, assuming the comment and the parameter name changes are going to be addressed in the future PRs.

**Comment by gafter** [comment]
@agocke Please review. Unless you have something that you feel must be addressed before submission, I'll make code review changes in the next PR to avoid merge conflicts.

**Comment by agocke** [comment]
LGTM, agreeing with Aleksey

**Comment by VSadov** [comment]
LGTM
