### PR TITLE
Skip enclosing parens in ancestors to find the when clause of a switch case

### LINKED ISSUE #14707: Conditional switch case statements fail to build
**Version Used**: Roslyn.20161021.6  

**Steps to Reproduce**: 

1. Create a conditional switch case statement

Example: 
```c#
  case Rectangle s when (s.Length == s.Height): 
```

**Expected Behavior**: 
Builds correctly

**Actual Behavior**: 
 No warning/error messages are showing up, but after building I get "csc.exe" exited with code -2146232797.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #14707
@AlekseyTs @agocke Please review
@dotnet/roslyn-compiler Additional review welcome.
@MattGertz For RC ask mode

This fixes a compiler crash when parens are used around a switch case's when clause expression.
The fix is small and focused, and therefore low risk.

### CODE REVIEW

**Comment by MattGertz** [comment]
Approved pending the usual.

**Comment by gafter** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

**Comment by gafter** [comment]
@dotnet-bot test windows_debug_unit64_prtest please

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/Instrumenter.cs [hunk 1]
```diff
@@ -256,7 +256,7 @@ public virtual BoundStatement InstrumentPatternSwitchStatement(BoundPatternSwitc
         public virtual BoundStatement InstrumentPatternSwitchWhenClauseConditionalGotoBody(BoundExpression original, BoundStatement ifConditionGotoBody)
         {
             Debug.Assert(!original.WasCompilerGenerated);
-            Debug.Assert(original.Syntax.Parent.Kind() == SyntaxKind.WhenClause);
+            Debug.Assert(original.Syntax.FirstAncestorOrSelf<WhenClauseSyntax>() != null);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/Instrumenter.cs]: >Debug.Assert(original.Syntax.FirstAncestorOrSelf<WhenClauseSyntax>() != null); [](start = 12, length = 78)

I think the assert can be stronger, i.e. it should skip only enclosing parens. Otherwise, it will not catch an incomplete expression.

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs [hunk 2]
```diff
@@ -388,7 +389,8 @@ public override BoundStatement InstrumentPatternSwitchStatement(BoundPatternSwit
 
         public override BoundStatement InstrumentPatternSwitchWhenClauseConditionalGotoBody(BoundExpression original, BoundStatement ifConditionGotoBody)
         {
-            WhenClauseSyntax whenClause = (WhenClauseSyntax)original.Syntax.Parent;
+            WhenClauseSyntax whenClause = original.Syntax.FirstAncestorOrSelf<WhenClauseSyntax>();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs]: >WhenClauseSyntax whenClause = original.Syntax.FirstAncestorOrSelf<WhenClauseSyntax>(); [](start = 12, length = 86)

It feels like something similar should be done with syntax in DynamicAnalysisInjector. Also, consider adding a test for dynamic analysis.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs]: Done

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/Instrumenter.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/Instrumenter.cs]: Thanks for the suggestion, but this assertion is as intended. I am not intending to assert that is the only situation that requires skipping. We want to place the instrumentation on the enclosing when clause, and this assertion is that such a thing exists.

**Comment by gafter** [comment]
@dotnet-bot test windows_release_unit32_prtest please

**Comment by AlekseyTs** [comment]
LGTM
