### PR TITLE
Assert duplicate named arguments produce correct diagnostics

### LINKED ISSUE #20050: Debug asserts in LocalRewriter.BuildArgumentsInEvaluationOrder in invalid code
**Version Used**: Latest sources

**Steps to Reproduce**:

1. Copy/paste C#:

```C#
    public class C
    {
        void M()
        {
            string.Format(format: "", format: "");
        }
    }
```

2. Waiting usually does it. Or cut/paste the `string.Format` line, Or `Ctrl+.` on the error squiggle, etc.

**Expected Behavior**: No Debug.Asserts

**Actual Behavior**: Debug.Asserts

**Example Stack:**
```
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildArgumentsInEvaluationOrder(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, bool expanded, System.Collections.Immutable.ImmutableArray<int> argsToParamsOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> arguments, Microsoft.CodeAnalysis.CSharp.Binder binder) Line 668	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArgumentsInEvaluationOrder(Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.SyntaxNode syntax, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> arguments, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, bool expanded, System.Collections.Immutable.ImmutableArray<int> argsToParamsOpt, bool invokedAsExtensionMethod) Line 526	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArguments.AnonymousMethod__0(Microsoft.CodeAnalysis.CSharp.BoundExpression n) Line 129	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArguments(Microsoft.CodeAnalysis.CSharp.BoundExpression boundNode, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> boundArguments, System.Collections.Immutable.ImmutableArray<string> argumentNamesOpt, System.Collections.Immutable.ImmutableArray<int> argumentsToParametersOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind> argumentRefKindsOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol> parameters, bool expanded, Microsoft.CodeAnalysis.SyntaxNode invocationSyntax, bool invokedAsExtensionMethod) Line 115	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.ArgumentsInEvaluationOrder.get() Line 63	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitInvocationExpression(Microsoft.CodeAnalysis.Semantics.IInvocationExpression operation) Line 205	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 69	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 79	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(Microsoft.CodeAnalysis.Semantics.IExpressionStatement operation) Line 187	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 756	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 79	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray<Microsoft.CodeAnalysis.IOperation>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IOperation> list) Line 21	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(Microsoft.CodeAnalysis.Semantics.IBlockStatement operation) Line 53	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 82	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 79	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.DescendantsAndSelf(Microsoft.CodeAnalysis.IOperation operation) Line 33	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.GetOperationsToAnalyze(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IOperation> operationBlocks) Line 2077	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference decl, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool shouldExecuteSyntaxNodeActions, bool shouldExecuteOperationActions, bool shouldExecuteCodeBlockActions, bool shouldExecuteOperationBlockActions, bool isInGeneratedCode, System.Threading.CancellationToken cancellationToken) Line 1802	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCodeSymbol, System.Threading.CancellationToken cancellationToken) Line 1639	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessSymbolDeclared(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 964	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessEventCore(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 919	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEvent(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 906	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 893	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 826	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecutePrimaryAnalysisTaskAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool usingPrePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 418	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.AttachQueueAndProcessAllEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken) Line 347	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken) Line 827	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync.AnonymousMethod__1() Line 659	C#
 	[External Code]	
```

### PR DESCRIPTION
**Pull request by OmarTawfik**
### Customer scenario
Getting IOperations trees on call expressions that have duplicate explicitly named arguments, will cause a `Debug.Assert()` to throw in the compiler. Example:
```C#
    public class C
    {
        void M()
        {
            string.Format(format: "", format: "");
        }
    }
```
### Bugs this fixes
Fixes #20050 
### Workarounds, if any
None.
### Risk
Low. One line fix.
### Is this a regression from a previous update?
No.
### Root cause analysis
It is a case where we didn't count for invalid arguments when constructing the IOperations tree.
### How was the bug found?
Reported on GitHub.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NamedAndOptionalTests.cs [hunk 1]
```diff
@@ -2350,5 +2350,22 @@ public void M2([Optional]DateTime p) { } // no default specified (would be illeg
...
+public class C
+{
+    void M()
+    {
+        string.Format(format: """", format: """");
+    }
+}").VerifyDiagnostics(
+                // (6,35): error CS1740: Named argument 'format' cannot be specified multiple times
+                //         string.Format(format: "", format: "");
+                Diagnostic(ErrorCode.ERR_DuplicateNamedArgument, "format").WithArguments("format").WithLocation(6, 35));
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NamedAndOptionalTests.cs]: Does this test hit `MakeArgumentsInEvaluationOrder`?

**Comment by jcouv** [comment]
On second thought, the stack in the bug report shows the problem happens in `GetOperationsToAnalyze`. Can you test such IOperation scenarios?

**Comment by OmarTawfik** [comment]
I was actually able to repro a failure through tests (VS didn't). Will fix this PR and tag people shortly.

**Comment by OmarTawfik** [comment]
@jcouv @cston after more inspection, we have two options:
* Add the invalid (duplicate) argument to the list of arguments when constructing the tree.
* Ignore it completely and depend on diagnostics informing the user that there is a duplicate argument.

I chose the first solution, and added tests to make sure that the node we add is marked as `IsInvalid`.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs [hunk 2]
```diff
@@ -570,5 +570,139 @@ void F(int p /*<bind>*/= M()/*</bind>*/)
...
+            string expectedOperationTree = @"
+IInvocationOperation (System.String System.String.Format(System.String format, params System.Object[] args)) (OperationKind.Invocation, Type: System.String, IsInvalid) (Syntax: 'string.Form ... format: """")')
+  Instance Receiver: 
+    null
+  Arguments(3):
+      IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: format) (OperationKind.Argument, Type: null) (Syntax: 'format: """"')
+        ILiteralOperation (OperationKind.Literal, Type: System.String, Constant: """") (Syntax: '""""')
+        InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
+        OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
+      IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: format) (OperationKind.Argument, Type: null, IsInvalid) (Syntax: 'format: """"')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs]: >IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: format) (OperationKind.Argument, Type: null, IsInvalid) (Syntax: 'format: """"') [](start = 6, length = 143)

I think this is wrong, we are not supposed to create IInvocationOperation when there are issues with mapping arguments to parameters. The IInvocationOperation can be created only for successful overload resolution case.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs [hunk 3]
```diff
@@ -570,5 +570,139 @@ void F(int p /*<bind>*/= M()/*</bind>*/)
...
+                // file.cs(6,45): error CS1740: Named argument 'format' cannot be specified multiple times
+                //         /*<bind>*/string.Format(format: "", format: "")/*</bind>*/;
+                Diagnostic(ErrorCode.ERR_DuplicateNamedArgument, "format").WithArguments("format").WithLocation(6, 45)
+            });
+        }
+
+        [Fact]
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [WorkItem(20050, "https://github.com/dotnet/roslyn/issues/20050")]
+        public void BuildsArgumentsOperationsForDuplicateExplicitArguments_CorrectOrder()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs]: >CorrectOrder [](start = 75, length = 12)

I am not sure what "CorrectOrder" mean in this scenario

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 4]
```diff
@@ -759,8 +759,6 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
                 int p = (!argsToParamsOpt.IsDefault) ? argsToParamsOpt[a] : a;
                 var parameter = parameters[p];
 
-                Debug.Assert(!processedParameters.Contains(p));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >Debug.Assert(!processedParameters.Contains(p)); [](start = 16, length = 47)

I think this assert should be put back. It catches real problems.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: The method should not be called in scenarios outlined in the issue.

---
In reply to: [177268255](https://github.com/dotnet/roslyn/pull/25730#discussion_r177268255) [](ancestors = 177268255)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Comment by OmarTawfik** [comment]
> The proposed fix violates an invariant that IInvocationOperation is created only when overload resolution succeeds.

> The method should not be called in scenarios outlined in the issue.

@AlekseyTs the compiler indeed generates `LazyInvalidOperation` for overload resolution failures. Check the first few lines of `CSharpOperationFactory.CreateBoundCallOperation()`. But in case of duplicate named parameters, the compiler produces diagnostics (as expected), but considers it a `Viable` overload, which continues to generate an `IInvocationOperation`.

For example, this is a true overload resolution failure:
```csharp
void N(int a, int b)
{
}

void M()
{
    /*<bind>*/N(a: 1, a: 2)/*</bind>*/;
}
```
We produce:
```
// file.cs(10,27): error CS1740: Named argument 'a' cannot be specified multiple times
// file.cs(10,19): error CS7036: There is no argument given that corresponds to the required formal parameter 'b' of 'C.N(int, int)'
```
And the overload resolution failure leads to this IOperations tree:
```
IInvalidOperation (OperationKind.Invalid, Type: System.Void, IsInvalid) (Syntax: 'N(a: 1, a: 2)')
  Children(2):
      ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1) (Syntax: '1')
      ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 2) (Syntax: '2')
```

Are you suggesting that additional duplicate arguments should fail overload resolution?

**Comment by AlekseyTs** [comment]
> Are you suggesting that additional duplicate arguments should fail overload resolution?

I am not suggesting this, I am pretty sure overload resolution fails in this case.

**Comment by AlekseyTs** [comment]
@OmarTawfik If you need more help with this issue, let's take this offline

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs (hunk 3 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs]: Arguments are not ordered. I'll fix it to be more explicit.

---
In reply to: [177267989](https://github.com/dotnet/roslyn/pull/25730#discussion_r177267989) [](ancestors = 177267989)

**Comment by OmarTawfik** [comment]
Discussed offline. The main issue is that the `BoundCall` is created with `LookupResultKind.Viable` even if it has duplicate named arguments. This needs to be changed.

**Comment by OmarTawfik** [comment]
Discussed offline. Overload resolution actually succeeds with such arguments. I'll change it and update the PR.

**Comment by OmarTawfik** [comment]
@cston @jcouv @AlekseyTs comments addressed.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs [hunk 5]
```diff
@@ -9,6 +9,7 @@ internal enum ArgumentAnalysisResultKind : byte
         NoCorrespondingParameter,
         FirstInvalid = NoCorrespondingParameter,
         NoCorrespondingNamedParameter,
+        DuplicateNamedArguments,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs]: >DuplicateNamedArguments [](start = 8, length = 23)

Should we use singular as the other members, i.e. "DuplicateNamedArgument"?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberAnalysisResult.cs [hunk 6]
```diff
@@ -211,7 +221,7 @@ public static MemberAnalysisResult BadArgumentConversions(ImmutableArray<int> ar
             Debug.Assert(conversions.Length != 0);
             Debug.Assert(badArguments.Length != 0);
             return new MemberAnalysisResult(
-                MemberResolutionKind.BadArguments,
+                MemberResolutionKind.BadArgumentConversion,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberAnalysisResult.cs]: > MemberResolutionKind.BadArgumentConversion, [](start = 15, length = 44)

Why was this change necessary?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberAnalysisResult.cs]: Never mind. I see why now. 

---
In reply to: [178668382](https://github.com/dotnet/roslyn/pull/25730#discussion_r178668382) [](ancestors = 178668382)

**Comment by AlekseyTs** [comment]
>                 switch (argumentAnalysis.Kind)

Should we handle new kind in this ```switch```?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:2918 in 738230c. [](commit_id = 738230ccc88c5fe882291b61153e1fbbe0c8dc43, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             switch (normalResult.Kind)

Should we explicitly handle new kind in this ```switch```?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:776 in 738230c. [](commit_id = 738230ccc88c5fe882291b61153e1fbbe0c8dc43, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 7]
```diff
@@ -740,6 +753,16 @@ private bool HadConstraintFailure(Location location, DiagnosticBag diagnostics)
                 symbols), location);
         }
 
+        private void ReportDuplicateNamedArguments(MemberResolutionResult<TMember> result, DiagnosticBag diagnostics, AnalyzedArguments arguments)
+        {
+            Debug.Assert(result.Result.BadArgumentsOpt.Length == 1);
+            var name = arguments.Names[result.Result.BadArgumentsOpt[0]];
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: >var [](start = 12, length = 3)

Please spell out the type

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs [hunk 8]
```diff
@@ -570,5 +570,97 @@ void F(int p /*<bind>*/= M()/*</bind>*/)
 
             VerifyOperationTreeAndDiagnosticsForTest<EqualsValueClauseSyntax>(source, expectedOperationTree, expectedDiagnostics);
         }
+
+        [Fact]
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [WorkItem(20050, "https://github.com/dotnet/roslyn/issues/20050")]
+        public void BuildsArgumentsOperationsForDuplicateExplicitArguments_Repro()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs]: >BuildsArgumentsOperationsForDuplicateExplicitArguments_Repro [](start = 20, length = 60)

Please add similar tests for properties (indexers).

File: src/Compilers/CSharp/Test/Semantic/Semantics/NonTrailingNamedArgumentsTests.cs [hunk 9]
```diff
@@ -1176,11 +1159,7 @@ void M()
             comp.VerifyDiagnostics(
                 // (8,38): error CS1740: Named argument 'x' cannot be specified multiple times
                 //         System.Console.Write(c[x: 1, x: 2, 3]);
-                Diagnostic(ErrorCode.ERR_DuplicateNamedArgument, "x").WithArguments("x").WithLocation(8, 38),
-                // (8,32): error CS1739: The best overload for 'this' does not have a parameter named 'x'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NonTrailingNamedArgumentsTests.cs]: >// (8,32): error CS1739: The best overload for 'this' does not have a parameter named 'x' [](start = 16, length = 89)

It feels like this error is more useful than the duplicate name error.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs [hunk 10]
```diff
@@ -114,29 +113,38 @@ public ImmutableArray<int> ToImmutableArray()
             ParameterMap argsToParameters = new ParameterMap(parametersPositions, argumentCount);
 
             // We have analyzed every argument and tried to make it correspond to a particular parameter. 
-            // There are now four questions we must answer:
+            // We must now answer the following questions:
             //
-            // (1) Is there any named argument used out-of-position and followed by unnamed arguments?
-            // (2) Is there any argument without a corresponding parameter?
-            // (3) Was there any named argument that specified a parameter that was already
+            // (1) Is there any named argument that were specified twice?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs]: >Is there any named argument that were specified twice? [](start = 19, length = 54)

It feels like we shouldn't start with this check. Consider adding it last. Usually, adding new checks last is a better approach, especially for condition that was not considered an error before.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 11]
```diff
@@ -372,12 +371,13 @@ private static ThreeState TryGetBestResult(ArrayBuilder<MemberResolutionResult<T
...
             MemberResolutionResult<TMember> firstUnsupported = default(MemberResolutionResult<TMember>);
 
-            var supportedInPriorityOrder = new MemberResolutionResult<TMember>[5]; // from highest to lowest priority
-            const int requiredParameterMissingPriority = 0;
-            const int nameUsedForPositionalPriority = 1;
-            const int noCorrespondingNamedParameterPriority = 2;
-            const int noCorrespondingParameterPriority = 3;
-            const int badNonTrailingNamedArgument = 4;
+            var supportedInPriorityOrder = new MemberResolutionResult<TMember>[6]; // from highest to lowest priority
+            const int duplicateNamedArguments = 0;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: >const int duplicateNamedArguments = 0; [](start = 12, length = 38)

Here it is probably appropriate to treat the new failure as highest priority because before it wasn't considered a failure.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 12]
```diff
@@ -372,12 +371,13 @@ private static ThreeState TryGetBestResult(ArrayBuilder<MemberResolutionResult<T
...
+            const int requiredParameterMissingPriority = 1;
+            const int nameUsedForPositionalPriority = 2;
+            const int noCorrespondingNamedParameterPriority = 3;
+            const int noCorrespondingParameterPriority = 4;
+            const int badNonTrailingNamedArgument = 5;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: > const int badNonTrailingNamedArgument = 5; [](start = 11, length = 43)

Curious: why do we use constants here to establish priority vs. giving the memwber of MemberResolutionKind an explicit numeric value and using that as priority?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs [hunk 13]
```diff
@@ -469,5 +477,35 @@ private static bool CanBeOptional(ParameterSymbol parameter, bool isMethodGroupC
...
+
+        private static int? CheckForDuplicateNamedArguments(AnalyzedArguments arguments)
+        {
+            if (arguments.Names.IsEmpty())
+            {
+                // No checks if there are no named arguments
+                return null;
+            }
+
+            var alreadyDefined = PooledHashSet<string>.GetInstance();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs]: >GetInstance(); [](start = 55, length = 14)

Should we pass in `arguments.Names.Count` as the initial capacity here?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 12 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: > Curious: why do we use constants here to establish priority vs. giving the memwber of MemberResolutionKind an explicit numeric value and using that as priority?

There are way more MemberResolutionKinds than priorities. This is the only place where we prioritize things. And we avoid spooky action at a distance. :-)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs (hunk 5 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs]: I chose the plural form as you cannot have one duplicate argument :)

---
In reply to: [178667114](https://github.com/dotnet/roslyn/pull/25730#discussion_r178667114) [](ancestors = 178667114)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs]: > I chose the plural form as you cannot have one duplicate argument 

Of course I can, the second one is a duplicate, the first one is not.

---
In reply to: [178707798](https://github.com/dotnet/roslyn/pull/25730#discussion_r178707798) [](ancestors = 178707798,178667114)

Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/ArgumentAnalysisResultKind.cs]: Alright. I'll fix.

---
In reply to: [178710288](https://github.com/dotnet/roslyn/pull/25730#discussion_r178710288) [](ancestors = 178710288,178707798,178667114)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs (hunk 13 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution_ArgsToParameters.cs]: ObjectPool does not consider initial capacity :( Maybe we can revise that design later.

---
In reply to: [178680788](https://github.com/dotnet/roslyn/pull/25730#discussion_r178680788) [](ancestors = 178680788)

**Comment by OmarTawfik** [comment]
>             switch (normalResult.Kind)

For error reporting reasons, this specific failure we always report on the argument, not the called method, so I don't think it will make a difference. Do you see otherwise?

---
In reply to: [378071925](https://github.com/dotnet/roslyn/pull/25730#issuecomment-378071925) [](ancestors = 378071925)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:776 in 738230c. [](commit_id = 738230ccc88c5fe882291b61153e1fbbe0c8dc43, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs [hunk 14]
```diff
@@ -570,5 +570,293 @@ void F(int p /*<bind>*/= M()/*</bind>*/)
...
+                // file.cs(10,27): error CS1740: Named argument 'a' cannot be specified multiple times
+                //         /*<bind>*/N(a: 1, a: 2)/*</bind>*/;
+                Diagnostic(ErrorCode.ERR_DuplicateNamedArgument, "a").WithArguments("a").WithLocation(10, 27)
+            });
+        }
+
+        [Fact]
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [WorkItem(20050, "https://github.com/dotnet/roslyn/issues/20050")]
+        public void BuildsArgumentsOperationsForDuplicateExplicitArguments_CorrectArgumentsOrder_Lambdas()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_InvalidExpression.cs]: >Lambdas [](start = 97, length = 7)

I do not see lambdas in this tests scenario. There are delegates though.

**Comment by OmarTawfik** [comment]
@jaredpar @cston @jcouv comments addressed. can I get another review?

**Comment by jaredpar** [comment]
approved
