### PR TITLE
Fix sorting for import completion

### LINKED ISSUE #41601: Add items from unimported namespaces does not sort items
**Version Used**: 
Version 16.6.0 Preview 1.0 [29811.143.master]

But this could repro on 16.5, but I don't have build.

**Steps to Reproduce**:
``` C#
using System;

namespace ConsoleApp189
{
  class Program
  {
    static void Main(string[] args)
    {
      AppliesTo
    }
  }

  class AppliesTo { }
  class AppliesToA { }

}

namespace Another
{
  class AppliesTo { }
  class AppliesToA { }
}

```
**Expected Behavior**:
Order to be in:

AppliesTo
AppliesTo (Another)
AppliesToA
AppliesToA (Another)

**Actual Behavior**:

Order switches between:

AppliesTo (Another)
AppliesTo
AppliesToA (Another)
AppliesToA

AppliesTo (Another)
AppliesToA (Another)
AppliesTo
AppliesToA

Order

### PR DESCRIPTION
**Pull request by genlu**
Fix #41601

The main issue is a regression in sorting order caused by a bug fix in editor
https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/219864

Which basically exposed a long existing bug in Roslyn that completion service and async completion sort items differently. 

A second issue is we show unimported items when in attribute name context as in-scope because we didn't mark it as "expanded", which also cause expander malfunctioning. 

AzDO bug: 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1069318

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs [hunk 1]
```diff
@@ -758,10 +759,41 @@ private static bool IsAllPunctuation(string filterText)
...
         {
-            // TODO(cyrusn): Actually use the right unicode categories here.
+            // TODO(cyrusn): Actually use the right Unicode categories here.
             return char.IsLetter(c)
                 || char.IsNumber(c)
                 || c == '_';
         }
+
+        /// <summary>
+        /// This comparer can handle expanded items.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: 'expand' (no pun intended) on what this means.

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs [hunk 2]
```diff
@@ -758,10 +759,41 @@ private static bool IsAllPunctuation(string filterText)
...
+            public int Compare(VSCompletionItem x, VSCompletionItem y)
+            {
+                var xHasPrefix = HasExpandedPrefix(x);
+                var yHasPrefix = HasExpandedPrefix(y);
+
+                if (xHasPrefix == yHasPrefix)
+                {
+                    // Don't use Ordinal because we want lowercase to be "smaller" than uppercase.
+                    // e.g. "Goo" before "GoTo"
+                    return string.Compare(x.SortText, y.SortText, StringComparison.InvariantCulture);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: fascinating.  you added a test for ths?

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs [hunk 3]
```diff
@@ -758,10 +759,41 @@ private static bool IsAllPunctuation(string filterText)
...
+                else if (xHasPrefix)
+                {
+                    return 1;
+                }
+                else
+                {
+                    return -1;
+                }
+
+                static bool HasExpandedPrefix(VSCompletionItem i) => i.SortText.Length > 1 && i.SortText[0] == ImportCompletionItem.SortTextPrefix;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: a local function here is overkill for me.  this is already a self contained class for literally just this purpose.  can we just make this a clear static helper method?

Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: can this please be explained.  what is a SortTextPrefix on SortText??

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs [hunk 4]
```diff
@@ -87,7 +87,7 @@ static CompletionItem GetAppropriateAttributeItem(CompletionItem attributeItem,
                     if (attributeItem.DisplayText.TryGetWithoutAttributeSuffix(isCaseSensitive: isCaseSensitive, out var attributeNameWithoutSuffix))
                     {
                         // We don't want to cache this item.
-                        return ImportCompletionItem.CreateAttributeItemWithoutSuffix(attributeItem, attributeNameWithoutSuffix);
+                        return ImportCompletionItem.CreateAttributeItemWithoutSuffix(attributeItem, attributeNameWithoutSuffix, CompletionItemFlags.Expanded);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: why is this guy 'expanded'?  what does that mean?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs [hunk 5]
```diff
@@ -16,7 +16,8 @@ namespace Microsoft.CodeAnalysis.Completion.Providers
 {
     internal static class ImportCompletionItem
     {
-        private const string SortTextFormat = "~{0} {1}";
+        public const char SortTextPrefix = '~';
+        private static readonly string s_sortTextFormat = $"{SortTextPrefix}{0} {1}";
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: oh... oh wow... that's awful.  

What's going on here, and can we doc why we need this?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs [hunk 6]
```diff
@@ -87,6 +88,9 @@ public static CompletionItem CreateAttributeItemWithoutSuffix(CompletionItem att
                  displayTextPrefix: attributeItem.DisplayTextPrefix,
                  displayTextSuffix: attributeItem.DisplayTextSuffix,
                  inlineDescription: attributeItem.InlineDescription);
+
+            item.Flags = flags;
+            return item;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: super bizarre that we can't pass this in through the constructor.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: this is particularly gnarly as it's basically just picking some random char and hoping that that's not something any roslyn language might ever use in an identifier.  imagine a world where `~` became a legal identifier character.  For example, in F# you can identifiers starting with `_`, `$`, `@`, `(grave accent)`, or `?`.  If we had picked any of those as this special character then that would break languages.  It's not a great idea to embed this sort of thing.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: i'm also super confused by this.  If we can already have a flag stating if it's an expanded item... then why don't we just compare that flag first (instead of extracting this information out from this string)?

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs [hunk 7]
```diff
@@ -758,10 +759,41 @@ private static bool IsAllPunctuation(string filterText)
...
+
+        /// <summary>
+        /// This comparer can handle expanded items.
+        /// </summary>
+        private class CompletionItemSortingComparer : IComparer<VSCompletionItem>
+        {
+            public static CompletionItemSortingComparer Instance { get; } = new CompletionItemSortingComparer();
+
+            public int Compare(VSCompletionItem x, VSCompletionItem y)
+            {
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: why can't this just check `CompletionItem.Flag`?

**Comment by CyrusNajmabadi** [comment]
:-/   Feeling very unsure of this approach.

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs (hunk 7 above)
Comment (genlu) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: Because the flag is on Roslyn CompletionItem, to get that we will need to get it from the VS item property bag first. We can put the flag in VS item's property bag directly, but I'm not sure whether it will be a perf hit with 10s of thousands items. Need to do some profiling

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: Doesn't the VSCompletionItem already know this info?  After all, doesn't it have this in its filters so it knows what is an 'expanded item' and what isn't?

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: It does, but the info is in an 'ImmutableArray<CompletionFilter>'. We will need to search though the list every time a comparison is made. As I said about retrieving Roslyn item from the property bag, it might or might not be a perf issue, just need to check.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs (hunk 4 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: Any item created by this service is "expanded", which means this is from unimported namespace.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs (hunk 6 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: I was trying to avoid (yet another) change to public API, right now `Flags` is internal.

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs (hunk 7 above)
Comment (genlu) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: The profiling result doesn't show much difference if we get the Roslyn item from the property bag and just compare that, so I made the change as you suggested above.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs (hunk 5 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: Fixed as you suggested.

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs (hunk 2 above)
Comment (genlu) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: I reverted this to keep the order identical as before (Using OrdinalIgnoreCase)

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs [hunk 8]
```diff
@@ -67,8 +69,9 @@ internal ItemManager(RecentItemsManager recentItemsManager)
                 AsyncCompletionLogger.LogSessionWithTypeImportCompletionEnabled();
             }
 
-
-            return Task.FromResult(data.InitialList.OrderBy(i => i.SortText).ToImmutableArray());
+            // Sort by default comparer of Roslyn CompletionItem
```
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs]: Doc comment with cref instead?

File: src/Features/Core/Portable/Completion/CompletionItem.cs [hunk 9]
```diff
@@ -368,13 +368,28 @@ public CompletionItem WithRules(CompletionItemRules rules)
 
         int IComparable<CompletionItem>.CompareTo(CompletionItem other)
         {
-            var result = StringComparer.OrdinalIgnoreCase.Compare(SortText, other.SortText);
-            if (result == 0)
+            // Make sure expanded items are listed after non-expanded ones
+            var thisIsExpandItem = Flags.IsExpanded();
```
Comment (dpoeschl) [inline src/Features/Core/Portable/Completion/CompletionItem.cs]: `thisIsExpandedItem`? (and similar for `other...`)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs [hunk 10]
```diff
@@ -16,7 +16,7 @@ namespace Microsoft.CodeAnalysis.Completion.Providers
 {
     internal static class ImportCompletionItem
     {
-        private const string SortTextFormat = "~{0} {1}";
+        private const string SortTextFormat = "{0} {1}";
```
Comment (dpoeschl) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: Yay!

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs (hunk 4 above)
Comment (genlu) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: Most of the code change in this PR (adding flags validation in tests) is actually caused by this, which is fixing a second issue also reported in https://github.com/dotnet/roslyn/issues/41601#issuecomment-585499602

File: eng/Versions.props [hunk 11]
```diff
@@ -31,7 +31,7 @@
     <CodeStyleLayerCodeAnalysisVersion>3.3.1</CodeStyleLayerCodeAnalysisVersion>
     <MicrosoftCodeAnalysisTestingVersion>1.0.1-beta1.20067.1</MicrosoftCodeAnalysisTestingVersion>
     <CodeStyleAnalyzerVersion>3.5.0-beta3-20078-04</CodeStyleAnalyzerVersion>
-    <VisualStudioEditorPackagesVersion>16.4.248</VisualStudioEditorPackagesVersion>
+    <VisualStudioEditorPackagesVersion>16.5.173-g9c5f5bc040</VisualStudioEditorPackagesVersion>
```
Comment (jasonmalinowski) [inline eng/Versions.props]: Was this needed for new APIs or just so we could have tests that validated the behavior?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: @genlu What would it take to make an internal Create method that passes it through? What's pretty terrifying here too is this field is *mutable* in what really should be an immutable type...

(This is fine if we have to do a mop-up, but let's make sure we actually do the mop-up!)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs (hunk 4 above)
Comment (jasonmalinowski) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: Rather than passing it in, should this just be hard-coded in ImportCompletionItem.CreateAttributeItemWithoutSuffix?

Comment (jasonmalinowski) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: Do we need to add this flag in other places as well? Where did the "attributeItem" come from originally?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 12]
```diff
@@ -5996,6 +5996,74 @@ namespace NS
...
+                    .WithChangedOption(CompletionOptions.ShowItemsFromUnimportedNamespaces, LanguageNames.CSharp, True)))
+
+                state.SendTypeChars("mytask")
+                Await state.WaitForAsynchronousOperationsAsync()
+
+                ' make sure expander is selected
+                state.AssertCompletionItemExpander(isAvailable:=True, isSelected:=True)
+                Await state.AssertSelectedCompletionItem(displayText:="MyTask1", inlineDescription:="")
+
+
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Extra blank line.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 13]
```diff
@@ -5996,6 +5996,74 @@ namespace NS
...
+                state.SendInvokeCompletionList()
+                Await state.WaitForUIRenderedAsync()
+
+                ' make sure expander is selected
+                state.SetCompletionItemExpanderState(isSelected:=True)
+                Await state.WaitForAsynchronousOperationsAsync()
+                Await state.WaitForUIRenderedAsync()
+
+                state.SendEscape()
+                Await state.AssertNoCompletionSession()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Is this whole it relevant to this test? Or is this copy/paste from a previous test that we changed?

File: src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb [hunk 14]
```diff
@@ -387,6 +387,17 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense
...
 
+        Public Sub AssertItemsInOrder(expectedOrder As (String, String)())
+            Dim session = GetExportedValue(Of IAsyncCompletionBroker)().GetSession(TextView)
+            Assert.NotNull(session)
+            Dim items = session.GetComputedItems(CancellationToken.None).Items
+            Assert.Equal(expectedOrder.Count, items.Count)
+            For i = 0 To expectedOrder.Count - 1
+                Assert.Equal(expectedOrder(i).Item1, items(i).DisplayText)
+                Assert.Equal(expectedOrder(i).Item2, items(i).Suffix)
+            Next
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb]: Consider just building a second list of tuples, and then calling Assert.Equal() on the entire lists; that way if the ordering doesn't match you'll get the entire lists to compare rather than "A doesn't match B" and you have no idea where that went wrong.

File: src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs [hunk 15]
```diff
@@ -337,12 +338,12 @@ protected virtual IEqualityComparer<string> GetStringComparer()
...
-                await VerifyAsync(markup, expectedItemOrNull: null, expectedDescriptionOrNull: null, sourceCodeKind: SourceCodeKind.Script, usePreviousCharAsTrigger: usePreviousCharAsTrigger, checkForAbsence: true, glyph: null, matchPriority: null, hasSuggestionModeItem: hasSuggestionModeItem, displayTextSuffix: displayTextSuffix, inlineDescription: inlineDescription, matchingFilters: null);
+                await VerifyAsync(markup, expectedItemOrNull: null, expectedDescriptionOrNull: null, sourceCodeKind: SourceCodeKind.Regular, usePreviousCharAsTrigger: usePreviousCharAsTrigger, checkForAbsence: true, glyph: null, matchPriority: null, hasSuggestionModeItem: hasSuggestionModeItem, displayTextSuffix: displayTextSuffix, inlineDescription: inlineDescription, matchingFilters: null, flags: null);
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs]: Should we be making the VerifyAsync just have a default parameter rather than having update all of this?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs (hunk 4 above)
Comment (jasonmalinowski) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: Or should this be passing `attributeItem.Flags | CompletionItemFlags.Expanded` if the existing item also had another flag?

File: eng/Versions.props (hunk 11 above)
Comment (genlu) [reply eng/Versions.props]: This is just to make sure tests work correctly. No new API involved.

File: src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj [hunk 16]
```diff
@@ -121,6 +121,10 @@
       <_Dependency Remove="Microsoft.Win32.Registry"/>
       <_Dependency Remove="System.Security.AccessControl"/>
       <_Dependency Remove="System.Security.Principal.Windows"/>
+      <_Dependency Remove="System.Security.Principal.Windows"/>
```
Comment (JoeRobich) [inline src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj]:
```suggestion
```

Comment (genlu) [reply src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj]: Thanks!

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 13 above)
Comment (genlu) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: This is relevant, to make sure the cache for unimported items are completely populated.

**Comment by genlu** [comment]
Retargeted the change to non-vs-deps branch in https://github.com/dotnet/roslyn/pull/41916. Will address comments in a followup.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs (hunk 6 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs]: Well, this is not the first mutable data on this type... But I totally agree, will do the mop-up in master after this is merged.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs (hunk 4 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.CacheEntry.cs]: I'd prefer to keep it this way, so it's clear in the cache implementation that those items are not cached. Alternatively, I'm fine moving the `CreateAttributeItemWithoutSuffix` helper to this file.

**Comment by genlu** [comment]
@JoeRobich Thanks!
