### PR TITLE
Handle speculation for AsNewClause by generating an EqualsValue node

### LINKED ISSUE #23807: VB: GenerateConstructorCodeFixProvider should not crash when code has semantic errors.
**Version Used**: 

Visual Studio Community 2017 v15.5.1

**Steps to Reproduce**:

Type in the following code in a VB console project:

```vb
Public Module Module1
  Public Class Test
    Private foo As Integer
    Private bar As String

    Private baz As New Test("hh")
  End Class

  Public Sub Main()
  End Sub
End Module
```

The editor will put a red squiggle on the `"hh"` of the line `Private baz As New Test("hh")`. When you hover over the sguiggle the tooltip correctly shows the error that too many arguments have been passed to `Sub New()` but then the `GenerateConstructorCodeFixProvider` kicks in and crashes:

vs_constructor_provider_crash

If you click the Enable button in that error message near the top, then hover over the squiggly again at `"hh"`, the `GenerateConstructorCodeFixProvider` crashes. You can repeat this as many times as you want and it crashes every time. The stack trace given is:

```
System.ArgumentException : Node is not within syntax tree
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.CheckSyntaxNode(VisualBasicSyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel,SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor.VisualBasicGenerateConstructorService.GetDelegatingConstructor(State state,SemanticDocument document,Int32 argumentCount,INamedTypeSymbol namedType,ISet`1 candidates,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateThisOrBaseDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateThisOrBaseDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GetEditAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.GenerateConstructorCodeAction.GetEditAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.GenerateConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

**Expected Behavior**:

It should not crash. I have used the `GenerateConstructorCodeFixProvider` many times and I usually trigger it by placing the caret on a blank line within the class just after the fields/properties. In fact you can trigger it without crashing in the sample code above, if you do this by placing the caret in the blank below `Private bar As String`. However the moment you hover the cursor over the red squiggly line, it crashes.

### PR DESCRIPTION
**Pull request by JoeRobich**
CreateSpeculativeSemanticModelForNode will create a speculativeModel from a generated EqualsValue node already, but the Type node we are searching for won't be part of the tree. So we generate the EqualsValue node instead and find the Type node so that we can get symbol information.

Fixes #23807

### CODE REVIEW

File: src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb [hunk 1]
```diff
@@ -242,6 +242,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor
                     End If
                 End If
 
+                If newNode.Kind = SyntaxKind.AsNewClause Then
+                    ' Speculation is not supported for AsNewClauseSyntax nodes.
```
Comment (dpoeschl) [inline src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb]: Why not?

File: src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb [hunk 2]
```diff
@@ -242,6 +242,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor
...
+                    ' Generate an EqualsValueSyntax node with the inner NewExpression of the AsNewClauseSyntax node for speculation.
+
+                    Dim asNewClauseNode = DirectCast(newNode, AsNewClauseSyntax)
+                    Dim equalsValueNode = SyntaxFactory.EqualsValue(asNewClauseNode.NewExpression)
+                    newNode = asNewClauseNode.CopyAnnotationsTo(equalsValueNode)
```
Comment (dpoeschl) [inline src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb]: Is this necessary? The node you're looking for on the next line is a _child_ of equalsValueNode/newNode that's already annotated with `s_annotation`. This line would copy any annotations from the higher-level AsNew to the EqualsValue, but I don't see where that matters downstream.

File: src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb [hunk 3]
```diff
@@ -242,6 +242,19 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor
...
+                    ' The SpeculationAnalyzer would do the work of creating the EqualsValueSyntax for us if we passed the AsNewClause,
+                    ' but we need to build it ourself so that we can locate the newTypeName node in the new tree. This way we can
+                    ' GetSymbolInfo for it.
+
+                    Dim asNewClauseNode = DirectCast(newNode, AsNewClauseSyntax)
+                    newNode = SyntaxFactory.EqualsValue(asNewClauseNode.NewExpression)
+                    newTypeName = DirectCast(newNode.GetAnnotatedNodes(s_annotation).Single(), TypeSyntax)
+                End If
+
                 Dim speculativeModel = SpeculationAnalyzer.CreateSpeculativeSemanticModelForNode(oldNode, newNode, document.SemanticModel)
```
Comment (heejaechang) [inline src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb]: is this because if compiler auto generate EqualsValueSyntax, it will rewire AsnewClauseSyntax causing speculation semantic mode's root node is attached to new tree where newTypeName can't be found anymore?

in that case, this feels like a bug on compiler? and can you check where speculativeModel.Tree.GetRoot() is pointing to? speculative one? or original tree? if it is speculative one, you can do GetAnnotatedNodes(s_annotation) to find newTypeName?

Comment (heejaechang) [reply src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb]: I think if you do speculativeModel.Tree.GetRoot().GetAnnotatedNodes .. that would be more general form and you don't need multiple GetAnnotatedNodes this code has per different cases?
