### PR TITLE
Require exactly one export of IStreamingFindUsagesPresenter when used

### LINKED ISSUE #24794: Flaky Test - FindReferencesCommandHandlerTests.TestSelection
Here is the flaky test:

2018-02-12T12:46:48.1889818Z          Errors Roslyn.Services.Editor2.UnitTests.dll: 
2018-02-12T12:46:48.1890548Z              Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesCommandHandlerTests.TestSelection [FAIL]
2018-02-12T12:46:48.1891664Z          Command: C:\Users\dlab\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.console.x86.exe "E:\A\_work\43\s\Binaries\Release\UnitTests\EditorServicesTest2\Roslyn.Services.Editor2.UnitTests.dll"  -html "E:\A\_work\43\s\Binaries\Release\UnitTests\EditorServicesTest2\xUnitResults\Roslyn.Services.Editor2.UnitTests.dll.html" -noshadow -verbose
2018-02-12T12:46:48.1892892Z          xUnit output log: E:\A\_work\43\s\Binaries\Release\UnitTests\EditorServicesTest2\xUnitResults\Roslyn.Services.Editor2.UnitTests.dll.out.log

### PR DESCRIPTION
**Pull request by sharwell**
Closes #24794 (not necessarily related, but I couldn't find any evidence of ongoing flakiness in the test and multiple stabilization passes have occurred since it was filed)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Let me know when you'd like eyes.  Also, teh combinatorial attribute is very nifty!

**Comment by sharwell** [comment]
@CyrusNajmabadi This is ready for review, but this pull request is _only_ the last commit.

**Comment by sharwell** [comment]
@CyrusNajmabadi this is now ready for review and the prerequisites have been merged so it's clean

File: src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb [hunk 1]
```diff
@@ -104,10 +106,13 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition
...
         Private Sub Test(workspaceDefinition As XElement, Optional expectedResult As Boolean = True)
             Test(workspaceDefinition, expectedResult,
-                Function(document As Document, cursorPosition As Integer, presenters As IEnumerable(Of Lazy(Of IStreamingFindUsagesPresenter)))
-                    Dim goToDefService = If(document.Project.Language = LanguageNames.CSharp,
-                        DirectCast(New CSharpGoToDefinitionService(presenters), IGoToDefinitionService),
-                        New VisualBasicGoToDefinitionService(presenters))
+                Function(document As Document, cursorPosition As Integer, presenters As Lazy(Of IStreamingFindUsagesPresenter))
+                    Dim goToDefService = document.Project.Solution.Workspace.Services.GetLanguageServices(document.Project.Language).GetRequiredService(Of IGoToDefinitionService)()
+                    If document.Project.Language = LanguageNames.CSharp Then
+                        Assert.IsAssignableFrom(Of CSharpGoToDefinitionService)(goToDefService)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb]: Why are these all needed? It seems like the unit tests are very much hard-coding internal implementation, but it's unclear to me the benefit.

File: src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs [hunk 2]
```diff
@@ -156,6 +156,7 @@ private Action CreateInsertTextHandler(ITextView textView, string text)
 
                 execute(
                     view,
+                    Assert.IsType<TestWaitIndicator>(workspace.GetService<IWaitIndicator>()),
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs]: Not sure how I feel about the random testing that implementations are a specific type of mock. This seems like we're just creating debt if/when we restructure helpers.

File: src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb]: > Why are these all needed? It seems like the unit tests are very much hard-coding internal implementation, but it's unclear to me the benefit.

It's simply preserving the behavior of the test from what it was before.

File: src/EditorFeatures/TestUtilities/TestWaitIndicator.cs [hunk 3]
```diff
@@ -5,27 +5,24 @@
...
-        public TestWaitIndicator()
-            : this(new UncancellableWaitContext())
-        {
-        }
+        private readonly VisualStudioIndicator.IWaitContext _platformWaitContext = new UncancellableWaitContext();
 
-        internal TestWaitIndicator(IWaitContext waitContext)
+        [ImportingConstructor]
+        [Obsolete(MefConstruction.ImportingConstructorMessage, error: true)]
+        internal TestWaitIndicator([Import(AllowDefault = true)] IWaitContext waitContext)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/TestWaitIndicator.cs]: So we import our version, but the platform one is not that same one? This seems really funky. I guess this isn't new, I'm just not quite sure what it means.

**Comment by sharwell** [comment]
> Also, why did we support multiple of these in the first place? That scenario is no longer applicable?

This was not clear to me. It never really supported multiples - they weren't imported in an ordered fashion and it always just used the `FirstOrDefault`. As best I can tell, support for multiple presenters may have been implemented to achieve the same goal as `AllowDefault = true`.

File: src/EditorFeatures/Test2/FindReferences/MockStreamingFindReferencesPresenter.vb [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+Imports System.Composition
+Imports Microsoft.CodeAnalysis.Editor.Host
+Imports Microsoft.CodeAnalysis.FindUsages
+Imports Microsoft.CodeAnalysis.Host.Mef
+
+Namespace Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences
+    <Export(GetType(IStreamingFindUsagesPresenter))>
+    <[Shared]>
+    <PartNotDiscoverable>
+    Friend Class MockStreamingFindReferencesPresenter
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/FindReferences/MockStreamingFindReferencesPresenter.vb]: So we have two IStreamingFindUsagesPresenter now? Can we unify these, or at least name them in some way that explains the distinction?

File: src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb [hunk 5]
```diff
@@ -1,27 +1,35 @@
...
-        Private ReadOnly _action As Action
 
-        Public Sub New(action As Action)
-            _action = action
+        <ImportingConstructor>
+        <Obsolete(MefConstruction.ImportingConstructorMessage, True)>
+        Public Sub New()
         End Sub
 
+        Public Property Action As Action
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb]: I worry if this ever gets assigned more than once, since it means two tests are sharing state in some way there's a potential risk of one depending on the other's value. Worth adding a block?

File: src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb [hunk 6]
```diff
@@ -1,27 +1,35 @@
...
 Imports Microsoft.CodeAnalysis.Editor.FindUsages
 Imports Microsoft.CodeAnalysis.Editor.Host
 Imports Microsoft.CodeAnalysis.FindUsages
+Imports Microsoft.CodeAnalysis.Host.Mef
 
 Namespace Microsoft.CodeAnalysis.Editor.UnitTests.Utilities.GoToHelpers
+    <Export(GetType(IStreamingFindUsagesPresenter))>
+    <[Shared]>
+    <PartNotDiscoverable>
     Friend Class MockStreamingFindUsagesPresenter
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb]: File name desn't match the type name. I'd give you a pass but since you're introducing a second MockStreamingFindReferencesPresenter I'm a bit less inclined to be nice.

File: src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj [hunk 7]
```diff
@@ -52,6 +52,7 @@
     <InternalsVisibleTo Include="Microsoft.CodeAnalysis.EditorFeatures2.UnitTests" />
     <InternalsVisibleTo Include="Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests" />
     <InternalsVisibleTo Include="Microsoft.VisualStudio.LanguageServices.UnitTests" />
+    <InternalsVisibleTo Include="Microsoft.VisualStudio.LanguageServices.Test.Utilities2" />
```
Comment (jasonmalinowski) [inline src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj]: Just out of curiosity, why? I would have hoped the test utilities are language independent? (I'm not saying to try fixing this, just curious what tangled mess we have.)

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs [hunk 8]
```diff
@@ -30,6 +30,11 @@ public VisualStudioTaskSchedulerFactory(IThreadingContext threadingContext, IAsy
 
         public override IWorkspaceTaskScheduler CreateEventingTaskQueue()
         {
+            if (!_threadingContext.HasMainThread)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: "HasMainThread" means "we have a concept of a main thread, but we're not saying if we're on it or not?"?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs [hunk 9]
```diff
@@ -30,6 +30,11 @@ public VisualStudioTaskSchedulerFactory(IThreadingContext threadingContext, IAsy
...
+            {
+                return new DenyWorkTaskScheduler();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: This should just throw, or otherwise we're just moving the crash from the point where we noticed something was wrong (and could debug it) to the point where it's going to cause random failures in other places.

File: src/VisualStudio/Core/Impl/CodeModel/CodeModelState.cs [hunk 10]
```diff
@@ -14,11 +14,13 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel
...
     internal sealed class CodeModelState
     {
+        private readonly HostLanguageServices _languageServices;
+
         public IThreadingContext ThreadingContext { get; }
         public IServiceProvider ServiceProvider { get; }
-        public ICodeModelService CodeModelService { get; }
-        public ISyntaxFactsService SyntaxFactsService { get; }
-        public ICodeGenerationService CodeGenerator { get; }
+        public ICodeModelService CodeModelService => _languageServices.GetRequiredService<ICodeModelService>();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Impl/CodeModel/CodeModelState.cs]: Why the change? To reduce memory?

File: src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb [hunk 11]
```diff
@@ -74,7 +74,7 @@ Namespace Microsoft.VisualStudio.LanguageServices.UnitTests.ProjectSystemShim.Fr
         <PartNotDiscoverable>
         <Export(GetType(VisualStudioWorkspace))>
         <Export(GetType(VisualStudioWorkspaceImpl))>
-        Private Class MockVisualStudioWorkspace
+        Friend Class MockVisualStudioWorkspace
```
Comment (jasonmalinowski) [inline src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb]: Why did these switch to Friend? The implementation should be isolated to these project system tests.

File: src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb [hunk 12]
```diff
@@ -179,6 +183,18 @@ Namespace Microsoft.VisualStudio.LanguageServices.UnitTests.ProjectSystemShim.Fr
                     Case GetType(SVsFileChangeEx)
                         Return _fileChangeEx
 
+                    Case GetType(SVsLinkedUndoTransactionManager)
```
Comment (jasonmalinowski) [inline src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb]: What is demanding these now?

File: src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb [hunk 13]
```diff
@@ -23,10 +23,12 @@ Namespace Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel
         )
 
             If workspace Is Nothing Then
+                GC.SuppressFinalize(Me)
```
Comment (jasonmalinowski) [inline src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb]: Why?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs (hunk 8 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: Exactly correct

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs (hunk 9 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: This cannot throw. It's part of the initialization sequence and would invalidate operations that never use the queue.

File: src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb (hunk 13 above)
Comment (sharwell) [reply src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb]: Because someone wrote a finalizer.

Comment (jasonmalinowski) [reply src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb]: Can you comment in the code?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs (hunk 9 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: What operations don't use the queue?

File: src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb]: This change is now removed from this pull request.

File: src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs]: This change is now removed from this pull request.

File: src/EditorFeatures/TestUtilities/TestWaitIndicator.cs (hunk 3 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/TestWaitIndicator.cs]: This change is now removed from this pull request.

File: src/EditorFeatures/Test2/FindReferences/MockStreamingFindReferencesPresenter.vb (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Test2/FindReferences/MockStreamingFindReferencesPresenter.vb]: This change is now removed from this pull request.

Comment (sharwell) [reply src/EditorFeatures/Test2/FindReferences/MockStreamingFindReferencesPresenter.vb]: *This* change is removed, but a similar feature is provided in a different way now.

File: src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb (hunk 5 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb]: I would have been impossible for this to occur. The MEF catalog is forcibly disposed between tests.

File: src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb (hunk 6 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb]: This file is no longer touched as part of this pull request.

File: src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj (hunk 7 above)
Comment (sharwell) [reply src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj]: This change is now removed from this pull request.

File: src/VisualStudio/Core/Impl/CodeModel/CodeModelState.cs (hunk 10 above)
Comment (sharwell) [reply src/VisualStudio/Core/Impl/CodeModel/CodeModelState.cs]: This change is now removed from this pull request.

File: src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb (hunk 11 above)
Comment (sharwell) [reply src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb]: This change is now removed from this pull request.

File: src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb (hunk 12 above)
Comment (sharwell) [reply src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb]: This change is now removed from this pull request.

File: src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb (hunk 13 above)
Comment (sharwell) [reply src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb]: This change is now removed from this pull request.

I would not comment in the code, but I would be happy to remove the finalizer.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs (hunk 9 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: This change is now removed from this pull request.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: :memo: I looked into just throwing here, but it's not clean. VisualStudioTaskSchedulerFactory may or may not be imported as a unit with VisualStudioWorkspace, so throwing here due to a requirement of the latter would not be clear.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs (hunk 8 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs]: This change is now removed from this pull request.

File: src/EditorFeatures/TestUtilities/MinimalTestExportProvider.cs [hunk 14]
```diff
@@ -91,5 +90,11 @@ public static ComposableCatalog GetEditorAssemblyCatalog()
             return ExportProviderCache.GetOrCreateAssemblyCatalog(assemblies, ExportProviderCache.CreateResolver())
                 .WithPart(typeof(TestExperimentationServiceInternal));
         }
+
+        public static ComposableCatalog WithDefaultFakes(this ComposableCatalog catalog)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/MinimalTestExportProvider.cs]: Is there an intended terminology difference here for "Fake" vs. "Mock"?

File: src/Workspaces/CoreTestUtilities/MEF/ExportProviderCache.cs [hunk 15]
```diff
@@ -200,6 +203,33 @@ public ExportProvider GetOrCreateExportProvider()
...
+                                        continue;
+                                    }
+
+                                    if (importBinding.ImportDefinition.Cardinality != ImportCardinality.ZeroOrMore)
+                                    {
+                                        // This failure occurs when a binding fails because multiple exports were
+                                        // provided but only a single one (at most) is expected. This typically occurs
+                                        // when a test ExportProvider is created with a mock implementation without
+                                        // first removing a value provided by default.
+                                        Assert.Null(error.Message);
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/MEF/ExportProviderCache.cs]: Why not just `throw new Exception(error.Message)`? Two small reasons:

1. The "expected null, actual: message" is confusing. We don't expect a null message. We expect to not be here.
2. If MEF ever gave a null message (even if that's a bug), then your assert won't fire and now you have two bugs.

(This mostly threw up a flag in my head because I commonly see people not wanting to just throw an exception in xUnit and workaround it with Assert.False(true, "message") or other things that get kinda confusing too.)

File: src/EditorFeatures/TestUtilities/MinimalTestExportProvider.cs (hunk 14 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/MinimalTestExportProvider.cs]: I prefer to use fake as the general term when a more specific scenario is not defined by the API. I like the summary of [What's the difference between faking, mocking, and stubbing?](https://stackoverflow.com/questions/346372/whats-the-difference-between-faking-mocking-and-stubbing) that my Google search showed:

> A stub is a controllable replacement for an existing dependency (or collaborator) in the system. ... The main thing to remember about mocks versus stubs is that mocks are just like stubs, but you assert against the mock object, whereas you do not assert against a stub. Fake is just the name used for both stubs and mocks.

Comment (sharwell) [reply src/EditorFeatures/TestUtilities/MinimalTestExportProvider.cs]: Updated for consistency in types added for this PR.
