### PR TITLE
Remove "Make readonly" suggestion from fixed size buffers

### LINKED ISSUE #26364: IDE0044 (add readonly modifier) fires incorrectly for fixed buffers
**Version Used**: 15.7.0 Preview 4.0

**Steps to Reproduce**:

1. In a new C# project, set "Allow unsafe" to true in the project properties.
2. In a new file, type
```C#
unsafe struct Foo
{
    private fixed byte _data[8];
}
```
2. Put caret on the _data field and press Ctrl . (light-bulb)

**Expected Behavior**:
No tip

**Actual Behavior**:
"Add readonly modifier" (IDE0044) is suggested to replace 'fixed' with 'readonly'.
If you take the suggestion, the app fails to compile with:
```
error CS0650: Bad array declarator: To declare a managed array the rank specifier precedes the variable's identifier. To declare a fixed size buffer field, use the fixed keyword before the field type.
error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression)
```

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
In C#, fixed size buffers cannot be `readonly`. Prior to this PR, the analyzer would suggest making a fixed size buffer readonly if it otherwise qualified. This PR aims to remove the "Make readonly" suggestion from fixed size buffers in C#.

To determine whether a field is `fixed`, I exposed the `IsFixed` property as part of the `IFieldSymbol` interface, where previously it was only exposed on the C#-specific version of `FieldSymbol`. In doing so, I mimicked the implementation of other existing properties in that interface that were only relevant to C#, such as `IsVolatile`, to attempt to remain consistent.

Fixes #26364.

### CODE REVIEW

**Comment by sharwell** [comment]
@jaredpar assigning to compilers for API change review. Please assign back to IDE once approved.

File: src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs [hunk 1]
```diff
@@ -39,6 +39,13 @@ public interface IFieldSymbol : ISymbol
         /// </summary>
         bool IsVolatile { get; }
 
+        /// <summary>
+        /// Returns true if this field was declared as "fixed".
+        /// Note that for a fixed-size buffer declaration, this.Type will be a pointer type, of which
+        /// the pointed-to type will be the declared element type of the fixed-size buffer.
+        /// </summary>
+        bool IsFixed { get; }
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: Language calls these "Fixed size buffers": https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#fixed-size-buffers

Perhaps the name shoudl be IsFixedSizeBuffer to reflect that?

Comment (Scott-Caldwell) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: I went with `IsFixed` because the existing implementation of the C# version of `FieldSymbol` already uses `IsFixed` to indicate fixed size buffers.

I could rename the interface property to `IsFixedSizeBuffer`, but that would lead to either a redundant property on C#'s `FieldSymbol` or a messy refactoring to rename the existing property on C#'s `FieldSymbol`. Of those, I think I like the redundant property best if we go this route. Thoughts?

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: You can just use explicit interfface implementation to implement the C# version (which forwards to the existing implicit implementation).

But hold off until the compiler people weigh in. They may prefer the name as is.  @gafter and @jcouv are good resources here for helping determine what would be the most appropriate public name :)

**Comment by jaredpar** [comment]
@sharwell API approved moving back to IDE

**Comment by sharwell** [comment]
@Scott-Caldwell Would you like to fix the merge conflicts or would you like me to go ahead and do it? 😄

File: src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: The compiler already chose to use `IsFixed` for the name here.  I don't think having this PR change that decision is right. I'd stick with the current language.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: > The compiler already chose to use IsFixed for the name here. I don't think having this PR change that decision is right. I'd stick with the current language.

I'm not sure that's relevant :)   The API is currently internal.  But this PR changes it to be public.  As such, it should be based on what's best given the langauge construct it represents.  Now, we may decide that's 'IsFixed'.  But it should be an actual decision, and not just choosing it based on what the compiler happens to have chose so far.  :)

As another example where this would certainly come up.  If we wanted to expose TypeWithAnnotations, we likely wouldn't call it that name.  Often times internal names are just picked for expediency, or because that specific dev thought it made sense, but without thought given to if that name would be best as a public eye.  When promoting internal to public we need to act without that biasing our decisions.

Comment (jaredpar) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: > But it should be an actual decision, and not just choosing it based on what the compiler happens to have chose so far. :)

I looked at the change and it met my expectations. Another compiler sign off is required hereand if they disagree that's fine. I think this name is just fine though.

Comment (agocke) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: @jaredpar I actually disagree.

The language has a specific notion of `fixed` meaning "cannot move in memory and does not require a `fixed` statement".

I think we misnamed this API and it should be called `IsFixedSizeBuffer`.

File: src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb [hunk 2]
```diff
@@ -412,6 +412,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
             End Get
         End Property
 
+        Private ReadOnly Property IFieldSymbol_IsFixed As Boolean Implements IFieldSymbol.IsFixed
+            Get
+                Return False
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb]: >Return False [](start = 16, length = 12)

Please add a targeted compiler test for this API for VB

**Comment by jaredpar** [comment]
@agocke 

> I  think we misnamed this API and it should be called IsFixedSizeBuffer.

That's fine. If we're doing that then I think we need to change the member on `FieldSymbol` as well. Having two different nams here only serves to create confusion. No reason to be inconsistent here.

**Comment by agocke** [comment]
@jaredpar 100% agree on changing the internal name, as well.

File: src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: >bool IsFixed { get; } [](start = 8, length = 21)

I am assuming this property is implicitly implemented by  C# FieldSymbol.  Please add targeted tests for this new API for C#.

**Comment by sharwell** [comment]
@AlekseyTs This is a new contributor who's focused on the IDE side to date, and the compiler change here was only a side effect. Can you point them to the location where these tests are since it'll be a new area to work in?

**Comment by sharwell** [comment]
@Scott-Caldwell It sounds like the high-level changes requested are the following:

1. Change the name of the new public property from `IsFixed`&rarr;`IsFixedSizeBuffer`
2. Change the name of the original internal property from `IsFixed`&rarr;`IsFixedSizeBuffer`
3. Add tests for the new public properties to the compiler layer test suite for both C# and VB code

If you have any questions about how to handle any of these, please feel free to reach out and we'll figure out a way to make it happen. Also, if any of this is a change you are not comfortable making at this time, please let me know if you'd like me to pick up where you left off so we can get the feature delivered. 👍

File: src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs]: 👍 Tests now added

**Comment by sharwell** [comment]
@agocke @AlekseyTs Can you review the update?
